### ISSUE TITLE
Rustup fails to install

### ISSUE THREAD

**Issue by thedrow** [Homebrew/linuxbrew-core#11214]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single formula? If it's a general `brew` problem please file this issue at Linuxbrew/brew: https://github.com/Linuxbrew/brew/issues/new/choose. If it's a tap (e.g. Brewsci/homebrew-bio) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/ad0fe1c4b0e6134ace5f14b3e9ff7a93
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Install rustup
- What happened (include command output)
```
brew install rustup
Updating Homebrew...
Fast-forwarded master to origin/master.
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
algol68g

==> Downloading https://github.com/rust-lang/rustup.rs/archive/1.16.0.tar.gz
==> Downloading from https://codeload.github.com/rust-lang/rustup.rs/tar.gz/1.16
        -=O#-  #     #    #                                                   
==> Downloading https://github.com/rust-lang/rustup.rs/pull/1521/commits/ebbfced
==> Downloading from https://github.com/rust-lang/rustup.rs/commit/ebbfced7ee4ae
#=#=-#  #                                                                     
==> Patching
==> Applying ebbfced7ee4aeb5be4c775f8f85e351093d5818f.diff
patching file src/rustup-utils/src/utils.rs
==> cargo install --root /home/linuxbrew/.linuxbrew/Cellar/rustup-init/1.16.0 --
Last 15 lines from /home/omer/.cache/Homebrew/Logs/rustup-init/01.cargo:
          /home/linuxbrew/.linuxbrew/bin/ld: openssl.c:(.text.ossl_connect_step1+0x1181): undefined reference to `sk_pop_free'
          /home/linuxbrew/.linuxbrew/bin/ld: openssl.c:(.text.ossl_connect_step1+0x1490): undefined reference to `sk_pop'
          /home/linuxbrew/.linuxbrew/bin/ld: openssl.c:(.text.ossl_connect_step1+0x14cf): undefined reference to `sk_num'
          /home/linuxbrew/.linuxbrew/bin/ld: openssl.c:(.text.ossl_connect_step1+0x14fc): undefined reference to `sk_pop_free'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: failed to compile `rustup v1.16.0 (/tmp/rustup-init-20190114-20008-1u1o93k/rustup.rs-1.16.0)`, intermediate artifacts can be found at `/tmp/rustup-init-20190114-20008-1u1o93k/rustup.rs-1.16.0/target`

Caused by:
  Could not compile `rustup`.

To learn more, run the command again with --verbose.

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
Please do not report this issue to Homebrew/brew or Homebrew/core,
which support macOS only."
```
- What you expected to happen
Rustup should compile.
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install rustup`

**Comment by thedrow** [comment]
Bump.

**Comment by thedrow** [comment]
Still fails to install...

**Comment by thedrow** [comment]
This is still happening.

**Comment by iMichka** [comment]
Yes. Because nobody is working on this. The bot will continue to try to close this endlessly. I propose that we close this until somebody wants to pick this up.
