### ISSUE TITLE
XeTeX (texlive) fails to compile document

### ISSUE THREAD

**Issue by ta2gch** [Homebrew/linuxbrew-core#11508]
This issue relates the formula `texlive.rb`.
`xelatex` command outputs this message when it compiles something.

    mktexfmt [ERROR]: -user mode but path setup is -sys type, bailing out.
    I can't find the format file `xelatex.fmt'!

I guess install-tl.sh can change mode of `mktexfmt` and the formula should set this option for this issue.

I tested this issue with docker like that way.

```sh
$ docker run --rm -it linuxbrew/linuxbrew /bin/bash
$ brew install texlive
$ cat > test.tex
\documentclass{article}
\begin{document}
\end{document}
$ xelatex test.tex
```

I'm sorry for I don't know how to fix this issue.

**Comment by ta2gch** [comment]
After `fmtutils-sys --all`, this issue solves. (https://bugzilla.redhat.com/show_bug.cgi?id=717268)

It should be added to the formula?

**Comment by JuPlutonic** [comment]
I think it is only related to CTAN/texlive types of packaging (--with-medium, --with-full, etc) and mb fonts.
PS *I'm comfortable with --with-medium installed texlive formula. LuaTex, not xelatex. And I use one of three tried editors: TexStudio. I never used TeX/LaTex before this winter…*
