### ISSUE TITLE
linuxbrew/xorg/mesa waste too much space

### ISSUE THREAD

**Issue by lidaobing** [Homebrew/linuxbrew-core#11510]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [*] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [*] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [*] ran `brew update` and can still reproduce the problem?
- [*] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [*] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [*] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
brew install gtk+3

- What happened (include command output)
mesa installed and used 1GB disk space.

```
$ brew list mesa | xargs ls -lS | head
-r-xr-xr-x 1 lidaobing lidaobing 65074872 Feb  4 20:17 /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/i915_dri.so
-r-xr-xr-x 1 lidaobing lidaobing 65074872 Feb  4 20:17 /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/kms_swrast_dri.so
-r-xr-xr-x 1 lidaobing lidaobing 65074872 Feb  4 20:17 /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/nouveau_dri.so
-r-xr-xr-x 1 lidaobing lidaobing 65074872 Feb  4 20:17 /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/r300_dri.so
-r-xr-xr-x 1 lidaobing lidaobing 65074872 Feb  4 20:17 /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/r600_dri.so
-r-xr-xr-x 1 lidaobing lidaobing 65074872 Feb  4 20:17 /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/radeonsi_dri.so
-r-xr-xr-x 1 lidaobing lidaobing 65074872 Feb  4 20:17 /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/swrast_dri.so
-r-xr-xr-x 1 lidaobing lidaobing 65074872 Feb  4 20:17 /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/vmwgfx_dri.so
-r-xr-xr-x 1 lidaobing lidaobing 57516832 Feb  4 20:17 /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/vdpau/libvdpau_nouveau.so.1.0.0
-r-xr-xr-x 1 lidaobing lidaobing 57516832 Feb  4 20:17 /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/vdpau/libvdpau_r300.so.1.0.0
$ brew list mesa | xargs ls -lS | head -8 | awk '{print $NF}' | xargs md5sum
xargs: ls: terminated by signal 13
36265f83edf05aaefcc79c85aef96067  /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/i915_dri.so
36265f83edf05aaefcc79c85aef96067  /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/kms_swrast_dri.so
36265f83edf05aaefcc79c85aef96067  /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/nouveau_dri.so
36265f83edf05aaefcc79c85aef96067  /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/r300_dri.so
36265f83edf05aaefcc79c85aef96067  /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/r600_dri.so
36265f83edf05aaefcc79c85aef96067  /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/radeonsi_dri.so
36265f83edf05aaefcc79c85aef96067  /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/swrast_dri.so
36265f83edf05aaefcc79c85aef96067  /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/vmwgfx_dri.so

```
- What you expected to happen
mesa installed and 7 dri files is a soft link of the last one. and save disk space.

- Step-by-step reproduction instructions (by running `brew install` commands)
brew install linuxbrew/xorg/mesa

**Comment by aswger** [comment]
```
$ file /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/i915_dri.so
/home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/i915_dri.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, not stripped
```
Well, we know from that output, the .so files not stripped, of course non-stripper elf got that big.
Maybe need some help to make formula properly strip the executable and .so files. The Tap is here https://github.com/Linuxbrew/homebrew-xorg

**Comment by lidaobing** [comment]
@aswger .so not stripped is not the major problem. the major problem is `i915_dri.so` is same as `kms_swrast_dri.so`, so there should be a soft link from `kms_swrast_dri.so` to `i915_dri.so`

**Comment by aswger** [comment]
```
$ ls -lh /usr/lib/x86_64-linux-gnu/dri/nouveau_vieux_dri.so
-rw-r--r-- 5 root root 9.6M Feb  9 00:12 /usr/lib/x86_64-linux-gnu/dri/nouveau_vieux_dri.so
$ ls -lh /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/i915_dri.so
-r-xr-xr-x 1 agus agus 63M Feb 13 20:30 /home/linuxbrew/.linuxbrew/Cellar/mesa/17.2.3_3/lib/dri/i915_dri.so
```

From above output, if you *worry* much about disk space, there is **huge difference** between stripped .so and non-stripped .so file size.

**Comment by lidaobing** [comment]
@aswger from your experiment, strip is another major problem. from my post, the top 8 files is exactly same, so we can save 65MB*7=455MB with soft link.

**Comment by lidaobing** [comment]
@stale reactive
