### ISSUE TITLE
nginx: error: tar: unrecognized option '--options'

### ISSUE THREAD

**Issue by Nobup** [Homebrew/linuxbrew-core#11706]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/8ef76f393cc955a7076abcf9cd7845b8

**Comment by aswger** [comment]
The formula still assume the system using bsd tar[1] not gnu tar it seems. https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/nginx.rb#L23

[1] https://www.freebsd.org/cgi/man.cgi?tar(1)

**Comment by keyosh0121** [comment]
I also faced same issue with RHEL7.1, while installing nginx. is there any way to use bsdtar instead of gnu-tar to get through?

**Comment by gitjy** [comment]
i have the same issue 

tar
-cJf
/home/linuxbrew/.linuxbrew/Cellar/nginx/1.15.8/share/nginx/src/src.tar.xz
--options
compression-level=9
.

tar: unrecognized option '--options'
Try `tar --help' or `tar --usage' for more information.

**Comment by JuPlutonic** [comment]
tar (GNU tar) no *--options* argument no difference how to create (type of compress program) archive.

**Comment by MetalGearDaner** [comment]
Hey there! I'm having the same issue while installing nginx:

tar
-cJf
/home/linuxbrew/.linuxbrew/Cellar/nginx/1.15.9/share/nginx/src/src.tar.xz
--options
compression-level=9
.

Any way to solve this?

**Comment by iMichka** [comment]
PR #11683 should fix this.
