### ISSUE TITLE
brew install r --with-tcl-tk fails to add support for tcl-tk

### ISSUE THREAD

**Issue by jwhite007** [Homebrew/linuxbrew-core#11756]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
https://gist.github.com/jwhite007/c2507f03238d0c969610fa944605f592
- What you were trying to do (and why)
```
$ brew info r
r: stable 3.5.2
Software environment for statistical computing
https://www.r-project.org/
Not installed
From: https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/r.rb
==> Dependencies
Build: pkg-config ✔
Required: gcc ✔, gettext ✔, jpeg ✔, libpng ✔, openblas ✔, pcre ✔, readline ✔, xz ✔, curl ✔
Recommended: cairo ✔, linuxbrew/xorg/xorg ✔
Optional: tcl-tk ✔
==> Options
--with-tcl-tk
        Build with tcl-tk support
--without-cairo
        Build without cairo support
--without-xorg
        Build without xorg support
==> Analytics
install: 7,390 (30 days), 31,665 (90 days), 109,928 (365 days)
install_on_request: 6,755 (30 days), 28,154 (90 days), 94,109 (365 days)
build_error: 0 (30 days)

$ brew install r --with-tcl-tk
```
- What happened (include command output)
No errors during installation. Everything seemed to be fine, except.
From within R:
```
> capabilities("tcltk")
tcltk
FALSE
```
- What you expected to happen
```
> capabilities("tcltk")
tcltk
TRUE
```
- Step-by-step reproduction instructions (by running `brew install` commands)
```
$ brew install r --with-tcl-tk
$ R
> capabilities("tcltk")
```

**Comment by jwhite007** [comment]
```args << "--with-tcltk" if build.with? "tcl-tk"``` was missing from the ```if OS.linux?``` block in r.rb. I added it to the block and did a ```brew reinstall r --with-tcl-tk```. Still...
```
> capabilities('tcltk')
tcltk
FALSE
```
The gist-logs for that are here, https://gist.github.com/jwhite007/aa4b9fcc37d6baaafad88c88868e483d

Looking at the gist-logs, one can see that the build is getting configured with the tcl-tk that I've installed via Linuxbrew.

**Comment by jwhite007** [comment]
I finally got it to work. The r.rb script is not correct. I had to edit to the following.
```
if OS.linux?
  args << "--libdir=#{lib}" # avoid using lib64 on CentOS
  args << "--with-cairo" if build.with? "cairo"
  args << "--without-x" if build.without? "xorg"
  args << "--with-tcltk" if build.with? "tcl-tk"
  args << "--with-tcl-config=#{HOMEBREW_PREFIX}/opt/tcl-tk/lib/tclConfig.sh" if build.with? "tcl-tk"
  args << "--with-tk-config=#{HOMEBREW_PREFIX}/opt/tcl-tk/lib/tkConfig.sh" if build.with? "tcl-tk"
```

**Comment by iMichka** [comment]
Would you like to open a pull request for this?

**Comment by jwhite007** [comment]
@iMichka, I will do so as soon as I make sure that the formula is solid. I'm not a Ruby programmer.

**Comment by jwhite007** [comment]
@iMichka, here is an update. I believe there is something wrong in how R is being built with the new formula, regardless of the tcl-tk stuff. In my old linuxbrew set-up, I had R 3.5.1 installed, and the library oligo was working just fine. In the new linuxbrew set-up, I installed R 3.5.2 using the new formula. The library oligo did not work. I then installed 3.5.1 using the new formula. Oligo did not work. I then installed 3.5.1 in the new set-up using the old formula. Oligo works. I'm now off to try whether installing 3.5.2 using the old formula will result in a functioning Oligo.

**Comment by jwhite007** [comment]
@iMichka, I've zeroed in on the problems that I'm having with the library oligo. The latest formula for R, builds with openblas integration as default, and there is no "without" option. I now have installed R 3.5.2 with the older formula. I will refer to that commit and work on the latest r.rb for the pull request later this evening or tomorrow as I have some other obligations this afternoon. The older formula does not integrate with openblas by default.

**Comment by jwhite007** [comment]
@iMichka, I'm in the process of the pull-request submission process; however, I'm running into problems with ```brew tests```. It appears that bundler is having trouble installing particular gems. I'll have to troubleshoot this.
