### ISSUE TITLE
brew install phantomjs does not work on non macOS (gives error as "install using cask" and "brew cask install phantomjs" pops error of supported only on macOS)

### ISSUE THREAD

**Issue by RohitG96** [Homebrew/linuxbrew-core#11763]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
   Trying to install phantomjs
- What happened (include command output)
```
 ➜  ~ brew install phantomjs
 Error: No available formula with the name "phantomjs" 
 It was migrated from homebrew/core to homebrew/cask.
 You can access it again by running:
   brew tap homebrew/cask
 And then you can install it by running:
   brew cask install phantomjs
```

- What you expected to happen
 Should have installed phantomjs

- Step-by-step reproduction instructions (by running `brew install` commands)
1. brew install phantomjs
2. brew cask install phantomjs

**Comment by iMichka** [comment]
Closing here, see for explantion https://github.com/Homebrew/linuxbrew-core/pull/11766#issuecomment-468999415
