### ISSUE TITLE
osmfilter doesn't install osmconvert 

### ISSUE THREAD

**Issue by kkkondo** [Homebrew/linuxbrew-core#11762]
Hello,
I have realized that ```osmfilter``` doesn't install osmconvert but only osmfilter and osmupdate.

Described in https://gitlab.com/osm-c-tools/osmctools,
```
A few really fast tools to convert, filter and update OpenStreetMap data files

Current Version: 0.9

Programm desrcriptions:
https://wiki.openstreetmap.org/wiki/osmconvert 
https://wiki.openstreetmap.org/wiki/osmfilter 
https://wiki.openstreetmap.org/wiki/osmupdate 
```

My procedure of installing was as follows:

```
$ brew install osmfilter
$ which osmconvert
$ (cd /home/linuxbrew/.linuxbrew/bin/; ls -ldt osm*)
  Feb 27 15:54 osmfilter -> ../Cellar/osmfilter/0.9/bin/osmfilter
  Feb 27 15:54 osmupdate -> ../Cellar/osmfilter/0.9/bin/osmupdate
$

$ brew test osmfilter
Testing osmfilter
==> Downloading https://download.gisgraphy.com/openstreetmap/pbf/AD.tar.bz2
Already downloaded: /home/smap/.cache/Homebrew/downloads/2f124032ba5b7d0d9bf0ad8b8b925b7743ae8be23e1a22358398b2b44af2f425--AD.tar.bz2
==> /home/linuxbrew/.linuxbrew/Cellar/osmfilter/0.9/bin/osmconvert AD -o=test.o5m
Last 15 lines from /home/smap/.cache/Homebrew/Logs/osmfilter/test.01.osmconvert:
2019-02-27 17:32:38 +0900

/home/linuxbrew/.linuxbrew/Cellar/osmfilter/0.9/bin/osmconvert
AD
-o=test.o5m

Error: osmfilter: failed
 


$ brew config
HOMEBREW_VERSION: 2.0.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 117c24f4b6294e037431d3a850ced6955d53e26f
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 26046173fd7c87a4023f1792609011a0fc48581c
Core tap last commit: 27 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/smap/.cache/Homebrew
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_DISPLAY: :0.0
HOMEBREW_LOGS: /home/smap/.cache/Homebrew/Logs
HOMEBREW_SYSTEM_CURL_TOO_OLD: 1
CPU: 16-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendo
r/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.20.1 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.64.0 => /home/linuxbrew/.linuxbrew/opt/curl/bin/curl
Kernel: Linux 3.13.0-107-generic x86_64 GNU/Linux
OS: Ubuntu 14.04.5 LTS (trusty)
Host glibc: 2.19
/usr/bin/gcc: 6.4.0
glibc: 2.23
gcc: 5.5.0_4
xorg: N/A
```

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

**Comment by iMichka** [comment]
Looking at their makefile, there seem to be a ENABLE_OSMCONVERT flag that needs to be set: https://gitlab.com/osm-c-tools/osmctools/blob/master/src/Makefile.am

You need to submit that change under the form of a pull request at https://github.com/Homebrew/homebrew-core/, and the change will later be merged to the linux repository.
