### ISSUE TITLE
gcc cannot find Linuxbrew-installed gmp, mpfr, and mpc

### ISSUE THREAD

**Issue by kitmonisit** [Homebrew/linuxbrew-core#11931]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I am trying to install a fresh Linuxbrew on my RHEL6 machine. I do not have `sudo` access. Therefore my Linuxbrew is in `$HOME/.linuxbrew`.
- What happened (include command output)
Various chicken-and-egg problems:
1. Plain `brew update` does not work, because "Git is not in your PATH". I worked around that with `HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_ENV_FILTERING=1 brew update`.
2. Now I try to `HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_ENV_FILTERING=1 brew install git`.
    - However `git` requires `glibc`.
    - But in order to install `glibc`, I need to `brew install gcc` to get a newer version.
3. Therefore I try `HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_ENV_FILTERING=1 brew install gcc --without-glibc`. However, the `configure` step of installation cannot find the Linuxbrew-installed `gmp`, `mpfr`, and `mpc`. This is where I'm stuck.
4. The output of `HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_ENV_FILTERING=1 brew gist-logs gcc` is here: https://gist.github.com/kitmonisit/b365a390b1097bf09bf5edceb2fd8483.
    - As for the warning about `LD_LIBRARY_PATH`, I have taken out the definition already. Another run of `brew install gcc` no longer has that warning but still reproduces the problem.
    - I have edited the `gist-logs` output to redact confidential path information.
    - The error message that jumps out for me is

```
checking for the correct version of gmp.h... yes
checking for the correct version of mpfr.h... yes
checking for the correct version of mpc.h... yes
checking for the correct version of the gmp/mpfr/mpc libraries... no
configure: error: Building GCC requires GMP 4.2+, MPFR 2.4.0+ and MPC 0.8.0+.
Try the --with-gmp, --with-mpfr and/or --with-mpc options to specify
their locations.  Source code for these libraries can be found at
their respective hosting sites as well as at
ftp://gcc.gnu.org/pub/gcc/infrastructure/.  See also
http://gcc.gnu.org/install/prerequisites.html for additional info.  If
you obtained GMP, MPFR and/or MPC from a vendor distribution package,
make sure that you have installed both the libraries and the header
files.  They may be located in separate packages.
```

5. These are the contents of `$HOME/.linuxbrew/lib`:

```
pkgconfig (DIR)
engines (DIR)
libcrypto.so.1.0.0
libcurl.so.4.5.0
libmpc.so.3.1.0
libssl.so.1.0.0
libmpfr.so.6.0.1
libz.so.1
libgmp.so.10
libz.so.1.2.11
libgmp.so.10.3.2
libgmpxx.so.4.5.2
libmpc.so.3
libcurl.so.4
libgmpxx.so.4
libmpfr.so.6
libbfd.a
libcrypto.a
libcurl.a
libgmp.a
libgmpxx.a
libmpc.a
libmpfr.a
libopcodes.a
libssl.a
libz.a
ld.so
libcrypto.so
libcurl.so
libgmp.so
libgmpxx.so
libmpc.so
libmpfr.so
libssl.so
libz.so
```

- What you expected to happen
It should install smoothly. My plan here is supposed to be:

      $ brew install gcc --without-glibc
      $ brew install glibc
      $ brew remove gcc
      $ brew install gcc
      $ brew install git

- Step-by-step reproduction instructions (by running `brew install` commands)
After installing Linuxbrew without `sudo` access, i.e. it's in `$HOME/.linuxbrew`, do the following:

      $ HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_ENV_FILTERING=1 brew install gcc --without-glibc

**Comment by kitmonisit** [comment]
`Building GCC requires GMP 4.2+, MPFR 2.4.0+ and MPC 0.8.0+.`

I compiled versions of GMP, MPFR, and MPC that have the same major version number as that in the error message: `gmp-4.3.2`, `mpfr-2.4.2`, and `mpc-0.8.1`. Then installed them in `/some/silly/path`.

I then did a `brew edit gcc` and modified these three lines: https://github.com/Homebrew/linuxbrew-core/blob/b4cfdecf261912519564e44bd7d3f76dadb21ccd/Formula/gcc.rb#L150-L152 like so:

      "--with-gmp=/some/silly/path",
      "--with-mpfr=/some/silly/path",
      "--with-mpc=/some/silly/path",

`configure` now seems to get past that error message. This time, `can't find a usable ISL.`

**Comment by kitmonisit** [comment]
So I compiled `isl-0.18` from http://isl.gforge.inria.fr/isl-0.18.tar.xz then installed into `/some/silly/path`.

`configure` gets past the missing library errors and proceeds to `make`. It does not finish. Here's the `02.make` log: https://gist.github.com/kitmonisit/585902f925d26716e9d8cf5e0d57285b

**Comment by kitmonisit** [comment]
Just to get past this, here's what I did

    $ export HOMEBREW_NO_AUTO_UPDATE=1
    $ export HOMEBREW_NO_ENV_FILTERING=1
    $ brew edit glibc

Then comment out lines 160 and 162. This is because `localedef` tries to write to `sudo`-protected `locale-archive`. So I'll ignore it:
https://github.com/Homebrew/linuxbrew-core/blob/b4cfdecf261912519564e44bd7d3f76dadb21ccd/Formula/glibc.rb#L159-L163

    $ brew install binutils linux-headers
    $ brew install glibc --force-bottle
    $ brew install gcc --force-bottle
    $ brew install expat --force-bottle
    $ brew install pcre2 --force-bottle
    $ brew install openssl
    $ brew install curl
    $ brew install gettext --force-bottle
    $ brew install pkgconfig --force-bottle
    $ brew install gpatch --force-bottle
    $ brew install ncurses --force-bottle
    $ brew install pkg-config --force-bottle
    $ brew install gettext --force-bottle
    $ brew install git
    $ unset HOMEBREW_NO_AUTO_UPDATE
    $ unset HOMEBREW_NO_ENV_FILTERING
    $ brew update

**Comment by iMichka** [comment]
Hi. Your plan looks ok to me and you found out most of the difficulties there are to install on older systems.

Homebrew will not allow you to pass flags to gcc or to the linker which are paths to libraries outside homebrew. This is why `HOMEBREW_NO_ENV_FILTERING` exists, which allows to bypass this. Of course, ideally, one should not use `HOMEBREW_NO_ENV_FILTERING`, this env variable is just there for debugging purposes.

This also means that configure may pass, but not make.

```
checking for the correct version of gmp.h... yes
checking for the correct version of mpfr.h... yes
checking for the correct version of mpc.h... yes
checking for the correct version of the gmp/mpfr/mpc libraries... no
```

As we do pass these flags, it seems to be finding everything it needs. What fails is the version comparison. But we do provide a way newer version of all these libraries, so this should be working. I really do not know what is going on here, but would be interest if we could find a solution.

Regarding the `localedef` problem in `glibc`, this is a different topic, and we should have a separate issue for that. Not sure what we should do here: bail out if you need sudo, or try to write to a different path.

**Comment by iMichka** [comment]
I am really sorry but I will not be able to help you further with this. I am stuck with a lot of other issues and projects, so you'll need to sort this out by yourself. Pull requests are welcome though.

**Comment by YuMan-Tam** [comment]
I had exactly the same error on a linux machine. The error went away when I build ```gmp```, ```mpfr```, and ```libmpc``` from source instead of bottles.

Hence, I am inclined to think there's something hard-coded in the bottles which doesn't work when we install ```gcc``` in non-standard path.
