### ISSUE TITLE
Various issues with GHC

### ISSUE THREAD

**Issue by sambrightman** [Homebrew/linuxbrew-core#11965]
(This issue template should be updated now that Homebrew/Linuxbrew are merged)

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Linuxbrew/homebrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?

There are some incorrect `PATH` warnings and some things I am unable to fix (non-default installation directory).

- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

I can `gist-logs` some scenarios once it is clear what is required.

- [N/A] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Upgrade `ghc`/`ghc@8.0`, as part of a `brew upgrade`.

- What happened (include command output)

```
==> make install
Last 15 lines from /apps/homefs1/sbrightman/.cache/Homebrew/Logs/ghc/06.make:
#  rts/dist/build/libHSrts.a rts/dist/build/libHSrts_p.a rts/dist/build/libHSrts-ghc8.4.4.so rts/dist/build/libHSrts_l.a rts/dist/build/libHSrts_debug.a rts/dist/build/libHSrts_thr.a rts/dist/build/libHSrts_thr_debug.a rts/dist/build/libHSrts_thr_l.a rts/dist/build/libHSrts_thr_p.a rts/dist/build/libHSrts_debug-ghc8.4.4.so rts/dist/build/libHSrts_thr-ghc8.4.4.so rts/dist/build/libHSrts_thr_debug-ghc8.4.4.so rts/dist/build/libHSrts_l-ghc8.4.4.so rts/dist/build/libHSrts_thr_l-ghc8.4.4.so rts/dist/build/libffi.so rts/dist/build/libffi.so.7 rts/dist/build/libffi.so.7.1.0 rts/dist/build/libCffi.a rts/dist/build/libCffi_p.a rts/dist/build/libCffi_l.a rts/dist/build/libCffi_debug.a rts/dist/build/libCffi_thr.a rts/dist/build/libCffi_thr_debug.a rts/dist/build/libCffi_thr_l.a rts/dist/build/libCffi_thr_p.a = libraries to install
#  "/spare/local2/sbrightman/tmp/ghc-20190305-2693001-5fqe4e/ghc-8.6.3/binary/lib/ghc-8.4.4/rts" = directory to install to
#
# The .dll case calls STRIP_CMD explicitly, instead of `install -s`, because
# on Win64, "install -s" calls a strip that doesn't understand 64bit binaries.
# For some reason, this means the DLLs end up non-executable, which means
# executables that use them just segfault.
/usr/bin/install -c -m 755 -d  "/spare/local2/sbrightman/tmp/ghc-20190305-2693001-5fqe4e/ghc-8.6.3/binary/lib/ghc-8.4.4/rts"
for i in  rts/dist/build/libHSrts.a rts/dist/build/libHSrts_p.a rts/dist/build/libHSrts-ghc8.4.4.so rts/dist/build/libHSrts_l.a rts/dist/build/libHSrts_debug.a rts/dist/build/libHSrts_thr.a rts/dist/build/libHSrts_thr_debug.a rts/dist/build/libHSrts_thr_l.a rts/dist/build/libHSrts_thr_p.a rts/dist/build/libHSrts_debug-ghc8.4.4.so rts/dist/build/libHSrts_thr-ghc8.4.4.so rts/dist/build/libHSrts_thr_debug-ghc8.4.4.so rts/dist/build/libHSrts_l-ghc8.4.4.so rts/dist/build/libHSrts_thr_l-ghc8.4.4.so rts/dist/build/libffi.so rts/dist/build/libffi.so.7 rts/dist/build/libffi.so.7.1.0 rts/dist/build/libCffi.a rts/dist/build/libCffi_p.a rts/dist/build/libCffi_l.a rts/dist/build/libCffi_debug.a rts/dist/build/libCffi_thr.a rts/dist/build/libCffi_thr_debug.a rts/dist/build/libCffi_thr_l.a rts/dist/build/libCffi_thr_p.a; do case $i in *.a) /usr/bin/install -c -m 644  $i  "/spare/local2/sbrightman/tmp/ghc-20190305-2693001-5fqe4e/ghc-8.6.3/binary/lib/ghc-8.4.4/rts"; true  "/spare/local2/sbrightman/tmp/ghc-20190305-2693001-5fqe4e/ghc-8.6.3/binary/lib/ghc-8.4.4/rts"/`basename $i` ;; *.dll) /usr/bin/install -c -m 755  $i  "/spare/local2/sbrightman/tmp/ghc-20190305-2693001-5fqe4e/ghc-8.6.3/binary/lib/ghc-8.4.4/rts" ; strip  "/spare/local2/sbrightman/tmp/ghc-20190305-2693001-5fqe4e/ghc-8.6.3/binary/lib/ghc-8.4.4/rts"/`basename $i` ;; *.so) /usr/bin/install -c -m 755  $i  "/spare/local2/sbrightman/tmp/ghc-20190305-2693001-5fqe4e/ghc-8.6.3/binary/lib/ghc-8.4.4/rts" ;; *.dylib) /usr/bin/install -c -m 755  $i  "/spare/local2/sbrightman/tmp/ghc-20190305-2693001-5fqe4e/ghc-8.6.3/binary/lib/ghc-8.4.4/rts";; *) /usr/bin/install -c -m 644  $i  "/spare/local2/sbrightman/tmp/ghc-20190305-2693001-5fqe4e/ghc-8.6.3/binary/lib/ghc-8.4.4/rts"; esac; done
"utils/ghc-cabal/dist-install/build/tmp/ghc-cabal-bindist" copy libraries/ghc-prim dist-install "strip" '' '/spare/local2/sbrightman/tmp/ghc-20190305-2693001-5fqe4e/ghc-8.6.3/binary' '/spare/local2/sbrightman/tmp/ghc-20190305-2693001-5fqe4e/ghc-8.6.3/binary/lib/ghc-8.4.4' '/spare/local2/sbrightman/tmp/ghc-20190305-2693001-5fqe4e/ghc-8.6.3/binary/share/doc/ghc-8.4.4/html/libraries' 'v p dyn'  
Installing library in /spare/local2/sbrightman/tmp/ghc-20190305-2693001-5fqe4e/ghc-8.6.3/binary/lib/ghc-8.4.4/ghc-prim-0.5.2.0
strip: /spare/local2/sbrightman/tmp/ghc-20190305-2693001-5fqe4e/ghc-8.6.3/binary/lib/ghc-8.4.4/ghc-prim-0.5.2.0/stxrLAps: not enough room for program headers, try linking with -N
strip:/spare/local2/sbrightman/tmp/ghc-20190305-2693001-5fqe4e/ghc-8.6.3/binary/lib/ghc-8.4.4/ghc-prim-0.5.2.0/stxrLAps[.note.gnu.build-id]: bad value
make[1]: *** [install_packages] Error 1
make: *** [install] Error 2

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
```

and

```
==> make install
Last 15 lines from /apps/homefs1/sbrightman/.cache/Homebrew/Logs/ghc@8.0/06.make:
Installing library in
/spare/local2/sbrightman/tmp/ghc@8.0-20190305-1846867-l6fwoe/ghc-8.0.2/binary/lib/ghc-7.8.4/ghc-7.8.4
"utils/ghc-cabal/dist-install/build/tmp/ghc-cabal-bindist" copy libraries/old-time dist-install "strip" '' '/spare/local2/sbrightman/tmp/ghc@8.0-20190305-1846867-l6fwoe/ghc-8.0.2/binary' '/spare/local2/sbrightman/tmp/ghc@8.0-20190305-1846867-l6fwoe/ghc-8.0.2/binary/lib/ghc-7.8.4' '/spare/local2/sbrightman/tmp/ghc@8.0-20190305-1846867-l6fwoe/ghc-8.0.2/binary/share/doc/ghc/html/libraries' 'v p dyn'  
Installing library in
/spare/local2/sbrightman/tmp/ghc@8.0-20190305-1846867-l6fwoe/ghc-8.0.2/binary/lib/ghc-7.8.4/old-time-1.1.0.2
"utils/ghc-cabal/dist-install/build/tmp/ghc-cabal-bindist" copy libraries/haskell98 dist-install "strip" '' '/spare/local2/sbrightman/tmp/ghc@8.0-20190305-1846867-l6fwoe/ghc-8.0.2/binary' '/spare/local2/sbrightman/tmp/ghc@8.0-20190305-1846867-l6fwoe/ghc-8.0.2/binary/lib/ghc-7.8.4' '/spare/local2/sbrightman/tmp/ghc@8.0-20190305-1846867-l6fwoe/ghc-8.0.2/binary/share/doc/ghc/html/libraries' 'v p dyn'  
Installing library in
/spare/local2/sbrightman/tmp/ghc@8.0-20190305-1846867-l6fwoe/ghc-8.0.2/binary/lib/ghc-7.8.4/haskell98-2.0.0.3
"utils/ghc-cabal/dist-install/build/tmp/ghc-cabal-bindist" copy libraries/haskell2010 dist-install "strip" '' '/spare/local2/sbrightman/tmp/ghc@8.0-20190305-1846867-l6fwoe/ghc-8.0.2/binary' '/spare/local2/sbrightman/tmp/ghc@8.0-20190305-1846867-l6fwoe/ghc-8.0.2/binary/lib/ghc-7.8.4' '/spare/local2/sbrightman/tmp/ghc@8.0-20190305-1846867-l6fwoe/ghc-8.0.2/binary/share/doc/ghc/html/libraries' 'v p dyn'
Installing library in
/spare/local2/sbrightman/tmp/ghc@8.0-20190305-1846867-l6fwoe/ghc-8.0.2/binary/lib/ghc-7.8.4/haskell2010-1.1.2.0
"/spare/local2/sbrightman/tmp/ghc@8.0-20190305-1846867-l6fwoe/ghc-8.0.2/binary/lib/ghc-7.8.4/bin/ghc-pkg" --force --global-package-db "/spare/local2/sbrightman/tmp/ghc@8.0-20190305-1846867-l6fwoe/ghc-8.0.2/binary/lib/ghc-7.8.4/package.conf.d" update rts/dist/package.conf.install
/spare/local2/sbrightman/tmp/ghc@8.0-20190305-1846867-l6fwoe/ghc-8.0.2/binary/lib/ghc-7.8.4/bin/ghc-pkg: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
make[1]: *** [install_packages] Error 127
make: *** [install] Error 2

READ THIS: https://github.com/Linuxbrew/brew/wiki/troubleshooting
```

- What you expected to happen

Successful upgrade/install.

- Step-by-step reproduction instructions (by running `brew install` commands)

I suspect that _any_ `brew install ghc` will fail on current master's GHC 8 (or `brew install ghc@8.0`), if performed on certain Linux setups.

For me, it was `brew upgrade` on RHEL 6.10 where `ghc` and `ghc8.0` were both installed (probably from source, originally).

GHC installation is troublesome, and there appears to be a history of tickets which are expired or contradict each other.

#6120 was the main issue I faced with `ghc@8.0` on RHEL 6.10 but it is closed and locked. #5996 seems to have ignored and removed the warning comment about using GHC 7 to bootstrap. I did not have trouble with #5821, which motivated the change. To me limited eyes this seems questionable: there is already precedent in the formula for enabling PIC, and does it make sense for GHC 8 to be bootstrapped with itself? After reverting the bootstrap version, I then had an issue with `libtinfo` which has been fixed in `ghc` but not `ghc@8.0`. The following patch got `ghc@8.0` to install cleanly for me from source:

```
diff --git Formula/ghc@8.0.rb Formula/ghc@8.0.rb
index 720b12be3c..44ffbcfce4 100644
--- Formula/ghc@8.0.rb
+++ Formula/ghc@8.0.rb
@@ -57,8 +57,10 @@ class GhcAT80 < Formula
   # "This is a distribution for Mac OS X, 10.7 or later."
   resource "binary" do
     if OS.linux?
-      url "https://downloads.haskell.org/~ghc/8.0.2/ghc-8.0.2-x86_64-deb7-linux.tar.xz"
-      sha256 "b2f5c304b57ac5840a0d2ef763a3c6fa858c70840f749cfad12ed227da973c0a"
+      # Using 8.0.1 gives the error message:
+      # strip: Not enough room for program headers, try linking with -N
+      url "https://downloads.haskell.org/~ghc/7.8.4/ghc-7.8.4-x86_64-unknown-linux-deb7.tar.xz"
+      sha256 "f62e00e93a5ac16ebfe97cd7cb8cde6c6f3156073d4918620542be3e0ad55f8d"
     else
       url "https://downloads.haskell.org/~ghc/8.0.2/ghc-8.0.2-x86_64-apple-darwin.tar.xz"
       sha256 "ff50a2df9f002f33b9f09717ebf5ec5a47906b9b65cc57b1f9849f8b2e06788d"
@@ -118,6 +120,8 @@ class GhcAT80 < Formula
       ENV.prepend_path "LIBRARY_PATH", gmp/"lib"
       # Fix ghc-stage2: error while loading shared libraries: libncursesw.so.5
       ln_s Formula["ncurses"].lib/"libncursesw.so", gmp/"lib/libncursesw.so.5"
+      # Fix ghc-stage2: error while loading shared libraries: libtinfo.so.5
+      ln_s Formula["ncurses"].lib/"libtinfo.so", gmp/"lib/libtinfo.so.5"
       # Fix ghc-pkg: error while loading shared libraries: libncursesw.so.6
       ENV.prepend_path "LD_LIBRARY_PATH", Formula["ncurses"].lib
     end
```

There was some discussion in other tickets that `patchelf` is to blame for the original error but I cannot see a new release since that discussion.

If I uninstall and re-install `ghc@8.0` it installs successfully from bottle and I do not hit this issue. However, subsequent releases have the same `strip` issue. `ghc` cannot be boostrapped with anything less than 8.2, which also still has the problem, so I cannot currently fix that by using 7.8. Perhaps it is somehow possible to install `ghc@8.2` and use it for bootstrapping `ghc`? No: `ghc@8.2` fails with the `strip` issue (I'm actually doubt that installing it would allow it to be used to bootstrap `ghc`...). In neither case can I use a bottle.

On Ubuntu 16.04, `ghc@8.0` builds from source without issue. With the patch above, it fails in the same way as `ghc` (8.6) fails from source:

```
/bin/bash: /spare/ssd/sbrightman/dev/linuxbrew/Cellar/ghc/8.6.3/libexec/integer-gmp/lib/libtinfo.so.5: no version information available (required by /bin/bash)
/bin/sh: /spare/ssd/sbrightman/dev/linuxbrew/Cellar/ghc/8.6.3/libexec/integer-gmp/lib/libtinfo.so.5: no version information available (required by /bin/sh)
mk/config.mk:521: *** missing separator.  Stop.
sh: /spare/ssd/sbrightman/dev/linuxbrew/Cellar/ghc/8.6.3/libexec/integer-gmp/lib/libtinfo.so.5: no version information available (required by sh)
```

It does not install from bottle.

This issue likely needs splitting off into several more focussed issues, but I wanted to gather all the problems first, and ask some general questions.

* should my patch for `ghc@8.0` be made into a PR to fix build-from-source on older distributions? It seems like there is an underlying issue with libtinfo that needs fixing first.
* should `ghc`s be able to bootstrap from `brew`-installed GHCs? Is this even possible?
* if not, how do I install recent GHCs when bottles do not work? I understand that build-from-source is not as big a priority as bottles, but it feels like it should work where necessary.

**Comment by iMichka** [comment]
Hi. Thanks for the detailed report.

The fix for `libtinfo` seems pretty straightforward. It can be added for the 3 ghc formula. Would you like to open a pull request for this?

> should ghcs be able to bootstrap from brew-installed GHCs? Is this even possible?

I think the best is to rely on some older ghc binary we download, like we do right now. We could use an older brewed ghc version to bootstrap the most recent one, but this adds dependencies between these formulae, and I would like to avoid that if possible.

> I understand that build-from-source is not as big a priority as bottles

This is true on mac, on Linux a little bit less. We do offer a little bit of support for build-from-source, as a lot of people do not have root access on their servers. Of course this implies more fiddling and patching, and we do not guarantee that it will work. Building from source is hard.

**Comment by iMichka** [comment]
Regarding the issue template, I'll fix that here: #11967

**Comment by sambrightman** [comment]
Unfortunately, there are two different errors for `libtinfo`. That part of the patch was already copied from the main `ghc` package. This one happens on RHEL 6 without the patch and is fixed with the patch:

```
/spare/local2/sbrightman/tmp/ghc@8.0-20190305-1846867-l6fwoe/ghc-8.0.2/binary/lib/ghc-7.8.4/bin/ghc-pkg: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

However, this one happens on Ubuntu 16.04's `ghc` (unmodified) and `ghc@8.0` (when the `libtinfo` patch is copied into it):

```
sh: /spare/ssd/sbrightman/dev/linuxbrew/Cellar/ghc/8.6.3/libexec/integer-gmp/lib/libtinfo.so.5: no version information available (required by sh)
```

The second also seems to need fixing before a PR would make sense. Do you mean "pretty straightforward" in the sense that you already know what to do here? I don't immediately see the problem that would cause this.

**Comment by iMichka** [comment]
> Do you mean "pretty straightforward" in the sense that you already know what to do here

No, I thought you knew what was going on, and your change was a one-liner, so making the change looked easy. But reading your description, we seem to be hitting multiple issues here.

I am really sorry that I can not offer more support. I am completely swamped by other issues and projects, so this issue here is really low priority for me. I won't be able to help more right now. Pull requests are welcome though, if you have at least some smaller fixes that may help.

**Comment by iMichka** [comment]
Closing here as I am really not working on this. Anybody can pick this up, and pull requests are welcome.
