### ISSUE TITLE
compcert installation error

### ISSUE THREAD

**Issue by ntysdd** [Homebrew/linuxbrew-core#12103]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
`brew install compcert`

- What happened (include command output)
```
File "cparser/pre_parser.mli", line 1:
Error: /home/linuxbrew/.linuxbrew/Cellar/menhir/20180905/share/menhir/menhirLib.cmi
is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
```

- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

https://gist.github.com/0976411e01a514e674e86991cae9f31f

**Comment by iMichka** [comment]
I started working on this. I am building the missing bottles from the dependencies one by one.
`ocaml-num` has been built and uploaded.

`coq` is the next one: #12147

**Comment by ntysdd** [comment]
Thank you.
