### ISSUE TITLE
gcc/glibc is outdated, errors out when building libvpx

### ISSUE THREAD

**Issue by slhck** [Homebrew/linuxbrew-core#12102]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

### What you were trying to do (and why)

I am trying to compile libvpx using the [steps mentioned here](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu). I have `gcc` installed through Linuxbrew.

#### What happened (include command output)

With the gcc shipped by Linuxbrew, this fails with a rather obscure error:

```
make[1]: *** No rule to make target '/usr/include/x86_64-linux-gnu/bits/libio.h', needed by 'vpx/src/vpx_decoder.c.o'.  Stop.
```

According to libvpx devs, and looking into the source code, `libio.h` isn't even used. So I forcibly remove gcc from Linuxbrew, try again with the gcc shipped by Ubuntu (`gcc (Ubuntu 8.2.0-7ubuntu1) 8.2.0`), and it works.

### Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install gcc
git -C libvpx pull 2> /dev/null || git clone --depth 1 https://chromium.googlesource.com/webm/libvpx.git && \
cd libvpx && \
PATH="$HOME/bin:$PATH" ./configure --prefix="$HOME/ffmpeg_build" --disable-examples --disable-unit-tests --enable-vp9-highbitdepth --as=yasm && \
PATH="$HOME/bin:$PATH" make
```

Seeing that gcc in Linuxbrew is 5.5.0 which was released in 2017, I think that a much more recent one should be shipped. Possibly the underlying issue is `glibc`? I am not too experienced with building under Linux to pinpoint exactly what goes wrong. But I know that [`libio.h` was deprecated](https://patchwork.kernel.org/patch/10158257/) and removed.

**Comment by iMichka** [comment]
> Seeing that gcc in Linuxbrew is 5.5.0 which was released in 2017

We do plan to update gcc soon (somewhere in the next 18 months I think). Right now we ship this one because we support older Linux versions.
You may try to use `brew install gcc@8` to get a newer version.

Could you try with `gcc@8`?

There may be another issue though, and we will need more time to debug this.

**Comment by slhck** [comment]
I can confirm that building works with `gcc@8`. Thanks for the suggestion!

Shall we keep this open until the new `gcc` version is released in Linuxbrew? I can't judge whether the underlying issue (whatever it is, exactly) could prevent other software builds from failing. I think one problem is that `gcc` was only installed as a dependency – and I didn't realize it was being used instead of the system default.

**Comment by iMichka** [comment]
> Shall we keep this open until the new `gcc` version is released in Linuxbrew?

This may take up to 18 months.

We could change the `libvpx` to use `gcc@8`, but as it builds fine on our CI, and for me locally, I do not want to do that change right now. It seems to be a compiler mixup on your setup. I have no clue how to fix this.

So unless we want to spend more time investigation, I propose to close this, as you have the `gcc@8` workaround.

**Comment by slhck** [comment]
> It seems to be a compiler mixup on your setup.

Not really; it's just that the old `gcc` apparently cannot be used for building (some) current software. Since it was installed as a byproduct of some other Linuxbrew installation, I didn't know it was overriding the default `gcc` shipped with Ubuntu.

I'll close this then, as there seems to be a workaround.
