### ISSUE TITLE
Can't install ledger

### ISSUE THREAD

**Issue by MetalGearDaner** [Homebrew/linuxbrew-core#12104]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

---

The gist-log link is: https://gist.github.com/MetalGearDaner/505bb3ae0cb2fdd78ad40d8487812154

I'm having issues while installing ledger. I have used the commando` brew install ledger` and the result is this:

```
==> Downloading https://github.com/ledger/ledger/archive/3.1.2.tar.gz
Already downloaded: /home/daniel/.cache/Homebrew/downloads/3afb688c9e5ed18cb5b3a16e23fb212cdf08ce074fc1faa4ad3cf82257803d20--ledger-3.1.2.tar.gz
==> ./acprep opt make --jobs=4 --output=build --prefix=/home/linuxbrew/.linuxbre
==> ./acprep opt make doc --jobs=4 --output=build --prefix=/home/linuxbrew/.linu
Last 15 lines from /home/daniel/.cache/Homebrew/Logs/ledger/02.acprep:
[  0%] Built target doc.doxygen
Scanning dependencies of target doc
[100%] Generating ledger.1.html
groff: can't find `DESC' file
groff:fatal error: invalid device `html' (try installing the `groff' package?)
doc/CMakeFiles/doc.dir/build.make:60: recipe for target 'doc/ledger.1.html' failed
make[3]: *** [doc/ledger.1.html] Error 3
make[3]: *** Deleting file 'doc/ledger.1.html'
CMakeFiles/Makefile2:185: recipe for target 'doc/CMakeFiles/doc.dir/all' failed
make[2]: *** [doc/CMakeFiles/doc.dir/all] Error 2
CMakeFiles/Makefile2:192: recipe for target 'doc/CMakeFiles/doc.dir/rule' failed
make[1]: *** [doc/CMakeFiles/doc.dir/rule] Error 2
Makefile:223: recipe for target 'doc' failed
make: *** [doc] Error 2
acprep: ERROR: Execution failed: make doc -j4

READ THIS: https://docs.brew.sh/Troubleshooting
```

I have already installed `groff` package but the error keeps happening.

**Comment by iMichka** [comment]
Fixed by #12105
