### ISSUE TITLE
Building `hello` on amzn2 with gcc 5.5.0_4 fails with "configure: error: C compiler cannot create executables"

### ISSUE THREAD

**Issue by MerelyAPseudonym** [Homebrew/linuxbrew-core#12128]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, ~Homebrew/homebrew-core formula (not cask) on macOS~ Homebrew/linuxbrew-core formula on Linux? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
**https://gist.github.com/db62a867d60c9beaae68c930a84f6f59**
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
I had recently installed Linuxbrew to `/home/linuxbrew/.linuxbrew` (via <https://docs.brew.sh/Homebrew-on-Linux#install>) on a fresh AWS EC2 instance running Amazon Linux 2, and was attempting to verify that everything was correctly set up by building the `hello` formula from source.
- What happened (include command output)
```sh-session
$ brew install --build-from-source hello
==> Downloading https://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
Already downloaded: /home/jtilles/.cache/Homebrew/downloads/0d3dc7a1e45d7ac6eb8d853c8ecccad6a4ab6abbbf38038f552e4735ad15d3cc--hello-2.10.tar.gz
==> ./configure --disable-silent-rules --prefix=/home/linuxbrew/.linuxbrew/Cellar/hello/2.10
Last 15 lines from /home/jtilles/.cache/Homebrew/Logs/hello/01.configure:
--disable-silent-rules
--prefix=/home/linuxbrew/.linuxbrew/Cellar/hello/2.10

configure: WARNING: unrecognized options: --disable-debug
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc-5
checking whether the C compiler works... no
configure: error: in `/tmp/hello-20190320-25913-188wmqj/hello-2.10':
configure: error: C compiler cannot create executables
See `config.log' for more details

READ THIS: https://docs.brew.sh/Troubleshooting
```
- What you expected to happen
Something roughly equivalent to what I see from a successful build on a local Mac:
```sh-session
$ brew install --build-from-source hello
==> Downloading https://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
Already downloaded: /Users/jtilles/Library/Caches/Homebrew/downloads/0d3dc7a1e45d7ac6eb8d853c8ecccad6a4ab6abbbf38038f552e4735ad15d3cc--hello-2.10.tar.gz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/hello/2.10
==> make install
🍺  /usr/local/Cellar/hello/2.10: 11 files, 125.3KB, built in 53 seconds
```
- Step-by-step reproduction instructions (by running `brew install` commands)
It's just a single command: `brew install --build-from-source hello`

A couple details to note:
1. Because I was trying to figure out how minimal the impact of setting up Linuxbrew on the rest of the system could be, I did *not* execute the commands from <https://docs.brew.sh/Homebrew-on-Linux#fedora-centos-or-red-hat>. My thinking was that brew would just download whatever was lacking and/or that `brew doctor` would let me know what system utilities were truly necessary.
2. In case it matters, here's all of the installed formulae:
```sh-session
$ brew ls
bzip2  expat  gettext  gmp	 libbsd  m4    ncurses	patchelf  zlib
curl   gcc    git      isl@0.18  libmpc  mpfr  openssl	pcre2
```

**Comment by MerelyAPseudonym** [comment]
By the way, in the future should I delete the opening paragraph of the issue template (“Please note we will close your issue without …”) after filling out the rest of the issue?

**Comment by MerelyAPseudonym** [comment]
Also, it might be relevant that `brew test gcc` also fails:

```sh-session
$ brew test --verbose gcc
Testing gcc
==> /home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/bin/gcc-5 -o hello-c hello-c.c
hello-c.c:1:19: fatal error: stdio.h: No such file or directory
compilation terminated.
Error: gcc: failed
Failed executing:
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1911:in `block in system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1848:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1848:in `system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb:313:in `block in <class:Gcc>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1724:in `block (3 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:476:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1723:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:864:in `with_logging'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1722:in `block in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1961:in `block in mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:55:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:55:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:55:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1960:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1716:in `run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:28:in `block in <main>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by iMichka** [comment]
@sjackman Do you have a little bit of time to look at this? I need to handle the incoming `boost` bump, and `llvm 8` upgrade in the next days.

**Comment by sjackman** [comment]
> By the way, in the future should I delete the opening paragraph of the issue template (“Please note we will close your issue without …”) after filling out the rest of the issue?

Yes, that'd be fine.

**Comment by sjackman** [comment]
> Because I was trying to figure out how minimal the impact of setting up Linuxbrew on the rest of the system could be, I did not execute the commands from https://docs.brew.sh/Homebrew-on-Linux#fedora-centos-or-red-hat.

These are nearly the minimum dependencies needed to install Homebrew on Linux. It's possible if you wanted to use some fewer host provided dependencies and use brewed dependencies instead.

```
hello-c.c:1:19: fatal error: stdio.h: No such file or directory
```

You need to install the `glibc` development package `glibc-devel` that includes libraries and headers.

> My thinking was that brew would just download whatever was lacking and/or that brew doctor would let me know what system utilities were truly necessary.

It's not that smart, yet, but it could be. You could open a PR if you're interested in working on that.
