### ISSUE TITLE
Valgrind failed to build on Ubuntu 16.04 LTS x86_64 due to default 32 bit option

### ISSUE THREAD

**Issue by thbtppl** [Homebrew/linuxbrew-core#12149]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Why is linuxbrew trying to build valgrind with the option `--enable-only32bit` by default? It seems to be the issue for building whilst I'm on a x64 architecture.
The gist is [https://gist.github.com/501da4f818320e051422d21ab01f67a1](https://gist.github.com/501da4f818320e051422d21ab01f67a1)

Command is `brew install valgrind`

**Comment by iMichka** [comment]
Hi. Thanks for reporting. I am trying to fix this here: #12157

Let's continue the discussion on the PR if there is any other issue.

**Comment by iMichka** [comment]
Fixed by #12157
