### ISSUE TITLE
node 11.12 formula might be broken

### ISSUE THREAD

**Issue by andreineculau** [Homebrew/linuxbrew-core#12148]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

`brew install node` ends up with these errors https://travis-ci.com/tobiipro/support-firecloud/jobs/186520556#L2452 on travis ci, same on circleci https://circleci.com/gh/tobiipro/support-firecloud/668

Since node 11.12 was releases a few days ago, made it to homebrew 2 days ago and to linuxbrew <12 hours ago (i'm guessing, judging that 12 hours ago, our jobs ran fine as they downloaded node 11.11), I'm opening the issue here. I don't see anyone with this issue reporting towards the node issue tracker. Thanks!

**Comment by iMichka** [comment]
Hi.

I just pushed the bottle for `node` in  #12143. It built fine on our CI. This will probably fix it for you.
Not sure how to fix the errors you have on your CI, but with the bottle you will not need to rebuild node from source.

The only thing I saw is that the node test is broken in Linuxbrew. But this has been the case for years, and I was never able to fix it.

**Comment by andreineculau** [comment]
Rerun the same jobs and they succeeded this time. Thanks!

**Comment by andreineculau** [comment]
and broken again... so I cannot basically compile node on my own with (my setup? of) travis and circleci.. googleing around shows up tickets like https://github.com/nodejs/node/issues/8144 - out of memory.

can you point me in the right direction to see how your CI is set up?
travis advertises 3 gigs, I guess your CI has more

if I look at this from the other direction - I would be happy telling brew "install the latest version that has a bottle". I could figure out that via git magic maybe. Are there other ways you know of to do that?

Thanks in advance!

**Comment by iMichka** [comment]
Each time we bump the node version, there is a more or less short time without pre-compiled bottle. And this is not going to change, due to our current workflow.

I do reduce the number of cores for circle to make this work:
```
# Reduce memory usage below 4 GB for Circle CI.
ENV["MAKEFLAGS"] = "-j8" if ENV["CIRCLECI"]
```

Or you may pay for a circle-ci subscription to get more Ram.

Or lobby the node developers to optimise their build system.

**Comment by andreineculau** [comment]
> Each time we bump the node version, there is a more or less short time without pre-compiled bottle. And this is not going to change, due to our current workflow.

ofc!

> -j8

!!! why didn't think of it! Thanks I can try it out

> Are there other ways you know of to do that?

Is there no way to associate the latest bottle available on bintray with a git hash, so I can do `brew install ...url.to.node.rb.at.<git-hash>...` ? Or maybe the git hash is not needed. Can one install directly a bottle?

**Comment by iMichka** [comment]
You could try to look at ‘brew install --force-bottle’. Maybe also use the HOMEBREW_NO_AUTO_UPDATE env flag. That may fix your workflow. And you would update manually only when you are sure that the update works for you.

**Comment by andreineculau** [comment]
By all means: thank you!

**Comment by andreineculau** [comment]
for future readers, nothing really worked, so today when i experienced this again, I resorted to 2 things

1. Travis doesn't have any swap, so create one https://github.com/tobiipro/support-firecloud/blob/40501856dc34acf6769c0f3d603997d687b9558a/ci/linux/bootstrap#L9-L20 . This alone would probably fix the build from failing, but it does take a lot of time

2. Find last `node.rb` commit with a bottle update https://github.com/tobiipro/support-firecloud/blob/749cab7f7ba6e96369e5c473965e7840366f440a/ci/brew-install-node.inc.sh#L6-L13

Will see the outcome next time the node formula gets updated, and there's no bottle for it.
