### ISSUE TITLE
Installing mariadb gives make Error 2

### ISSUE THREAD

**Issue by MathiasTG** [Homebrew/linuxbrew-core#12189]
Just installed linuxbrew-wrapper, tried installing mariadb and this came at me (inserted below).
Running Ubuntu 18.04 LTS.

Uploaded gist-logs:
https://gist.github.com/MathiasTG/adcedda25e8b51b28c356aba923dadaa

Ran brew update, everything up to date. Clean bill of health from brew doctor.

Been looking around but i couldnt find any similar issue.
Any help is really appreciated.

`brew install mariadb
==> Downloading https://downloads.mariadb.org/f/mariadb-10.3.13/source/mariadb-1
Already downloaded: /home/mtg/.cache/Homebrew/downloads/a969154d7e4be2f9a1b0b7c2ca19900bbfb7cd3a5edc1891828350b382338573--mariadb-10.3.13.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG 
==> make
Last 15 lines from /home/mtg/.cache/Homebrew/Logs/mariadb/02.make:
cd /tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga && /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-7  -DHAVE_CONFIG_H -DMRN_GROONGA_EMBEDDED -DMRN_GROONGA_NORMALIZER_MYSQL_EMBEDDED -DMYSQL_DYNAMIC_PLUGIN -DWITH_GROONGA_NORMALIZER_MYSQL=1 -D_FILE_OFFSET_BITS=64 -Dmroonga_EXPORTS -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/include -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga/lib -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/sql -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/pcre -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13 -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga/vendor/groonga/include  -pie -fPIC -Wl,-z,relro,-z,now -fstack-protector --param=ssp-buffer-size=4 -fno-rtti -DNDEBUG -D_FORTIFY_SOURCE=2 -DDBUG_OFF -fPIC   -o CMakeFiles/mroonga.dir/lib/mrn_count_skip_checker.cpp.o -c /tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga/lib/mrn_count_skip_checker.cpp
[ 86%] Building CXX object storage/mroonga/CMakeFiles/mroonga.dir/lib/mrn_query_parser.cpp.o
cd /tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga && /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-7  -DHAVE_CONFIG_H -DMRN_GROONGA_EMBEDDED -DMRN_GROONGA_NORMALIZER_MYSQL_EMBEDDED -DMYSQL_DYNAMIC_PLUGIN -DWITH_GROONGA_NORMALIZER_MYSQL=1 -D_FILE_OFFSET_BITS=64 -Dmroonga_EXPORTS -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/include -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga/lib -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/sql -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/pcre -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13 -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga/vendor/groonga/include  -pie -fPIC -Wl,-z,relro,-z,now -fstack-protector --param=ssp-buffer-size=4 -fno-rtti -DNDEBUG -D_FORTIFY_SOURCE=2 -DDBUG_OFF -fPIC   -o CMakeFiles/mroonga.dir/lib/mrn_query_parser.cpp.o -c /tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga/lib/mrn_query_parser.cpp
[ 86%] Building CXX object storage/mroonga/CMakeFiles/mroonga.dir/lib/mrn_smart_bitmap.cpp.o
cd /tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga && /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-7  -DHAVE_CONFIG_H -DMRN_GROONGA_EMBEDDED -DMRN_GROONGA_NORMALIZER_MYSQL_EMBEDDED -DMYSQL_DYNAMIC_PLUGIN -DWITH_GROONGA_NORMALIZER_MYSQL=1 -D_FILE_OFFSET_BITS=64 -Dmroonga_EXPORTS -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/include -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga/lib -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/sql -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/pcre -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13 -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga/vendor/groonga/include  -pie -fPIC -Wl,-z,relro,-z,now -fstack-protector --param=ssp-buffer-size=4 -fno-rtti -DNDEBUG -D_FORTIFY_SOURCE=2 -DDBUG_OFF -fPIC   -o CMakeFiles/mroonga.dir/lib/mrn_smart_bitmap.cpp.o -c /tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga/lib/mrn_smart_bitmap.cpp
[ 86%] Building CXX object storage/mroonga/CMakeFiles/mroonga.dir/lib/mrn_table_fields_offset_mover.cpp.o
cd /tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga && /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-7  -DHAVE_CONFIG_H -DMRN_GROONGA_EMBEDDED -DMRN_GROONGA_NORMALIZER_MYSQL_EMBEDDED -DMYSQL_DYNAMIC_PLUGIN -DWITH_GROONGA_NORMALIZER_MYSQL=1 -D_FILE_OFFSET_BITS=64 -Dmroonga_EXPORTS -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/include -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga/lib -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/sql -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/pcre -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13 -I/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga/vendor/groonga/include  -pie -fPIC -Wl,-z,relro,-z,now -fstack-protector --param=ssp-buffer-size=4 -fno-rtti -DNDEBUG -D_FORTIFY_SOURCE=2 -DDBUG_OFF -fPIC   -o CMakeFiles/mroonga.dir/lib/mrn_table_fields_offset_mover.cpp.o -c /tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga/lib/mrn_table_fields_offset_mover.cpp
[ 86%] Linking CXX shared module ha_mroonga.so
cd /tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga && /home/linuxbrew/.linuxbrew/Cellar/cmake/3.14.0/bin/cmake -E cmake_link_script CMakeFiles/mroonga.dir/link.txt --verbose=1
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-7 -fPIC  -pie -fPIC -Wl,-z,relro,-z,now -fstack-protector --param=ssp-buffer-size=4 -fno-rtti -DNDEBUG -D_FORTIFY_SOURCE=2 -DDBUG_OFF  -shared  -o ha_mroonga.so CMakeFiles/mroonga.dir/ha_mroonga.cpp.o CMakeFiles/mroonga.dir/mrn_table.cpp.o CMakeFiles/mroonga.dir/udf/mrn_udf_last_insert_grn_id.cpp.o CMakeFiles/mroonga.dir/udf/mrn_udf_snippet.cpp.o CMakeFiles/mroonga.dir/udf/mrn_udf_snippet_html.cpp.o CMakeFiles/mroonga.dir/udf/mrn_udf_command.cpp.o CMakeFiles/mroonga.dir/udf/mrn_udf_escape.cpp.o CMakeFiles/mroonga.dir/udf/mrn_udf_normalize.cpp.o CMakeFiles/mroonga.dir/udf/mrn_udf_highlight_html.cpp.o CMakeFiles/mroonga.dir/udf/mrn_udf_query_expand.cpp.o CMakeFiles/mroonga.dir/lib/mrn_match_escalation_threshold_scope.cpp.o CMakeFiles/mroonga.dir/lib/mrn_path_mapper.cpp.o CMakeFiles/mroonga.dir/lib/mrn_smart_grn_obj.cpp.o CMakeFiles/mroonga.dir/lib/mrn_index_table_name.cpp.o CMakeFiles/mroonga.dir/lib/mrn_index_column_name.cpp.o CMakeFiles/mroonga.dir/lib/mrn_debug_column_access.cpp.o CMakeFiles/mroonga.dir/lib/mrn_auto_increment_value_lock.cpp.o CMakeFiles/mroonga.dir/lib/mrn_external_lock.cpp.o CMakeFiles/mroonga.dir/lib/mrn_multiple_column_key_codec.cpp.o CMakeFiles/mroonga.dir/lib/mrn_field_normalizer.cpp.o CMakeFiles/mroonga.dir/lib/mrn_encoding.cpp.o CMakeFiles/mroonga.dir/lib/mrn_parameters_parser.cpp.o CMakeFiles/mroonga.dir/lib/mrn_lock.cpp.o CMakeFiles/mroonga.dir/lib/mrn_condition_converter.cpp.o CMakeFiles/mroonga.dir/lib/mrn_time_converter.cpp.o CMakeFiles/mroonga.dir/lib/mrn_database_manager.cpp.o CMakeFiles/mroonga.dir/lib/mrn_value_decoder.cpp.o CMakeFiles/mroonga.dir/lib/mrn_database_repairer.cpp.o CMakeFiles/mroonga.dir/lib/mrn_context_pool.cpp.o CMakeFiles/mroonga.dir/lib/mrn_operations.cpp.o CMakeFiles/mroonga.dir/lib/mrn_operation.cpp.o CMakeFiles/mroonga.dir/lib/mrn_database.cpp.o CMakeFiles/mroonga.dir/lib/mrn_column_name.cpp.o CMakeFiles/mroonga.dir/lib/mrn_count_skip_checker.cpp.o CMakeFiles/mroonga.dir/lib/mrn_query_parser.cpp.o CMakeFiles/mroonga.dir/lib/mrn_smart_bitmap.cpp.o CMakeFiles/mroonga.dir/lib/mrn_table_fields_offset_mover.cpp.o  -L/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga/vendor/groonga/lib  -L/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga/vendor/groonga/vendor/plugins/groonga-normalizer-mysql/normalizers  -L/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/libservices -Wl,-rpath,/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga/vendor/groonga/lib:/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/storage/mroonga/vendor/groonga/vendor/plugins/groonga-normalizer-mysql/normalizers:/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13/libservices: -lpthread ../../libservices/libmysqlservices.a vendor/groonga/lib/libgroonga.a vendor/groonga/vendor/plugins/groonga-normalizer-mysql/normalizers/libmysql_normalizer.a vendor/groonga/lib/libgroonga.a -lpthread -lrt -lpthread -lz -ldl -lm -lstdc++ 
make[2]: Leaving directory '/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13'
[ 86%] Built target mroonga
make[1]: Leaving directory '/tmp/mariadb-20190325-5463-18ms7ou/mariadb-10.3.13'
Makefile:154: recipe for target 'all' failed
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
mariadb: Build a bottle for Linuxbrew https://github.com/Homebrew/linuxbrew-core/pull/12184
`

**Comment by iMichka** [comment]
This should be fixed by #12184, I built binaries for mariadb. I can not reproduce this error on our CI, so unless you demonstrate a reproducible example of this inside a docker container, I can not do much more.
