### ISSUE TITLE
ponyc failed to install on Ubuntu 18.10 with undefined method error

### ISSUE THREAD

**Issue by jec** [Homebrew/linuxbrew-core#12233]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I'm trying to install `ponyc` on Ubuntu 18.10, and I get the error `undefined method 'installed?' for OS::Mac::Xcode:Module`.

I ran `brew update` twice and `brew doctor` and have included those below, along with the `brew install` command and its output.

```
jim@jim-thinkpad-p1:~% brew update
Already up-to-date.
jim@jim-thinkpad-p1:~% brew update
Already up-to-date.
jim@jim-thinkpad-p1:~% brew doctor
Your system is ready to brew.
jim@jim-thinkpad-p1:~% brew install ponyc
Error: undefined method `installed?' for OS::Mac::Xcode:Module
Did you mean?  instance_of?
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirements/xcode_requirement.rb:14:in `xcode_installed_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirements/xcode_requirement.rb:6:in `block in <class:XcodeRequirement>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:58:in `instance_eval'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:58:in `block in satisfied?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:189:in `yielder'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:58:in `satisfied?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:438:in `block in expand_requirements'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:220:in `block in prune?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:218:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:218:in `prune?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:208:in `block (2 levels) in expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:306:in `each_key'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/set.rb:306:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/delegate.rb:341:in `block in delegating_block'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:207:in `block in expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:206:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:206:in `expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1525:in `recursive_requirements'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:432:in `expand_requirements'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:370:in `compute_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:141:in `verify_deps_exist'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:134:in `prelude'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:318:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:251:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:249:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:249:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'
```

I ran `brew gist-logs ponyc` and it created the gist at https://gist.github.com/jec/b6c94ddf6177be9a34872be2429dba14 .

I've used homebrew on macOS for years, and it's great! This is my first attempt at using it on Linux.

**Comment by iMichka** [comment]
Fixed by #12356 and #12459
