### ISSUE TITLE
util-linux 2.32.1 build fails on Ubuntu 16.04 LTS x86_64

### ISSUE THREAD

**Issue by thbtppl** [Homebrew/linuxbrew-core#12270]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Trying to install util-linux with `brew install util-linux` after a `brew update` several minutes ago.
Configure stage seems to work, and make install step fails.
The output link for the gist is
[https://gist.github.com/a7caff9c5bfc85751440768d67db2a2f](https://gist.github.com/a7caff9c5bfc85751440768d67db2a2f)

End of error message is 

```
make[2]: Leaving directory '/tmp/util-linux-20190328-55785-1ywqje9/util-linux-2.32.1'
Makefile:12106: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/tmp/util-linux-20190328-55785-1ywqje9/util-linux-2.32.1'
Makefile:12409: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by iMichka** [comment]
#12271 should fix this.
