### ISSUE TITLE
Flex 2.6.4 causes segfault on build

### ISSUE THREAD

**Issue by darkclouder** [Homebrew/linuxbrew-core#12313]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why):
Install flex
- What happened (include command output)
```
Last 15 lines from /home/.../.cache/Homebrew/Logs/flex/02.make:
libtool: link: gcc-7 -shared  -fPIC -DPIC  .libs/libmain.o .libs/libyywrap.o   -lm  -g -O2   -Wl,-soname -Wl,libfl.so.2 -o .libs/libfl.so.2.0.0
libtool: link: (cd ".libs" && rm -f "libfl.so.2" && ln -s "libfl.so.2.0.0" "libfl.so.2")
libtool: link: (cd ".libs" && rm -f "libfl.so" && ln -s "libfl.so.2.0.0" "libfl.so")
libtool: link: ar cru .libs/libfl.a  libmain.o libyywrap.o
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: ranlib .libs/libfl.a
libtool: link: ( cd ".libs" && rm -f "libfl.la" && ln -s "../libfl.la" "libfl.la" )
/bin/bash ../libtool  --tag=CC   --mode=link gcc-7  -g -O2   -o stage1flex stage1flex-scan.o stage1flex-buf.o stage1flex-ccl.o stage1flex-dfa.o stage1flex-ecs.o stage1flex-filter.o stage1flex-gen.o stage1flex-main.o stage1flex-misc.o stage1flex-nfa.o stage1flex-options.o stage1flex-parse.o stage1flex-regex.o stage1flex-scanflags.o stage1flex-scanopt.o stage1flex-skel.o stage1flex-sym.o stage1flex-tables.o stage1flex-tables_shared.o stage1flex-tblcmp.o stage1flex-yylex.o    -lm 
libtool: link: gcc-7 -g -O2 -o stage1flex stage1flex-scan.o stage1flex-buf.o stage1flex-ccl.o stage1flex-dfa.o stage1flex-ecs.o stage1flex-filter.o stage1flex-gen.o stage1flex-main.o stage1flex-misc.o stage1flex-nfa.o stage1flex-options.o stage1flex-parse.o stage1flex-regex.o stage1flex-scanflags.o stage1flex-scanopt.o stage1flex-skel.o stage1flex-sym.o stage1flex-tables.o stage1flex-tables_shared.o stage1flex-tblcmp.o stage1flex-yylex.o  -lm
./stage1flex   -o stage1scan.c ./scan.l
Makefile:1696: recipe for target 'stage1scan.c' failed
make[1]: *** [stage1scan.c] Segmentation fault (core dumped)
make[1]: Leaving directory '/tmp/flex-20190329-28483-5movv4/flex-2.6.4/src'
Makefile:533: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```
- What you expected to happen
To Install
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install flex`

This seems to be a problem with flex 2.6.4, according to the flex issue tracker: https://github.com/westes/flex/issues/219

I installed it with 2.6.3 through an old version of the formula and it worked: `brew install https://raw.githubusercontent.com/Homebrew/linuxbrew-core/6c47135b3341496dd5dd2c00e5ba578374c9a577/Formula/flex.rb`.
Consider removing 2.6.4 from the formula.

**Comment by iMichka** [comment]
Hi. Thanks for reporting. Did you try to add this patch to the formula? https://github.com/westes/flex/pull/221

If this works, we can patch the current version until 2.6.5 is out.

**Comment by darkclouder** [comment]
That patch seems to don't do it for me.
Added
```
  # https://github.com/westes/flex/pull/221 fixes https://github.com/westes/flex/issues/219
  # Should be fixed with 2.6.5 too
  patch do
    url "https://github.com/westes/flex/commit/23797fd0b0908dd2c5775e6135728c7384f4e952.diff?full_index=1"
    sha256 "a06b8d29adcedc75749fb52714221844dd19a269fb53c5ea45f7a9023f44b8b3"
  end
```
To the formula right above `def install`.

Output:
```
$ brew reinstall flex -s
==> Reinstalling flex 
==> Downloading https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz
Already downloaded: /home/.../.cache/Homebrew/downloads/4c923b0def66967b27bb97fc512c040d33b8c116a7a7bf01ffc4170e2a7aef41--flex-2.6.4.tar.gz
==> Downloading https://github.com/westes/flex/commit/23797fd0b0908dd2c5775e6135728c7384f4e952.diff?full_index=1
#=#=-#  #                                                                     
==> Patching
==> Applying 23797fd0b0908dd2c5775e6135728c7384f4e952.diff
patching file configure.ac
patching file src/misc.c
==> ./configure --disable-silent-rules --enable-shared --prefix=/d1/data/.../.linuxbrew/Cellar/flex/2.6.4
==> make install
Last 15 lines from /home/.../.cache/Homebrew/Logs/flex/02.make:
libtool: link: (cd ".libs" && rm -f "libfl.so.2" && ln -s "libfl.so.2.0.0" "libfl.so.2")
libtool: link: (cd ".libs" && rm -f "libfl.so" && ln -s "libfl.so.2.0.0" "libfl.so")
config.status: creating src/config.h
libtool: link: ar cru .libs/libfl.a  libmain.o libyywrap.o
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: ranlib .libs/libfl.a
libtool: link: ( cd ".libs" && rm -f "libfl.la" && ln -s "../libfl.la" "libfl.la" )
/bin/bash ../libtool  --tag=CC   --mode=link gcc-7  -g -O2   -o stage1flex stage1flex-scan.o stage1flex-buf.o stage1flex-ccl.o stage1flex-dfa.o stage1flex-ecs.o stage1flex-filter.o stage1flex-gen.o stage1flex-main.o stage1flex-misc.o stage1flex-nfa.o stage1flex-options.o stage1flex-parse.o stage1flex-regex.o stage1flex-scanflags.o stage1flex-scanopt.o stage1flex-skel.o stage1flex-sym.o stage1flex-tables.o stage1flex-tables_shared.o stage1flex-tblcmp.o stage1flex-yylex.o    -lm 
libtool: link: gcc-7 -g -O2 -o stage1flex stage1flex-scan.o stage1flex-buf.o stage1flex-ccl.o stage1flex-dfa.o stage1flex-ecs.o stage1flex-filter.o stage1flex-gen.o stage1flex-main.o stage1flex-misc.o stage1flex-nfa.o stage1flex-options.o stage1flex-parse.o stage1flex-regex.o stage1flex-scanflags.o stage1flex-scanopt.o stage1flex-skel.o stage1flex-sym.o stage1flex-tables.o stage1flex-tables_shared.o stage1flex-tblcmp.o stage1flex-yylex.o  -lm
./stage1flex   -o stage1scan.c ./scan.l
Makefile:1696: recipe for target 'stage1scan.c' failed
make[1]: *** [stage1scan.c] Segmentation fault (core dumped)
make[1]: Leaving directory '/tmp/flex-20190330-45192-1q8j13x/flex-2.6.4/src'
Makefile:534: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
Flex 2.6.4 causes segfault on build https://github.com/Homebrew/linuxbrew-core/issues/12313
```

**Comment by iMichka** [comment]
Could you try: `HOMEBREW_CC=gcc-5 HOMEBREW_CXX=g++5 brew install flex` ?

**Comment by olliencc** [comment]
> Could you try: `HOMEBREW_CC=gcc-5 HOMEBREW_CXX=g++5 brew install flex` ?

this worked for me!

**Comment by iMichka** [comment]
Maybe you hit this issue, which is now fixed: https://github.com/Homebrew/brew/pull/5958
Did you have `gcc@7` installed on your system?

It may also be that the system gcc-7 was used here, and it was conflicting with other libraries from homebrew that are built with gcc-5.

As we have a workaround, I propose that we close this issue.
