### ISSUE TITLE
brew install ninja broken on linux

### ISSUE THREAD

**Issue by acgetchell** [Homebrew/linuxbrew-core#12430]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.

This is a linuxbrew issue and the template given above points here.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

https://travis-ci.org/acgetchell/CDT-plusplus/jobs/514859478

To help us debug your issue please explain:
- What you were trying to do (and why)
Install Ninja
- What happened (include command output)
https://travis-ci.org/acgetchell/CDT-plusplus/jobs/514859478#L763
- What you expected to happen
The formula to install
- Step-by-step reproduction instructions (by running `brew install` commands)
brew install Ninja on Travis-CI:

**Comment by iMichka** [comment]
The bug is in the `python@2` build, see:
https://stackoverflow.com/questions/55464231/when-command-brew-install-python2-then-error-theme-error-how-to-resolve

I have no solution for this right now. But it looks like it tried to build `python@2` from source. We have a bottle now (your build probably hit the few minutes were there was no bottle on linuxbrew). So I consider this fixed by that workaround. Of course it would be great if somebody could dig further into this.
