### ISSUE TITLE
pandoc fails to build on Ubuntu 18.04

### ISSUE THREAD

**Issue by pgcudahy** [Homebrew/linuxbrew-core#12473]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/pgcudahy/a50848800874293af20f601d9978beda

- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
Upgrade pandoc
- What happened (include command output)

https://gist.github.com/pgcudahy/a50848800874293af20f601d9978beda

- What you expected to happen
Upgrade and install pandoc
- Step-by-step reproduction instructions (by running `brew install` commands)
brew upgrade pandoc

**Comment by pgcudahy** [comment]
The error mentioned both gcc-5 and gcc-7. I tried`HOMEBREW_CC=gcc-7 HOMEBREW_CXX=g++7 brew upgrade pandoc` and it works! But I have no idea why.

**Comment by iMichka** [comment]
Hi. I also built a bottle with our CI here: #12497

If we have a workaround, I propose to close this. I personally do not have time to look at this more in detail.
