### ISSUE TITLE
brew install ccls failed on debian 9

### ISSUE THREAD

**Issue by fcying** [Homebrew/linuxbrew-core#12509]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?
```
$brew config
HOMEBREW_VERSION: 2.1.0-30-g1c65591
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1c655916fe9a9fd46b73fc23f5f54d15d934b8f9
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core.git
Core tap HEAD: 3a7fc784ff25781954a64c8a1154efc9757ec482
Core tap last commit: 29 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/fcying/.cache/Homebrew
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LOGS: /home/fcying/.cache/Homebrew/Logs
HOMEBREW_VISUAL: vim
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 6.0 build 600
Git: 2.11.0 => /usr/bin/git
Curl: 7.52.1 => /usr/bin/curl
Kernel: Linux 4.9.0-8-amd64 x86_64 GNU/Linux
OS: Debian GNU/Linux 9.8 (stretch) (stretch)
Host glibc: 2.24
/usr/bin/gcc: 6.3.0
glibc: N/A
gcc: N/A
xorg: N/A

$ brew doctor
Your system is ready to brew.
```

To help us debug your issue please explain:
- What you were trying to do (and why)
brew install ccls
- What happened (include command output)
install failed
```
$brew install ccls
Updating Homebrew...
==> Installing dependencies for ccls: rapidjson, libffi, gmp, mpfr, libmpc, isl@0.18, gcc, binutils, libedit, libelf, xz, python, libxml2 and llvm
==> Installing ccls dependency: rapidjson
==> Downloading https://github.com/miloyip/rapidjson/archive/v1.1.0.tar.gz
Already downloaded: /home/fcying/.cache/Homebrew/downloads/1162750ef7f177edea51e3a8d7792250c8376c3260982579c2f784dcd5de979a--rapidjson-1.1.0.tar.gz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/rapidjson/1.1.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_
==> make install
Last 15 lines from /home/fcying/.cache/Homebrew/Logs/rapidjson/02.make:
Generating hierarchical class index...
Generating member index...
Generating file index...
Generating file member index...
Generating example index...
finalizing index lists...
writing tag file...
lookup cache used 2783/65536 hits=44276 misses=2985
finished...
/home/linuxbrew/.linuxbrew/Cellar/cmake/3.14.1/bin/cmake -E touch /tmp/rapidjson-20190412-58994-1fuz7tv/rapidjson-1.1.0/doc/html
make[2]: Leaving directory '/tmp/rapidjson-20190412-58994-1fuz7tv/rapidjson-1.1.0'
[ 12%] Built target doc
make[1]: Leaving directory '/tmp/rapidjson-20190412-58994-1fuz7tv/rapidjson-1.1.0'
Makefile:143: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by iMichka** [comment]
It's `rapidjson` which is failing to build, not `ccls`.

**Comment by fcying** [comment]
@iMichka 
I test `brew install rapidjson`, it can gen gist-logs
```
https://gist.github.com/fcying/655cbb1b40e7c28081c33f61054898f3
```
`rapidjson` need `ccache`, but not check dependencies, after I install `ccache`, It can be installed.
```
brew info rapidjson
==> Dependencies
Build: cmake ✔, doxygen ✔
```
