### ISSUE TITLE
python@2 failing to build on fedora 29 x64

### ISSUE THREAD

**Issue by yilkalargaw** [Homebrew/linuxbrew-core#12519]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

I tried to install crystal-lang using linuxbrew so I ran brew install crystal-lang. It installed all the other dependencies but failed on installing python@2.  I have installed linux brew as a non  root user in the ~/.linuxbrew directory. I use the Fedora 29 x64 . 

The installation does not fail on building the python 2 but rather on building the documentation using make html command. I checked out the formula and it has a single codeblock building the documentation.  

I tried to replicate the issue on a digialocean container but It worked fine on the fedora droplet. I was able to replicate the issue using a new installaiton of fedora 29 on virtual machine.

the output of running brew install python@2 is 
```
==> Downloading https://www.python.org/ftp/python/2.7.16/Python-2.7.16.tar.xz
Already downloaded: /home/convolutioner/.cache/Homebrew/downloads/443be8562a8907a15ac37e78a8fe5f42b5341c566a2dbb59db3aa2c910ce8b5b--Python-2.7.16.tar.xz
==> ./configure --prefix=/home/convolutioner/.linuxbrew/Cellar/python@2/2.7.16 -
==> make
==> make install PYTHONAPPSDIR=/home/convolutioner/.linuxbrew/Cellar/python@2/2.
==> Downloading https://files.pythonhosted.org/packages/c2/f7/c7b501b783e5a74cf1
Already downloaded: /home/convolutioner/.cache/Homebrew/downloads/6969a0201d69d0d7d7b40b24e8d0398bb05ba0864eaea9bc8a5c6c083188d9af--setuptools-40.8.0.zip
==> Downloading https://files.pythonhosted.org/packages/36/fa/51ca4d57392e2f6939
Already downloaded: /home/convolutioner/.cache/Homebrew/downloads/f2693316324c3d9eb7eeecc9579a7011cfea010f0ff3b2f6cee28b0f635d5a44--pip-19.0.3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/b7/cf/1ea0f5b3ce55cacde1
Already downloaded: /home/convolutioner/.cache/Homebrew/downloads/80ce15c6d4faca56ad3ddac06140426fa848de2d39ad1fc5b7088cd4b1d06518--wheel-0.33.1.tar.gz
==> make html
Last 15 lines from /home/convolutioner/.cache/Homebrew/Logs/python@2/04.make:
writing output... [ 98%] whatsnew/2.1
writing output... [ 98%] whatsnew/2.2
writing output... [ 98%] whatsnew/2.3
writing output... [ 99%] whatsnew/2.4
writing output... [ 99%] whatsnew/2.5
writing output... [ 99%] whatsnew/2.6
writing output... [ 99%] whatsnew/2.7
writing output... [100%] whatsnew/index

generating indices... genindex py-modindex
writing additional pages... download index
Theme error:
An error happened in rendering the page index.
Reason: TemplateNotFound()
make: *** [Makefile:40: build] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
Python: not configured with Tk and break matplotlib https://github.com/Homebrew/linuxbrew-core/issues/11256

```

**Comment by iMichka** [comment]
Hi. I think this has to do with https://github.com/Homebrew/homebrew-core/pull/38877#issuecomment-482579540. I think removing the docs building may be the best solution.

**Comment by yilkalargaw** [comment]
Yep I was wondering why python 3 was installed. I'll wait for the pull request to be merged.

**Comment by fcying** [comment]
I got the same problem on ubuntu 14.04 x64
```
==> make html
Last 15 lines from /home/fcying/.cache/Homebrew/Logs/python@2/04.make:
writing output... [ 98%] whatsnew/2.1
writing output... [ 98%] whatsnew/2.2
writing output... [ 98%] whatsnew/2.3
writing output... [ 99%] whatsnew/2.4
writing output... [ 99%] whatsnew/2.5
writing output... [ 99%] whatsnew/2.6
writing output... [ 99%] whatsnew/2.7
writing output... [100%] whatsnew/index

generating indices... genindex py-modindex
writing additional pages... download index
Theme error:
An error happened in rendering the page index.
Reason: TemplateNotFound()
make: *** [build] Error 2
```

**Comment by kigawas** [comment]
Definitely same problem and error logs on Centos 7 x64

**Comment by mrtndwrd** [comment]
Same problem on Ubuntu 18.04.1 LTS. Is there any specific reason why `make html` is run?

**Comment by yilkalargaw** [comment]
Current formula works.

**Comment by iMichka** [comment]
Yes. It is now fixed, we removed the doc building.

I will rebuild a bottle soon too.
