### ISSUE TITLE
brew install ccls failed on debian 9

### ISSUE THREAD

**Issue by fcying** [Homebrew/linuxbrew-core#12518]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/fcying/a9a5f70a2e9a06129b30512b330d0dc7
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
```
brew install ccls
```
- What happened (include command output)
install failed
```
$ brew install ccls
Updating Homebrew...
==> Downloading https://github.com/MaskRay/ccls/archive/0.20190314.tar.gz
Already downloaded: /home/fcying/.cache/Homebrew/downloads/e9f30d1765e81309bbb38b81ecf18399dd9087b823c36571462ea4490127cf6a--ccls-0.20190314.tar.gz
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/ccls/0.20190314 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FI
==> make install
Last 15 lines from /home/fcying/.cache/Homebrew/Logs/ccls/02.make:
make[2]: *** [CMakeFiles/ccls.dir/src/config.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/ccls.dir/build.make:78: recipe for target 'CMakeFiles/ccls.dir/src/clang_tu.cc.o' failed
make[2]: *** [CMakeFiles/ccls.dir/src/clang_tu.cc.o] Error 1
In file included from /tmp/ccls-20190412-77289-14gfg60/ccls-0.20190314/src/filesystem.cc:19:0:
/tmp/ccls-20190412-77289-14gfg60/ccls-0.20190314/src/utils.hh:18:20: fatal error: optional: No such file or directory
compilation terminated.
CMakeFiles/ccls.dir/build.make:104: recipe for target 'CMakeFiles/ccls.dir/src/filesystem.cc.o' failed
make[2]: *** [CMakeFiles/ccls.dir/src/filesystem.cc.o] Error 1
make[2]: Leaving directory '/tmp/ccls-20190412-77289-14gfg60/ccls-0.20190314'
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/ccls.dir/all' failed
make[1]: *** [CMakeFiles/ccls.dir/all] Error 2
make[1]: Leaving directory '/tmp/ccls-20190412-77289-14gfg60/ccls-0.20190314'
Makefile:132: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by fcying** [comment]
I test use gcc-7, it have another error
https://gist.github.com/fcying/20d29e0d526f3279064e833f2c0619a8
```
export HOMEBREW_CC=gcc-7
export HOMEBREW_CXX=g++-7
brew install ccls
Last 15 lines from /home/fcying/.cache/Homebrew/Logs/ccls/02.make:
/home/linuxbrew/.linuxbrew/bin/ld: CMakeFiles/ccls.dir/src/pipeline.cc.o: in function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<ccls::pipeline::LaunchStdin()::{lambda()#1}> > >::~_State_impl()':
pipeline.cc:(.text+0x1b8): undefined reference to `std::thread::_State::~_State()'
/home/linuxbrew/.linuxbrew/bin/ld: CMakeFiles/ccls.dir/src/pipeline.cc.o: in function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<ccls::pipeline::LaunchStdout()::{lambda()#1}> > >::~_State_impl()':
pipeline.cc:(.text+0x1e8): undefined reference to `std::thread::_State::~_State()'
/home/linuxbrew/.linuxbrew/bin/ld: CMakeFiles/ccls.dir/src/pipeline.cc.o:(.rodata+0x78): undefined reference to `typeinfo for std::thread::_State'
/home/linuxbrew/.linuxbrew/bin/ld: CMakeFiles/ccls.dir/src/pipeline.cc.o:(.rodata+0xf0): undefined reference to `typeinfo for std::thread::_State'
collect2: error: ld returned 1 exit status
CMakeFiles/ccls.dir/build.make:736: recipe for target 'ccls' failed
make[2]: *** [ccls] Error 1
make[2]: Leaving directory '/tmp/ccls-20190412-84283-1izo3gp/ccls-0.20190314'
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/ccls.dir/all' failed
make[1]: *** [CMakeFiles/ccls.dir/all] Error 2
make[1]: Leaving directory '/tmp/ccls-20190412-84283-1izo3gp/ccls-0.20190314'
Makefile:132: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by xu-cheng** [comment]
See https://github.com/Homebrew/homebrew-core/pull/39337 and https://github.com/Homebrew/brew/issues/6070
