### ISSUE TITLE
libvmaf does not create symlink in /usr/local/share

### ISSUE THREAD

**Issue by slhck** [Homebrew/linuxbrew-core#12531]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? ----> https://gist.github.com/slhck/2d9171330a505bfa599e73612da5bb6c
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? 

To help us debug your issue please explain:

## What you were trying to do (and why)

Install and use libvmaf in conjunction with ffmpeg.

## What happened (include command output)

libvmaf expects a resource file to be present in `/usr/local/share/model/vmaf_v0.6.1.pkl`. The directory is not present though, so libvmaf fails to run (e.g. when used from within ffmpeg).

## What you expected to happen

**The directory should be a symlink** to the Cellar path in which the `share/model` directory exists. Apparently that symlink is not created.

This is present under macOS:

```
$ ls -la /usr/local/share/model
… /usr/local/share/model -> ../Cellar/libvmaf/1.3.13/share/model
```

… but not with Linuxbrew:

```
$ ls -la /usr/local/share/model
ls: cannot access '/usr/local/share/model': No such file or directory
```

I can see that from the Linuxbrew `gist-logs` no such symlink is created:

```
make[1]: Entering directory '/tmp/libvmaf-20190412-29424-1q3nlbf/vmaf-1.3.13/wrapper'
mkdir -p /home/linuxbrew/.linuxbrew/Cellar/libvmaf/1.3.13/lib
mkdir -p /home/linuxbrew/.linuxbrew/Cellar/libvmaf/1.3.13/include
mkdir -p /home/linuxbrew/.linuxbrew/Cellar/libvmaf/1.3.13/share
mkdir -p /home/linuxbrew/.linuxbrew/Cellar/libvmaf/1.3.13/lib/pkgconfig
cp libvmaf.a /home/linuxbrew/.linuxbrew/Cellar/libvmaf/1.3.13/lib/libvmaf.a
cp src/libvmaf.h /home/linuxbrew/.linuxbrew/Cellar/libvmaf/1.3.13/include/
cp -r ../model /home/linuxbrew/.linuxbrew/Cellar/libvmaf/1.3.13/share/
cp libvmaf.pc /home/linuxbrew/.linuxbrew/Cellar/libvmaf/1.3.13/lib/pkgconfig/
make[1]: Leaving directory '/tmp/libvmaf-20190412-29424-1q3nlbf/vmaf-1.3.13/wrapper'
```

## Step-by-step reproduction instructions (by running `brew install` commands)

```
$ brew install libvmaf
$ brew tap varenc/ffmpeg
$ brew install varenc/ffmpeg/ffmpeg --with-libvmaf
$ ffmpeg -f lavfi -i testsrc -f lavfi -i testsrc -filter_complex libvmaf -f null /dev/null
ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-27ubuntu1~18.04)
  configuration: --prefix=/home/linuxbrew/.linuxbrew/Cellar/ffmpeg/4.1.3-with-options --enable-shared --enable-hardcoded-tables --cc=gcc-7 --host-cflags= --host-ldflags= --enable-gpl --enable-libaom --enable-libmp3lame --enable-libopus --enable-libsnappy --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --disable-libjack --disable-indev=jack --disable-htmlpages --enable-libvmaf --enable-version3
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, lavfi, from 'testsrc':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: rawvideo (RGB[24] / 0x18424752), rgb24, 320x240 [SAR 1:1 DAR 4:3], 25 tbr, 25 tbn, 25 tbc
Input #1, lavfi, from 'testsrc':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #1:0: Video: rawvideo (RGB[24] / 0x18424752), rgb24, 320x240 [SAR 1:1 DAR 4:3], 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 (rawvideo) -> libvmaf:main
  Stream #1:0 (rawvideo) -> libvmaf:reference
  libvmaf -> Stream #0:0 (wrapped_avframe)
Press [q] to stop, [?] for help
Start calculating VMAF score...
Input model at /usr/local/share/model/vmaf_v0.6.1.pkl cannot be read successfully.
Caught VmafException: Error loading model (.pkl): Trouble reading the file:/usr/local/share/model/vmaf_v0.6.1.pkl
[Parsed_libvmaf_0 @ 0x562b31dfb980] libvmaf encountered an error, check log for details
Error while filtering: Invalid argument
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #1:0
```

A Dockerfile to install and reproduce everything is [here](https://github.com/slhck/ffmpeg-quality-metrics/blob/master/Dockerfile).

**Comment by slhck** [comment]
As a workaround, the proper model path can be looked up with:

```
$(brew --prefix libvmaf)/share/model/vmaf_v0.6.1.pkl
```

This will always point to the latest installed version.

**Comment by slhck** [comment]
This is still an issue.

**Comment by dawidd6** [comment]
We do not install files anywhere but in prefix.

**Comment by slhck** [comment]
As you can see, under macOS the link is created:

    … /usr/local/share/model -> ../Cellar/libvmaf/1.3.13/share/model

But on Linuxbrew it isn't.

**Comment by dawidd6** [comment]
As I said, we **do not** install files outside the defined prefix.

**Comment by dawidd6** [comment]
Also you are installing ffmpeg from third party tap. This is not an issue on our side.

**Comment by slhck** [comment]
Please read the issue description. The third-party tap is just an application that uses libvmaf. I am installing libvmaf via `brew install libvmaf`, so the issue is not caused by a third party tap.

Is Linuxbrew behaving differently when compared to macOS Homebrew *on purpose*? Homebrew installs quite a few symlinks in `/usr/local/`. I have dozens there, from all sorts of formulae (git, perl, python, tmux, …).

**Comment by dawidd6** [comment]
Yes, Homebrew on Linux installs files to different prefix than macOS.
Linux: `/home/linuxbrew/.linuxbrew`
macOS: `/usr/local`

**Comment by slhck** [comment]
Okay, thanks a lot for the info. That makes things clearer.

However, I'm still not sure how this dependency can be resolved. Can ffmpeg (in Homebrew) be made aware of the different share path? I mean, we can't rewrite the software to call `brew --prefix libvmaf` during runtime… currently it's hardcoded to `/usr/local/share/model` in ffmpeg.

**Comment by dawidd6** [comment]
It always can be patched.
