### ISSUE TITLE
recon-ng Error while installing

### ISSUE THREAD

**Issue by thirtygreen** [Homebrew/linuxbrew-core#12651]
Hi,

I ran all the diagnostics. still doesn't work.

Trying to install recon-ng
Ended up with this message

InstallationError: Command "/home/linuxbrew/.linuxbrew/Cellar/recon-ng/4.9.4/libexec/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-wIrbP5/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-lp6WPO/install-record.txt --single-version-externally-managed --compile --install-headers /home/linuxbrew/.linuxbrew/Cellar/recon-ng/4.9.4/libexec/include/site/python2.7/lxml" failed with error code 1 in /tmp/pip-req-build-wIrbP5/

Was hoping it would install correctly
Ran command 'brew install recon-ng'

**Comment by issyl0** [comment]
Thanks for reporting this! I've managed to fix it, as far as I can tell, in the PR linked above. The install was failing at `pip install lxml` because required dependencies weren't there.

**Comment by issyl0** [comment]
@thirtygreen This should be fixed now, if you `brew update`.
