### ISSUE TITLE
`brew install gmp` fails on arm64

### ISSUE THREAD

**Issue by vielmetti** [Homebrew/linuxbrew-core#12681]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

```
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/gmp/6.1.2_2 --enable-cxx --with-pic --build=core2-linux-gnu
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/gmp/01.configure:
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking ABI=64
checking whether gcc-7 is gcc... yes
checking compiler gcc-7 -O2 -pedantic -fomit-frame-pointer -m64 ... no
checking ABI=x32
checking whether gcc-7 is gcc... yes
checking compiler gcc-7 -O2 -pedantic -fomit-frame-pointer -mx32 ... no
checking ABI=32
checking whether gcc-7 is gcc... yes
checking compiler gcc-7 -m32 -O2 -pedantic -fomit-frame-pointer ... no
checking compiler gcc-7 -O2 -pedantic -fomit-frame-pointer ... yes
checking compiler gcc-7 -O2 -pedantic -fomit-frame-pointer has sizeof(long)==4... no
configure: error: could not find a working compiler, see config.log for details
```

My usual suspicion in this is an outdated config.guess file somewhere.

**Comment by vielmetti** [comment]
Or perhaps for the changes in #4399 that force `--build=core2-linux-gnu` - my deep suspicion is that this isn't the right choice on arm64.

**Comment by vielmetti** [comment]
https://github.com/Homebrew/linuxbrew-core/blob/3b4960db14553aafdb0f57a18d7f5ca1c241e54c/Formula/gmp.rb#L28 looks like it wants a conditional for Intel vs arm64 to make this work.

**Comment by iMichka** [comment]
Hi. We would accept a pull request to fix this, but won't spend too much time to support arm64 issues. We are quite understaffed right now, so arm64 support is done on a case by case basis.

**Comment by vielmetti** [comment]
Understood! I'll work on a PR, especially if you can help me sort out how to test locally.
