### ISSUE TITLE
Cannot install Linuxbrew anymore (Probably caused by cdb4d41b903680c23839f6c465c427196586b282)

### ISSUE THREAD

**Issue by Thomas--S** [Homebrew/linuxbrew-core#12730]
I tried to install Homebrew/Linuxbrew today with 
```
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
```

It worked in the morning, but now, it doesn't work anymore.

I get this error twice:

```
Error: Invalid formula: /home/<username>/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
gcc: /home/<username>/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb:347: syntax error, unexpected end-of-input, expecting keyword_end
Error: Cannot tap homebrew/core: invalid syntax in tap!
Error: Failure while executing; `/home/<username>/.linuxbrew/bin/brew tap homebrew/core` exited with 1.
```

I'm not familiar with ruby or how Homebrew/Linuxbrew works internally, but I guess that the 
following change causes the problem:

https://github.com/Homebrew/linuxbrew-core/commit/cdb4d41b903680c23839f6c465c427196586b282#diff-baf58e557d0debf0bd219be97ec02ab8L96

**Comment by iMichka** [comment]
Can you try again? I just pushed a patch.

**Comment by Thomas--S** [comment]
Thank you very much for your quick reply!

Everything seems to work perfectly now again.

:+1:

**Comment by iMichka** [comment]
Thanks. Sorry for the mistake, I just saw the error at the same time you did :)
