### ISSUE TITLE
Can't upgrade/install gcc@8.

### ISSUE THREAD

**Issue by jendas1** [Homebrew/linuxbrew-core#12943]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I ran brew upgrade & got error on upgrading gcc@8 which also broke the previous installation of gcc-8, even uninstalled and tried to install it, always ends with an error. Gist is here: https://gist.github.com/c3239c4e56dd968b9ee1e4ff9e717497
Output
```makefile
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-8.2.0/gcc-8.2.0.tar.xz
Already downloaded: /cluster/home/studenyj/.cache/Homebrew/downloads/241c8efec83436d0c5a6fe75389062072fef694334fbbb253d612b0ef7e82cf4--gcc-8.2.0.tar.xz
==> Patching
patching file gcc/graphite.h
==> ../configure --with-bugurl=https://github.com/Linuxbrew/homebrew-core/issues --disable-multilib -
==> make
Last 15 lines from /cluster/home/studenyj/.cache/Homebrew/Logs/gcc@8/02.make:
/bin/sh ../../gcc/../move-if-change tmp-output.c insn-output.c
echo timestamp > s-output
/bin/sh ../../gcc/../move-if-change tmp-attrtab.c    insn-attrtab.c
/bin/sh ../../gcc/../move-if-change tmp-dfatab.c     insn-dfatab.c
/bin/sh ../../gcc/../move-if-change tmp-latencytab.c insn-latencytab.c
echo timestamp > s-attrtab
/bin/sh ../../gcc/../move-if-change tmp-automata.c insn-automata.c
echo timestamp > s-automata
rm gcc.pod
make[3]: Leaving directory '/tmp/gcc@8-20190507-23831-khwtlz/gcc-8.2.0/build/gcc'
make[2]: *** [Makefile:4618: all-stage1-gcc] Error 2
make[2]: Leaving directory '/tmp/gcc@8-20190507-23831-khwtlz/gcc-8.2.0/build'
make[1]: *** [Makefile:24352: stage1-bubble] Error 2
make[1]: Leaving directory '/tmp/gcc@8-20190507-23831-khwtlz/gcc-8.2.0/build'
make: *** [Makefile:945: all] Error 2
```

**Comment by jendas1** [comment]
Source of error (in .cache/Homebrew/Logs/gcc@8/02.make):
../../gcc/doc/invoke.texi:1758: unknown command `8-20190507-49165-ubr21i'
../../gcc/doc/invoke.texi:1758: @include: could not find /tmp/gcc/gcc-8.2.0/build/gcc/../../gcc/../libiberty/at-file.texi

**Comment by jendas1** [comment]
Any thoughts?

**Comment by jonchang** [comment]
#12960 probably fixed this. Run `brew update` again and see if that works. If not feel free to re-open this issue with updated debugging info.
