### ISSUE TITLE
install go using build when linuxbrew install at ~/.linuxbrew

### ISSUE THREAD

**Issue by fcying** [Homebrew/linuxbrew-core#13021]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
I test it at one machine, two accounts. One account(A) install brew in `/home/linuxbrew`, another(B) install brew in `~/.linuxbrew`.
Then I run `brew install go` with 2 accounts separately.
Account(A)  download bottle, Account(B) download go_src and build it.
Is this intentionally designed like this? Or is there any problem?

account(A):
```
$brew config
HOMEBREW_VERSION: 2.1.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4025eadc2c3b9b71aa7029d7ddc6ede1cb88d482
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: f603094587769353deb6cac5faf0f6de98324166
Core tap last commit: 34 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/fcying/.cache/Homebrew
HOMEBREW_LOGS: /home/fcying/.cache/Homebrew/Logs
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_VISUAL: vim
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 6.0 build 600
Git: 2.11.0 => /usr/bin/git
Curl: 7.52.1 => /usr/bin/curl
Kernel: Linux 4.9.0-9-amd64 x86_64 GNU/Linux
OS: Debian GNU/Linux 9.9 (stretch) (stretch)
Host glibc: 2.24
/usr/bin/gcc: 6.3.0
glibc: N/A
gcc: 5.5.0_4
xorg: N/A


$brew install go
==> Downloading https://linuxbrew.bintray.com/bottles/go-1.12.5.x86_64_linux.bottle.tar.gz
```

account(B):
```
$brew config    
HOMEBREW_VERSION: 2.1.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4025eadc2c3b9b71aa7029d7ddc6ede1cb88d482
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: f603094587769353deb6cac5faf0f6de98324166
Core tap last commit: 24 minutes ago
HOMEBREW_PREFIX: /home/test/.linuxbrew
HOMEBREW_CELLAR: /home/test/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/test/.cache/Homebrew
HOMEBREW_LOGS: /home/test/.cache/Homebrew/Logs
HOMEBREW_REPOSITORY: /home/test/.linuxbrew/Homebrew
HOMEBREW_VISUAL: vim
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.3.7 => /home/test/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 6.0 build 600
Git: 2.11.0 => /usr/bin/git
Curl: 7.52.1 => /usr/bin/curl
Kernel: Linux 4.9.0-9-amd64 x86_64 GNU/Linux
OS: Debian GNU/Linux 9.9 (stretch) (stretch)
Host glibc: 2.24
/usr/bin/gcc: 6.3.0
glibc: N/A
gcc: 5.5.0_4
xorg: N/A


$brew install go
==> Downloading https://dl.google.com/go/go1.12.5.src.tar.gz
```

**Comment by jonchang** [comment]
**Please use the Discourse in the future for for asking a question.** See https://docs.brew.sh/Bottles#cellar-cellar. `go` doesn't create a relocatable bottle, so when installing to a nonstandard prefix `brew` must build from source.
