### ISSUE TITLE
core2-linux-gnu make configure of gmp crashing on my jetson nano

### ISSUE THREAD

**Issue by unplugandplay** [Homebrew/linuxbrew-core#13079]
Hello I received my jetson nano yesterday, and as I tried to install the llvm bottle, the gmp one was required.

The install of the gmp crash at ./configure time.

This is the  ./configure line I found:
```./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/gmp/6.1.2_2 --enable-cxx --with-pic --build=core2-linux-gnu```

If I delete the `core2-linux-gnu` part, things go thru. It is like core2-linux-gnu gets the compiler not tried agains arm64 architecture....

Apparently this wass added in a commit in february if I have read correctly the latest patch.

**Comment by iMichka** [comment]
From the doc: https://docs.brew.sh/Homebrew-on-Linux#arm

**Homebrew can run on 32-bit ARM (Raspberry Pi and others) and 64-bit ARM (AArch64), but no binary packages (bottles) are available. Support for ARM is on a best-effort basis. Pull requests are welcome to improve the experience on ARM platforms.**

We would accept a pull request to fix your issue, but do not plan to work on this ourselves right now. Thanks for your understanding.
