### ISSUE TITLE
Superfluous `root_url` in the formulae bottle block

### ISSUE THREAD

**Issue by xu-cheng** [Homebrew/linuxbrew-core#13110]
Recently, I noticed that there are superfluous `root_url "https://linuxbrew.bintray.com/bottles"` in the formulae bottle block. 

This seems to be a bug in the bottle CI?

/cc @sjackman @iMichka

**Comment by iMichka** [comment]
This is happening since the linuxbrew-homebrew merge. There should a patch somewhere that we forgot to port to homebrew. It is somewhere on my todo list since months, I had no time to look at this.

If I remember well this fix should be done in `brew`, as that line comes from there.

**Comment by issyl0** [comment]
I had a quick look and [I think I've found the lines in the old codebase](https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/dev-cmd/bottle.rb#L44-L46)? I'm not sure what needs doing to fix this (we _don't_ want the `root_url` stanzas?), but I'm happy to investigate and have a go if no-one gets there first.

**Comment by sjackman** [comment]
Nice find. Thank you, Issy. That code is identical to the code in Homebrew/brew
https://github.com/Homebrew/brew/blob/e098c37dc3734dbe097ed9804a3a88737ff71add/Library/Homebrew/dev-cmd/bottle.rb#L16-L18
```
    <% if !["#{HOMEBREW_BOTTLE_DEFAULT_DOMAIN}/bottles", "https://homebrew.bintray.com/bottles"].include?(root_url) %>
    root_url "<%= root_url %>"
    <% end %>
```

@iMichka Are you pulling the bottles on macOS? If so, try setting this alias…
```sh
alias linuxbrew-pull='HOMEBREW_BOTTLE_DOMAIN=https://linuxbrew.bintray.com linuxbrew pull --bottle --bintray-org=linuxbrew --test-bot-user=LinuxbrewTestBot'
```

**Comment by sjackman** [comment]
An option could be to automatically set `HOMEBREW_BOTTLE_DOMAIN` to `https://linuxbrew.bintray.com` when the core remote is `https://github.com/Homebrew/linuxbrew-core`?
