### ISSUE TITLE
patchelf: Corrupts glib

### ISSUE THREAD

**Issue by sjackman** [Homebrew/linuxbrew-core#13148]
First reported here: https://github.com/brewsci/homebrew-bio/issues/632

The file `/home/linuxbrew/.linuxbrew/Cellar/glib/2.60.2/lib/libglib-2.0.so.0.6000.2` is corrupted when the bottle is poured and relocated using `patchelf 0.10`.

```console
$ ldd /home/linuxbrew/.linuxbrew/lib/libglib-2.
0.so.0
Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != NULL' failed!
$ patchelf --print-needed /home/linuxbrew/.linuxbrew/lib/libglib-2.0.so.0
$
```

The following workaround downgrades `patchelf` to version 0.9_1 and reinstalls `glib`.
```sh
brew unlink patchelf
brew install https://raw.githubusercontent.com/Homebrew/linuxbrew-core/1d5b681f01440527bc47b3937f25bee3e82b9169/Formula/patchelf.rb
brew reinstall glib
```

**Comment by sjackman** [comment]
I've reported this bug upstream at https://github.com/NixOS/patchelf/issues/170

**Comment by iMichka** [comment]
Maybe we could force `glib` to be built from source for the time being. Not perfect but it would avoid downgrading. If we downgrade, we need to bump the version scheme too.

**Comment by sjackman** [comment]
Is it only `glib` that's affected? Do you know of any other affected bottles? I'm also wondering if we were to rebottle `glib` using `patchelf` 0.10, would it then be possible to pour it using `patchelf` 0.10? I'll test that now.

**Comment by sjackman** [comment]
Yes, that worked.
@imichka Let's bump the revision of `glib` and rebuild its bottle. Hopefully this issue doesn't affect too many more bottles.

**Comment by iMichka** [comment]
Cool. I'll open a PR. You can probably not mix both patchelf versions in some cases.

**Comment by iMichka** [comment]
#13149

**Comment by sjackman** [comment]
Thanks, Michka!

**Comment by iMichka** [comment]
Fixed by #13149

**Comment by sjackman** [comment]
It has been reported by two people @dpo and @Albert65 that pouring `gmp` using `patchelf` 0.10 corrupts `gmp`.
```
==> Pouring gmp-6.1.2_2.x86_64_linux.bottle.1.tar.gz
Error: Failure while executing; /home/linuxbrew/.linuxbrew/bin/patchelf --print-rpath /home/linuxbrew/.linuxbrew/Cellar/gmp/6.1.2_2/lib/libgmp.so.10.3.2 exited with 127. Here's the output:
/home/linuxbrew/.linuxbrew/bin/patchelf: �4���: ELF���: x�: Error 489305239
```
I'm unfortunately not able to reproduce this behaviour in the `linuxbrew/brew` Docker image.
```
==> Installing gcc dependency: gmp
==> Downloading https://linuxbrew.bintray.com/bottles/gmp-6.1.2_2.x86_64_linux.b
==> Downloading from https://akamai.bintray.com/09/09d722e6321b67257e80f08b7c692
######################################################################## 100.0%
==> Pouring gmp-6.1.2_2.x86_64_linux.bottle.1.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/gmp/6.1.2_2: 20 files, 3.8MB
$ patchelf --version
patchelf 0.10
```

**Comment by dpo** [comment]
Are you able to reproduce by cloning Linuxbrew (or using the install script) on CircleCI?

**Comment by sjackman** [comment]
I opened this PR to test installing `gcc` (and its dependency `gmp`) on TravisCI: https://github.com/Linuxbrew/install/pull/60

**Comment by sjackman** [comment]
Pouring both `m4` and `gmp` failed on TravisCI. See https://github.com/Linuxbrew/install/pull/60

**Comment by sjackman** [comment]
Pouring the newly rebuilt `gmp-6.1.2_3.x86_64_linux.bottle.1.tar.gz` bottle failed.
```
==> Pouring gmp-6.1.2_3.x86_64_linux.bottle.1.tar.gz
Error: Failure while executing; `/home/linuxbrew/.linuxbrew/bin/patchelf --print-rpath /home/linuxbrew/.linuxbrew/Cellar/gmp/6.1.2_3/lib/libgmp.so.10.3.2` exited with . Here's the output:
```
https://travis-ci.org/Linuxbrew/install/builds/534517165#L897

**Comment by sjackman** [comment]
I believe this issue is resolved by PR https://github.com/Homebrew/linuxbrew-core/pull/13210.
Run…
```sh
brew update
brew reinstall patchelf
```
