### ISSUE TITLE
mtr starts but no packets are sent, no data appears on Ubuntu 18.04.1

### ISSUE THREAD

**Issue by speedstercamaro** [Homebrew/linuxbrew-core#13194]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I have Ubuntu running on Windows 10, I want to run mtr to diagnose packet loss along hops in traceroute.  I run Ubuntu as administrator and type in `sudo mtr "hostName"`.  It looks like mtr opens but no data ever displays.  It just shows the headings but it appears no packets are sent.  I've included a screen grab.
![CaptureMTR](https://user-images.githubusercontent.com/50690539/57973568-b199a000-795f-11e9-8b78-790f1fbf55e7.PNG)

**brew config output**
HOMEBREW_VERSION: 2.1.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4025eadc2c3b9b71aa7029d7ddc6ede1cb88d482
Last commit: 12 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 063ab9792143ca6ec7a26b7813b8733456ceaef8
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/speedstercamaro/.cache/Homebrew
HOMEBREW_LOGS: /home/speedstercamaro/.cache/Homebrew/Logs
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 4.4.0-17763-Microsoft x86_64 GNU/Linux
OS: Ubuntu 18.04.1 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.4.0
glibc: N/A
gcc: 5.5.0_4
xorg: N/A

**brew doctor output**
Your system is ready to brew.

**Comment by iMichka** [comment]
Hi.

This is probably an upstream issue. We just provide the package: if you need help with it you should open an issue at: https://github.com/traviscross/mtr/

If we did not package it correctly and the issue is due to this, we would be willing to fix it, in case upstream helps us setup the correct build flags (in case anything special is needed for windows).
