### ISSUE TITLE
Installing mysql@5.7 fails due to missing rpcgen dependency

### ISSUE THREAD

**Issue by xama5** [Homebrew/linuxbrew-core#13192]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install`
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/xama5/dd476a50c0b7a9cc30a0b2778d3c19e6

- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
- What you were trying to do (and why)

Install mysql@5.7

- What happened (include command output)

```
Last 15 lines from /home/oliver/.cache/Homebrew/Logs/mysql@5.7/01.cmake:
-- Performing Test X_GETPOSTN_NOT_USE_CONST
-- Performing Test X_GETPOSTN_NOT_USE_CONST - Failed
-- Performing Test HAS_INCOMPATIBLE_POINTER_TYPES
-- Performing Test HAS_INCOMPATIBLE_POINTER_TYPES - Success
-- Performing Test X_PUTLONG_NOT_USE_CONST
-- Performing Test X_PUTLONG_NOT_USE_CONST - Failed
CMake Error at rapid/plugin/group_replication/rpcgen.cmake:93 (MESSAGE):
  Could not find rpcgen
Call Stack (most recent call first):
  rapid/plugin/group_replication/CMakeLists.txt:29 (INCLUDE)

```

Formula to rpcgen: https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/rpcgen.rb

The Formula uses xcodebuild, which most likely isn't to be found on Linux systems:

https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/rpcgen.rb#L26

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install mysql@5.7`

Not reproducible with the docker container provided by linuxbrew/linuxbrew.

**Comment by dawidd6** [comment]
We have a bottle now for `mysql@5.7`. So I guess this issue should be no longer valid.
@xama5 do you still experience problems?

**Comment by xama5** [comment]
@dawidd6 Awesome! The installation works now on a fresh installation. Thanks for your hard work!
