### ISSUE TITLE
Cannot install both gcc@8 and gcc@9

### ISSUE THREAD

**Issue by MatthewFluet** [Homebrew/linuxbrew-core#13240]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

```
[mtf@sulfur Formula]$ brew gist-logs gcc@9
Error: No logs.
[mtf@sulfur Formula]$ brew gist-logs gcc@8
Error: No logs.
```

- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
[mtf@sulfur Formula]$ brew config
HOMEBREW_VERSION: 2.1.3                                                                                                                                                           ORIGIN: https://github.com/Homebrew/brew
HEAD: 099b047349d4ec67519206f15401d0e1cf90e953
Last commit: 32 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 23a8617aa869a6fe01af66c9f3d9d36dda4e772a
Core tap last commit: 18 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/mtf/.cache/Homebrew
HOMEBREW_LOGS: /home/mtf/.cache/Homebrew/Logs
CPU: 16-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.21.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.47.0 => /usr/bin/curl
Kernel: Linux 4.4.0-148-generic x86_64 GNU/Linux
OS: Ubuntu 16.04.6 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: N/A
xorg: N/A
[mtf@sulfur Formula]$ brew doctor
Your system is ready to brew.
```

To help us debug your issue please explain:
- What you were trying to do (and why)

Install multiple versions of gcc (for performance and feature-support comparisons).  gcc@6, gcc@7, and gcc@8 peacefully coexist, so tried to install gcc@9.

- What happened (include command output)

```
[mtf@sulfur Formula]$ brew install gcc@9
==> Downloading https://linuxbrew.bintray.com/bottles/gcc@9-9.1.0.x86_64_linux.bottle.tar.gz
Already downloaded: /home/mtf/.cache/Homebrew/downloads/0150c0c0911e9f5eae3689b1693f91b57fddde765dac873b0c11961b78aab721--gcc@9-9.1.0.x86_64_linux.bottle.tar.gz
==> Pouring gcc@9-9.1.0.x86_64_linux.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /home/linuxbrew/.linuxbrew
Could not symlink share/locale/be/LC_MESSAGES/cpplib.mo
Target /home/linuxbrew/.linuxbrew/share/locale/be/LC_MESSAGES/cpplib.mo
is a symlink belonging to gcc@8. You can unlink it:
  brew unlink gcc@8

To force the link and overwrite all conflicting files:
  brew link --overwrite gcc@9

To list all files that would be deleted:
  brew link --overwrite --dry-run gcc@9

Possible conflicting files are:
/home/linuxbrew/.linuxbrew/share/locale/be/LC_MESSAGES/cpplib.mo -> /home/linuxbrew/.linuxbrew/Cellar/gcc@8/8.3.0/share/locale/be/LC_MESSAGES/cpplib.mo
...
/home/linuxbrew/.linuxbrew/share/locale/zh_TW/LC_MESSAGES/gcc.mo -> /home/linuxbrew/.linuxbrew/Cellar/gcc@8/8.3.0/share/locale/zh_TW/LC_MESSAGES/gcc.mo
==> Creating the GCC specs file: /home/linuxbrew/.linuxbrew/Cellar/gcc@9/9.1.0/lib/gcc/9/gcc/x86_64-pc-linux-gnu/9.1.0/specs
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/gcc@9/9.1.0: 1,521 files, 239.2MB
```

- What you expected to happen

gcc@9 to successfully install and peacefully coexist with gcc@6, gcc@7, and gcc@8.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install gcc@8
brew install gcc@9
```

### Notes

The relevant difference between `gcc@6.rb`/`gcc@7.rb` and `gcc@8.rb`/`gcc@9.rb` seems to be that the former are configured with `"--disable-nls"` while the latter are not.  Perhaps a reasonable policy would be for only the latest version of gcc to be configured with Native Language Support (NLS).

**Comment by iMichka** [comment]
Hi. Yes, only the latest one should have NLS. Would you like to open a pull request to add `--disable-nls` to `gcc@8.rb/gcc@9.rb` ? I can guide you if you need any help to do this.

**Comment by MatthewFluet** [comment]
@iMichka Sure, I can work on a PR.  Some questions:

* Should the PR be submitted to Homebrew/linuxbrew-core or to Homebrew/homebrew-core?  The various gcc formulas seem to have diverged considerably (and Homebrew/homebrew-core doesn't have a `gcc@9.rb`).
* You suggested that only the latest gcc version should have NLS.  Do you mean that only the "default" `gcc.rb` formula should have `--enable-nls` (it currently has `--disable-nls` and on Linux installs gcc 5.5) and all `gcc@*.rb` formulas should have `--disable-nls`?  Or do you mean that only `gcc@9.rb` should have `--enable-nls` and all of the other `gcc@*.rb` formulas should have `--disable-nls`?
* If both `gcc@8.rb` and `gcc@9.rb` are changed, should they be separate PRs?

**Comment by iMichka** [comment]
@MatthewFluet I think we should disable nls for all the gcc formulae. Unless somebody needs it, then we may enable it for `gcc` only (which is `gcc5`  for linuxbrew).

In #13301 you made the change for `gcc@8`.  Would you like to open a new PR for `gcc@9`, with the equivalent changes?

**Comment by MatthewFluet** [comment]
@iMichka I've opened #13421 to configure `gcc@9` with `-disable-nls`.

**Comment by iMichka** [comment]
Done with #13421 and #13301
