### ISSUE TITLE
PR at homebrew-core reporting problems with go@1.11

### ISSUE THREAD

**Issue by zbeekman** [Homebrew/linuxbrew-core#13281]
I'm going to invoke my fellow maintainer privilege and open this w/o the template. You're welcome to close it.

Original PR: https://github.com/Homebrew/homebrew-core/pull/40202

User's logs: https://gist.github.com/c9fa7c3dc17a417509b6f4167c801f54

Comments from PR:

> This changes copies the pattern used in go@1.10. Go 1.11 compiles the std
library with the -race flag which requires cgo, so that environment variable
is set too.

CC: @gcla

**Comment by issyl0** [comment]
Looks like this was fixed by @gcla in #13317 which was merged five days ago. Thanks for the triage, @zbeekman. Closing.
