### ISSUE TITLE
llvm doesn't include libcxx

### ISSUE THREAD

**Issue by NikolausDemmel** [Homebrew/linuxbrew-core#13332]
When installing `llvm` (from bottle) on linuxbrew, it doesn't include `libc++`:

```
linuxbrew@372a5ef726e5:~$ ls /home/linuxbrew/.linuxbrew/opt/llvm/include/
clang  clang-c  lld  lldb  llvm  llvm-c  polly
```

I'm confused as to whether that is intended or not.

Looking at past issues, it was removed some time https://github.com/Homebrew/linuxbrew-core/issues/1041, then later it was added as an option https://github.com/Homebrew/linuxbrew-core/pull/1413. Currently, there is no option, but in the formula there are still references to libcxx and even the caveat mentions it.

```
==> llvm
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/home/linuxbrew/.linuxbrew/opt/llvm/lib -Wl,-rpath,/home/linuxbrew/.linuxbrew/opt/llvm/lib"
```

I read that with the 2.0 release Homebrew doesn't have options in the core formulae. Not sure if that also applies to `linuxbrew-core`. Maybe that is why the option was removed?

IMHO, it would be great if `libc++` was built and installed with llvm (no option). Still, clang should continue to be configured to use `libstdc++` per default, as that is the reasonable default on Linux. But it would give users of clang the option to manually compile their code with `libc++` if they want.

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
linuxbrew@372a5ef726e5:~$ brew gist-logs llvm
Error: No logs.
linuxbrew@372a5ef726e5:~$ brew config
HOMEBREW_VERSION: 2.1.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 099b047349d4ec67519206f15401d0e1cf90e953
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core.git
Core tap HEAD: 4abc3f49eaea28d369f6c586757d7d2dd387f5e3
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/linuxbrew/.cache/Homebrew
HOMEBREW_LOGS: /home/linuxbrew/.cache/Homebrew/Logs
CPU: dodeca-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 8.0 build 800
Git: 2.20.1 => /usr/bin/git
Curl: 7.47.0 => /usr/bin/curl
Kernel: Linux 4.4.0-148-generic x86_64 GNU/Linux
OS: Ubuntu 16.04.5 LTS (xenial)
Host glibc: 2.23
/usr/bin/gcc: 5.4.0
glibc: N/A
gcc: 5.5.0_4
xorg: N/A
linuxbrew@372a5ef726e5:~$ brew doctor
Your system is ready to brew.
```

**Comment by iMichka** [comment]
The same rules apply for the linux repo as for the mac repo: no options. (There may still be some options here and there, we need to clean those up).

So for Linux you will get `libstdc++`, and that's all. The best thing you could do is to host the formula in your own tap, with `libc++` enabled.

This should be:
> To use the bundled libstdc++ please add the following LDFLAGS:

A pull request to fix this would be welcome. It is just the mac text that was not updated for the Linux formula.

**Comment by NikolausDemmel** [comment]
Thanks for the quick reply.

> The same rules apply for the linux repo as for the mac repo: no options. (There may still be some options here and there, we need to clean those up).

I understand.

> So for Linux you will get libstdc++, and that's all. The best thing you could do is to host the formula in your own tap, with libc++ enabled.

Wait, why is shipping libc++ but still configuring clang to use the system-libstdc++ by default not possible? So it would be built and installed, but not used unless the user invokes clang with `-stdlib=libc++`. There would be not option in the formula. This is similar on macos: The llvm formula ships with its own libc++, but clang uses the systems default libc++ (the one from Apple / XCode) by default. Or maybe I misunderstood and its not technically possible?

> This should be:
>
>> To use the bundled libstdc++ please add the following LDFLAGS:

There is no bundled `libstd++` in the llvm formula... (or is there?). It seems to use the system one (which is and IMHO should be the default for clang from the llvm formula, see above) or you can also use libstdc++ from one of the `gcc@x` formulae, by passing include and linker flags.

**Comment by iMichka** [comment]
I think we can ship both. We did this at one point in the past. It's just a matter of finding the right configuration flags in the build.

As this is a feature request, we only accept pull requests to make the change. Nothing is fundamentally broken right now with llvm, and I doubt anybody on our side will have time to work on this. But I would be ready to review a workig pull request. Thanks for your understanding.

Of course any other maintainer of user can pick this up and give a hand.

**Comment by NikolausDemmel** [comment]
Thanks for the reply and willingness to review a PR. I understand the position of the maintainers.

I'm not sure if I'll get around to this any time soon, for now I have successfully switched to gcc@9 from linuxbrew for the particular project where I wanted to use clang from linuxbrew.

If anybody else comes across this issue and wants to make the addition, that'd be great of course.
