### ISSUE TITLE
unzip is not found

### ISSUE THREAD

**Issue by gera2ld** [Homebrew/linuxbrew-core#14038]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Install Vim.

- What happened (include command output)

unzip is not found.

```
==> Installing vim dependency: unzip
==> Downloading https://downloads.sourceforge.net/project/infozip/UnZip%206.x%20%28latest%29/UnZip%206.0/unzip60.tar.gz
Already downloaded: ~/.cache/Homebrew/downloads/d0f59184a257740ddd7fb7bd57265c587ddc952b01bb1d105e81a7c74df847d4--unzip60.tar.gz
==> Downloading https://deb.debian.org/debian/pool/main/u/unzip/unzip_6.0-22.debian.tar.xz
==> Downloading from https://cdn-aws.deb.debian.org/debian/pool/main/u/unzip/unzip_6.0-22.debian.tar.xz
-=#=#   #   #
curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "unzip--patch"
Download failed: https://deb.debian.org/debian/pool/main/u/unzip/unzip_6.0-22.debian.tar.xz
```

I think the URL here is incorrect:

https://github.com/Homebrew/linuxbrew-core/blob/085ca8ff7c6c5458f5a66e6d6cbbd65b7323676f/Formula/unzip.rb#L25

- What you expected to happen

Download from a correct URL and finish installation.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
$ brew install vim
```

**Comment by iMichka** [comment]
@gera2ld the url has changed, it should be https://cdn-aws.deb.debian.org/debian/pool/main/u/unzip/unzip_6.0-23.debian.tar.xz.

This needs to be fixed in the upstream homebrew-core repository: https://github.com/Homebrew/homebrew-core/blob/master/Formula/unzip.rb

You can open a pull request there to get this fixed. We can guide you through the different steps if you need some help.

As this is not a linuxbrew-core issue, I'll close this ticket.

**Comment by gera2ld** [comment]
The fix has been merged into homebrew-core, but not updated in this repo. Do I need to open a PR here too?

**Comment by iMichka** [comment]
Thanks!

No, you need to wait a little bit, I need to merge the upstream changes to this repo. This takes around 24 hours (or more when I am on holidays)
