### ISSUE TITLE
circular dependency between util-linux and systemd

### ISSUE THREAD

**Issue by jokeyrhyme** [Homebrew/linuxbrew-core#14105]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

Effectively trying to `brew install gnupg` via `brew bundle --global`

```
$ cat ~/.Brewfile
brew "bash"
brew "fish"
brew "gnupg"
brew "tmux"
brew "zsh"

$ brew bundle --global
```

- What happened (include command output)

```
$ brew bundle --global
Error: Formulae dependency graph sorting failed (likely due to a circular dependency):
util-linux: ["ncurses", "zlib", "pcre2", "readline", "systemd"]
systemd: ["libbsd", "expat", "libcap", "ncurses", "zlib", "util-linux"]
Please run the following commands and try again:
  brew update
  brew uninstall --ignore-dependencies --force util-linux systemd
  brew install util-linux systemd
```

This was caused by gnupg's dependency upon libusb, which depends upon systemd, which depends upon util-linux, which depends on systemd, etc...

- What you expected to happen

This should have installed `gnupg` without errors or additional manual steps

- Step-by-step reproduction instructions (by running `brew install` commands)

See above Brewfile contents and shell commands

I noticed that util-linux only has an optional (but enabled by default) dependency upon systemd

So, potentially, one way of breaking this circular dependency could be to extract this out of the util-linux formula, into a new util-linux-systemd formula:

- util-linux: changed to always `--without-systemd`, no dependency upon systemd
- systemd: no functional change, continues to depend upon util-linux, note added to refer users to util-linux-systemd
- util-linux-systemd: new, cloned from util-linux, but always just does the `--with-systemd` part, depends upon both util-linux and systemd

**Comment by jokeyrhyme** [comment]
Note that the suggested commands do fix the issue (and prevent further reproduction of the issue), but it requires manual intervention, which is not necessary for the majority of other formula in linuxbrew

**Comment by iMichka** [comment]
Hi. `util-linux` does not depend on `systemd`. See:

```
brew deps --include-build util-linux
gpatch
ncurses
pkg-config
xz
zlib
```

Can you report your `brew config`?

**Comment by jokeyrhyme** [comment]
```
$ brew config
HOMEBREW_VERSION: 2.1.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: fddf5b16bd8df577380a1d810d17825ef611b81f
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 5d7269b355b7fccc331f582eda8359f8b034e471
Core tap last commit: 26 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/ron/.cache/Homebrew
HOMEBREW_LOGS: /home/ron/.cache/Homebrew/Logs
CPU: octa-core 64-bit unknown_0x17_0x8
Homebrew Ruby: 2.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: 8.0 build 800
Git: 2.22.0 => /bin/git
Curl: 7.65.1 => /usr/bin/curl
Kernel: Linux 5.1.15-arch1-1-ARCH x86_64 GNU/Linux
OS: N/A
Host glibc: 2.29
/usr/bin/gcc: 9.1.0
glibc: N/A
gcc: N/A
xorg: N/A
```

Unfortunately, this doesn't exactly capture the state I was in when I had the error (which persisted for a few days), because I've since run the recommended commands, and even uninstalling these packages won't get be back to being able to reproduce it :S

I'm feeling kinda' silly now, although thanks heaps for your interest

Maybe it was a brief issue with `brew bundle`, or (more likely) something weird with my setup

Feel free to close
