### ISSUE TITLE
-e:178: syntax error, unexpected '.'

### ISSUE THREAD

**Issue by zenny** [Homebrew/linuxbrew-core#14108]
While trying to install linuxbrew as described at https://docs.brew.sh/Homebrew-on-Linux :

```
$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
-e:178: syntax error, unexpected '.'
    exe if $CHILD_STATUS&.success? && !exe.empty? && Fi...
                          ^
```

I tried with single quotes:

```
$ sh -c '$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)'
sh: #!/bin/sh: No such file or directory

```

It is unbelievable because it is a standard in all *nix

```
$ which sh
/bin/sh
```

Any input? 

Cheers,
/z

**Comment by issyl0** [comment]
Hi @zenny. This appears to be a duplicate issue to https://github.com/Linuxbrew/install/issues/65. Do any of the tips there help you, or https://joseph-long.com/writing/linuxbrew-with-ancient-git/?
