### ISSUE TITLE
bzip2 on linux is broken since 1.0.7 upgrade

### ISSUE THREAD

**Issue by turip** [Homebrew/linuxbrew-core#14120]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
done
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ X ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/turip/b499bcde9d0a28e21531b13943b98591
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
I am trying to run brew update && brew upgrade bzip2 on linux.

Since the update to 1.0.7, the install is broken due to these lines in the formula: https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/bzip2.rb#L25-L27

- What happened (include command output)
turip@turip-xps:~/src/pde$ brew install pde
==> Installing pde from prezi/internal
==> Installing dependencies for prezi/internal/pde: bzip2, python, python@2 and prezi-onelogin-python-aws-assume-role
==> Installing prezi/internal/pde dependency: bzip2
==> Downloading https://sourceware.org/pub/bzip2/bzip2-1.0.7.tar.gz
Already downloaded: /home/turip/.cache/Homebrew/downloads/ac84bf1c9b044425ed154c09c8efe52c9dbe78e96221dc4f6c15809daf862cd1--bzip2-1.0.7.tar.gz
==> make install PREFIX=/home/linuxbrew/.linuxbrew/Cellar/bzip2/1.0.7
==> make -f Makefile-libbz2_so clean
==> make -f Makefile-libbz2_so
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - libbz2.so.1.0.6

- What you expected to happen

bzip2 works

- Step-by-step reproduction instructions (by running `brew install` commands)

Have a linux machine, do brew install bzip2

**Comment by iMichka** [comment]
This should fix it: bottle-bzip2
