### ISSUE TITLE
brew install latexml failed

### ISSUE THREAD

**Issue by CAMOBAP795** [Homebrew/linuxbrew-core#14126]
### Checklist
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

#### What you were trying to do (and why)
`brew install latexml` to install `latexml`

#### What happened (include command output)
https://gist.github.com/CAMOBAP795/b5811cdbe1c3c9374f34a822c5e54ea5

#### What you expected to happen
`latexml` should be installed successfullly

#### Step-by-step reproduction instructions (by running `brew install` commands)
 - `brew install latexml`

**Comment by iMichka** [comment]
Fixed by #14129
