### ISSUE TITLE
Java fails to install

### ISSUE THREAD

**Issue by thedrow** [Homebrew/linuxbrew-core#14124]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? No logs found
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
HOMEBREW_VERSION: 2.1.6-44-g895467a
ORIGIN: https://github.com/Homebrew/brew
HEAD: 895467ad9f57a9245c36def26abca729f2559fbb
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 8fc90f9949f42879aed819b772e737ec50d59e9c
Core tap last commit: 8 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/omer/.cache/Homebrew
HOMEBREW_LOGS: /home/omer/.cache/Homebrew/Logs
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.5.1 => /usr/bin/ruby2.5
Clang: 8.0 build 800
Git: 2.22.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 4.15.0-54-generic x86_64 GNU/Linux
OS: Ubuntu 18.04.2 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.4.0
glibc: N/A
gcc: 5.5.0_4
xorg: N/A
```
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/omer/.pyenv/shims/python3-config
  /home/omer/.pyenv/shims/python3.7m-config
  /home/omer/.pyenv/shims/python3.5m-config
  /home/omer/.pyenv/shims/python3.6-config
  /home/omer/.pyenv/shims/python3.7-config
  /home/omer/.pyenv/shims/python3.6m-config
  /home/omer/.pyenv/shims/python3.5-config
  /home/omer/.pyenv/shims/python-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  ruby
  openjdk
  subversion
  tox
```

To help us debug your issue please explain:

- What you were trying to do (and why)
`brew upgrade`
- What happened (include command output)
```
==> Reinstalling 4 broken dependents from source:
jdk, mycli, pipenv, rst-lint
==> Reinstalling jdk 
==> Downloading http://ftp.osuosl.org/pub/funtoo/distfiles/oracle-java/jdk-9.0.4
##O#- #                                                                       
curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "jdk"
Download failed: http://ftp.osuosl.org/pub/funtoo/distfiles/oracle-java/jdk-9.0.4_linux-x64_bin.tar.gz
```
- What you expected to happen
Homebrew should download the correct resource.
- Step-by-step reproduction instructions (by running `brew install` commands)
`brew install jdk`

**Comment by issyl0** [comment]
Hi @thedrow. We're unable to find another download link for `jdk` that's workable for us, so it can't be installed. The recommended software to install is now `adoptopenjdk`, so please try that.

**Comment by thedrow** [comment]
That's fine by me but some of the formulas depend on `jdk`.

**Comment by sjackman** [comment]
We'll change those formulae to depend on `:java` instead. Feel free to open PR to change `jdk` or `openjdk` to `:java` if you find any.
