### ISSUE TITLE
brew install docker-compose failed

### ISSUE THREAD

**Issue by wolfogre** [Homebrew/linuxbrew-core#14131]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

run `brew install docker-compose` to install docker-compose

- What happened (include command output)

```text
==> Downloading https://github.com/docker/compose/archive/1.24.1.tar.gz
Already downloaded: /home/songjianxin/.cache/Homebrew/downloads/cbb40814fe26a9662e06040d15eb72705776ed2970eea095df0d9553c0ad8417--compose-1.24.1.tar.gz
==> Downloading https://files.pythonhosted.org/packages/37/27/706af3ee62032933a3217454609c50a5325a6bd9c2c2f495b58c456ba286/virtualenv-16.6.1.tar.gz
######################################################################## 100.0%
==> python3 -c import setuptools... --no-user-cfg install --prefix=/tmp/docker-compose--homebrew-virtualenv-20190710-1648113-1qnk3j3/target --install-s
==> python3 -s /tmp/docker-compose--homebrew-virtualenv-20190710-1648113-1qnk3j3/target/bin/virtualenv -p python3 /home/linuxbrew/.linuxbrew/Cellar/doc
==> /home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.24.1/libexec/bin/pip install -v --no-binary :all: --ignore-installed /tmp/docker-compose-2019071
Last 15 lines from /home/songjianxin/.cache/Homebrew/Logs/docker-compose/03.pip:
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.24.1/libexec/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.24.1/libexec/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.24.1/libexec/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.24.1/libexec/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 362, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.24.1/libexec/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 147, in prep_for_dist
    "Installing build dependencies"
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.24.1/libexec/lib/python3.7/site-packages/pip/_internal/build_env.py", line 195, in install_requirements
    call_subprocess(args, spinner=spinner)
  File "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.24.1/libexec/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.24.1/libexec/bin/python3.7 /home/linuxbrew/.linuxbrew/Cellar/docker-compose/1.24.1/libexec/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-qhvtas3a/overlay --no-warn-script-location -v --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel 'cffi>=1.1; python_implementation != '"'"'PyPy'"'"''" failed with error code 1 in None

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
docker-compose: Build a bottle for Linuxbrew https://github.com/Homebrew/linuxbrew-core/pull/14028
```

- What you expected to happen

docker-compose should be installed successfullly

- Step-by-step reproduction instructions (by running `brew install` commands)

`brew install docker-compose`

BTW: the same error occuerred in [CI test](https://circleci.com/gh/Homebrew/linuxbrew-core/30774?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) of #14028

**Comment by dawidd6** [comment]
Can confirm this. Tested on `linuxbrew/brew` Docker image.

**Comment by issyl0** [comment]
This should be fixed now. Please `brew update` and try to install again.
