### ISSUE TITLE
meson strips rpath off a bunch of packages 

### ISSUE THREAD

**Issue by Char-Aznable** [Homebrew/linuxbrew-core#14202]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:
One example is already mentioned here https://github.com/Homebrew/linuxbrew-core/pull/13709 where brew install gtk+ failed due to rpath problem
This also affects glib and gdk-pixbuf and a bunch other packages for which I lost count

**Comment by Char-Aznable** [comment]
Another package that is affected is libsoup. After brew install libsoup by building from source I got:

ldd /home/linuxbrew/.linuxbrew/Cellar/libsoup/2.66.2_1/lib64/libsoup-gnome-2.4.so.1.8.0
        linux-vdso.so.1 (0x00007fff9b330000)
        libsoup-2.4.so.1 => not found
        libglib-2.0.so.0 => not found
        libgobject-2.0.so.0 => not found
        libgio-2.0.so.0 => not found
        libc.so.6 => /home/linuxbrew/.linuxbrew/Cellar/glibc/2.23/lib/libc.so.6 (0x00007f8d1a864000)
        /home/linuxbrew/.linuxbrew/Cellar/glibc/2.23/lib64/ld-linux-x86-64.so.2 (0x00007f8d1ac03000)

**Comment by Char-Aznable** [comment]
Upstream issue https://github.com/mesonbuild/meson/issues/3882 mentioned the cause of this problem. Fixing individual package by 'install_rpath' will get out of hand soon. There doesn't seem a scalable solution at this point. Related to https://github.com/Homebrew/linuxbrew-core/issues/9753

**Comment by jonchang** [comment]
http://cdn.netbsd.org/pub/pkgsrc/current/pkgsrc/devel/py-meson/patches/patch-mesonbuild_scripts_depfixer.py

this looks promising

**Comment by Char-Aznable** [comment]
I submitted two prs so that libsoup and gdk-pixbuf can build for now

**Comment by Char-Aznable** [comment]
The other problem is that meson installs libraries into lib64 and these formula lack a step to move lib64 to lib and symlink it back

**Comment by iMichka** [comment]
Yes, for this issue I have been using `"--libdir=#{lib}"` when needed, as a meson parameter.

**Comment by Char-Aznable** [comment]
@jonchang The patch http://cdn.netbsd.org/pub/pkgsrc/current/pkgsrc/devel/py-meson/patches/patch-mesonbuild_scripts_depfixer.py you suggest does seem to work. The lib64 vs lib thing still needs some attention

**Comment by iMichka** [comment]
I just noticed that we have a `meson-internal` formula, which should contain the correct patches now: #14647

Not sure why we carry the official `meson` and a patched version ... the situation is quite unsatisfactory. It would be great if one of these patches got upstreamed and we could clean up all this mess.

**Comment by iMichka** [comment]
I am OK to accept `meson-internal` as a dependency for Linux for all the packages that need it ... For example this could be acceptable for #14204 and #14203.

**Comment by Char-Aznable** [comment]
`meson-internal` currently doesn't work for #14203 because it's a few revision behind what is required by libsoup.

**Comment by Char-Aznable** [comment]
`meson-internal` solves the problems for #14204

**Comment by iMichka** [comment]
Fixed by #16054.
