### ISSUE TITLE
Brew installation, and all brew commands fail with ruby gem dependency issue (cannot load such file bigdecimal)

### ISSUE THREAD

**Issue by autarchprinceps** [Homebrew/linuxbrew-core#14254]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

I tried to install Homebrew on Linux starting with the automatic install script, but I also tried the alternative installation, both installations as well as subsequent brew commands fail with the following error message:

/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/xml_mini.rb:5:in `require': cannot load such file -- bigdecimal (LoadError)
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/xml_mini.rb:5:in `<top (required)>'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/core_ext/array/conversions.rb:3:in `require'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/core_ext/array/conversions.rb:3:in `<top (required)>'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/duration.rb:3:in `require'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/duration.rb:3:in `<top (required)>'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/core_ext/numeric/time.rb:3:in `require'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.3/lib/active_support/core_ext/numeric/time.rb:3:in `<top (required)>'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/global.rb:13:in `require'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/global.rb:13:in `<top (required)>'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:23:in `require_relative'
	from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:23:in `<main>'
Failed during: /home/linuxbrew/.linuxbrew/bin/brew update --force

I looked into said gem directory, and there is indeed no installation of bigdecimal, which appears to be a necessary dependency. Now I don't know how homebrew sets up its gems or ruby, I couldn't find such binaries in the directory anywhere, so I don't know, if or how I could repair the state of the gems in that directory. Normally gems should autoresolve dependencies.

For context, I am running Amazonlinux 2 on standard 64bit Intel Hardware.

**Comment by iMichka** [comment]
Hi. Installation issues need to be reported to https://github.com/Linuxbrew/install.

Thanks.

Please also put the error message between triple `, so that the text is properly formatted for GitHub. Thanks!
