### ISSUE TITLE
Programs fail to run after some time (Illegal instruction (core dumped))

### ISSUE THREAD

**Issue by hwalinga** [Homebrew/linuxbrew-core#14281]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

----

Using linuxbrew on Ubuntu 16.04.6 LTS in $HOME/.linuxbrew.

Some programs installed by brew fail to run after some time reporting a `Illegal instruction (core dumped)`. 

This is for example the strace for ncdu: 

https://termbin.com/e492

What could have caused this and how to fix this or prevent in the future?

**Comment by jonchang** [comment]
Can you paste `brew config` here, thanks.

**Comment by hwalinga** [comment]
@jonchang 

Brew config: 

https://termbin.com/aetbq

Brew doctor:

https://termbin.com/izrf

**Comment by jonchang** [comment]
My guess is that since you have Homebrew installed in a nonstandard location, you don't get the full benefit of our binary bottles. Some packages will be built from source, and it's possible that those packages are incorrectly configured and will compile code that is incompatible with your processor. You can try setting `HOMEBREW_ARCH` to e.g., `core2` and then reinstall from source (see `man brew` for details), but it'll be up to you to debug this kind of issue since it is specific to your CPU and setup.

**Comment by hwalinga** [comment]
It didn't work. But thanks for the tip anyway.
