### ISSUE TITLE
is bsdmake required in linuxbrew?

### ISSUE THREAD

**Issue by hanxue** [Homebrew/linuxbrew-core#14312]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Is `bsdmake` even relevant as a dependency in Linuxbrew? `bsdmake` is Apple's port of FreeBSD's bsdmake for the MacOS environment, https://opensource.apple.com/tarballs/bsdmake

I was trying to install `spiped`, which has `bsdmake` as its build dependency. The build results in this error message

```
==> Applying patch-setrlimit.diff
patching file main.c
Error: An exception occurred within a child process:
  NameError: uninitialized constant OS::Mac::X11
```

Full logs at https://gist.github.com/hanxue/65c1351c955ccb91d716745926cde016

But that's not the point. Even if we remove https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/bsdmake.rb#L43, it will still fail to build. 

For example, instead of customizing homebrew's spiped formula, isn't it better to write a new formula for Linuxbrew, without using bsdmake?

**Comment by jonchang** [comment]
> For example, instead of customizing homebrew's spiped formula, isn't it better to write a new formula for Linuxbrew, without using bsdmake?

Yes, that would be ideal. Please open a pull request for this; feel free to ping me if you need help with any part of the process.
