### ISSUE TITLE
Failed to install makpekg due to rejection of the file wraptmfs

### ISSUE THREAD

**Issue by gusbemacbe** [Homebrew/linuxbrew-core#14520]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [X] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

I was trying to install `makpekg`
- What happened (include command output)

The file `wraptmfs` was reject and the compiling was aborted by brew.

- What you expected to happen

Nothing

- Step-by-step reproduction instructions (by running `brew install` commands)
* `brew install makepkg`
* The error appeared:

```
==> ./configure --disable-static --disable-silent-rules --prefix=/home/linuxbrew/.linuxbrew/Cellar/fakeroot/1.23
==> make wraptmpf.h
==> patch < patch-for-wraptmpf-h
Last 15 lines from /home/gusbemacbe/.cache/Homebrew/Logs/fakeroot/03.patch:
2019-07-30 03:17:16 -0300

patch < patch-for-wraptmpf-h

patching file wraptmpf.h
Hunk #1 FAILED at 575.
1 out of 1 hunk FAILED -- saving rejects to file wraptmpf.h.rej
```

* Output of `brew doctor` (no problems):

```
Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /sbin/update-texmf-config
  /bin/python-config
  /bin/x86_64-linux-gnu-python3-config
  /bin/x86_64-linux-gnu-pkg-config
  /bin/python3m-config
  /bin/im-config
  /bin/x86_64-linux-gnu-python3.7dm-config
  /bin/GraphicsMagick-config
  /bin/x86_64-linux-gnu-python3m-config
  /bin/ncursesw5-config
  /bin/sdl2-config
  /bin/xslt-config
  /bin/libpng16-config
  /bin/x86_64-linux-gnu-python3.7-dbg-config
  /bin/pth-config
  /bin/python3.7m-config
  /bin/x86_64-linux-gnu-python3.7m-config
  /bin/apt-config
  /bin/ncurses5-config
  /bin/x86_64-linux-gnu-python3.7-config
  /bin/x86_64-linux-gnu-python2-config
  /bin/libpng-config
  /bin/pkg-config
  /bin/python3-config
  /bin/python3.7-dbg-config
  /bin/python3-dbg-config
  /bin/i686-linux-gnu-pkg-config
  /bin/gsl-config
  /bin/x86_64-linux-gnu-python3-dbg-config
  /bin/x86_64-linux-gnu-python2.7-config
  /bin/x86_64-linux-gnu-python-config
  /bin/gnustep-config
  /bin/GraphicsMagickWand-config
  /bin/x86_64-linux-gnu-python3dm-config
  /bin/libwmf-config
  /bin/xml2-config
  /bin/python3.7-config
  /bin/python2-config
  /bin/pcre-config
  /bin/x86_64-pc-linux-gnu-pkg-config
  /bin/python3dm-config
  /bin/taglib-config
  /bin/ncurses6-config
  /bin/ncursesw6-config
  /bin/python3.7dm-config
  /bin/python2.7-config
  /bin/GraphicsMagick++-config
  /bin/curl-config
  /bin/kf5-config
```

* Output of `brew config` (no problems):

```
HOMEBREW_VERSION: 2.1.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 549a40bedb32171912a449d8d0e7bcae02d5b432
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 44e47c1876077f8af59f8d5c4558ba48adcd4634
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/gusbemacbe/.cache/Homebrew
HOMEBREW_LOGS: /home/gusbemacbe/.cache/Homebrew/Logs
CPU: 16-core 64-bit unknown_0x17_0x8
Homebrew Ruby: 2.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.20.1 => /bin/git
Curl: 7.64.0 => /usr/bin/curl
Kernel: Linux 5.0.0-21-generic x86_64 GNU/Linux
OS: Ubuntu 19.04 (disco)
Host glibc: 2.29
/usr/bin/gcc: 8.3.0
glibc: N/A
gcc: 5.5.0_4
xorg: 20170115_1
```

**Comment by dawidd6** [comment]
https://github.com/Homebrew/linuxbrew-core/pull/16208

**Comment by issyl0** [comment]
Hi, @gusbemacbe. We just pushed a fix for the `fakeroot` formula, so if you `brew update`, the install of `makepkg` should succeed. Thanks for using Homebrew on Linux!

**Comment by dawidd6** [comment]
Not so fast @issyl0 :). Still need to test building of `makepkg` itself.

**Comment by gusbemacbe** [comment]
Tonight, I will test, because the IT tech guy will clean the dirt in my computers. Each 4 months, I call him to clean the dirt.

**Comment by dawidd6** [comment]
@gusbemacbe did you do it?

**Comment by gusbemacbe** [comment]
Hi @dawidd6 !

Sorry for my long absence, I was in much hurry with icons themes. 

But yes, on Fedora, and `makepkg` worked, but the last error was with `gem`. Here is the following error:

```
gem install nokogiri -- --with-xslt-dir=/home/linuxbrew/.linuxbrew/opt/libxslt
Building native extensions with: '--with-xslt-dir=/home/linuxbrew/.linuxbrew/opt/libxslt'
This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    current directory: /home/gusbemacbe/.gem/ruby/gems/nokogiri-1.10.4/ext/nokogiri
/usr/bin/ruby -I /usr/share/rubygems -r ./siteconf20191014-16734-1fits2a.rb extconf.rb --with-xslt-dir\=/home/linuxbrew/.linuxbrew/opt/libxslt
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.4.0
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib64
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)
        --help
        --clean
        --use-system-libraries
        --enable-static
        --disable-static
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib64
        --enable-cross-build
        --disable-cross-build

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/gusbemacbe/.gem/ruby/extensions/x86_64-linux/2.6.0/nokogiri-1.10.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/gusbemacbe/.gem/ruby/gems/nokogiri-1.10.4 for inspection.
Results logged to /home/gusbemacbe/.gem/ruby/extensions/x86_64-linux/2.6.0/nokogiri-1.10.4/gem_make.out
```

**Comment by dawidd6** [comment]
What is this output? What did you try to do?

**Comment by gusbemacbe** [comment]
Firstly I installed `makepkg` successfully, and in the end of `makepkg` installation, I was suggested to run `gem install nokogiri -- --with-xslt-dir=/home/linuxbrew/.linuxbrew/opt/libxslt`. Following, it gave that error. I felt that `makepkg` needed the nokogiri package.

**Comment by dawidd6** [comment]
It's a caveat for `libxslt`:
```
==> libxslt
To allow the nokogiri gem to link against this libxslt run:
  gem install nokogiri -- --with-xslt-dir=/home/linuxbrew/.linuxbrew/opt/libxslt
```
