### ISSUE TITLE
Can't fully use `HOMEBREW_BOTTLE_DOMAIN` due to `root_url` in some formulae

### ISSUE THREAD

**Issue by mikesep** [Homebrew/linuxbrew-core#14598]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
  I want to install Linuxbrew using bottles from a local mirror. I set `HOMEBREW_BOTTLE_DOMAIN` to my local mirror URL, but `gmp`, `mpfr`, and `pcre2` are still downloaded from https://linuxbrew.bintray.com.

- What happened (include command output)
  ```
  ...
  ==> Installing curl dependency: m4
  ==> Downloading [REDACTED_URL]/bottles/m4-1.4.18.x86_64_linux.bottle.tar.gz
  ######################################################################## 100.0%
  ==> Pouring m4-1.4.18.x86_64_linux.bottle.tar.gz
  🍺  /home/linuxbrew/.linuxbrew/Cellar/m4/1.4.18: 13 files, 1.1MB
  ==> Installing curl dependency: gmp
  ==> Downloading https://linuxbrew.bintray.com/bottles/gmp-6.1.2_3.x86_64_linux.bottle.1.tar.gz
  ######################################################################## 100.0%
  ==> Pouring gmp-6.1.2_3.x86_64_linux.bottle.1.tar.gz
  🍺  /home/linuxbrew/.linuxbrew/Cellar/gmp/6.1.2_3: 20 files, 3.8MB
  ...
  ```

- What you expected to happen
  I wanted all bottles to be downloaded from my `HOMEBREW_BOTTLE_DOMAIN`.

- Step-by-step reproduction instructions (by running `brew install` commands)
  1. Run https://github.com/Linuxbrew/install/blob/master/install-ruby.
  2. `export HOMEBREW_BOTTLE_DOMAIN`
  3. Run a slightly modified version of https://github.com/Linuxbrew/install/blob/master/install.

-----

I'm pretty sure this is caused by the `root_url` lines in the formulae in question. It looks like these lines were previously discussed in #13110, but by my count, there are still 337 formulae (out of 4873) that still have `root_url` lines.

I'm not familiar with how the Linuxbrew test bot process updates the formulae. If there is agreement that the lines should be removed, I'm happy to put in a PR to directly modify the files if that's the right action. If there's something else I can do to help, please let me know.

Thanks for the awesomeness that is Linuxbrew! 😄

**Comment by issyl0** [comment]
Hi, @mikesep.

> Thanks for the awesomeness that is Linuxbrew!

Thanks for the kind words, and for using Homebrew on Linux!

> I'm pretty sure this is caused by the root_url lines in the formulae in question.

Me too.

> I'm not familiar with how the Linuxbrew test bot process updates the formulae.

It's my understanding that if `HOMEBREW_BOTTLE_DOMAIN` is set when bottles are pulled (as per the discussion in #13110), or if we're pulling them directly on Linux, then the `root_url` lines get removed by the LinuxbrewTestBot. Obviously, the speed at which that happens for each of the remaining `root_url` lines is dictated by how often we merge changes and build bottles for those formulae, which may not be regularly.

> I'm happy to put in a PR to directly modify the files if that's the right action.

Yep, that sounds like a good course of action. We look forward to your PR!

**Comment by mikesep** [comment]
For the record, with the PR merged, `brew` is indeed fetching all bottles from my `HOMEBREW_BOTTLE_DOMAIN`.
