### ISSUE TITLE
`lsof` 4.93.2 fails to install with `Errno::ENOENT: No such file or directory - lsof.8`

### ISSUE THREAD

**Issue by estraph** [Homebrew/linuxbrew-core#14662]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ~ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?~ failed with `Error: Not Found`
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
➜  ~ brew config
HOMEBREW_VERSION: 2.1.9-7-gde72a23
ORIGIN: https://github.com/Homebrew/brew
HEAD: de72a2310930c3f0903292770b433f197a8d8a6c
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 65fcc24a883eab20dcba1cb1bf6bfee76379cad7
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/raph/.cache/Homebrew
HOMEBREW_LOGS: /home/raph/.cache/Homebrew/Logs
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.17.2 => /bin/git
Curl: 7.61.1 => /usr/bin/curl
Kernel: Linux 4.14.133-113.105.amzn2.x86_64 x86_64 GNU/Linux
OS: Amazon Linux release 2 (Karoo) (Karoo)
Host glibc: 2.26
/usr/bin/gcc: 7.3.1
glibc: N/A
gcc: N/A
xorg: N/A
```
```
➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/raph/.pyenv/shims/python3.7-config
  /home/raph/.pyenv/shims/python3.7m-config
  /home/raph/.pyenv/shims/python3-config
  /home/raph/.pyenv/shims/python-config
  /bin/pkg-config
  /bin/python-config
  /bin/python2-config
  /bin/python2.7-config
  /bin/pcre-config
  /bin/krb5-config
  /bin/ncursesw6-config
  /bin/ncurses6-config
```

To help us debug your issue please explain:

- What you were trying to do (and why)
Upgrading `lsof` from `4.91` to `4.93.2`

- What happened (include command output)
```
➜  ~ brew upgrade lsof
==> Upgrading 1 outdated package:
lsof 4.91 -> 4.93.2
==> Upgrading lsof 
==> Downloading https://github.com/lsof-org/lsof/archive/4.93.2.tar.gz
==> Downloading from https://codeload.github.com/lsof-org/lsof/tar.gz/4.93.2
######################################################################## 100.0%
==> ./Configure -n linux
==> make
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - lsof.8
```

- What you expected to happen
`lsof` should upgrade without errors.

- Step-by-step reproduction instructions (by running `brew install` commands)
`brew upgrade lsof` or `brew install lsof`

**Comment by estraph** [comment]
Seems like this is the offending code:

https://github.com/Homebrew/linuxbrew-core/commit/5e0cd152435d4f7e33038c5880fa67283df36c5e#diff-9c9bfed23435f4cfb785a8a846b678ddR35

Which was merged in https://github.com/Homebrew/linuxbrew-core/pull/14649

**Comment by estraph** [comment]
This comment by @issyl0 on that PR seems relevant: https://github.com/Homebrew/linuxbrew-core/pull/14649#issuecomment-518555722

> TODO: Check that lsof builds on Linux now, as there was a complicated conflict in the install step.

**Comment by issyl0** [comment]
Sorry about this, @estraf! I was hoping I’d get to fix this before anyone noticed, but my work day was too long. I’ll look at this now.

**Comment by estraph** [comment]
Thank you, it's actually blocking my project somewhat now, let me know if I can help

**Comment by estraph** [comment]
Looks like there are new maintainers for `lsof` and they renamed the manpage to upper-case `Lsof`, there are other issues open for this, e.g. https://github.com/lsof-org/lsof/issues/66

**Comment by issyl0** [comment]
Thanks for the help testing on the PR, @estraph, and for raising this issue. The fix is now in master, so if you `brew update` and `brew upgrade` again it will install cleanly. As you've got local changes now, you may need to `brew update-reset` to get a blank slate.

:rocket:

**Comment by estraph** [comment]
Thanks for the swift action!
