### ISSUE TITLE
Unable to install libevent

### ISSUE THREAD

**Issue by eredi93** [Homebrew/linuxbrew-core#14731]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
- What happened (include command output)
- What you expected to happen
- Step-by-step reproduction instructions (by running `brew install` commands)

### Unable to install libevent

I'm trying to install libevent but if fails with `'./ltmain.sh' not found`
```
$ brew install libevent
==> Downloading https://github.com/libevent/libevent/archive/release-2.1.11-stable.tar.gz
Already downloaded: /home/jacopo/.cache/Homebrew/downloads/7fc0b50cb53a5fecb38f6713603e8bc4d5d7ce854ae791fef6654812a4c877d3--libevent-release-2.1.11-stable.tar.gz
==> ./autogen.sh
Last 15 lines from /home/jacopo/.cache/Homebrew/Logs/libevent/01.autogen.sh:
glibtoolize: copying file 'm4/ltsugar.m4'
glibtoolize: copying file 'm4/ltversion.m4'
glibtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /home/linuxbrew/.linuxbrew/Cellar/autoconf/2.69_1/bin/autoconf --force
autoreconf: running: /home/linuxbrew/.linuxbrew/Cellar/autoconf/2.69_1/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:25: installing './compile'
configure.ac:33: installing './config.guess'
configure.ac:33: installing './config.sub'
configure.ac:13: installing './install-sh'
configure.ac:129: error: required file './ltmain.sh' not found
configure.ac:13: installing './missing'
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
autoreconf: automake failed with exit status: 1

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
libevent: Build a bottle for Linuxbrew https://github.com/Homebrew/linuxbrew-core/pull/14715
$
```

Brew config output
```
$ brew config
HOMEBREW_VERSION: 2.1.9-19-g34f4853
ORIGIN: https://github.com/Homebrew/brew
HEAD: 34f48530c8d3edac59b819cebffc30770dcc6a82
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 0f32334540637de6f5805c14c2abe27207d44b11
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/jacopo/.cache/Homebrew
HOMEBREW_LOGS: /home/jacopo/.cache/Homebrew/Logs
HOMEBREW_GITHUB_API_TOKEN: set
CPU: octa-core 64-bit broadwell
Homebrew Ruby: 2.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.22.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.61.1 => /usr/bin/curl
Kernel: Linux 4.14.133-113.112.amzn2.x86_64 x86_64 GNU/Linux
OS: Amazon Linux release 2 (Karoo) (Karoo)
Host glibc: 2.26
/usr/bin/gcc: 7.3.1
glibc: N/A
gcc: N/A
xorg: 20170115_1
```
brew doctor
```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/jacopo/.pyenv/shims/python3.7-config
  /home/jacopo/.pyenv/shims/python3-config
  /home/jacopo/.pyenv/shims/python3.7m-config
  /home/jacopo/.pyenv/shims/python-config
  /bin/pkg-config
  /bin/python-config
  /bin/python2-config
  /bin/python2.7-config
  /bin/pcre-config
  /bin/krb5-config
  /bin/ncursesw6-config
  /bin/ncurses6-config
  /bin/curl-config
$
```

**Comment by iMichka** [comment]
We had no issue building the precompiled binary: #14715

Can you try to update and try again?

If it works for you, I propose to close this issue. Of course you could also report it to the `libevent` developers.

**Comment by eredi93** [comment]
i updated `brew` and it worked at first try 🤷‍♂ 
not sure what happened but thx 😄
