### ISSUE TITLE
Cannot compile program with NetCDF and gfortran@9

### ISSUE THREAD

**Issue by dmey** [Homebrew/linuxbrew-core#14967]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 2.1.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: 925ec737fba1db97d0170c56de982900711cacd3
Last commit: 10 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 2c7aca41906a755bce3828c80182e7242d0ea24b
Core tap last commit: 9 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/david/.cache/Homebrew
HOMEBREW_LOGS: /home/david/.cache/Homebrew/Logs
CPU: quad-core 64-bit unknown_0x6_0x45
Homebrew Ruby: 2.5.1 => /usr/bin/ruby2.5
Clang: N/A
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 4.4.0-18362-Microsoft x86_64 GNU/Linux
OS: Ubuntu 18.04.3 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.4.0
glibc: N/A
gcc: 5.5.0_4
xorg: N/A
```

To help us debug your issue please explain:

- What you were trying to do (and why)

Compile Fortran program that depends on `libnetcdff`

- What happened (include command output)

```
Fatal Error: Cannot read module file 'netcdf.mod' opened at (1), because it was created by a different version of GNU Fortran
```

- What you expected to happen

Read `netcdf.mod` and continue

- Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install netcdf gcc@9
wget https://www.unidata.ucar.edu/software/netcdf/examples/programs/simple_xy_wr.f90
gfortran-9 -c -I/home/linuxbrew/.linuxbrew/include/ simple_xy_wr.f90
gfortran-9 -o simple_xy_wr simple_xy_wr.o -L/home/linuxbrew/.linuxbrew/lib -lnetcdff
```

**Comment by zbeekman** [comment]
how linux brew picks the compiler is a bit opaque. It's been on my todo list for quite some time to get saner Fortran  compiler handling in Homebrew, and seeing others encounter similar issues is pushing me closer to carving out some time to make that happen.

You might be able to get away with something like:

```
brew unlink gcc # if you brew install'ed gcc
export FC=$(brew --prefix)/opt/gcc@9/bin/gfortran-9
brew rm netcdf
brew install gcc@9
brew install --cc=gcc-9 netcdf
```

But this is a dirty hack and I should make it so that fortran compilers respect `--cc=gcc-<#>` at the very least, and probably stop allowing rogue Fortran compilers to be used by Homebrew. Soon F18/new-flang/not-legacy-flang/i-don't-know-what-to-call-it-anymore will be part of llvm/clang in official releases, and we may need to consider how to deal with building using f18.

**Comment by zbeekman** [comment]
also, FYI, this is not an easy problem to remedy; lack of portability/standardization of `.mod` files between vendors and even compiler versions within a vendor make this a real nightmare. Even with submodules, you'd think you could ship a parent module and then keep the submodule implementations private, and ship compiled object files, but the Fortran ABI is not standardized, so this probably also won't work.

**Comment by iMichka** [comment]
Right now this is not something we are actively working on. Looks like it might not be easy to fix.

@zbeekman provided a possible workaround that might be worth trying out.
