### ISSUE TITLE
Nushell for Linux

### ISSUE THREAD

**Issue by xasx** [Homebrew/linuxbrew-core#15316]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
    `brew install nushell`

- What happened (include command output)
   - Rust nightly for Apple Darwin was downloaded
   - Compilation of the Bottle failed, so does the whole installing

- What you expected to happen
    - A platform-specific (i.e. Linux) Rust nightly is downloaded
    - compilation succeeds

- Step-by-step reproduction instructions (by running `brew install` commands)
    `brew install nushell`

The bottle does just seem to not be adapted for Linux so far.

**Comment by iMichka** [comment]
See https://github.com/Homebrew/homebrew-core/pull/45391#issuecomment-545046665

We are waiting for a stable release. We should not have accepted such an unstable package in homebrew-core ... but now it's sort of too late. We will be waiting for a working update.

**Comment by waldyrious** [comment]
Just tested installing nushell on Linux after the updates from upstream's [PR#46505](https://github.com/Homebrew/homebrew-core/pull/46505) were picked up in 19a857f3a, and a Linux bottle was built in #17569 / 133aa0c4d. It worked as expected, so finally this issue is actually resolved! 🎉
