### ISSUE TITLE
go@1.12 installs darwin version

### ISSUE THREAD

**Issue by lucasyvas** [Homebrew/linuxbrew-core#15732]
- [X ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X ] ran `brew update` and can still reproduce the problem?
- [X ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

go@1.12 installs the darwin version. This is a dependency of `kubernetes-cli`, so that formula cannot install.

**Comment by issyl0** [comment]
@lucasyvas Thanks for reporting this. Please `brew update` and try installing it again - the [fix to install the Linux version](https://github.com/Homebrew/linuxbrew-core/pull/15731) has just been merged to master.
