### ISSUE TITLE
aws-google-auth installation fails with NoMethodError: undefined method `sdk_path_if_needed' for OS::Mac:Module

### ISSUE THREAD

**Issue by endorama** [Homebrew/linuxbrew-core#15747]
- [x] are reporting a bug others will be able to reproduce and not asking a question or requesting software.
- [x] have a problem with `brew install`.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/endorama/1bc11eec34e621d30a861fb51341bb5a
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
  Installing `aws-google-auth` formula on Elementary OS 5.0 (Ubuntu 18.04 derivate)
- What happened (include command output)
Formula did not installed correctly
```
$ brew install aws-google-auth                                                                            19:29:59
==> Downloading https://github.com/cevoaustralia/aws-google-auth/archive/0.0.32.tar.gz
Already downloaded: /home/etenani/.cache/Homebrew/downloads/10e84de7933d0d4a359dc6e3d308ff234b43cd92408086b14aa81a4c58bf59c7--aws-google-auth-0.0.32.tar.gz
==> Downloading https://files.pythonhosted.org/packages/11/74/2c151a13ef41ab9fb43b3c4ff9e788e0496ed7923b2078d42cab30622
Already downloaded: /home/etenani/.cache/Homebrew/downloads/507d2087bf24df82641b681a5fe4da778ef50ebe819a86ea1b584f70788f0f63--virtualenv-16.7.4.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/tmp/aws-google-auth--homebrew-virtualenv-20190923-1
==> python3 -s /tmp/aws-google-auth--homebrew-virtualenv-20190923-11210-8sskxs/target/bin/virtualenv -p python3 /home/l
==> Downloading https://files.pythonhosted.org/packages/b4/ef/063484f1f9ba3081e920ec9972c96664e2edb9fdc3d8669b0e3b8fc0a
Already downloaded: /home/etenani/.cache/Homebrew/downloads/86face960af0765bfb2d0403cf507a317ab5e2584108453ce42031f7ca477bf9--entrypoints-0.3.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/aws-google-auth/0.0.32/libexec/bin/pip install -v --no-deps --no-binary :all: --i
==> Downloading https://files.pythonhosted.org/packages/81/1a/6b2971adc1bca55b9a53ed1efa372acff7e8b9913982a396f3fa046ef
Already downloaded: /home/etenani/.cache/Homebrew/downloads/93abb18b17ef7e99cfcc8c8619a85ced65b38d9549d84f90087ba814f1e14c85--Pillow-6.0.0.tar.gz
Error: An exception occurred within a child process:
  NoMethodError: undefined method `sdk_path_if_needed' for OS::Mac:Module

```
- What you expected to happen
The formula should install correctly
- Step-by-step reproduction instructions (by running `brew install` commands)
  - `brew install aws-google-auth`

**Comment by iMichka** [comment]
I will try to fix this here: #16056

**Comment by iMichka** [comment]
FYI I merged the changes, so it should be good.

But upstream moved the tag of their release, so that the source file they initially shipped is now gone, and a different one is now there ...

2019-10-07T21:58:47.6459029Z ==> Downloading https://github.com/cevoaustralia/aws-google-auth/archive/0.0.32.tar.gz
2019-10-07T21:58:48.0006209Z Error: An exception occurred within a child process:
2019-10-07T21:58:48.0007403Z   ChecksumMismatchError: SHA256 mismatch
2019-10-07T21:58:48.0007971Z Expected: d5ac9776ecfe0b0d6daa9cc160b2614e4c53fa37633528e3f661efc58fd24754
2019-10-07T21:58:48.0008116Z   Actual: c70b81e451c4b0ca5172b409cf5b4445e670006252f762351fdd7460f01c634b
2019-10-07T21:58:48.0009346Z  Archive: /home/vsts_azpcontainer/.cache/Homebrew/downloads/10e84de7933d0d4a359dc6e3d308ff234b43cd92408086b14aa81a4c58bf59c7--aws-google-auth-0.0.32.tar.gz

**Comment by iMichka** [comment]
Issue opened at https://github.com/cevoaustralia/aws-google-auth/issues/152

**Comment by iMichka** [comment]
I will close this issue as this is now an upstream issue. Once https://github.com/cevoaustralia/aws-google-auth/issues/152 is solved, the change can be made to https://github.com/Homebrew/homebrew-core and then merged back here. We will then make an attempt to build this formula again.
