### ISSUE TITLE
Multiple 32-bit arm versions for binary build with go. Which to use in formula? 

### ISSUE THREAD

**Issue by mavogel** [Homebrew/linuxbrew-core#15761]
## Concern
In `goreleaser` we support the build of brew formulas for go binaries but were not quite sure which 32-bit arm version to put in the formula.

Golang allows building binaries for multiple arm 32-bit versions according to their [docs](https://golang.org/doc/install/source#environment)

> $GOARM (for arm only; default is auto-detected if building on the target processor, 6 if not). Possible values are: 5,6,7
> GOARM=5: use software floating point; when CPU doesn't have VFP co-processor
GOARM=6: use VFPv1 only; default if cross compiling; usually ARM11 or better cores (VFPv2 or better is also supported)
GOARM=7: use VFPv3; usually Cortex-A cores

Homebrew supports 32-bit arm as well in their formulas as well according to the [docs](https://docs.brew.sh/Homebrew-on-Linux#arm) but 

> Support for ARM is on a best-effort basis. Pull requests are welcome to improve the experience on ARM platforms.

## Questions
1. What exactly means `on a best-effort basis`?
1. Is it possible to support multiple 32-bit arm version a single formula?
1. Which version (5,6,7) would the maintainers recommend to use in the formula if not?

## Related issues
- https://github.com/goreleaser/goreleaser/pull/1153
- https://github.com/goreleaser/goreleaser/issues/1146

**Comment by iMichka** [comment]
> What exactly means on a best-effort basis?

It means that brew supports it (there is some basic infrastructure for it in brew), but almost no formula has been tested with 32 bit arm. We do not have a CI for it. We do not have the manpower to do anything related to 32 bit arm.

>Is it possible to support multiple 32-bit arm version a single formula?

Yes. You can compile everything from source. Binaries are not available. If binaries are wished, this should be started as a fork from this repo. Once enough binaries are ready and published, and the project has enough maintainers, these binaries could be moved back to this main repo.

>Which version (5,6,7) would the maintainers recommend using in the formula if not?

I have no clue :)

**Comment by mavogel** [comment]
thx @iMichka for your answer. The other maintainers answered as well here: https://discourse.brew.sh/t/multiple-arm-32-bit-binaries-build-with-golang-which-to-use-in-formula/5757
