### ISSUE TITLE
brew install octave fails (ubuntu)

### ISSUE THREAD

**Issue by mmngreco** [Homebrew/linuxbrew-core#15851]
- [ ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [x] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```bash
base ❯ brew gist-logs octave
Error: No logs.
```

To help us debug your issue please explain:

- What you were trying to do (and why)

Im trying to install `octave`.

- What happened (include command output)

```bash
base ❯ brew install octave
==> Installing dependencies for octave: pstoedit, qhull, qrupdate, metis, m4, suite-sparse, sundials, texinfo and curl
==> Installing octave dependency: pstoedit
==> Downloading https://downloads.sourceforge.net/project/pstoedit/pstoedit/3.74/pstoedit-3.74.tar.gz
Already downloaded: /home/mgreco/.cache/Homebrew/downloads/82f1bb0c6bb9594726b06c01688154da0c16dd11cea2d526b4c4fa99e6487e67--pstoedit-3.74.tar.gz
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/pstoedit/3.74
==> make install
Last 15 lines from /home/mgreco/.cache/Homebrew/Logs/pstoedit/02.make:
   abs(long long __x) { return __builtin_llabs (__x); }
   ^
/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/include/c++/5.5.0/cstdlib:166:3: note: candidate: long int std::abs(long int)
   abs(long __i) { return __builtin_labs(__i); }
   ^
libtool: compile:  g++-5 -DHAVE_CONFIG_H -I. -DHAVE_LIBPLOTTER -DHAVE_MKSTEMP -DDEFAULTGS=gs -DPSTOEDITDATADIR=\"/home/linuxbrew/.linuxbrew/Cellar/pstoedit/3.74/share/pstoedit\" -DPSTOEDITLIBDIR=\"/home/linuxbrew/.linuxbrew/Cellar/pstoedit/3.74/lib/pstoedit\" -Wall -Wextra -Wuninitialized -Wswitch-default -Wunused -Wshadow -Wwrite-strings -Wcast-qual -Wpointer-arith -Wno-long-long -D_LITTLE_ENDIAN -g -O2 -DINTERNALBOOL -c drvjava.cpp  -fPIC -DPIC -o .libs/drvjava.o
libtool: compile:  g++-5 -DHAVE_CONFIG_H -I. -DHAVE_LIBPLOTTER -DHAVE_MKSTEMP -DDEFAULTGS=gs -DPSTOEDITDATADIR=\"/home/linuxbrew/.linuxbrew/Cellar/pstoedit/3.74/share/pstoedit\" -DPSTOEDITLIBDIR=\"/home/linuxbrew/.linuxbrew/Cellar/pstoedit/3.74/lib/pstoedit\" -Wall -Wextra -Wuninitialized -Wswitch-default -Wunused -Wshadow -Wwrite-strings -Wcast-qual -Wpointer-arith -Wno-long-long -D_LITTLE_ENDIAN -g -O2 -DINTERNALBOOL -c drvjava2.cpp  -fPIC -DPIC -o .libs/drvjava2.o
/bin/bash ../libtool  --tag=CXX   --mode=compile g++-5 -DHAVE_CONFIG_H -I.  -DHAVE_LIBPLOTTER  -DHAVE_MKSTEMP     -DDEFAULTGS=gs -DPSTOEDITDATADIR="\"/home/linuxbrew/.linuxbrew/Cellar/pstoedit/3.74/share/pstoedit\"" -DPSTOEDITLIBDIR="\"/home/linuxbrew/.linuxbrew/Cellar/pstoedit/3.74/lib/pstoedit\"" -Wall -Wextra -Wuninitialized -Wswitch-default -Wunused -Wshadow -Wwrite-strings -Wcast-qual -Wpointer-arith -Wno-long-long -D_LITTLE_ENDIAN  -g -O2 -DINTERNALBOOL -c -o drvpdf.lo drvpdf.cpp
Makefile:874: recipe for target 'drvdxf.lo' failed
make[1]: *** [drvdxf.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
libtool: compile:  g++-5 -DHAVE_CONFIG_H -I. -DHAVE_LIBPLOTTER -DHAVE_MKSTEMP -DDEFAULTGS=gs -DPSTOEDITDATADIR=\"/home/linuxbrew/.linuxbrew/Cellar/pstoedit/3.74/share/pstoedit\" -DPSTOEDITLIBDIR=\"/home/linuxbrew/.linuxbrew/Cellar/pstoedit/3.74/lib/pstoedit\" -Wall -Wextra -Wuninitialized -Wswitch-default -Wunused -Wshadow -Wwrite-strings -Wcast-qual -Wpointer-arith -Wno-long-long -D_LITTLE_ENDIAN -g -O2 -DINTERNALBOOL -c drvpdf.cpp  -fPIC -DPIC -o .libs/drvpdf.o
make[1]: Leaving directory '/tmp/pstoedit-20191001-22166-je2q7f/pstoedit-3.74/src'
Makefile:467: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting
```
- What you expected to happen

Getting octave installed.

- Step-by-step reproduction instructions (by running `brew install` commands)

```bash
brew install octave
```

also

```bash
brew install pstoedit
```

**Comment by dawidd6** [comment]
Thanks for bringing this up. I see that we had a bottle earlier for 4.4.1, but don't have one for latest 5.1.0. Here is a PR: https://github.com/Homebrew/linuxbrew-core/pull/15852. Will try to work on that.

**Comment by mmngreco** [comment]
Hi @dawidd6, Thank you for you reply. I would like to know if there is a workaround to install octave 4.4.1 or 5.1.0.

**Comment by dawidd6** [comment]
It's still building on CI as I write this comment, will see later.

**Comment by dawidd6** [comment]
Bottle was built successfully and is already uploaded.

https://github.com/Homebrew/linuxbrew-core/commit/9057b4d037f72858eaa1cc97f0465b3c7723a44d
