### ISSUE TITLE
Graphviz fails to update to 2.42.2 on Ubuntu Bionic 18.04.2 x86_64

### ISSUE THREAD

**Issue by pmarreck** [Homebrew/linuxbrew-core#16046]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X ] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md)
- [X ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [X ] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)

I was simply trying to `brew upgrade` and got this failure

- What happened (include command output)

See below for entire terminal log

- What you expected to happen

Everything to update properly.

- Step-by-step reproduction instructions (by running `brew install` commands)

```
Administrator:~/environment (master) $ brew update; brew upgrade
Already up-to-date.
==> Upgrading 3 outdated packages:
graphviz 2.40.1_2 -> 2.42.2
imagemagick 7.0.8-59 -> 7.0.8-68
shared-mime-info 1.13.1 -> 1.14
==> Upgrading graphviz 
==> Downloading https://gitlab.com/graphviz/graphviz/-/archive/2.42.2/graphviz-2.42.2.tar.gz
Already downloaded: /home/ubuntu/.cache/Homebrew/downloads/bd3e5ec2141de7efe748dec0d8688c02ef453b2cf4c144e9dde6fcbb6e56d424--graphviz-2.42.2.tar.gz
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - lib/vmalloc/features/vmalloc
Administrator:~/environment (master) $ uname -a
Linux ip-172-31-43-117 4.15.0-1047-aws #49-Ubuntu SMP Fri Aug 23 09:02:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Administrator:~/environment (master) $ brew doctor
Your system is ready to brew.
Administrator:~/environment (master) $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
Administrator:~/environment (master) $ brew config
HOMEBREW_VERSION: 2.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: b7e0eaae2bd6600500c961ac342b5d817b25b571
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 2b5def7cbb0fab4ddcefde6684442ed322d3cbc7
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/ubuntu/.cache/Homebrew
HOMEBREW_LOGS: /home/ubuntu/.cache/Homebrew/Logs
CPU: single-core 64-bit haswell
Homebrew Ruby: 2.3.7 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/bin/ruby
Clang: N/A
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 4.15.0-1047-aws x86_64 GNU/Linux
OS: Ubuntu 18.04.2 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.4.0
glibc: N/A
gcc: 5.5.0_4
xorg: 20170115_1
Administrator:~/environment (master) $ brew install graphviz
Error: graphviz 2.40.1_2 is already installed
To upgrade to 2.42.2, run `brew upgrade graphviz`.
Administrator:~/environment (master) $ brew upgrade graphviz
==> Upgrading 1 outdated package:
graphviz 2.40.1_2 -> 2.42.2
==> Upgrading graphviz 
==> Downloading https://gitlab.com/graphviz/graphviz/-/archive/2.42.2/graphviz-2.42.2.tar.gz
Already downloaded: /home/ubuntu/.cache/Homebrew/downloads/bd3e5ec2141de7efe748dec0d8688c02ef453b2cf4c144e9dde6fcbb6e56d424--graphviz-2.42.2.tar.gz
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - lib/vmalloc/features/vmalloc
Administrator:~/environment (master) $ 
```

**Comment by dawidd6** [comment]
https://github.com/Homebrew/linuxbrew-core/pull/16041

**Comment by dawidd6** [comment]
Should be fixed now.
