### ISSUE TITLE
itk version 5.0.1: Request for a bottle

### ISSUE THREAD

**Issue by aboualiaa** [Homebrew/linuxbrew-core#16902]
- [x] checked that there aren't other open issues for the same formula bottle request?
- [x] does the FORMULA `itk` version 5.0.1 not have the `bottle` block? bottle does not exist
- [ ] ran `brew install FORMULA` and it succeeded?

the current bottle of the formula itk is of version 4.13 while version 5.0.1 has been released since july.

**Comment by dawidd6** [comment]
Hello, thanks for raising this issue, but we do not accept request for formula updates here.
This issue template is meant to be used by users when they want to request a bottle for software that currently does not have one for linux.

Nevertheless I submitted PR upstream: https://github.com/Homebrew/homebrew-core/pull/46131

**Comment by dawidd6** [comment]
It is done.
