### ISSUE TITLE
folly failed to build on Centos7

### ISSUE THREAD

**Issue by dopeter** [Homebrew/linuxbrew-core#17065]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [y ] ran `brew update` and can still reproduce the problem?
- [y ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
Install folly on Centos7 

## What happened (include command output)

build failure

<details>
  <summary>Command output</summary>
  <pre>

==> Downloading https://github.com/facebook/folly/archive/v2019.10.28.00.tar.gz
Already downloaded: /home/xiachang/.cache/Homebrew/downloads/8e3e5d28acdee6f9a5c845bbfeec830583240c31f80bf43efa51b07faa5fc25b--folly-2019.10.28.00.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/linuxbrew/.linuxbrew/Cellar/folly/2019.10.28.00 -DCMAKE_BUI
==> make
Last 15 lines from /home/xiachang/.cache/Homebrew/Logs/folly/02.make:
/home/linuxbrew/.linuxbrew/bin/ld: CMakeFiles/folly_base.dir/folly/system/ThreadName.cpp.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/home/linuxbrew/.linuxbrew/bin/ld: CMakeFiles/folly_base.dir/folly/io/async/test/ScopedBoundPort.cpp.o: relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/home/linuxbrew/.linuxbrew/bin/ld: CMakeFiles/folly_base.dir/folly/io/async/test/SocketPair.cpp.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/home/linuxbrew/.linuxbrew/bin/ld: CMakeFiles/folly_base.dir/folly/io/async/test/TimeUtil.cpp.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libdouble-conversion.a(double-conversion.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libdouble-conversion.a(fast-dtoa.cc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libdouble-conversion.a(strtod.cc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/home/linuxbrew/.linuxbrew/bin/ld: /home/linuxbrew/.linuxbrew/lib/libdouble-conversion.a(cached-powers.cc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/home/linuxbrew/.linuxbrew/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/folly.dir/build.make:532: libfolly.so] Error 1
make[2]: Leaving directory '/tmp/folly-20191106-67254-o5o0rd/folly-2019.10.28.00/_build'
make[1]: *** [CMakeFiles/Makefile2:146: CMakeFiles/folly.dir/all] Error 2
make[1]: Leaving directory '/tmp/folly-20191106-67254-o5o0rd/folly-2019.10.28.00/_build'
make: *** [Makefile:133: all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

  </pre>
</details>

## What you expected to happen

Install successful

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install folly

**Comment by dawidd6** [comment]
This formula is problematic for us. We couldn't get it to build successfully.

Would happily accept a PR fixing it.

**Comment by dawidd6** [comment]
Should be fixed now.
