### ISSUE TITLE
`envchain` installation fails with fatal error: libsecret/secret.h: No such file or directory

### ISSUE THREAD

**Issue by endorama** [Homebrew/linuxbrew-core#17202]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
`gist-logs` fails with "Error: not found"
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

<details>
<summary>brew config</summary>
<pre>
HOMEBREW_VERSION: 2.1.16-40-g20cf2af
ORIGIN: https://github.com/Homebrew/brew
HEAD: 20cf2afede4070b0058d1faee869dea19dc9f5b9
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: d637658d97a90e6269a55387932f8f71fffd6e99
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/.../.cache/Homebrew
HOMEBREW_LOGS: /home/.../cache/Homebrew/Logs
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_VISUAL: vim
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: N/A
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 4.15.0-66-generic x86_64 GNU/Linux
OS: elementary OS 5.0 Juno (juno)
Host glibc: 2.27
/usr/bin/gcc: 7.4.0
glibc: N/A
gcc: 5.5.0_4
xorg: N/A
</pre>
</details>

<details>
<summary>brew doctor</summary>
<pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/.../.asdf/shims/python-config
  /home/.../.asdf/shims/python3.7-config
  /home/.../.asdf/shims/python3.7m-config
  /home/.../.asdf/shims/python3-config
  /home/.../.asdf/shims/python3.8-config
  /home/.../.local/bin/pre-commit-validate-config

</pre>
</details>

## What you were trying to do (and why)
Install `envchain`

## What happened (include command output)

Installation fails with `fatal error: libsecret/secret.h: No such file or directory`.

<details>
  <summary>Command output</summary>
  <pre>
==> Downloading https://github.com/sorah/envchain/archive/v1.0.1.tar.gz
Already downloaded: /home/.../.cache/Homebrew/downloads/e659f58e6e8f2248e90dda887c64c6a39e748c7b552b6a67a1b6517fa0b0a9f5--envchain-1.0.1.tar.gz
==> make DESTDIR=/home/linuxbrew/.linuxbrew/Cellar/envchain/1.0.1 install
Last 15 lines from /home/.../.cache/Homebrew/Logs/envchain/01.make:
2019-11-11 16:06:21 +0100

make
DESTDIR=/home/linuxbrew/.linuxbrew/Cellar/envchain/1.0.1
install

gcc-5 -c -Wall -Wextra -ansi -pedantic -std=c99 `pkg-config --cflags libsecret-1`  -o envchain.o envchain.c
gcc-5 -c -Wall -Wextra -ansi -pedantic -std=c99 `pkg-config --cflags libsecret-1`  -o envchain_linux.o envchain_linux.c
envchain_linux.c:2:30: fatal error: libsecret/secret.h: No such file or directory
compilation terminated.
make: *** [Makefile:20: envchain_linux.o] Error 1
make: *** Waiting for unfinished jobs....

READ THIS: https://docs.brew.sh/Troubleshooting
  </pre>
</details>

## What you expected to happen

`envchain` installs successfully

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install envchain`

I suspect this may be due to how `envchain` includes `libsecrets`? 

https://github.com/sorah/envchain/blob/master/envchain_linux.c#L2

**Comment by dawidd6** [comment]
Thanks for reporting this. I'll try to fix it here: https://github.com/Homebrew/linuxbrew-core/pull/17203.

**Comment by endorama** [comment]
It's working! Thanks for the quick fix!
