### ISSUE TITLE
mpv install leads to relocation error due to mujs

### ISSUE THREAD

**Issue by beilharz** [Homebrew/linuxbrew-core#17239]
- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/74f0244b8700ed33cd81d57f5c62bb3a
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
`brew install mpv`

## What happened (include command output)

Mainly `relocation R_X86_64_32S against `.data' can not be used when making a shared object`

<details>
  <summary>Command output</summary>
  <pre>

==> Installing dependencies for mpv: mujs
==> Installing mpv dependency: mujs
==> Downloading https://linuxbrew.bintray.com/bottles/mujs-1.0.6.x86_64_linux.bottle.tar.gz
Already downloaded: /home/jb/.cache/Homebrew/downloads/76dc489b1670fde58f657419818d4b2471f087b4dfb02c631eb8c19945926db2--mujs-1.0.6.x86_64_linux.bottle.tar.gz
==> Pouring mujs-1.0.6.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/mujs/1.0.6: 9 files, 712.3KB
==> Installing mpv
==> Downloading https://github.com/mpv-player/mpv/archive/v0.30.0.tar.gz
Already downloaded: /home/jb/.cache/Homebrew/downloads/6422a0fbfaf710b695ab35308553ff9d60fc54a157b9923d05fbf28b7662643d--mpv-0.30.0.tar.gz
==> ./bootstrap.py
==> python3 waf configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/mpv/0.30.0 --enable-html-build --enable-javascript --enable-libmpv-shared --enable-lua --enable-libarchi
==> python3 waf install
Last 15 lines from /home/jb/.cache/Homebrew/Logs/mpv/03.python3:
[257/469] Linking build/libmpv.so
[258/469] Compiling osdep/polldev.c
[259/469] Compiling osdep/timer-linux.c
[260/469] Compiling demux/demux_edl.c
[261/469] Compiling osdep/timer.c
[262/469] Compiling demux/demux_lavf.c
[263/469] Compiling osdep/threads.c
[264/469] Compiling demux/demux_libarchive.c
/usr/bin/ld: /home/linuxbrew/.linuxbrew/Cellar/mujs/1.0.6/lib/libmujs.a(libmujs.o): relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/tmp/mpv-20191113-15348-150k31/mpv-0.30.0/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)

READ THIS: https://docs.brew.sh/Troubleshooting

  </pre>
</details>

## What you expected to happen

mpv being installed

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install mpv`

## Possible Solution 

Adding `-fPIC` to `CFLAGS` in mujs Makefile as advised by the error message seems to fix the problem.  

<details>
  <summary>Command output</summary>
  <pre>
⋊> ~ cd ~/.cache/Homebrew/mujs--git/                                                                (base) 19:21:37
⋊> ~/.c/H/mujs--git on 14dc935 ⨯ vim Makefile                                                       (base) 19:41:47
⋊> ~/.c/H/mujs--git on 14dc935 ⨯ git diff                                                           (base) 19:41:57
diff --git a/Makefile b/Makefile
index 32b3607..190c244 100644
--- a/Makefile
+++ b/Makefile
@@ -15,7 +15,7 @@ endif
 
 # Compiler flags for various configurations:
 
-CFLAGS := -std=c99 -pedantic -Wall -Wextra -Wno-unused-parameter
+CFLAGS := -std=c99 -pedantic -Wall -Wextra -Wno-unused-parameter -fPIC
 
 ifeq "$(CC)" "clang"
   CFLAGS += -Wunreachable-code
⋊> ~/.c/H/mujs--git on 14dc935 ⨯ make clean                                                         (base) 19:41:58
rm -rf build
⋊> ~/.c/H/mujs--git on 14dc935 ⨯ make release                                                       (base) 19:42:03
make build=release
make[1]: Entering directory '/home/jb/.cache/Homebrew/mujs--git'
cc -std=c99 -pedantic -Wall -Wextra -Wno-unused-parameter -fPIC -Os -DHAVE_READLINE  -o build/release/libmujs.o -c one.c
In file included from one.c:3:0:
jsbuiltin.c: In function 'Encode':
jsbuiltin.c:100:45: warning: argument 'str' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
 static void Encode(js_State *J, const char *str, const char *unescaped)
                                             ^
jsbuiltin.c: In function 'Decode':
jsbuiltin.c:128:45: warning: argument 'str' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
 static void Decode(js_State *J, const char *str, const char *reserved)
                                             ^
In file included from one.c:16:0:
json.c: In function 'JSON_stringify':
json.c:327:18: warning: variable 'gap' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
  const char *s, *gap;
                  ^
cc -std=c99 -pedantic -Wall -Wextra -Wno-unused-parameter -fPIC -Os -DHAVE_READLINE  -o build/release/main.o -c main.c
cc -Wl,-s -o build/release/mujs build/release/libmujs.o build/release/main.o -lreadline -lm
cc -std=c99 -pedantic -Wall -Wextra -Wno-unused-parameter -fPIC -Os -DHAVE_READLINE  -o build/release/pp.o -c pp.c
pp.c: In function 'main':
pp.c:88:6: warning: variable 'minify' might be clobbered by 'longjmp' or 'vfork' [-Wclobbered]
  int minify = 0;
      ^
cc -Wl,-s -o build/release/mujs-pp build/release/libmujs.o build/release/pp.o -lm
make[1]: Leaving directory '/home/jb/.cache/Homebrew/mujs--git'
⋊> ~/.c/H/mujs--git on 14dc935 ⨯ make prefix=/home/linuxbrew/.linuxbrew/Cellar/mujs/1.0.6 install   (base) 19:42:32
Creating build/release/mujs.pc
install -d /home/linuxbrew/.linuxbrew/Cellar/mujs/1.0.6/include
install -d /home/linuxbrew/.linuxbrew/Cellar/mujs/1.0.6/lib
install -d /home/linuxbrew/.linuxbrew/Cellar/mujs/1.0.6/lib/pkgconfig
install -d /home/linuxbrew/.linuxbrew/Cellar/mujs/1.0.6/bin
install -m 644 mujs.h /home/linuxbrew/.linuxbrew/Cellar/mujs/1.0.6/include
install -m 644 build/release/mujs.pc /home/linuxbrew/.linuxbrew/Cellar/mujs/1.0.6/lib/pkgconfig
install -m 755 build/release/mujs /home/linuxbrew/.linuxbrew/Cellar/mujs/1.0.6/bin
ar cr build/release/libmujs.a build/release/libmujs.o
install -m 644 build/release/libmujs.a /home/linuxbrew/.linuxbrew/Cellar/mujs/1.0.6/lib
⋊> ~/.c/H/mujs--git on 14dc935 ⨯ brew install mpv                                                   (base) 19:42:34
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from 1e58e225a to 930bbe0b9.
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Downloading https://github.com/mpv-player/mpv/archive/v0.30.0.tar.gz
Already downloaded: /home/jb/.cache/Homebrew/downloads/6422a0fbfaf710b695ab35308553ff9d60fc54a157b9923d05fbf28b7662643d--mpv-0.30.0.tar.gz
==> ./bootstrap.py
==> python3 waf configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/mpv/0.30.0 --enable-html-build --enable-javasc
==> python3 waf install
==> Caveats
zsh completions have been installed to:
  /home/linuxbrew/.linuxbrew/share/zsh/site-functions
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/mpv/0.30.0: 28 files, 16.8MB, built in 1 minute 4 seconds
  </pre>
</details>

**Comment by dawidd6** [comment]
I think the issue here might be the fact that the build system wants to link against static `mujs` library instead of dynamic one, which seems to be complied with `-FPiC` flag but it's not installed to prefix.

**Comment by beilharz** [comment]
@dawidd6 yes, that seems to be the issue, thanks. 
The reason is that install for mujs [defaults to install-static](http://git.ghostscript.com/?p=mujs.git;a=blob;f=Makefile;h=32b3607de7b0d65c26bef114aac1f48e18d37171;hb=14dc9355bd71818cf01c1c690c1c91a0978ea9b8#l120)
Is changing the [mujs formular](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/mujs.rb#L23) to install-shared the right thing to do?

**Comment by dawidd6** [comment]
Yep, I've already tried that here https://github.com/Homebrew/linuxbrew-core/pull/17240/commits/5378d888353b529a817f50eac3cf17fad9dac449 and it seems to do the trick. You can submit a PR with that patch if you want (remember to bump the revision too) or just wait for me to do so.

**Comment by dawidd6** [comment]
Should be fixed now.

**Comment by beilharz** [comment]
Yes it is fixed for me. Thank you!
