### ISSUE TITLE
blast: version 2.10.0 referred to in formula no longer available on NCBI

### ISSUE THREAD

**Issue by ckeeling** [Homebrew/linuxbrew-core#17238]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Trying to brew install maker

## What happened (include command output)
```
...
==> Installing brewsci/bio/maker dependency: blast
==> Downloading https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.10.0/ncbi-blast-2.10.0+-src.tar.gz
##O#- #                                                                       
curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "blast"
Download failed: https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.10.0/ncbi-blast-2.10.0+-src.tar.gz
```

I notice in line 4 of the formula for blast, that this url doesn't exist. NCBI doesn't have (on 13/11/2019) a 2.10.0 directory, and the LATEST isn't 2.10.0 either.
url "https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.10.0/ncbi-blast-2.10.0+-src.tar.gz"

This line of the formula was changed a few days ago by @tseemann.  Maybe too soon, or NCBI subsequently pulled their new version?

## What you expected to happen

blast to properly install

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install maker

**Comment by issyl0** [comment]
Hi @ckeeling. Thanks for the comprehensive issue writeup! However, you'll need to raise this issue in [brewsci/bio](https://github.com/brewsci/homebrew-bio/issues) as `maker` is from that tap. Thanks!

**Comment by issyl0** [comment]
Oops, my mistake! This is us, not Brew Sci. But it's an upstream formula that comes from [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core). Updates get merged in periodically. Looks like there isn't an update waiting. I'll re-open this and do some more investigation...

**Comment by ckeeling** [comment]
No worries, where I already have an earlier version, upgrading blast (independent of maker) also fails.

```
brew upgrade blast
Updating Homebrew...
==> Upgrading 1 outdated package:
blast 2.9.0 -> 2.10.0
==> Upgrading blast 
==> Downloading https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.10.0/ncbi-blast-2.10.0+-src.tar.gz
curl: (22) The requested URL returned error: 404 Not Found                    

Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "blast"
Download failed: https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.10.0/ncbi-blast-2.10.0+-src.tar.gz
```

**Comment by tseemann** [comment]
Looks like NCBI pulled the source code. I clearly discovered it accidently too early!

**Comment by ckeeling** [comment]
Perfect, thanks.
