### ISSUE TITLE
openjdk install error

### ISSUE THREAD

**Issue by hidvegin** [Homebrew/linuxbrew-core#17374]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X ] ran `brew update` and can still reproduce the problem?
- [X ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

brew install openjdk

## What happened (include command output)

Installation stoped with error.

<details>
  <summary>Command output</summary>
  <pre>

  brew install openjdk
==> Downloading https://hg.openjdk.java.net/jdk-updates/jdk13u/archive/jdk-13.0.
Already downloaded: /home/hidvegi/.cache/Homebrew/downloads/1d269c3494918f742ce34065ae326d878d3a39f988b064249f58cbac0b7a67ac--jdk13u-jdk-13.0.1+9.tar.bz2
==> Downloading https://download.java.net/java/GA/jdk12.0.2/e482c34c86bd4bf8b56c
Already downloaded: /home/hidvegi/.cache/Homebrew/downloads/0c063c1db55c4b1323810e59dca242bbd1bedc828894003511e13362cc81291b--openjdk-12.0.2_osx-x64_bin.tar.gz
==> ./configure --without-version-pre --without-version-opt --with-version-build
Last 15 lines from /home/hidvegi/.cache/Homebrew/Logs/openjdk/01.configure:
checking pkg-config is at least version 0.9.0... yes
checking for default LOG value... 
checking headless only... no
checking for graphviz dot... no, cannot generate full docs
checking for pandoc... no, cannot generate full docs
checking full docs... no, missing dependencies
checking for cacerts file... default
checking for jni library path... default
checking if packaged modules are kept... yes (default)
checking for version string... 13.0.1+9
configure: Found potential Boot JDK using configure arguments
configure: Potential Boot JDK found at /tmp/openjdk-20191117-24264-70o5vg/jdk13u-jdk-13.0.1+9/boot-jdk/Contents/Home is incorrect JDK version (/tmp/openjdk-20191117-24264-70o5vg/jdk13u-jdk-13.0.1+9/build/.configure-support/generated-configure.sh: line 29699: /tmp/openjdk-20191117-24264-70o5vg/jdk13u-jdk-13.0.1+9/boot-jdk/Contents/Home/bin/java: cannot execute binary file: Exec format error); ignoring
configure: (Your Boot JDK version must be one of: 12 13)
configure: error: The path given by --with-boot-jdk does not contain a valid Boot JDK
configure exiting with result code 1

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
openjdk@12: Build a bottle for Linux https://github.com/Homebrew/linuxbrew-core/pull/17223
openjdk: Build a bottle for Linux https://github.com/Homebrew/linuxbrew-core/pull/17073
openjdk@11: Build a bottle for Linux https://github.com/Homebrew/linuxbrew-core/pull/17074

  </pre>
</details>

## What you expected to happen

Fully installation.

## Step-by-step reproduction instructions (by running `brew install` commands)

brew update
brew install openjdk

**Comment by dawidd6** [comment]
This is being worked on here: https://github.com/Homebrew/linuxbrew-core/pull/17073

**Comment by hidvegin** [comment]
dawidd6: Thank you for your comment. I am not an expert, but I think from your comment, I should wait for solve the bug until that I can not install openjdk from linuxbrew. Is it right?

**Comment by chiqj** [comment]
@dawidd6 Hi, any update for this issue? The PR is pending now.

**Comment by iMichka** [comment]
You could try the `adoptopendk` formulae meanwhile.

Building `opendjk` from source looks like it is very hard (it should not ...). We are struggling with this build right now.

**Comment by chiqj** [comment]
> You could try the `adoptopendk` formulae meanwhile.
> 
> Building `opendjk` from source looks like it is very hard (it should not ...). We are struggling with this build right now.

Thank you, it works. BTY, I really appreciate your efforts for this repo, have a nice day.

**Comment by iMichka** [comment]
All the `openjdk` formulae have now been fixed, and we provide bottles for them.
