### ISSUE TITLE
Switch formulae that depend on `openssl` to `openssl@1.1`

### ISSUE THREAD

**Issue by issyl0** [Homebrew/linuxbrew-core#17403]
Upstream in Homebrew/homebrew-core, OpenSSL < 1.1 is [being removed](https://github.com/Homebrew/homebrew-core/pull/46876) as it's EOL.

We have some formulae that have `openssl` as a dependency on Linux (and some that haven't been changed/deleted from upstream yet). We should change all of these to depend on openssl@1.1, and ensure they all still build and test OK.

----

This formulae list was generated on November 18th with `ack -l "depends_on \"openssl\""` in `brew --repo homebrew/core`:

- [x] erlang@19 (deleted upstream https://github.com/Homebrew/homebrew-core/commit/d695f9f9e80986db7b9fb09534ddc62bb57c6bf6)
- [x] erlang@21 (#17441)
- [x] angle-grinder (#17404)
- [x] awslogs (#17407)
- [x] erlang (#17440)
- [x] awsume (fixed upstream: https://github.com/Homebrew/homebrew-core/commit/56c93ec7af1cb79fe5c82edf27a33838f10b1013)
- [x] mosh (#17408)
- [x] mongo-c-driver (#17442)
- [x] libsasl2 (#17423)
- [x] aria2 (#17411)
- [x] manticoresearch (fixed upstream https://github.com/Homebrew/homebrew-core/commit/c0b8317e696b4fd1a6e1e60932f3c39a30e022a1)
- [x] virtuoso (fixed upstream https://github.com/Homebrew/homebrew-core/pull/46885)
- [x] ruby@2.0 (deleted upstream https://github.com/Homebrew/homebrew-core/commit/fd1558ce39c3416e7ff9f21a4cdcbf6d08b862ab)
- [x] cmake #17405
- [x] erlang@20 #17414
- [x] singularity (#17409)
- [x] libzip #17406
- [x] rustup-init (#17443)

Formulae list generated on November 19th with `grep -Ri 'uses_from_macos "openssl"'` in `brew --repo homebrew/core`:

- [x] curl (#17444)
- [x] mdcat (#17446)
- [x] websocat (#17445)
----

**Comment by issyl0** [comment]
Oh, I see, the aliases are symlinks. 👩‍🏫

**Comment by dawidd6** [comment]
I'm suggesting to also search for `uses_from_macos "openssl"`, because for example `curl` formula has it.

**Comment by dawidd6** [comment]
`brew uses openssl --include-build --include-test | sort` might have been a better command to get all formulae that depend on `openssl`, heh.

**Comment by issyl0** [comment]
Heh, I forget that `brew uses` is even a thing. Old habits...

**Comment by dawidd6** [comment]
Everything checked!

**Comment by issyl0** [comment]
Wonderful! Thanks, all!
