### ISSUE TITLE
howdoi fails to install: libxml/xmlversion.h: No such file or directory (libxml2)

### ISSUE THREAD

**Issue by brandonkal** [Homebrew/linuxbrew-core#17574]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
   "Ready to brew"
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/32f30da89fb2b9a83a4c6e36498767a1
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install howdoi on Linux

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/howdoi/05.python3:
src/lxml/includes/etree_defs.h:14:10: fatal error: libxml/xmlversion.h: No such file or directory
 #include "libxml/xmlversion.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Compile failed: command 'gcc-7' failed with exit status 1
creating tmp
cc -I/usr/include/libxml2 -c /tmp/xmlXPathInit1v0ln_22.c -o tmp/xmlXPathInit1v0ln_22.o
/tmp/xmlXPathInit1v0ln_22.c:1:10: fatal error: libxml/xpath.h: No such file or directory
 #include "libxml/xpath.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
error: command 'gcc-7' failed with exit status 1
*********************************************************************************
Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
*********************************************************************************

  </pre>
</details>

## What you expected to happen

Install should succeed

Note that `pip3 howdoi` with brew-provided python 3 succeeds.
It installs these packages: `cssselect, lxml, pyquery, pygments, chardet, certifi, urllib3, idna, requests, cachelib, appdirs, howdoi`

## Step-by-step reproduction instructions (by running `brew install` commands)

You can see the failed build here: https://cloud.drone.io/brandonkal/docker-dev/1/1/2
The source is also available.
This failed with `brew bundle` but testing `brew install howdoi` also fails on its own.

**Comment by dawidd6** [comment]
Should be fixed now.

**Comment by brandonkal** [comment]
> Should be fixed now.

Yes it is installs now. Thank you for the quick fix.
