### ISSUE TITLE
'brew install hledger' fails: compilation error when building hledger-lib-1.5.1

### ISSUE THREAD

**Issue by MatthiasKauer** [Homebrew/linuxbrew-core#17618]
*Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.*

- [x] ran `brew update` and can still reproduce the problem? *Yes, even ran `brew update-reset` and finally reinstalled.*
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem? *Yes. Fixing them didn't help. After reinstall, there were no more issues anyway in `brew doctor`*
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? *Yes, see below*
- [NA] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
I became aware that hledger has a new interesting feature so I tried to upgrade it. I installed it via linuxbrew a while ago so I issued 'brew update' followed by 'brew upgrade hledger'. I believe this gave the same error that I am seeing now. I figured that the whole linuxbrew merging with homebrew repo adjustment may have messed with my settings, so I re-installed brew as described here https://github.com/Linuxbrew/legacy-linuxbrew/issues/49
```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/uninstall)"                                                                                   
rm -rf ~/.linuxbrew
```

## What happened (include command output)
My command line looks like this
```
x BOL0k matt@hp840:~/Downloads $ brew install hledger                                                                                                                          
cabal: Error: some packages failed to install:
hledger-lib-1.5.1-yKwgzzpKdVAtxUETj0SIQ failed during the building phase. The
exception was:
ExitFailure 1


READ THIS: https://docs.brew.sh/Troubleshooting
```
The logs I investigated are all included in 
https://gist.github.com/MatthiasKauer/7d73e81b5ad591165d2da8b60aeaf32f

I have tried compiling hledger using the stack method described on https://hledger.org/download.html
That succeeded after I manually upgraded stack.

## What you expected to happen
A new hledger version should be available: 1.15

## Step-by-step reproduction instructions (by running `brew install` commands)
```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/uninstall)"                                                                                   
rm -rf ~/.linuxbrew # in my case actually: /home/linuxbrew/.linuxbrew 
brew install hledger
```

**Comment by iMichka** [comment]
Fixed by #17633

**Comment by MatthiasKauer** [comment]
It works now. Thank you!
I believe there was no more compilation anymore now. Did you move the entire compilation step to your end?

**Comment by dawidd6** [comment]
We built a bottle. https://docs.brew.sh/Bottles
