### ISSUE TITLE
Can't install PHP 7.4 on WSL with Ubuntu 19.10

### ISSUE THREAD

**Issue by eduardoturconi** [Homebrew/linuxbrew-core#17794]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install PHP 7.4 package

## What happened (include command output)

Check on method of MacOS module fails

https://gist.github.com/efddedabedff49b23dcb386835058d6f

<details>
  <summary>Command output</summary>
  <pre>

  brew install php
==> Downloading https://www.php.net/distributions/php-7.4.0.tar.xz
Already downloaded: /home/eduardo/.cache/Homebrew/downloads/e77e2ae71ff7dcc4a0f5e4b4fa946e9bc4c610b00a6a3df0e67e53f2cd01927c--php-7.4.0.tar.xz
==> ./buildconf --force
Error: An exception occurred within a child process:
  NoMethodError: undefined method `sdk_path_if_needed' for OS::Mac:Module

  </pre>
</details>

## What you expected to happen

Get the package installed

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install php`

**Comment by issyl0** [comment]
Thanks for the report, @eduardoturconi. We're trying to fix this in #17775.

**Comment by black-snow** [comment]
Looking forward to it :)

**Comment by iMichka** [comment]
This has been fixed with #17963.
