### ISSUE TITLE
mpi4py: Request for a bottle

### ISSUE THREAD

**Issue by ax3l** [Homebrew/linuxbrew-core#17842]
Hi,

I added my first bottles for `mpi4py` (https://github.com/Homebrew/homebrew-core/pull/46086) and `adios2` (https://github.com/Homebrew/homebrew-core/pull/45997) on the `homebrew-core` repo about a month ago. The bottles for macOS were auto-created but somehow the `x86_64_linux` bottles are still missing, although the formula's are both merged herein.

I am posting this request for bottle as hinted in https://github.com/Homebrew/homebrew-core/pull/46086#issuecomment-560164141 by @issyl0 :)

- [x] checked that there aren't other open issues for the same formula bottle request?
- [x] does the `mpi4py` and `adios2` not have the `bottle` block (for Linux)?
- [x] ran `brew install mpi4py` and `brew install adios2` and it succeeded?

**Comment by issyl0** [comment]
Thanks for the issue. I've opened two PRs, one for each formula.

**Comment by ax3l** [comment]
Thank you, this is great!

**Comment by issyl0** [comment]
These two formulae now have bottles. Thanks for your help!

**Comment by ax3l** [comment]
Thank you as well, hooray! :rocket:
