### ISSUE TITLE
llvm: can't upgrade

### ISSUE THREAD

**Issue by Char-Aznable** [Homebrew/linuxbrew-core#18140]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

brew upgrade llvm

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

==> Upgrading 1 outdated package:
llvm 8.0.0_1 -> 9.0.0_1
glibc: Your system's glibc version is 2.27, and Homebrew's glibc version is 2.23.
Installing a version of glibc that is older than your system's can break formulae installed from source.
Error: llvm: An unsatisfied requirement failed this build.

  </pre>
</details>

## What you expected to happen

llvm upgraded to 9.0

## Step-by-step reproduction instructions (by running `brew install` commands)

brew upgrade llvm

This happens on Ubuntu 18.04.3 LTS

**Comment by dawidd6** [comment]
Include the output of `brew doctor` and `brew config`.

**Comment by Char-Aznable** [comment]
I think the problem here is the OS is recently upgraded from ubuntu 16 to ubuntu 18 with the linuxbrew installation from the ubuntu 16. The linuxbrew glibc is older than the ubuntu 18 one, which traps all the brew upgrade. Is there a way to upgrade linuxbrew with the OS upgrade or do I have to reinstall linuxbrew?

**Comment by iMichka** [comment]
If it is an upgrade from ubuntu 16 to 18: can you try to `brew uninstall glibc`. You should not need the brewed `glibc`.  We only provide it for older versions of linux.

**Comment by Char-Aznable** [comment]
`brew uninstall glibc` complains about broken dependency. I ended up reinstalling linuxbrew from scratch...

**Comment by iMichka** [comment]
Sorry you had to start from scratch. I know for sure that migrating a linuxbrew install from one ubuntu version to another is not really tested on our side (we would have to test installing all packages, or upgrading packages from different states ...). In general it should work, but you still may hit some edge cases.

We plan to move our build infrastructure to18.04 this year (I'll surely discuss this at the FOSDEM with the other maintainers). This will help us keep up with newer versions of Linux.

As you were able to workaround your issue, I'll close this ticket.

**Comment by Char-Aznable** [comment]
It's OK. Good to know that it's switching to the 18.04 infrastructure
