### ISSUE TITLE
sonobuoy: Request for previous bottles

### ISSUE THREAD

**Issue by tdensmore** [Homebrew/linuxbrew-core#18194]
The community has kept `sonobuoy` up to date, but it looks like the previous versions of the formula has been removed / over-written?

The latest version of `sonobuoy` (0.17.0) is incompatible with AWS EKS. 

I looked at the official `sonobuoy` releases on the [GitHub repo](https://github.com/vmware-tanzu/sonobuoy) and found two previous releases: `0.16.4` and `0.16.5`.  I tried to install a previous version of `sonobuoy` using `brew`, but it seems that the latest `0.17.0` version is all that is available:

```
brew search sonobuoy
==> Formulae
sonobuoy
```

**Comment by issyl0** [comment]
Homebrew generally only ships latest releases of software as per the [policy](https://docs.brew.sh/Versions). There are [ways of installing previous versions](https://docs.brew.sh/Tips-N'-Tricks#installing-previous-versions-of-formulae), though.

If the `sonobuoy` development team are aware of the AWS EKS compatibility problems, maybe they'll release a fix soon. Good luck!

**Comment by tdensmore** [comment]
Is it possible to generate previous versions of a binary for homebrew? 

The fact that the latest version of `sonobuoy` does not support EKS is **not** a bug. Sonobuoy is a tool that works with many cloud providers, not just AWS. Therefore many versions of this tool are needed.

The fact that there is only one released version of `sonobuoy` available as a formula might be a bug ...

**Comment by sjackman** [comment]
Homebrew doesn't support installing older versions of a formulae. Check out `brew extract --help` though.

**Comment by tdensmore** [comment]
I confused. Maybe you can help. 

In the[ official brew documentation](https://docs.brew.sh/Tips-N'-Tricks) it says that I can switch into a previously installed version of a formula:
```
brew info <formula>
brew switch <formula> <version>
```
So I assume  that `homebrew` can only roll forward, and if I have old versions that I have previously installed, I can switch back to them, but I cannot use old versions if I have not previously installed them.

Is that correct?

**Comment by iMichka** [comment]
Yes, as the title of that sections tells it:
> Activate a **previously installed** version of a formula

It's also not the most used feature. Homebrew's philosophy is to provide always the latests version.
If you need a specific version we do not support, you can read this:
https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md

**Comment by sjackman** [comment]
A little hidden gem: you can also install old bottles directly from Bintray.
See https://bintray.com/homebrew/bottles/sonobuoy/0.16.5#files
```
brew install https://dl.bintray.com/homebrew/bottles/sonobuoy-0.16.5.catalina.bottle.tar.gz
```

**Comment by tdensmore** [comment]
Thank you! This is what I was looking for (but could not find). I will gladly add this to the docs if needed.

**Comment by iMichka** [comment]
It's not officially supported. The same for `brew switch`. We provide this as-is, for people who know what they do. But we will not provide any support for bugs resulting from the usage of these features.

The bottle you are downloading may also not be working, depending on the depencies which may or may not be there.
