### ISSUE TITLE
cannot change locale (en_US.UTF-8)

### ISSUE THREAD

**Issue by crydotsnake** [Homebrew/linuxbrew-core#18357]
Hello People.

First, i'd like to say thanks for developing homebrew for linux! i like it, and it is a really helpfull friend. 

Today i installed Linuxbrew on my Ubuntu 19.10 machine, and after i run these commands

```
test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
```
i get this two errors, everytime i started my terminal.
``` 
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh: line 4: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh: line 4: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
```

Best Regards!, (and merry christmas! :santa:)
Simon.

**Comment by crydotsnake** [comment]
God it!, this worked for me https://github.com/Linuxbrew/brew/issues/568#issuecomment-367417842

Thanks to @rfay ! :smile:.

**Comment by issyl0** [comment]
Thank you for the kind words - they're very motivational!

**Comment by crydotsnake** [comment]
It's just the truth ! :blush: @issyl0
