### ISSUE TITLE
mingw-w64 broken after upgrade to 7.0.0, hangs building gcc@9 "make all-gcc"

### ISSUE THREAD

**Issue by rfay** [Homebrew/linuxbrew-core#18364]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/rfay/85e53700edc225c109cd36f4bd02fcda
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew install mingw-w64` or `brew upgrade mingw-w64`

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

$ brew upgrade mingw-w64
==> Upgrading 1 outdated package:
mingw-w64 6.0.0_2 -> 7.0.0
==> Upgrading mingw-w64 
==> Downloading https://downloads.sourceforge.net/project/mingw-w64/mingw-w64/mingw-w64-release/mingw-w64-v7.0.0.tar.bz2
Already downloaded: /home/rfay/.cache/Homebrew/downloads/f16e8f6f5b79724d556568b67cfc07b789de2da9760d6e20ad5e515071bf3eeb--mingw-w64-v7.0.0.tar.bz2
==> Downloading https://ftp.gnu.org/gnu/binutils/binutils-2.33.1.tar.xz
Already downloaded: /home/rfay/.cache/Homebrew/downloads/de34fb8f4377ad3b9702f1429319331ee040b1e8c5611684234e774f3823ab88--binutils-2.33.1.tar.xz
==> ../configure --target=i686-w64-mingw32 --with-sysroot=/home/linuxbrew/.linuxbrew/Cellar/mingw-w64/7.0.0/toolchain-i686 --pre
==> make
==> make install
==> ../configure --host=i686-w64-mingw32 --prefix=/home/linuxbrew/.linuxbrew/Cellar/mingw-w64/7.0.0/toolchain-i686/i686-w64-ming
==> make
==> make install
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-9.2.0/gcc-9.2.0.tar.xz
Already downloaded: /home/rfay/.cache/Homebrew/downloads/d826388c1d62d3837abf5966bfcb52111c0fea536be81417ab4718ba089422f1--gcc-9.2.0.tar.xz
==> ../configure --target=i686-w64-mingw32 --with-sysroot=/home/linuxbrew/.linuxbrew/Cellar/mingw-w64/7.0.0/toolchain-i686 --pre
==> make all-gcc

  </pre>
</details>

## What you expected to happen

Install or upgrade

## Step-by-step reproduction instructions (by running `brew install` commands)

I've tested on both Ubuntu 16.04 (several different VMs) and Ubuntu 18.04. Both were working before today's "mingw-w64: update 7.0.0 bottle." in 
804c5ef33ab96b4a10240282a2a800e100b1ad3e and 90c25282216031ca0c0ed56d873cabdc5ed1a042

To test, just `brew upgrade mingw-w64` or `brew install mingw-w64` on Ubuntu 18.04 or Ubuntu 16.04.

Note: This is working OK with 7.0.0 on macOS Catalina.

**Comment by iMichka** [comment]
Hi. No need to open an issue for this. We have an open pull request here, and we know it is broken: #18362

The discussion can continue on #18362.
