### ISSUE TITLE
"brew install botan" fails, NoMethodError: undefined method `preferred_arch' for OS::Mac:Module

### ISSUE THREAD

**Issue by j-mckim** [Homebrew/linuxbrew-core#18694]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I am trying to install the botan brew.

## What happened (include command output)

"brew install botan" failed to complete, instead issuing a diagnostic message.

<details>
  <summary>Command output</summary>
  <pre>

==> Downloading https://botan.randombit.net/releases/Botan-2.12.1.tar.xz
Already downloaded: /home/jmckim/.cache/Homebrew/downloads/ddd76b53ebead05fff164968f131967847346d20deca43f96fbf6853b5e4ac56--Botan-2.12.1.tar.xz
Error: An exception occurred within a child process:
  NoMethodError: undefined method `preferred_arch' for OS::Mac:Module

  </pre>

brew gist-logs output is at
https://gist.github.com/j-mckim/80caf26c1e20d0cfcd3e9b558a837f74

</details>

## What you expected to happen

I expected no failure. Headers libraries and other files from the botan brew should have been installed in /home/linuxbrew/.linuxbrew/. They were not.

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install botan

A copy of the gist logs:
[80caf26c1e20d0cfcd3e9b558a837f74-7d75a14e555497942760e7d015d49b98b9d44649.zip](https://github.com/Homebrew/linuxbrew-core/files/4032766/80caf26c1e20d0cfcd3e9b558a837f74-7d75a14e555497942760e7d015d49b98b9d44649.zip)

**Comment by issyl0** [comment]
We've fixed the build and built a bottle for it. Please try installing again! Thanks for using Homebrew on Linux!
