### ISSUE TITLE
OpenJDK 13 install fails WSL Ubuntu on Win10

### ISSUE THREAD

**Issue by black-snow** [Homebrew/linuxbrew-core#18994]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

```
$ brew config
HOMEBREW_VERSION: 2.2.3-11-gdfe028a
ORIGIN: https://github.com/Homebrew/brew
HEAD: dfe028a731e2ddb81bbe575d966c658b2177195c
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core.git
Core tap HEAD: 2d058609e64b884b51fce067e9c8d2a26a70516f
Core tap last commit: 7 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CACHE: /home/xxx/.cache/Homebrew
HOMEBREW_LOGS: /home/xxx/.cache/Homebrew/Logs
HOMEBREW_BREW_GIT_REMOTE: https://github.com/Homebrew/brew
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/linuxbrew-core
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_VISUAL: vim
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: N/A
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 4.4.0-18362-Microsoft x86_64 GNU/Linux
OS: Ubuntu 18.04.3 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.4.0
glibc: N/A
gcc: 5.5.0_7
xorg: N/A
```

```
$ brew doctor
Your system is ready to brew.
```

## What you were trying to do (and why)

`brew install openjdk` which *atm* is `openjdk: stable 13.0.1+9 (bottled)`

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

$ brew install openjdk
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/services).
No changes to formulae.

==> Tapping linuxbrew/xorg
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg'...
remote: Enumerating objects: 182, done.
remote: Counting objects: 100% (182/182), done.
remote: Compressing objects: 100% (172/172), done.
remote: Total 182 (delta 114), reused 20 (delta 9), pack-reused 0
Receiving objects: 100% (182/182), 94.82 KiB | 626.00 KiB/s, done.
Resolving deltas: 100% (114/114), done.
Tapped 155 formulae (200 files, 462.1KB).
==> Installing dependencies for openjdk: alsa-lib, cups, fontconfig, unzip, zip, linuxbrew/xorg/libpthread-stubs, linuxbrew/xorg/xorgproto, linuxbrew/xorg/libxau, linuxbrew/xorg/libxdmcp, linuxbrew/xorg/libxcb, linuxbrew/xorg/libx11, linuxbrew/xorg/libxext, linuxbrew/xorg/libxrender, linuxbrew/xorg/libxrandr, linuxbrew/xorg/libice, linuxbrew/xorg/libsm, linuxbrew/xorg/libxt, linuxbrew/xorg/libxfixes, linuxbrew/xorg/libxi and linuxbrew/xorg/libxtst
==> Installing openjdk dependency: alsa-lib
==> Downloading https://linuxbrew.bintray.com/bottles/alsa-lib-1.2.1.1.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/e3/e34ed1fe2d15292da93c911bb70a204019c223fc475ded583b3dfa477479c797?__gda__=exp=1579266696~hmac=2f770744f1fa6f4e5acf832ccbf1e4fd0e082153ebe001fb44bd8402
######################################################################## 100.0%
==> Pouring alsa-lib-1.2.1.1.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/alsa-lib/1.2.1.1: 133 files, 2.0MB
==> Installing openjdk dependency: cups
==> Downloading https://github.com/apple/cups/releases/download/v2.3.1/cups-2.3.1-source.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/44137852/0bdfcf80-1d8e-11ea-941e-8efbe84383c6?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53
######################################################################## 100.0%
==> ./configure --with-components=core --without-bundledir --prefix=/home/linuxbrew/.linuxbrew/Cellar/cups/2.3.1
==> make install
Error: No available formula with the name "linuxbrew/extra/linux-pam"
==> Searching for a previously deleted formula (in the last month)...
Warning: linuxbrew/extra is shallow clone. To get complete history run:
  git -C "$(brew --repo linuxbrew/extra)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.

  </pre>
</details>

## What you expected to happen

Successful install.

## Step-by-step reproduction instructions (by running `brew install` commands)

Just `brew install openjdk` inside your WSL.

**Comment by dawidd6** [comment]
https://github.com/Homebrew/linuxbrew-core/pull/19029

**Comment by dawidd6** [comment]
Reading the install log, I can tell you have `linuxbrew/extra` tapped, which is deprecated. Please run `brew untap linuxbrew/extra` and try again.

**Comment by dawidd6** [comment]
The bottle built just fine, I'm pulling it now. It must be a problem on your side. Please try the command I wrote above.

**Comment by black-snow** [comment]
@dawidd6 thanks for checking. In the meantime I installed JDK 13 from ubuntu 19.10 universe.
I'll just close this for now.
