### ISSUE TITLE
systemd build failed on CentOS

### ISSUE THREAD

**Issue by Liam0205** [Homebrew/linuxbrew-core#19082]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to `brew install gnupg` on CentOS 6.5. Since `gnupg` depends on `libusb`, who in return depends on `systemd`, Linuxbrew tried to build `systemd` from source but failed to do so.

## What happened (include command output)

After building all other dependencies of `gnupg`, I was trying to build `systemd` by `brew install --verbose systemd`, and checking what would happen.

<details>
  <summary>Command output</summary>
  <pre>

https://gist.github.com/1723f498f06164d21c9ab2b5da56acca

  </pre>
</details>

## What you expected to happen

Building `systemd` successfully.

## Step-by-step reproduction instructions (by running `brew install` commands)

```bash
brew install --verbose systemd
```

**Comment by joshuak94** [comment]
I would also like to add my logs.

https://gist.github.com/joshuak94/c6c1df6f3bccbb32bd0dbe8f34b0ce81

**Comment by joshuak94** [comment]
I will note that I was able to successfully install systemd as such `brew install https://raw.githubusercontent.com/dawidd6/linuxbrew-core/systemd-244/Formula/systemd.rb` from pull request #19050.

Then you can install a package which depends on systemd with the --ignore-dependencies option, assuming all other dependencies are met.

**Comment by dawidd6** [comment]
Fixed by: https://github.com/Homebrew/linuxbrew-core/pull/19050

**Comment by Liam0205** [comment]
@dawidd6 

`brew update`d, and a new problem encountered. see <https://gist.github.com/f0e564fd44b30afa63cfb0d4581e1d89> please.
