### ISSUE TITLE
znc: script `znc-buildmod` does not capture linker library search paths, fails to build C++ module code

### ISSUE THREAD

**Issue by slippycheeze** [Homebrew/linuxbrew-core#19150]
**Note:** no logs supplied because the ZNC formula builds correctly, but generates an incorrect script for use after installation.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ~~ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?~~
- [ ] ~~if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?~~

## What you were trying to do (and why)

Using ZNC as an IRC bouncer, I wanted to build the [ZNC playback module][znc-playback], which is [a single C++ file][playback.cpp] that should be compiled with `znc-buildmod`.

`znc-buildmod` is a shell script generated as part of the ZNC build process.  It wraps calling the compiler (`g++` in linuxbrew) with appropriate arguments to compile the C++ code into a shared object that can be dynamically loaded into the ZNC process.

For that, using the same libraries (eg: zlib) as the ZNC process itself is quite important.  When ZNC is installed as, eg, a "/usr/bin" style global install this is simply the "system" version of the library, but for linuxbrew those are located in the Cellar.

For my ZNC, for example:
```
] ldd =znc |& grep linuxbrew
        libssl.so.1.1 => /usr/local/google/home/slippycheeze/.linuxbrew/opt/openssl@1.1/lib/libssl.so.1.1 (0x00007f3e85d9c000)
        libcrypto.so.1.1 => /usr/local/google/home/slippycheeze/.linuxbrew/opt/openssl@1.1/lib/libcrypto.so.1.1 (0x00007f3e85ae6000)
        libz.so.1 => /usr/local/google/home/slippycheeze/.linuxbrew/lib/libz.so.1 (0x00007f3e858d1000)
        libicuuc.so.64 => /usr/local/google/home/slippycheeze/.linuxbrew/lib/libicuuc.so.64 (0x00007f3e854d5000)
        libicudata.so.64 => /usr/local/google/home/slippycheeze/.linuxbrew/lib/libicudata.so.64 (0x00007f3e83892000)
        /usr/local/google/home/slippycheeze/.linuxbrew/lib/ld.so => /lib64/ld-linux-x86-64.so.2 (0x00007f3e8602f000)
```
[znc-playback]: https://wiki.znc.in/Playback
[playback.cpp]: https://github.com/jpnurmi/znc-playback

## What happened (include command output)

Some, but not all, compiler and linker flags are preserved in the script (attached, in a zip) 
[znc-buildmod.zip](https://github.com/Homebrew/linuxbrew-core/files/4098374/znc-buildmod.zip)

<details>
  <summary>Command output</summary>
  <pre>
] curl -LO https://raw.githubusercontent.com/jpnurmi/znc-playback/master/playback.cpp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9522  100  9522    0     0  64775      0 --:--:-- --:--:-- --:--:-- 64775
] znc-buildmod playback.cpp
Building "playback.so" for ZNC 1.7.5... /bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
[ !! ] Error while building "playback.so"
] sh -x =znc-buildmod playback.cpp
+ ERROR='[ !! ]'
+ WARNING='[ ** ]'
+ OK='[ ok ]'
+ test x = x
+ CXX=g++-8
+ test xg++-8 = x
+ check_binary g++-8 'What happened to your compiler?'
+ which g++-8
+ test 0 = 1
+ test -z playback.cpp
+ CXXFLAGS=' -std=c++11  -O2 -D_FORTIFY_SOURCE=2 -Wall -W -Wno-unused-parameter -Woverloaded-virtual -Wshadow -pthread -I/home/slippycheeze/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/include -I/home/slippycheeze/.linuxbrew/Cellar/icu4c/64.2/include -fvisibility=hidden -fPIC -include znc/zncconfig.h -I/home/slippycheeze/.linuxbrew/Cellar/znc/1.7.5/include '
+ LIBS='-ldl  -pthread -L/home/slippycheeze/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/lib -lssl -lcrypto -lz -L/home/slippycheeze/.linuxbrew/Cellar/icu4c/64.2/lib -licuuc -licudata '
+ MODLINK='-shared '
+ VERSION=1.7.5
+ test -n ''
+ test -n playback.cpp
+ FILE=playback.cpp
+ shift
+ MOD=playback
+ MOD=playback
+ MOD=playback
+ test '!' -f playback.cpp
+ printf 'Building "playback.so" for ZNC 1.7.5... '
Building "playback.so" for ZNC 1.7.5... + g++-8 -std=c++11 -O2 -D_FORTIFY_SOURCE=2 -Wall -W -Wno-unused-parameter -Woverloaded-virtual -Wshadow -pthread -I/home/slippycheeze/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/include -I/home/slippycheeze/.linuxbrew/Cellar/icu4c/64.2/include -fvisibility=hidden -fPIC -include znc/zncconfig.h -I/home/slippycheeze/.linuxbrew/Cellar/znc/1.7.5/include -shared -o playback.so playback.cpp -ldl -pthread -L/home/slippycheeze/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/lib -lssl -lcrypto -lz -L/home/slippycheeze/.linuxbrew/Cellar/icu4c/64.2/lib -licuuc -licudata
/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
+ echo '[ !! ] Error while building "playback.so"'
[ !! ] Error while building "playback.so"
+ exit 1
  </pre>
</details>

## What you expected to happen

I'd expect that the path to zlib in the linuxbrew build was captured into the `znc-buildmod` script as part of the build, as the paths to the `icu4c`, `znc`, and `openssl` were.

The final state, of course, is that the C++ code is turned into a dynamic module and installed as expected with the script.  Compilation succeeds, basically.

I have not debugged this all the way through, but from debugging build issues in homebrew on macOS I'd venture a guess that the superenv added those as part of the cc wrapper script, rather than via the LDFLAGS, etc, for the formula.

Side note: I'd expect that the search paths for shared libraries exactly match the ZNC binary in this build script.  It is expected to capture and replace the appropriate compiler options to safely build a shared library that'll work as part of the ZNC binary.

## Step-by-step reproduction instructions (by running `brew install` commands)

**Note:** I've included the command sequence to reproduce the in-formula bug, not just the `brew` specific commands.

```
brew install znc
curl -LO https://raw.githubusercontent.com/jpnurmi/znc-playback/master/playback.cpp
znc-buildmod playback.cpp
```

**Comment by slippycheeze** [comment]
Note: successful build invocation:
```
CXXFLAGS="-I$(brew --prefix zlib)/include" LDFLAGS="-L$(brew --prefix zlib)/lib" sh -x znc-buildmod playback.cpp
```

**Comment by dawidd6** [comment]
I just tried it and got this:

```
linuxbrew@4971c8235d58:~$ sh -x $(which znc-buildmod) playback.cpp 
+ ERROR=[ !! ]
+ WARNING=[ ** ]
+ OK=[ ok ]
+ test x = x
+ CXX=g++-5
+ test xg++-5 = x
+ check_binary g++-5 What happened to your compiler?
+ which g++-5
+ test 0 = 1
+ test -z playback.cpp
+ CXXFLAGS= -std=c++11  -O2 -Wall -W -Wno-unused-parameter -Woverloaded-virtual -Wshadow -pthread -I/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/include -I/home/linuxbrew/.linuxbrew/Cellar/icu4c/64.2/include -fvisibility=hidden -fPIC -include znc/zncconfig.h -I/home/linuxbrew/.linuxbrew/Cellar/znc/1.7.5/include 
+ LIBS=-ldl  -pthread -L/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/lib -lssl -lcrypto -lz -L/home/linuxbrew/.linuxbrew/Cellar/icu4c/64.2/lib -licuuc -licudata 
+ MODLINK=-shared 
+ VERSION=1.7.5
+ test -n 
+ test -n playback.cpp
+ FILE=playback.cpp
+ shift
+ MOD=playback
+ MOD=playback
+ MOD=playback
+ test ! -f playback.cpp
+ printf Building "playback.so" for ZNC 1.7.5... 
Building "playback.so" for ZNC 1.7.5... + g++-5 -std=c++11 -O2 -Wall -W -Wno-unused-parameter -Woverloaded-virtual -Wshadow -pthread -I/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/include -I/home/linuxbrew/.linuxbrew/Cellar/icu4c/64.2/include -fvisibility=hidden -fPIC -include znc/zncconfig.h -I/home/linuxbrew/.linuxbrew/Cellar/znc/1.7.5/include -shared -o playback.so playback.cpp -ldl -pthread -L/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/lib -lssl -lcrypto -lz -L/home/linuxbrew/.linuxbrew/Cellar/icu4c/64.2/lib -licuuc -licudata
+ echo [ ok ]
[ ok ]
+ test -n 
+ exit 0
```

**Comment by dawidd6** [comment]
Best I can do is to push this fix: https://github.com/Homebrew/linuxbrew-core/pull/19151/commits/8b97a36dba1f6f6623a7189bf31568f9a1779437

After applying this commit, I get:

```
linuxbrew@4971c8235d58:~$ sh -x $(which znc-buildmod) playback.cpp 
+ ERROR=[ !! ]
+ WARNING=[ ** ]
+ OK=[ ok ]
+ test x = x
+ CXX=g++-5
+ test xg++-5 = x
+ check_binary g++-5 What happened to your compiler?
+ which g++-5
+ test 0 = 1
+ test -z playback.cpp
+ CXXFLAGS= -std=c++11 -I/home/linuxbrew/.linuxbrew/opt/zlib/include  -O2 -Wall -W -Wno-unused-parameter -Woverloaded-virtual -Wshadow -pthread -I/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/include -I/home/linuxbrew/.linuxbrew/Cellar/icu4c/64.2/include -fvisibility=hidden -fPIC -include znc/zncconfig.h -I/home/linuxbrew/.linuxbrew/Cellar/znc/1.7.5_1/include 
+ LIBS=-ldl  -pthread -L/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/lib -lssl -lcrypto -lz -L/home/linuxbrew/.linuxbrew/Cellar/icu4c/64.2/lib -licuuc -licudata 
+ MODLINK=-shared 
+ VERSION=1.7.5
+ test -n 
+ test -n playback.cpp
+ FILE=playback.cpp
+ shift
+ MOD=playback
+ MOD=playback
+ MOD=playback
+ test ! -f playback.cpp
+ printf Building "playback.so" for ZNC 1.7.5... 
Building "playback.so" for ZNC 1.7.5... + g++-5 -std=c++11 -I/home/linuxbrew/.linuxbrew/opt/zlib/include -O2 -Wall -W -Wno-unused-parameter -Woverloaded-virtual -Wshadow -pthread -I/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/include -I/home/linuxbrew/.linuxbrew/Cellar/icu4c/64.2/include -fvisibility=hidden -fPIC -include znc/zncconfig.h -I/home/linuxbrew/.linuxbrew/Cellar/znc/1.7.5_1/include -shared -o playback.so playback.cpp -ldl -pthread -L/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/lib -lssl -lcrypto -lz -L/home/linuxbrew/.linuxbrew/Cellar/icu4c/64.2/lib -licuuc -licudata
+ echo [ ok ]
[ ok ]
+ test -n 
+ exit 0
```

**Comment by slippycheeze** [comment]
Thanks for that!  FWIW, I'm pretty sure your initial invocation would have ended up building with the system zlib headers, not the homebrew ones.  I don't think I have those installed, which'd explain why it built for you, but not for me.

The final result should be fine, though.  (and, TBH, since zlib is pretty ABI-stable, probably the system headers would be just fine too.)
