### ISSUE TITLE
deno: Request for a bottle

### ISSUE THREAD

**Issue by brandonkal** [Homebrew/linuxbrew-core#19168]
It was in there earlier (0.28.1 I believe). Looks like it got lost in the move to 0.30.0.

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] checked that there aren't other open issues for the same formula bottle request?
- [ ] does the FORMULA not have the `bottle` block?
- [ ] ran `brew install FORMULA` and it succeeded?

**Comment by dawidd6** [comment]
We have trouble building it: https://github.com/Homebrew/linuxbrew-core/pull/18872.

Would appreciate some help with that.

**Comment by iMichka** [comment]
As we have an open pull request, let's continue the discussion there.
