### ISSUE TITLE
git-annex install fails with brew's gcc

### ISSUE THREAD

**Issue by dankessler** [Homebrew/linuxbrew-core#19180]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to install `git-annex` using `brew` on linux.
I did this by running
```
brew install git-annex
```

## What happened (include command output)

Things run for a long time but then I get the below error message

<details>
  <summary>Command output</summary>
  <pre>

```
==> Downloading https://hackage.haskell.org/package/git-annex-7.20191230/git-annex-7.20191230.
Already downloaded: /home/vagrant/.cache/Homebrew/downloads/02072c3a58705d107d672ed8713eec9ff6221d065789b2ce71c45295b3d57ce7--git-annex-7.20191230.tar.gz
==> cabal v1-sandbox init
==> cabal v1-update
==> cabal v1-install --jobs=1 --max-backjumps=100000 alex
Last 15 lines from /home/vagrant/.cache/Homebrew/Logs/git-annex/03.cabal:
2020-01-24 01:37:24 +0000

cabal
v1-install
--jobs=1
--max-backjumps=100000
alex

gcc-5: error: unrecognized command line option '-no-pie'
`gcc-5' failed in phase `C Compiler'. (Exit code: 1)

READ THIS: https://docs.brew.sh/Troubleshooting


```

  </pre>
</details>

This appears in the [uploaded gist-log](https://gist.github.com/dankessler/442e3c173354b6643b328e2acc9a7d07#file-03-cabal-L9-L10)

## What you expected to happen

I expected `git-annex` to be successfully installed. 

## Step-by-step reproduction instructions (by running `brew install` commands)
I originally encountered this error on my `Pop OS 19.04` box, and also on a `Centos 7.6.1810` box in a high performance computing cluster. 

I wanted to reproduce it in a minimal environment. 
I am able reproduce this in a clean, vagrant-built bionic64 environment as follows:
1. Using vagrant and virtualbox, setup `hashicorp/bionic64`, get it up, and ssh
2. sudo apt update
2. sudo apt upgrade
3. sudo apt install build-essential
4. Install linuxbrew by running `sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"`
5. Run block of code from [installation instructions](https://docs.brew.sh/Homebrew-on-Linux)
```
test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
```
7. Run `brew install gcc`, as suggested by installer after step 5 above
7. Run `brew install git-annex`
8. Encounter error described above.

## Troubleshooting and Possible Solution

After further investigation, I believe the problem is that `cabal` queries the *system* managed `gcc` (which for me is at `/usr/bin/gcc`) to determine what flags it supports (and it does support `--no-pie`), but then when it actually calls `gcc`, it's calling the `brew`-installed `gcc` (which does not support this flag). I believe this is related to the behavior [described here](https://gitlab.haskell.org/ghc/ghc/issues/16656#note_201335), i.e., `cabal` uses `ghc --info` which when I run it at the terminal produces lots of output, but importantly includes the line `,("C compiler supports -no-pie","YES")`. If I run `gcc -no-pie` I get an error message about it being an unsupported option. If I run `/usr/bin/gcc -no-pie` (forcing it to use the system `gcc`) it no longer complains about the option. (In both cases it complains about no input files, but that is expected).

I created another clean `bionic64` vagrant box, did the same steps as above, except I skipped step 6 (i.e., did not run `brew install gcc`). Without a `homebrew`-managed `gcc`, it was forced to exclusively use my system-provided `gcc`. This time, `brew install git-annex` made it much farther (but still fell down on some other error that I don't fully understand; [here is the gist-log for that attempt](https://gist.github.com/dankessler/dcb78790707597c174d2336fda889d3e). 

Although the fix didn't work on bionic64, it did work on some other systems I've used, but they're not "clean" so its hard for me to isolate why it worked there.

**Comment by dawidd6** [comment]
https://github.com/Homebrew/linuxbrew-core/pull/19192

**Comment by dawidd6** [comment]
This is what I get, while trying to build it:

```
Database/Keys/SQL.hs:31:1: error:
    Generating Persistent entities now requires the following language extensions:

DerivingStrategies
StandaloneDeriving

Please enable the extensions by copy/pasting these lines into the top of your file:

{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE StandaloneDeriving #-}
   |
31 | share [mkPersist sqlSettings, mkMigrate "migrateKeysDb"] [persistLowerCase|
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
git-annex-7.20191230-JGm7b2Gk5I8w0hi2BDCiw failed during the building phase.
The exception was:
ExitFailure 1
```

Don't know Haskell, don't know what to do with it.

**Comment by dankessler** [comment]
@dawidd6 do you have the `brew`-provided `gcc` installed? I get to an error similar to yours when I don't use `brew`'s `gcc`

**Comment by dankessler** [comment]
I tried building from source on a MacBook Pro running OS X 10.15.3 and got the same error as @dawidd6, which leads me to suspect that if the bottling service for homebrew-core tried to rebuild these bottles, it'd fall down in the same way. Perhaps cabal has changed in some way?

Narrowly, the issue I initially raised has to do with brew's `gcc` conflicting with linux's `gcc`, and I think that is a real issue, but one that is constrained to `linuxbrew` and is "fixed" by not suggesting `linuxbrew` users run `brew install gcc`, although perhaps not doing this will cause other things to break. This *new* error, however, does not seem to be linux specific. 

Perhaps it'd be most fruitful for us to try to resolve the `gcc` problem in this issue, and then I can open an issue on `homebrew-core` regarding the cabal-related build failure.

**Comment by iMichka** [comment]
As we have a pull request open, let's continue the discussion there: #19192

**Comment by dankessler** [comment]
@iMichka the problem is that the problem that initially prompted this issue is still not resolved.

Specifically, after installation of `linuxbrew`, users are guided to run `brew install gcc`, which will later cause `brew install git-annex` to fail. The fix would seem to require better sandboxing or not telling users to install `gcc` using brew. 

Even after that is fixed, there is another problem that comes up later in the build process, which is being discussed at #19192 , but even if that is fixed, the issue here will remain.
