### ISSUE TITLE
pstoedit failed to build on CentOS 6.10

### ISSUE THREAD

**Issue by jmvtee** [Homebrew/linuxbrew-core#19241]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I am trying to install octave. pstoedit is a dependency of octave, and the pstoedit installation fails.

## What happened (include command output)

The install tries to access an invalid URL and fails:

<details>
  <summary>Command output</summary>
  <pre>

[GA@GA-DA33428 home]$ brew install pstoedit
==> Downloading https://downloads.sourceforge.net/project/pstoedit/pstoedit/3.75/pstoedit-3.75.tar.gz
Already downloaded: /home/GA/.cache/Homebrew/downloads/6a7b6dc619641d9fe3b99240a8d91ec3ad993123a498c3431f8fcf1cfc33d3d3--pstoedit-3.75.tar.gz
==> Downloading https://raw.githubusercontent.com/macports/macports-ports/master/graphics/pstoedit/files/patch-src-dxfacad.h.diff
curl: (22) The requested URL returned error: 404 Not Found

Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "pstoedit--patch"
Download failed: https://raw.githubusercontent.com/macports/macports-ports/master/graphics/pstoedit/files/patch-src-dxfacad.h.diff

  </pre>
</details>

## What you expected to happen

I expected the installation to succeed.

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install octave

or

brew install pstoedit

Gist: https://gist.github.com/jmvtee/a49b16a498253b2115a46b8069a7aaea

**Comment by dawidd6** [comment]
We are aware of this issue. In fact there is already a PR opened to address it: https://github.com/Homebrew/linuxbrew-core/pull/18710, but we encountered some build problems. Would appreciate any help with this.

**Comment by jmvtee** [comment]
I've never worked with a big open source project, but I'm willing to try to help. I know C++ fairly well, and git. How would I go about reproducing the build error? It looks like the repo is mostly Ruby code.

**Comment by dawidd6** [comment]
Delete the whole `patch` block from formula file and try to build it with `brew install --build-from-source pstoedit`.

**Comment by jmvtee** [comment]
Hmm. I'm not familiar with Docker, and I'm not sure whether it can run on CentOS 6. Here's something I have done-- I hope it provides some insight. I copied the pstoedit--3.75.tar.gz file that brew downloaded to another location and extracted it. From the terminal, running ./configure complained that g++ was too old. I dug around at the pstoedit website and found this:

Compiling pstoedit:
-------------------
You need a C++ compiler supporting C++17 standard at least, e.g., g++ 8 or newer to compile pstoedit.

The version of gcc reported is:
gcc (Homebrew GCC 5.5.0_7) 5.5.0

If I disregard the warning and call make anyway, there's a long stream of errors about the compiler not being able to handle the newer C++ standard. When I use devtoolset-8, with gcc version gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3) to configure and make, everything works.

So, perhaps the formula needs to be edited to require a newer version of gcc/g++?

**Comment by jmvtee** [comment]
Forgot to share this: http://www.calvina.de/pstoedit/readme.txt

**Comment by dawidd6** [comment]
Already tried that. Didn't help.

**Comment by jmvtee** [comment]
Can you confirm which version of gcc is actually getting used by the build server? It looks like an older version of gcc is getting used in spite of your changes.

https://discourse.brew.sh/t/default-gcc-for-linux/4953

**Comment by jmvtee** [comment]
Please disregard my last comment. I found the error in the server log and see g++-9.

**Comment by jmvtee** [comment]
Consider adding -std=c++17 to your g++ calls?

https://gcc.gnu.org/projects/cxx-status.html#cxx17

**Comment by iMichka** [comment]
As we have a pull request, let's continue the discussing this on the PR.
