### ISSUE TITLE
`brew install qt`: Makefile:50: recipe for target 'sub-src-make_first' failed

### ISSUE THREAD

**Issue by anishmittal2020** [Homebrew/linuxbrew-core#19314]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

qt is a dependency for something else, as installing that failed, I tried to install qt separately:

```
 brew install qt
```

## What happened (include command output)

```
$ brew install qt
==> Downloading https://download.qt.io/official_releases/qt/5.14/5.14.1/single/qt-everywhere-src-5.14.1.tar.xz
Already downloaded: /home/nikhil/.cache/Homebrew/downloads/47ce549552781565a244b172a24bdb0568c746f7bf71906eca39a55226f51f8b--qt-everywhere-src-5.14.1.tar.xz
==> ./configure -verbose -prefix /home/linuxbrew/.linuxbrew/Cellar/qt/5.14.1 -release -opensource -confirm-licen
==> make
Last 15 lines from /home/nikhil/.cache/Homebrew/Logs/qt/02.make:
rm -f ../../lib/libQt5Widgets.so.5.14.1
mv -f libQt5Widgets.so.5.14.1 ../../lib/libQt5Widgets.so.5.14.1
rm -f ../../lib/libQt5Widgets.so
rm -f ../../lib/libQt5Widgets.so.5
rm -f ../../lib/libQt5Widgets.so.5.14
mv -f libQt5Widgets.so ../../lib/libQt5Widgets.so
mv -f libQt5Widgets.so.5 ../../lib/libQt5Widgets.so.5
mv -f libQt5Widgets.so.5.14 ../../lib/libQt5Widgets.so.5.14
make[3]: Leaving directory '/tmp/qt-20200129-31698-1moafeb/qt-everywhere-src-5.14.1/qtbase/src/widgets'
make[2]: Leaving directory '/tmp/qt-20200129-31698-1moafeb/qt-everywhere-src-5.14.1/qtbase/src'
Makefile:50: recipe for target 'sub-src-make_first' failed
make[1]: *** [sub-src-make_first] Error 2
make[1]: Leaving directory '/tmp/qt-20200129-31698-1moafeb/qt-everywhere-src-5.14.1/qtbase'
Makefile:87: recipe for target 'module-qtbase-make_first' failed
make: *** [module-qtbase-make_first] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
qt: Build a bottle for Linux https://github.com/Homebrew/linuxbrew-core/pull/19305
```

**Comment by iMichka** [comment]
I pushed a new binary: #19305

Trying to build qt from source on any other system than our docker image will probably never work ... their build system is too unstable for that.
