### ISSUE TITLE
Install failed and homebrew added itself as a remote on all git repos

### ISSUE THREAD

**Issue by btilford** [Homebrew/linuxbrew-core#19381]
Following the install instructions on https://docs.brew.sh/Homebrew-on-Linux it seemed like it installed successfully but I was unable to install any packages.

When I went to push a change to the project I'm working on that failed and I noticed I had the following in my remotes list `git remote -v`
```
origin  https://github.com/Homebrew/brew (fetch)
origin  https://github.com/Homebrew/brew (push)
```

Thinking I'd done something dumb like installing from the project's directory I tried removing it but I could only remove the real origin for the project the hombrew origins would not go away. So I deleted the `.git` directory and checked it out again. Still the homebrew origin came back. Then I checked all my other repos and they all had the homebrew origin in them as well. I've nuked everything to do with homebrew and still can't get these to go away.  

I've never seen this type of behavior with git and can't figure out what's going on, I've checked `/` and `/home` and `~/` to see if maybe brew put a repo there or something like that but there is nothing there.

**Comment by dawidd6** [comment]
What is your distribution and git version?
Did you check the contents of `~/.gitconfig` file?

Give us some more information.

**Comment by iMichka** [comment]
Yes, please open this issue in https://github.com/Linuxbrew/install.
