### ISSUE TITLE
starship: Request for a bottle

### ISSUE THREAD

**Issue by develop7** [Homebrew/linuxbrew-core#19458]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] checked that there aren't other open issues for the same formula bottle request?
- [x] does the `starship` not have the `bottle` block?
- [x] ran `brew install starship` and it succeeded?

**Comment by dawidd6** [comment]
Fixed by: https://github.com/Homebrew/linuxbrew-core/commit/0c55c3a8321a48978c2b4928da7fa51acb6647ed
