### ISSUE TITLE
Systemd update can't read logs

### ISSUE THREAD

**Issue by pgcudahy** [Homebrew/linuxbrew-core#19506]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
Read systemd logs with `journalctl`

## What happened (include command output)
Trying to run `journalctl` gives the error
```
Journal file /var/log/journal/ad9213e031ec2a16399a42515988884e/user-1001@ae426ac82df44a8489f745ad63e8c9ea-000000000000215f-0005848bb1ab0334.journal uses an unsupported feature, ignoring file.
Use SYSTEMD_LOG_LEVEL=debug journalctl --file=/var/log/journal/ad9213e031ec2a16399a42515988884e/user-1001@ae426ac82df44a8489f745ad63e8c9ea-000000000000215f-0005848bb1ab0334.journal to see the details.
-- No entries --
```
When I run the recommended command, I get 
```
Journal effective settings seal=no compress=no compress_threshold_bytes=8B
Journal file /var/log/journal/ad9213e031ec2a16399a42515988884e/user-1001@ae426ac82df44a8489f745ad63e8c9ea-000000000000215f-0005848bb1ab0334.journal uses incompatible flag lz4-compressed disabled at compilation time.
Failed to open journal file /var/log/journal/ad9213e031ec2a16399a42515988884e/user-1001@ae426ac82df44a8489f745ad63e8c9ea-000000000000215f-0005848bb1ab0334.journal: Protocol not supported
mmap cache statistics: 0 hit, 1 miss
Failed to open files: Protocol not supported
```

## What you expected to happen

The normal logs to appear. They do display with `/bin/journalctl` on ubuntu

Could this be related to the recent upgrade of [systemd](https://github.com/Homebrew/linuxbrew-core/pull/19050)? The base ubuntu version of `journalctl` has +LZ4 enabled, while brew's version does not.

```
pgcudahy:~$ /bin/journalctl --version
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
pgcudahy:~$ /home/linuxbrew/.linuxbrew/Cellar/systemd/244/bin/journalctl --version
systemd 244 (244)
-PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS -ACL +XZ -LZ4 -SECCOMP +BLKID -ELFUTILS -KMOD -IDN2 -IDN -PCRE2 default-hierarchy=unified
```

**Comment by dawidd6** [comment]
@Homebrew/linux Maybe we should make `systemd` keg only? So it wouldn't conflict with the system provided one.

**Comment by sjackman** [comment]
@pgcudahy Would you like to try `brew edit systemd` and enabling `+LZ4` and see whether that fixes your problem, and report back? We'd be happy to accept a PR to enable LZ4 by default if it does.
