### ISSUE TITLE
Installing custom formula for Vim, options not present (+clipboard)

### ISSUE THREAD

**Issue by zzzachzzz** [Homebrew/linuxbrew-core#19505]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I'm trying to install an edited formula for Vim. I ran `brew edit vim` and added the option `--with-features=huge` to the `system "./configure"` section. I then installed with `brew install --build-from-source vim`, I  tried `brew install --build-from-source $(brew formula vim)` as well, just to ensure it was referring to the modified formula. I have also tried the option `--enable-clipboard`, and tried removing the option `--without-x`, in case that clipboard related option was overwriting anything.

## What happened (include command output)

Despite `--with-features=huge` appearing in the configure output (see the `brew gist-logs` output: https://gist.github.com/zzzachzzz/f7b1c0f7538511c036250fa315154323), the `clipboard` option is disabled.
```
$ which vim
/home/linuxbrew/.linuxbrew/bin/vim
$ vim --version
...
-clipboard
...
```

## What you expected to happen

When using the option `--with-features=huge`, I expect all available Vim features to be present. The output of `vim --version` should include `+clipboard`.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. `brew edit vim`
2. Add the option `--with-features=huge`. Example `./configure` section:
```
system "./configure", "--prefix=#{HOMEBREW_PREFIX}",
                       "--mandir=#{man}",
                       "--enable-multibyte",
                       "--with-tlib=ncurses",
                      "--enable-cscope",
                      "--enable-terminal",
                      "--with-compiledby=Homebrew",
                      "--enable-perlinterp",
                      "--enable-rubyinterp",
                      "--enable-python3interp",
                      "--enable-gui=no",
                      # "--without-x",
                      "--with-features=huge",
                      "--enable-luainterp",
                      "--with-lua-prefix=#{Formula["lua"].opt_prefix}"
```
3. `brew install --build-from-source vim`
4. `/home/linuxbrew/.linuxbrew/bin/vim --version`
5. Clipboard option is disabled, indicated by `-clipboard`

**Comment by dawidd6** [comment]
https://gist.github.com/lirenlin/63453cda5181028b2565

Try adding `--with-x` and deleting `--enable-gui=no`.

**Comment by zzzachzzz** [comment]
> https://gist.github.com/lirenlin/63453cda5181028b2565
> 
> Try adding `--with-x` and deleting `--enable-gui=no`.

It's worth noting that this is on Windows Subsystem for Linux. I have successfully gotten clipboard enabled Vim builds from `vim-gtk` before.
Result:
```
$ brew install --build-from-source vim
Updating Homebrew...
==> Downloading https://github.com/vim/vim/archive/v8.2.0200.tar.gz
Already downloaded: /home/zach/.cache/Homebrew/downloads/cd5dac5668e0ce4206de124f4673fae73df9caf826275752a6b02a0c189dbe8e--vim-8.2.0200.tar.gz
==> ./configure --prefix=/home/linuxbrew/.linuxbrew --mandir=/home/linuxbrew/.linuxbrew/Cellar/vim/8.2.0200/share/man --enable-multibyte --with-tlib=ncurses --enable-cscope --enable-terminal --with-compiledby=Home
Last 15 lines from /home/zach/.cache/Homebrew/Logs/vim/01.configure:
checking --disable-channel argument... no
checking for socket in -lsocket... no
checking for gethostbyname in -lnsl... yes
checking whether compiling with process communication is possible... yes
checking --enable-terminal argument... yes
checking --enable-autoservername argument... no
checking --enable-multibyte argument... yes
checking --disable-rightleft argument... no
checking --disable-arabic argument... no
checking --enable-xim argument... defaulting to auto
checking --enable-fontset argument... no
checking for xmkmf... no
checking for X... no
checking if X11 header files can be found... no
configure: error: could not configure X

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
Installing custom formula for Vim, options not present (+clipboard) https://github.com/Homebrew/linuxbrew-core/issues/19505
```
With config:
```
system "./configure", "--prefix=#{HOMEBREW_PREFIX}",
                      "--mandir=#{man}",
                      "--enable-multibyte",
                      "--with-tlib=ncurses",
                      "--enable-cscope",
                      "--enable-terminal",
                      "--with-compiledby=Homebrew",
                      "--enable-perlinterp",
                      "--enable-rubyinterp",
                      "--enable-python3interp",
                      # "--enable-gui=no",
                      "--with-x",
                      "--with-features=huge",
                      "--enable-clipboard",
                      "--enable-luainterp",
                      "--with-lua-prefix=#{Formula["lua"].opt_prefix}"
```
