### ISSUE TITLE
Node builds have problems when run as root

### ISSUE THREAD

**Issue by dawidd6** [Homebrew/linuxbrew-core#19517]
Errors like this didn't happen on Azure, where we built bottles as `linuxbrew` user, but happen on GH Actions, where we are building them as `root`.

```
gyp ERR! stack Error: EACCES: permission denied, stat '/tmp/node@10-test-20200206-45421-ngvatc/node_modules/bignum/.node-gyp/10.19.0'
```

https://github.com/Homebrew/linuxbrew-core/runs/430180675?check_suite_focus=true
https://github.com/Homebrew/linuxbrew-core/runs/430180727?check_suite_focus=true
https://github.com/Homebrew/linuxbrew-core/runs/430180618?check_suite_focus=true

It's kinda funny how `root` can get permission denied.

Of course the easiest and cleanest solution would be to run `test-bot` as normal user, but this is tricky on GH Actions.
Any other ideas?

**Comment by issyl0** [comment]
We could ask GitHub what they recommend. I could open an issue in the maintainer feedback group.

**Comment by dawidd6** [comment]
What group? I don't know anything about it.

**Comment by iMichka** [comment]
I worked around this issue with the `--unsafe-perm"` flag, see #19647

I think we should at this flag to Language::Node.std_npm_install_args
