### ISSUE TITLE
Why are Java tools (ant, maven) depend (again!) on openjdk?

### ISSUE THREAD

**Issue by cstamas** [Homebrew/linuxbrew-core#19538]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Upgrade ant, maven that were present.

## What happened (include command output)

It wants to install a zillion of dependencies I really don't think are needed:
```
cstamas@Albert ~ $ brew upgrade ant 
==> Upgrading 1 outdated package:
ant 1.10.7 -> 1.10.7_1
==> Upgrading ant 
==> Installing dependencies for ant: alsa-lib, cups, libpng, freetype, util-linux, fontconfig, zip, linuxbrew/xorg/libpthread-stubs, linuxbrew/xorg/xorgproto, linuxbrew/xorg/libxau, linuxbrew/xorg/libxdmcp, linuxbrew/xorg/libxcb, linuxbrew/xorg/libx11, linuxbrew/xorg/libxext, linuxbrew/xorg/libxrender, linuxbrew/xorg/libxrandr, linuxbrew/xorg/libice, linuxbrew/xorg/libsm, linuxbrew/xorg/libxt, linuxbrew/xorg/libxfixes, linuxbrew/xorg/libxi, linuxbrew/xorg/libxtst and openjdk
```
## What you expected to happen

Upgrade ant w/o forcing me to use openjdk.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew upgrade ant` or `brew upgrade maven`

I use Linux Mint 19.3 + AdoptopenJDK 1.8 is installed. Seems `depends_on :java => "1.8+"` is _again_ replaced with explicit openjdk dependency, I do not want. I want to use adoptopenjdk.

**Comment by cstamas** [comment]
Specifically this change: https://github.com/Homebrew/linuxbrew-core/commit/dfa8d0ffe99217b01916b5e3aca89f81a742f03f#diff-c1b5b8517fbb927f7d1cd14bdefd5fc2


Undoes what we did in https://github.com/Homebrew/linuxbrew-core/issues/13608

**Comment by SMillerDev** [comment]
They're both builds from the same source and homebrew is going to use homebrew dependencies in its formulae if possible. If you don't want this you could maintain a copy of ant in a personal tap, which is very easy to do: https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap

**Comment by cstamas** [comment]
They're both builds from the same source

Can you elaborate this? As I see from formulae, the binaries are being downloaded, so for sure you are not meaning "ant build" or "maven build". Moreover, as I see the cemented `openjdk` dependency is barely needed to set up `JAVA_HOME` env variable _to perform a  "test"?_

Could it be made in more sane way? Ie. detect Java presence automatically (like with `:java`) and set JAVA_HOME only if not set? And finally, these "tests" (at least for Maven) does not much sense IMO. Why not just `mvn -v` and match output version (and that is error free)?

**Comment by SMillerDev** [comment]
And finally, these "tests" (at least for Maven) does not much sense IMO. Why not just mvn -v and match output version (and that is error free)?

It's error free because it doesn't test something that generally breaks if packaged incorrectly. 

  As I see from formulae, the binaries are being downloaded

The adoptopenjdk binaries are a compiled openjdk. The openjdk formula is a compiled openjdk. They’re both the same source.

**Comment by cstamas** [comment]
Well, I understand. But at same time, dislike this choice (am not Gentoo user :smile: ).

Seems, for my case, it would make sense to move my JVM based tool management off Linuxbrew and use something like SDKMAN instead... (linuxbrew is still very cool for other stuff, like git, ansible, etc).

**Comment by cstamas** [comment]
Ok, so a bit of broader picture: I am coming (returning) to Linux from macOS (00-07 opensuse, 07-16 macOS, 16- linux mint). So, this "switch" made sense. Formulas like `ant`, `groovy`, `gradle` and `maven` removed from brew. Installed SDKMAN instead, and reinstalled it using it. All fine here.

**Comment by reitermarkus** [comment]
@cstamas, at least for Java development related software, we allow you to override `JAVA_HOME`, but we will still default to the latest `openjdk` formula possible.

**Comment by cstamas** [comment]
@reitermarkus is cool. Actually, I did `brew upgrade` today on my mac as well, spotted same thing (openjdk being pulled in w/ no ant or maven version upgrade), and let it finished. Then realized:
* this is Homebrew change (so not specific to Linuxbrew as I assumed) -- it is merely the deps that differs for openjdk on macOS and Linux
* openjdk being pulled is keg-only (was reported as such on macOS) -- so it does NOT override my JDK present on system, which was my main problem with this.

Ultimately, it is (mac|linux)brew that needs this keg-only openjdk just to verify (perform tests), and possibly build java stuff (not needed in case of ant and maven).
