### ISSUE TITLE
Can't `brew install git --HEAD` , get `ArgumentError: no time information in ""`

### ISSUE THREAD

**Issue by phil-blain** [Homebrew/linuxbrew-core#19589]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

What: Install Git from the tip of the git.git `master` branch by doing `brew install git --HEAD`.
Why: because some bugs are fixed in `master` and Git 2.26 is not yet released.

## What happened (include command output)
1. First I installed homebrew, which succeeded. 
2. Then immediately I did  `brew install git --HEAD`.
This first installed the curl dependencies: `patchelf, m4, gmp, mpfr, libmpc, isl@0.18, zlib, binutils, linux-headers, glibc, gcc, pkg-config` and `openssl@1.1`. Then it installed `curl`. 
Then it installed git dependencies: `gpatch, ncurses, gettext, bzip2, pcre2, libbsd` and `expat`.
Then it installed Git 2.25 (not HEAD). Then it ended with :
~~~ruby
Error: git 2.25.0_1 is already installed
To install HEAD_1, first run `brew unlink git`.
Warning: Skipping (old) /path/to/my/$HOME/.linuxbrew/Cellar/git/2.25.0_1 due to it being linked
~~~

So then I did 

~~~ 
$ brew unlink git
Unlinking  /path/to/my/$HOME/.linuxbrew/Cellar/git/2.25.0_1... 205 symlinks removed
$ brew install git --HEAD
~~~

<details>
  <summary>Output of second `brew install git --HEAD`</summary>
  <pre>

==> Cloning https://github.com/git/git.git
Cloning into ' /path/to/my/$HOME/.cache/Homebrew/git--git'...
Checking out files: 100% (3692/3692), done.
==> Checking out branch master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Submodule 'sha1collisiondetection' (https://github.com/cr-marcstevens/sha1collisiondetection.git) registered for path 'sha1collisiondetection'
Cloning into 'sha1collisiondetection'...
Submodule path 'sha1collisiondetection': checked out '855827c583bc30645ba427885caa40c5b81764d2'
$HOME/.cache/Homebrew/git--git/sha1collisiondetection
Error: An exception occurred within a child process:
  ArgumentError: no time information in ""

  </pre>
</details>

Notice the (Ruby?) error at the end:
~~~
Error: An exception occurred within a child process:
  ArgumentError: no time information in ""
~~~
Notice also that brew seems to run `git submodule update --init` but this is not necessary for Git as the `sah1collisiondetection` submodule is not mandatory for the build.

## What you expected to happen

I expected Brew to be able to install Git from tip of `master` by doing `brew install git --HEAD`.

## Step-by-step reproduction instructions (by running `brew install` commands)

These steps were done on Ubuntu 14.04:
~~~bash
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
# don't give sudo password as I don't have root access
# install to  /path/to/my/$HOME/.linuxbrew
eval $($HOME/.linuxbrew/bin/brew shellenv)
brew install git --HEAD
brew unlink git
brew install git --HEAD
~~~

## What I tried
- I tried adding the portable Ruby installed by brew to my path with 
~~~bash
PATH= /path/to/my/$HOME/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/current/bin:$PATH
~~~
before running `brew install git --HEAD`
- I also tried adding a more recent version of Git to my path before running  `brew install git --HEAD`.
- I tried `brew uninstall git && brew install git --HEAD`. This also installed 2.25 and ended (as above) with 
~~~bash
Error: git 2.25.0_1 is already installed
To install HEAD_1, first run `brew unlink git`.
Warning: Skipping (old)  /path/to/my/$HOME/.linuxbrew/Cellar/git/2.25.0_1 due to it being linked
~~~
- `brew gist-logs git` gives "Error: No logs."

## Brew doctor
~~~bash
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  git

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.
~~~
Note that I don't have root access so I can't install brew to `/home/linuxbrew/.linuxbrew`.

## Brew config
~~~bash
$ brew config
HOMEBREW_VERSION: 2.2.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4493f27db28be7f083737424cecd8edb863ec3f6
Last commit: 8 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: eba35626b052bdc58c82dfbe8088a5b328418442
Core tap last commit: 27 minutes ago
HOMEBREW_PREFIX: $HOME/.linuxbrew
HOMEBREW_CELLAR: $HOME/.linuxbrew/Cellar
HOMEBREW_CACHE: $HOME/.cache/Homebrew
HOMEBREW_LOGS: $HOME/.cache/Homebrew/Logs
HOMEBREW_REPOSITORY: $HOME/.linuxbrew/Homebrew
HOMEBREW_SYSTEM_CURL_TOO_OLD: 1
CPU: dodeca-core 64-bit sandybridge
Homebrew Ruby: 2.6.3 => $HOME/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: N/A
Git: 2.25.0 => $HOME/.linuxbrew/bin/git
Curl: 7.68.0 => $HOME/.linuxbrew/opt/curl/bin/curl
Java: 1.7.0_181
Kernel: Linux 4.4.0-128-generic x86_64 GNU/Linux
OS: Ubuntu 14.04.5 LTS (trusty)
Host glibc: 2.19
/usr/bin/gcc: 4.8.4
glibc: 2.23
gcc: 5.5.0_7
xorg: N/A
~~~

**Comment by iMichka** [comment]
From brew doctor:
```
Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.
```

**Comment by phil-blain** [comment]
@iMichka I'm not sure what you want to point me to there, I don't know anything about Ruby so I won't be able to do a PR to solve this problem... 

I would have thought at least this issue could be kept open so that it has more visibility ?

If installing to somewhere else than /home/linuxbrew/.linuxbrew/ is not supported, and we can't wven ask for help, why document it at all ?....

**Comment by iMichka** [comment]
> I would have thought at least this issue could be kept open so that it has more visibility ?

We do not do this like this here. The issue will stay open for 30 days and be closed automatically. And I know from experience that an issue like yours might follow this path.

> If installing to somewhere else than /home/linuxbrew/.linuxbrew/ is not supported, and we can't even ask for help, why document it at all ?....

Some people use that configuration. If they have an issue, they open pull requests for fixes. These are mostly maintainers, or people with a lot of time to fix things. Time we do not have for this configuration.

The best thing is to open a discussion on https://discourse.brew.sh, and hope that somebody from the community helps you.

What we give support on is that `brew install git` in `/home/linuxbrew/.linuxbrew/` should always work. This is the only thing we want to guarantee for our users.
