### ISSUE TITLE
brew update broken my virtual environments , specifically import ssl

### ISSUE THREAD

**Issue by jainraje** [Homebrew/linuxbrew-core#19597]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
YES
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
YES
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
Install pyenv

Here is the log:
brew install pyenv
==> Installing dependencies for pyenv: autoconf, openssl@1.1 and readline
==> Installing pyenv dependency: autoconf
==> Downloading https://homebrew.bintray.com/bottles/autoconf-2.69.high_sierra.bottle.4.tar.gz
==> Downloading from https://akamai.bintray.com/63/63957a3952b7af5496012b3819c9956822fd7d895d63339c23fdc65c502e1a40?__gda__=exp=1581476798~hmac=19c5b07a521fed22434b38d8131cd69c7a6081a43a0fd16d97560110def8a0ab&response-
######################################################################## 100.0%
==> Pouring autoconf-2.69.high_sierra.bottle.4.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/autoconf
==> Summary
🍺  /usr/local/Cellar/autoconf/2.69: 71 files, 3.0MB
==> Installing pyenv dependency: openssl@1.1
==> Downloading https://homebrew.bintray.com/bottles/openssl@1.1-1.1.1d.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/c7/c7681ee40cb3680cd9fafcdb092bde153b9d4903907d67858baa5f19025f927b?__gda__=exp=1581476801~hmac=d1d208a50bf7341a44dc3a30000be26cb6f0af15b3af7e12f7f13191d4f4d53a&response-
######################################################################## 100.0%
==> Pouring openssl@1.1-1.1.1d.high_sierra.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because openssl/libressl is provided by macOS so don't link an incompatible version.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.bash_profile

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/openssl@1.1/1.1.1d: 7,983 files, 17.9MB

## What happened (include command output)

After installation completed. I set my python virtualenv and tried to the jupiter notebook.

But received the following errors:

jupyter notebook
Traceback (most recent call last):
  File "/Users/rajeev/.virtualenvs/py3-dev/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/Users/rajeev/.virtualenvs/py3-dev/lib/python3.6/site-packages/notebook/notebookapp.py", line 64, in <module>
    from tornado import httpserver
  File "/Users/rajeev/.virtualenvs/py3-dev/lib/python3.6/site-packages/tornado/httpserver.py", line 29, in <module>
    import ssl
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: dlopen(/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload/_ssl.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload/_ssl.cpython-36m-darwin.so
  Reason: image not found

I know the paths are messed up. Home-brew updated the openssl which broken my virtual enc. 

Please, please help me. Please point me to a solution. 

TIA,
--jainraje

**Comment by jonchang** [comment]
`/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload/_ssl.cpython-36m-darwin.so`

This version of python is old. Run `brew upgrade python`

**Comment by jainraje** [comment]
why did you close this? please reopen.

I have several versions of python on my system. the issue is still open. will you please help me fix the paths and symlink?

**Comment by jainraje** [comment]
you suggestion completely broke my system.

**Comment by jainraje** [comment]
my virtual environments are now all broken. why do you give bad advice and then close this issue without any response form me...???

**Comment by iMichka** [comment]
Hi.

Please watch your tone and keep calm. No need to be aggressive.

It's not bad advice. We can only solve issues if you are running the latest version of brew, hence the `brew upgrade`.

This issue should have been raised at https://github.com/Homebrew/homebrew-core, you are also on the wrong repository.
