### ISSUE TITLE
`brew bump-formula-pr ... adoptopenjdk` fails with bad replace

### ISSUE THREAD

**Issue by skinzler** [Homebrew/linuxbrew-core#19633]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Bump to latest adoptopenjdk release, for security.

## What happened (include command output)

Bump fails because adoptopenjdk formula doesn't include expected, and required?, "sha256 ... :x86_64_linux" text.

<details>
  <summary>Command output</summary>
  <pre>

$ brew bump-formula-pr --url \
?   https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u242-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u242b08.tar.gz \
?   --sha256 f39b523c724d0e0047d238eb2bb17a9565a60574cf651206c867ee5fc000ab43 \
?   --version 1.8.0.242 --message 'adoptopenjdk 1.8.0.242' \
?   --no-browse --dry-run adoptopenjdk
==> git remote add homebrew https://github.com/Homebrew/homebrew-core
==> git fetch homebrew master
==> git cat-file -e homebrew/master:Formula/adoptopenjdk.rb
==> git checkout homebrew/master
==> replace /https:\/\/github\.com\/AdoptOpenJDK\/openjdk8\-binaries\/releases\/download\/jdk8u212\-b03\/OpenJDK8U\-jdk_x64_linux_hotspot_8u212b03\.tar\.gz/ with "https://github.com/AdoptOpenJDK/openjdk8-bina
==> replace "dd28d6d2cde2b931caf94ac2422a2ad082ea62f0beee3bf7057317c53093de93" with "f39b523c724d0e0047d238eb2bb17a9565a60574cf651206c867ee5fc000ab43"
==> replace /^    sha256 ".+" => :x86_64_linux\n/m with "\\2"
==> replace "1.8.0.212" with "1.8.0.242"
Error: inreplace failed
/app/linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/adoptopenjdk.rb:
  expected replacement of /^    sha256 ".+" => :x86_64_linux\n/m with "\\2"

  </pre>
</details>

## What you expected to happen

Completion of dry-run without errors.

## Step-by-step reproduction instructions (by running `brew install` commands)

See command and output above.

$ brew cat adoptopenjdk
class Adoptopenjdk < Formula
  desc "Prebuilt binaries produced from OpenJDK class libraries"
  homepage "https://adoptopenjdk.net/"
  url "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u212-b03/OpenJDK8U-jdk_x64_linux_hotspot_8u212b03.tar.gz"
  version "1.8.0.212"
  sha256 "dd28d6d2cde2b931caf94ac2422a2ad082ea62f0beee3bf7057317c53093de93"

  bottle :unneeded

  depends_on :linux

  def install
    prefix.install Dir["*"]
    share.install prefix/"man"
  end

  test do
    (testpath/"Hello.java").write <<~EOS
      class Hello
      {
        public static void main(String[] args)
        {
          System.out.println("Hello Homebrew");
        }
      }
    EOS
    system bin/"javac", "Hello.java"
    assert_predicate testpath/"Hello.class", :exist?, "Failed to compile Java program!"
    assert_equal "Hello Homebrew\n", shell_output("#{bin}/java Hello")
  end
end

**Comment by skinzler** [comment]
Forgot this:
$ brew config
HOMEBREW_VERSION: 2.2.5-56-g23ab620
ORIGIN: https://github.com/Homebrew/brew
HEAD: 23ab620cd412a5b80d300055e18e5325a8d8edee
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: edf5ccaec9f81503c10a6695981e0ead4f8e6397
Core tap last commit: 28 minutes ago
HOMEBREW_PREFIX: /app/linuxbrew
HOMEBREW_CELLAR: /app/linuxbrew/Cellar
HOMEBREW_CACHE: /app/linuxbrew/.cache/Homebrew
HOMEBREW_LOGS: /app/linuxbrew/.cache/Homebrew/Logs
HOMEBREW_REPOSITORY: /app/linuxbrew/Homebrew
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
HOMEBREW_NO_INSTALL_CLEANUP: true
HOMEBREW_VISUAL: via
CPU: dual-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /app/linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: N/A
Git: 2.25.0 => /app/linuxbrew/bin/git
Curl: 7.60.0 => /usr/bin/curl
Kernel: Linux 4.12.14-95.16-default x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.22
/usr/bin/gcc: 4.8.5
glibc: 2.23
gcc: 5.5.0_7
xorg: N/A
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: You have uncommitted modifications to Homebrew.
If this is a surprise to you, then you should stash these modifications.
Stashing returns Homebrew to a pristine state but can be undone
should you later need to do so for some reason.
  cd /app/linuxbrew/Homebrew/Library && git stash && git clean -d -f

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.

**Comment by dawidd6** [comment]
The bug is here:

https://github.com/Homebrew/brew/blob/23ab620cd412a5b80d300055e18e5325a8d8edee/Library/Homebrew/dev-cmd/bump-formula-pr.rb#L262

We should first check if there is any `sha256 ... :x86_64_linux` line in formula file.
