### ISSUE TITLE
Allowable values for HOMEBREW_ARCH?  Value to use for maximum compatibility?

### ISSUE THREAD

**Issue by alanhoyle** [Homebrew/linuxbrew-core#19664]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x ] ran `brew update` and can still reproduce the problem?
- [ x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I'm working in a compute cluster environment and different machines have different CPU brands and  architectures (GenuineIntel Xeons, AuthenticAMD Opterons, etc).  I'm trying to use linuxbrew with the same binaries on multiple machines.  

## What happened (include command output)

Several of my brewed commands work perfectly fine on some nodes but fail with "Illegal instruction" errors on other nodes.  This includes `curl` which is needed to run several of the core `brew` commands, but also includes other things like commands in `csvkit`

<details>
  <summary>Command output</summary>
  <pre>
[alanh@login1:~] $  /home/alanh/.linuxbrew/bin/curl --version  # interactive session on a login node
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1d zlib/1.2.11
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smt
[alanh@login1:~] $ sinteractive # starts an interactive session on a cluster node
[alanh@node-2-8:~] $ /home/alanh/.linuxbrew/bin/curl --version
Illegal instruction
[alanh@node-2-8:~] $ 

  </pre>
</details>

## What you expected to happen

The same binary would work in both places.

## Step-by-step reproduction instructions (by running `brew install` commands)

I know I should be able to recompile by exporting a value for the `HOMEBREW_ARCH` environment variable, but I can't find any documentation for what values are possible or what would be recommended to build to make a more universal/portable binary that would work.

I think my original builds were on Intel Xeon CPUs, but most of the actual compute nodes are AMD Opterons, so things work on the former, but not the latter.  

Can someone let me know what I should put into `HOMEBREW_ARCH` to work for both of the above cases?  What are the allowable values?  Looking at [the documentation](https://docs.brew.sh/Manpage) and Googling/searching has not given anything aside from telling me that the default value is `-march=native`.

**Comment by alanhoyle** [comment]
I found [the gcc documentation](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html) which seems to list values.  However, is it possible to make brew use -mtune instead of -march to give a generic binary that might run faster sometimes?

**Comment by jonchang** [comment]
> Can someone let me know what I should put into HOMEBREW_ARCH to work for both of the above cases? What are the allowable values? Looking at the documentation and Googling/searching has not given anything aside from telling me that the default value is -march=native.

This lives in `extend/os/linux/hardware/cpu.rb`.

> However, is it possible to make brew use -mtune instead of -march to give a generic binary that might run faster sometimes?

This is not possible in Homebrew. Note that the documentation you linked states that you should favor setting `-march` to a specific CPU when possible. In your case, you should set `HOMEBREW_ARCH` to the oldest CPU that your cluster's compute nodes are using. In practice this will either be `core2` or `nehalem` (if all CPUs support SSE4).
