### ISSUE TITLE
Elasticsearch 7

### ISSUE THREAD

**Issue by StudioMaX** [Homebrew/linuxbrew-core#19670]
Are there any chances to add support for the Elasticsearch 7 in any way? Only 6.8.x is [currently supported](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/elasticsearch.rb), although 7.6 already exists.

It seems that there [were attempts](https://github.com/Homebrew/homebrew-core/pull/38966) to add it to the main homebrew repository, but because of some problems there was no progress.

After that, Elastic have released the official Tap, which they support, but only for macOS - https://github.com/elastic/homebrew-tap

Elasticsearch 6.8 EOL at 2020-11-20, according to [their table](https://www.elastic.co/support/eol).

So what should I do as a user to upgrade to the latest supported version?

**Comment by jonchang** [comment]
Please open a pull request to Homebrew/homebrew-core. You can probably create the formula as `elasticsearch@7` so it doesn't break everything for 6.x users, which was part of the issue with the last pull request.

**Comment by StudioMaX** [comment]
Creating the formula in `Homebrew/homebrew-core` means that there will be two separate ways to install Elasticsearch on macOS: the official method, which mentioned in [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/brew.html) via `brew install elastic/tap/elasticsearch-full` and the formula in homebrew-core which must be updated by maintainers. So why will users have to install the Elasticsearch 7 on macOS not in the official way that is mentioned in the documentation and which is supported by the application’s developers, but from the formula that will be supported by homebrew-core's community? (and, to be honest, the formula for Elasticsearch@7 has not been created for more than a year, which means nobody needs Elasticsearch@7 in the repository).

**Comment by issyl0** [comment]
> After that, Elastic have released the official tap, which they support, but only for macOS - https://github.com/elastic/homebrew-tap

You could make a PR to add Linux support to the tap and use their official solution? Maybe Elastic don't realise that Homebrew works on Linux.

**Comment by jonchang** [comment]
> Creating the formula in Homebrew/homebrew-core means that there will be two separate ways to install Elasticsearch on macOS: the official method, which mentioned in documentation via brew install elastic/tap/elasticsearch-full and the formula in homebrew-core which must be updated by maintainers. So why will users have to install the Elasticsearch 7 on macOS not in the official way that is mentioned in the documentation and which is supported by the application’s developers, but from the formula that will be supported by homebrew-core's community? (and, to be honest, the formula for Elasticsearch@7 has not been created for more than a year, which means nobody needs Elasticsearch@7 in the repository).

Upstream is free to recommend a different installation method. If something is open source and builds on macOS it is eligible to be packaged in Homebrew/core. If you have further questions please post them to Homebrew's Discourse: https://discourse.brew.sh/
