### ISSUE TITLE
openssl@1.1 and gettext installation error

### ISSUE THREAD

**Issue by hidvegin** [Homebrew/linuxbrew-core#19671]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [X ] ran `brew update` and can still reproduce the problem?
- [X ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

SZEGED[loginnode] ~ (1)$ brew config
HOMEBREW_VERSION: >=2.2.0 (shallow or no git repository)
ORIGIN: https://github.com/Homebrew/brew
HEAD: 5b126ec850b688cba57a9cf17be08d321ad4d10f
Last commit: 28 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: c7b6075ec2fca0eed7949ea79aa5de651fe31998
Core tap last commit: 10 hours ago
HOMEBREW_PREFIX: /mnt/stori/home/fk8jybr/.linuxbrew
HOMEBREW_CELLAR: /mnt/stori/home/fk8jybr/.linuxbrew/Cellar
HOMEBREW_CACHE: /home/fk8jybr/.cache/Homebrew
HOMEBREW_LOGS: /home/fk8jybr/.cache/Homebrew/Logs
HOMEBREW_REPOSITORY: /mnt/stori/home/fk8jybr/.linuxbrew/Homebrew
HOMEBREW_NO_ANALYTICS_THIS_RUN: 1
HOMEBREW_SYSTEM_CURL_TOO_OLD: 1
CPU: 16-core 64-bit unknown_0x10_0x9
Homebrew Ruby: 2.6.3 => /mnt/stori/home/fk8jybr/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: N/A
Git: 1.8.3.1 => /bin/git
Curl: 7.29.0 => /usr/bin/curl
Kernel: Linux 3.10.0-1062.12.1.el7.x86_64 x86_64 GNU/Linux
OS: CentOS Linux release 7.7.1908 (Core)
Host glibc: 2.17
/usr/bin/gcc: 4.8.5
glibc: 2.23
gcc: 5.5.0_7
xorg: N/A

SZEGED[loginnode] ~ (0)$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/fk8jybr/.linuxbrew/bin/ncurses6-config
  /home/fk8jybr/.linuxbrew/bin/pkg-config
  /home/fk8jybr/.linuxbrew/bin/ncursesw6-config

Warning: An outdated version (1.8.3.1) of Git was detected in your PATH.
Git 2.7.0 or newer is required for Homebrew.
Please upgrade:
  brew install git

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.

## What you were trying to do (and why)

I run brew update command. brew found curl and git are out-dated.

## What happened (include command output)

brew tried install curl and git with dependences but brew could not install openssl@1.1 and gettext.

<details>
  <summary>
</summary>
  <pre>

 SZEGED[loginnode] ~ (1)$ brew update
==> Installing dependencies for curl: openssl@1.1
==> Installing curl dependency: openssl@1.1
==> Downloading https://www.openssl.org/source/openssl-1.1.1d.tar.gz
Already downloaded: /home/fk8jybr/.cache/Homebrew/downloads/567481d93e12a0cdaf990a51159f5ccf67fdb7bbcf6a1d961df071365e44731e--openssl-1.1.1d.tar.gz
==> perl ./Configure --prefix=/mnt/stori/home/fk8jybr/.linuxbrew/Cellar/openssl@
==> make
Last 15 lines from /home/fk8jybr/.cache/Homebrew/Logs/openssl@1.1/02.make:
gcc-5  -I. -Icrypto/include -Iinclude -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/mnt/stori/home/fk8jybr/.linuxbrew/etc/openssl@1.1\"" -DENGINESDIR="\"/mnt/stori/home/fk8jybr/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/lib/engines-1.1\"" -DNDEBUG  -MMD -MF crypto/bf/bf_ofb64.d.tmp -MT crypto/bf/bf_ofb64.o -c -o crypto/bf/bf_ofb64.o crypto/bf/bf_ofb64.c
gcc-5  -I. -Icrypto/include -Iinclude -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/mnt/stori/home/fk8jybr/.linuxbrew/etc/openssl@1.1\"" -DENGINESDIR="\"/mnt/stori/home/fk8jybr/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/lib/engines-1.1\"" -DNDEBUG  -MMD -MF crypto/bf/bf_skey.d.tmp -MT crypto/bf/bf_skey.o -c -o crypto/bf/bf_skey.o crypto/bf/bf_skey.c
gcc-5  -I. -Icrypto/include -Iinclude -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/mnt/stori/home/fk8jybr/.linuxbrew/etc/openssl@1.1\"" -DENGINESDIR="\"/mnt/stori/home/fk8jybr/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/lib/engines-1.1\"" -DNDEBUG  -MMD -MF crypto/bio/b_addr.d.tmp -MT crypto/bio/b_addr.o -c -o crypto/bio/b_addr.o crypto/bio/b_addr.c
gcc-5  -I. -Icrypto/include -Iinclude -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/mnt/stori/home/fk8jybr/.linuxbrew/etc/openssl@1.1\"" -DENGINESDIR="\"/mnt/stori/home/fk8jybr/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/lib/engines-1.1\"" -DNDEBUG  -MMD -MF crypto/bio/b_dump.d.tmp -MT crypto/bio/b_dump.o -c -o crypto/bio/b_dump.o crypto/bio/b_dump.c
gcc-5  -I. -Icrypto/include -Iinclude -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/mnt/stori/home/fk8jybr/.linuxbrew/etc/openssl@1.1\"" -DENGINESDIR="\"/mnt/stori/home/fk8jybr/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/lib/engines-1.1\"" -DNDEBUG  -MMD -MF crypto/bio/b_print.d.tmp -MT crypto/bio/b_print.o -c -o crypto/bio/b_print.o crypto/bio/b_print.c
crypto/bio/b_print.c: In function 'roundv':
crypto/bio/b_print.c:538:5: internal compiler error: Illegal instruction
     if (value >= 0.5)
     ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/linuxbrew-core/issues> for instructions.
make[1]: *** [crypto/bio/b_print.o] Error 1
make[1]: Leaving directory `/tmp/openssl@1.1-20200220-12263-6udszt/openssl-1.1.1d'
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

==> Installing dependencies for git: gettext, bzip2, pcre2, openssl@1.1, curl, libbsd and expat
==> Installing git dependency: gettext
==> Downloading https://ftp.gnu.org/gnu/gettext/gettext-0.20.1.tar.xz
Already downloaded: /home/fk8jybr/.cache/Homebrew/downloads/ae9054eb313c4bc212a180985b803835865e320d827a3e0f677a9f89ea251d24--gettext-0.20.1.tar.xz
==> ./configure --prefix=/mnt/stori/home/fk8jybr/.linuxbrew/Cellar/gettext/0.20.
==> make
Last 15 lines from /home/fk8jybr/.cache/Homebrew/Logs/gettext/02.make:
term-ostream.oo.c:184:10: internal compiler error: Illegal instruction
          + delta_saturation * delta_saturation * 0.2f
          ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/linuxbrew-core/issues> for instructions.
make[4]: *** [config.h] Error 1
make[4]: Leaving directory `/tmp/gettext-20200220-13611-1izll28/gettext-0.20.1/libtextstyle/lib'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/tmp/gettext-20200220-13611-1izll28/gettext-0.20.1/libtextstyle'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/tmp/gettext-20200220-13611-1izll28/gettext-0.20.1/libtextstyle'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/gettext-20200220-13611-1izll28/gettext-0.20.1'
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

Already up-to-date.

  </pre>
</details>

## What you expected to happen

brew install curl and git with dependences.

## Step-by-step reproduction instructions (by running `brew install` commands)

I run only brew update.

**Comment by jonchang** [comment]
`CPU: 16-core 64-bit unknown_0x10_0x9`

what CPU are you using? This doesn't appear to match anything that Homebrew supports.

**Comment by hidvegin** [comment]
This is a HP CP4000BL cluster with AMD Opteron 6174 CPUs (4 CPUs/cluster).

**Comment by iMichka** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like util-linux. If it's an option for you, you could open a ticket with your information systems department to ask that they create a linuxbrew role account with home directory `/home/linuxbrew`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below. On macOS the default installation directory is `/usr/local`. On Linux the default installation directory is `/home/linuxbrew/.linuxbrew`.

http://docs.brew.sh/Installation.html#alternative-installs
http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
http://docs.brew.sh/Bottles.html#cellar-cellar

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.

**Comment by jonchang** [comment]
@hidvegin this CPU doesn't have SSE4.1/4.2 instructions, a configuration which I believe we no longer support in Homebrew. You are likely going to have to build the entire toolchain (including e.g., gcc) from source. As pointed out above, we are unable to support this non-standard configuration, though we might consider patches which fix things for you and don't break things for our other users.
