### ISSUE TITLE
cannot load such file -- os/linux/glibc

### ISSUE THREAD

**Issue by SmarkWZP** [Homebrew/linuxbrew-core#19699]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  
![image](https://user-images.githubusercontent.com/22745814/75128384-c8470180-56fe-11ea-824e-f371c4fb78cb.png)

  </pre>
</details>

## What you expected to happen

download success

**Comment by jonchang** [comment]
> * [ ]  ran `brew update` and can still reproduce the problem?
> * [ ]  ran `brew doctor`, fixed all issues and can still reproduce the problem?
> * [ ]  ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
> * [ ]  if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

Please full out the full issue template, thanks. This issue can be re-opened once you have provided the requested information.
