### ISSUE TITLE
Cannot install bazel

### ISSUE THREAD

**Issue by thedrow** [Homebrew/linuxbrew-core#19703]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/20fd4aee6ad86cf20f7d3d8f8069d1fd
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install bazel

## What happened (include command output)

Bazel failed to build but the logs do not contain any error.

<details>
  <summary>Command output</summary>
  <pre>

brew install bazel                                                                                                                         │deb ...
==> Downloading https://github.com/bazelbuild/bazel/releases/download/2.1.1/bazel-2.1.1-dist.zip                                             │Unpacking postgresql-11 (11.7-2.pgdg18.04+1) over (11.7-1.pgdg1
gcc-7: The build tool has reset ENV; --env=std required.                                                                                     │8.04+1) ...
Target //src:bazel_nojdk failed to build                                                                                                     │Setting up libpq5:amd64 (12.2-2.pgdg18.04+1) ...
INFO: Elapsed time: 93.125s, Critical Path: 0.62s                                                                                            │Setting up postgresql-client-11 (11.7-2.pgdg18.04+1) ...
INFO: 1 process: 1 local.                                                                                                                    │Setting up postgresql-11 (11.7-2.pgdg18.04+1) ...
FAILED: Build did NOT complete successfully                                                                                                  │Processing triggers for postgresql-common (212.pgdg18.04+1) ...
                                                                                                                                             │Building PostgreSQL dictionaries from installed myspell/hunspel
ERROR: Could not build Bazel                                                                                                                 │l packages...
                                                                                                                                             │  en_us
READ THIS: https://docs.brew.sh/Troubleshooting 

  </pre>
</details>

## What you expected to happen

Bazel should compile itself correctly.

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install bazel

**Comment by iMichka** [comment]
Hi. We have repeatedly tried to build bazel over the last year; and failed:

#13619
#14087
#16117
#14006
#18548

As this took hours of maintainer time away to no awail, we have given up fixing this.

Anybody can open a pull request to fix the issue; but we will not be working on this. Sorry
