### ISSUE TITLE
libcbor fails to compile, blocks openssh

### ISSUE THREAD

**Issue by jkt628** [Homebrew/linuxbrew-core#19737]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

brew upgrade

## What happened (include command output)

libcbor fails to compile.

<details>
  <summary>Command output</summary>
  <pre>

==> Downloading https://github.com/PJK/libcbor/archive/v0.5.0.tar.gz
Already downloaded: /home/thomasso/.cache/Homebrew/downloads/2b8907b983a708370a5dd6cdb2c7ffe58a2ab110123c048e2131835eeeb21308--libcbor-0.5.0.tar.gz
==> cmake -G Unix Makefiles ..
==> make
Last 15 lines from /home/thomasso/.cache/Homebrew/Logs/libcbor/02.make:
/usr/bin/ld: <artificial>:(.text.startup+0x70): undefined reference to `cbor_build_uint8'
/usr/bin/ld: <artificial>:(.text.startup+0x78): undefined reference to `cbor_move'
/usr/bin/ld: <artificial>:(.text.startup+0x83): undefined reference to `cbor_array_push'
/usr/bin/ld: <artificial>:(.text.startup+0x8b): undefined reference to `cbor_array_size'
/usr/bin/ld: <artificial>:(.text.startup+0x96): undefined reference to `cbor_array_handle'
/usr/bin/ld: <artificial>:(.text.startup+0xba): undefined reference to `cbor_describe'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/CMakeFiles/sort.dir/build.make:88: examples/sort] Error 1
make[2]: Leaving directory '/tmp/libcbor-20200228-20829-p59pek/libcbor-0.5.0/build'
make[1]: *** [CMakeFiles/Makefile2:994: examples/CMakeFiles/sort.dir/all] Error 2
cd /tmp/libcbor-20200228-20829-p59pek/libcbor-0.5.0/build/src && /home/linuxbrew/.linuxbrew/Cellar/cmake/3.16.4/bin/cmake -E cmake_symlink_library libcbor.so.0.0.0 libcbor.so.0 libcbor.so
make[2]: Leaving directory '/tmp/libcbor-20200228-20829-p59pek/libcbor-0.5.0/build'
[100%] Built target cbor_shared
make[1]: Leaving directory '/tmp/libcbor-20200228-20829-p59pek/libcbor-0.5.0/build'
make: *** [Makefile:166: all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
libcbor: Fix build for Linux https://github.com/Homebrew/linuxbrew-core/pull/19689

  </pre>
</details>

## What you expected to happen

upgrade openssh with all dependencies

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install libcbor

**Comment by jkt628** [comment]
https://gist.github.com/a1d2802c059391876b7b6a0a16b93261

**Comment by dawidd6** [comment]
https://github.com/Homebrew/linuxbrew-core/pull/19689

**Comment by xanderlent** [comment]
Hi folks, this is somewhat my fault, (I spearheaded the changes upstream,) so I'm taking another look at this issue today.

See also: #19684 and Homebrew/homebrew-core#50588.

**Comment by jkt628** [comment]
still current

**Comment by xanderlent** [comment]
Hi folks, libcbor should build with Linuxbrew now that #19689 is merged, and we are working on libfido2 in #20080.

The only remaining problem is that I wrote the test for libfido2 on macOS, and it expects to be able to scan for USB HIDs, which isn't always the case on Linux. I would appreciate suggestions on testing that the library works without also testing device access.

**Comment by iMichka** [comment]
`libcbor` and `libfido2` have been fixed. I also fixed the `openssh` test; and built a bottle: #20271.

This is now fixed.

**Comment by jkt628** [comment]
confirmed, many thanks!
