### ISSUE TITLE
Path to MariaDB@10.2 is incorrect

### ISSUE THREAD

**Issue by tylerssn** [Homebrew/linuxbrew-core#19763]
```
==> Downloading from http://mirror.23media.de/mariadb//mariadb-10.2.30/source/mariadb-10.2.3
##O#- #                                                                       
curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "mariadb@10.2"
Download failed: https://downloads.mariadb.org/f/mariadb-10.2.30/source/mariadb-10.2.30.tar.gz
```

- [x] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install MariabDB@10.2 on Ubuntu 18.04 because I need it.

## What happened (include command output)

Install failed when attempting to download at:

```bash
$brew install mariadb@10.2

==> Downloading https://downloads.mariadb.org/f/mariadb-10.2.30/source/mariadb-10.2.30.tar.g
==> Downloading from http://mirror.23media.de/mariadb//mariadb-10.2.30/source/mariadb-10.2.3
##O#- #                                                                       
curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "mariadb@10.2"
Download failed: https://downloads.mariadb.org/f/mariadb-10.2.30/source/mariadb-10.2.30.tar.gz
```

```bash
$ brew gist-logs
Error: No logs.
```

## What you expected to happen

I expected MariaDB 10.2 to be installed

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install mariadb@10.2`

**Comment by issyl0** [comment]
This is a bit of an odd one. We link to `downloads.mariadb.org` which then downloads from seemingly the closest available mirror. But not all mirrors have all versions. As far as I can tell, it's a case of trying to download multiple times and eventually you'll get a working mirror. But that's not a great solution. I'll see what others maintainers think we should do to make this more reliable.
