### ISSUE TITLE
Post install fails when updating openssl@1.1 

### ISSUE THREAD

**Issue by thedrow** [Homebrew/linuxbrew-core#19802]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Nothing special, just stuck because I have no ca-certificates.

I did `brew upgrade`. That's all.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

  brew postinstall openssl@1.1
==> Postinstalling openssl@1.1
==> Downloading https://curl.haxx.se/ca/cacert-2020-01-01.pem
curl: (77) error setting certificate verify locations:
  CAfile: /home/linuxbrew/.linuxbrew/etc/openssl@1.1/cert.pem
  CApath: /home/linuxbrew/.linuxbrew/etc/openssl@1.1/certs

Trying a mirror...
==> Downloading https://gist.githubusercontent.com/dawidd6/16d94180a019f31fd31bc679365387bc/raw/ef02c78b9d6427585d756528964d18a2b9e318f7/cacert-2020-01-01.pem
curl: (77) error setting certificate verify locations:
  CAfile: /home/linuxbrew/.linuxbrew/etc/openssl@1.1/cert.pem
  CApath: /home/linuxbrew/.linuxbrew/etc/openssl@1.1/certs

Warning: The post-install step did not complete successfully
You can try again using `brew postinstall openssl@1.1

  </pre>
</details>

## What you expected to happen

post install action should succeed.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install openssl@1.1
```

**Comment by dawidd6** [comment]
Run: `HOMEBREW_CURLRC=1 brew reinstall openssl curl`

**Comment by thedrow** [comment]
> HOMEBREW_CURLRC=1 brew reinstall openssl curl

Same error.

**Comment by dawidd6** [comment]
If you have curl installed by system package manager, you can just uninstall the brewed one, upgrade openssl and then install brewed curl again.

**Comment by thedrow** [comment]
Yes that works as a workaround.

**Comment by zhangpy** [comment]
fail with another issue:
Last 15 lines from ~/.cache/Homebrew/Logs/openssl@1.1/02.make:
gcc-7  -I. -Icrypto/include -Iinclude -fPIC -arch x86_64 -Wa,--noexecstack -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"~/.linuxbrew/etc/openssl@1.1\"" -DENGINESDIR="\"~/.linuxbrew/Cellar/openssl@1.1/1.1.1d/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG  -MMD -MF crypto/bn/rsaz_exp.d.tmp -MT crypto/bn/rsaz_exp.o -c -o crypto/bn/rsaz_exp.o crypto/bn/rsaz_exp.c
CC="gcc-7" /usr/bin/perl crypto/bn/asm/x86_64-gf2m.pl macosx crypto/bn/x86_64-gf2m.s
gcc-7 -fPIC -arch x86_64 -Wa,--noexecstack -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"~/.linuxbrew/etc/openssl@1.1\"" -DENGINESDIR="\"~/.linuxbrew/Cellar/openssl@1.1/1.1.1d/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG  -c -o crypto/bn/x86_64-gf2m.o crypto/bn/x86_64-gf2m.s
CC="gcc-7" /usr/bin/perl crypto/bn/asm/x86_64-mont.pl macosx crypto/bn/x86_64-mont.s
gcc-7 -fPIC -arch x86_64 -Wa,--noexecstack -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"~/.linuxbrew/etc/openssl@1.1\"" -DENGINESDIR="\"~/.linuxbrew/Cellar/openssl@1.1/1.1.1d/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG  -c -o crypto/bn/x86_64-mont.o crypto/bn/x86_64-mont.s
CC="gcc-7" /usr/bin/perl crypto/bn/asm/x86_64-mont5.pl macosx crypto/bn/x86_64-mont5.s
gcc-7 -fPIC -arch x86_64 -Wa,--noexecstack -O3 -Wall -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"~/.linuxbrew/etc/openssl@1.1\"" -DENGINESDIR="\"~/.linuxbrew/Cellar/openssl@1.1/1.1.1d/lib/engines-1.1\"" -D_REENTRANT -DNDEBUG  -c -o crypto/bn/x86_64-mont5.o crypto/bn/x86_64-mont5.s
crypto/bn/x86_64-mont5.s: Assembler messages:
crypto/bn/x86_64-mont5.s:1211: Error: unknown pseudo-op: `.private_extern'
crypto/bn/x86_64-mont5.s:2891: Error: unknown pseudo-op: `.private_extern'
Makefile:1944: recipe for target 'crypto/bn/x86_64-mont5.o' failed
make[1]: *** [crypto/bn/x86_64-mont5.o] Error 1
make[1]: Leaving directory '/tmp/openssl@1.1-20200310-19435-1231dss/openssl-1.1.1d'
Makefile:174: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by netflash** [comment]
> If you have curl installed by system package manager, you can just uninstall the brewed one, upgrade openssl and then install brewed curl again.

I got caught into the same issue. This workaround worked for me too. 
Thanks!
