### ISSUE TITLE
m4: Can't compile

### ISSUE THREAD

**Issue by hyslion** [Homebrew/linuxbrew-core#19809]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Trying to install the `tmux` on Raspberry Pi with raspbian.
`m4` is installed as a dependency.

## What happened (include command output)

Failed to compile `m4`.

`brew gist-log m4` [output](https://gist.github.com/hyslion/35ddff45bbbeb84b43f401ec9e51a5b9)

<details>
  <summary>Command output</summary>
  <pre>
pi@raspberrypi:~ $ brew install tmux global vim
Updating Homebrew...
==> Installing dependencies for tmux: pkg-config, m4, libbsd, expat, gdbm, openssl@1.1, berkeley-db, perl, autoconf, automake, bison, gpatch, ncurses, readline, zlib, sqlite, xz, bzip2, libffi, python, sphinx-doc, cmake, help2man, gettext, flex, doxygen, libtool, libevent and utf8proc
==> Installing tmux dependency: pkg-config
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
Already downloaded: /home/pi/.cache/Homebrew/downloads/5bdbf3b3fdadaf72744884b98b74a2ff887bd63a20b246f811a222a146ad7b64--pkg-config-0.29.2.tar.gz
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/pkg-config/0.29.2_1 --disable-host-tool --with-internal-glib --with-pc-path=/home/linuxbrew/.linuxbrew/lib/pkgconfig:/home/linuxbrew/.linuxbrew/share/pk
==> make
==> make check
==> make install
🍺  /home/linuxbrew/.linuxbrew/Cellar/pkg-config/0.29.2_1: 11 files, 655.8KB, built in 2 minutes 30 seconds
==> Installing tmux dependency: m4
==> Downloading https://ftp.gnu.org/gnu/m4/m4-1.4.18.tar.xz
Already downloaded: /home/pi/.cache/Homebrew/downloads/bb74c92bda9bdc32be0653ca50751920ff35cfe8f329499d0bea86fbe66ce580--m4-1.4.18.tar.xz
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/m4/1.4.18
==> make
Last 15 lines from /home/pi/.cache/Homebrew/Logs/m4/02.make:
  #error "Please port gnulib freadahead.c to your platform! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
   ^~~~~
make[3]: *** [Makefile:1915: freadahead.o] Error 1
make[3]: *** Waiting for unfinished jobs....
fseeko.c: In function 'rpl_fseeko':
fseeko.c:110:4: error: #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
   #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
    ^~~~~
make[3]: *** [Makefile:1915: fseeko.o] Error 1
make[3]: Leaving directory '/tmp/m4-20200310-22141-1b3u3mp/m4-1.4.18/lib'
make[2]: *** [Makefile:1674: all] Error 2
make[2]: Leaving directory '/tmp/m4-20200310-22141-1b3u3mp/m4-1.4.18/lib'
make[1]: *** [Makefile:1572: all-recursive] Error 1
make[1]: Leaving directory '/tmp/m4-20200310-22141-1b3u3mp/m4-1.4.18'
make: *** [Makefile:1528: all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

pi@raspberrypi:~ $
  </pre>
</details>

## What you expected to happen

`m4` must be built successfully.

I think `m4` needs this [patch](http://git.openembedded.org/openembedded-core/tree/meta/recipes-devtools/m4/m4/m4-1.4.18-glibc-change-work-around.patch) when `glibc>=2.28`. 
Actually, I've tried this patch with [this modified formulae](https://gist.github.com/hyslion/ad7add2b2aa19850c34185cff2b81ff8).

## Step-by-step reproduction instructions (by running `brew install` commands)

Just run `brew install m4`.

**Comment by studyentwickler** [comment]
It happens by me if I try to install maven, because of this dependency I cannot install maven

**Comment by jonchang** [comment]
```
CPU: quad-core 32-bit arm
Kernel: Linux 4.19.97-v7l+ armv7l GNU/Linux
OS: Raspbian GNU/Linux 10 (buster) (buster)
```

This is not [a supported configuration](https://docs.brew.sh/Homebrew-on-Linux#arm). Please open pull requests to fix issues you encounter in lieu of filing issues.

**Comment by hyslion** [comment]
Thanks.
