### ISSUE TITLE
fselect: Request for a bottle

### ISSUE THREAD

**Issue by develop7** [Homebrew/linuxbrew-core#19867]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] checked that there aren't other open issues for the same formula bottle request?
- [x] does the FORMULA not have the `bottle` block?
- [x] ran `brew install FORMULA` and it succeeded?

Please update bottle for `fselect-0.6.9` which hasn't been built for some reason

**Comment by issyl0** [comment]
Thanks for the nudge. Doing this in https://github.com/Homebrew/linuxbrew-core/runs/512372253?check_suite_focus=true. Let's see how it goes...

**Comment by issyl0** [comment]
[It worked](https://github.com/Homebrew/linuxbrew-core/commit/336c13a54c478e3b5ae4a468773de119b96a96e2)!

**Comment by develop7** [comment]
Wonder why didn't it work before and how to prevent breaking it in the future?

**Comment by dawidd6** [comment]
It probably got lost between the merges, happens sometimes. We now have errors reporting configured on CI, so should be easier to track failures.
