### ISSUE TITLE
lv command warns that gzcat is an unknown command when treating a gzipped file 

### ISSUE THREAD

**Issue by kkdd** [Homebrew/linuxbrew-core#19938]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

```console
$ brew info lv
lv: stable 4.51 (bottled)
Powerful multi-lingual file viewer/grep
 :
 :
$ brew cat lv
 :
 :
  def install
    # zcat doesn't handle gzip'd data on OSX.
    # Reported upstream to nrt@ff.iij4u.or.jp
    inreplace "src/stream.c", 'gz_filter = "zcat"', 'gz_filter = "gzcat"'
 :
 :
$ brew install lv
$ lv example.txt.gz
gzcat: No such file or directory
```

## What happened (include command output)

The above warns that ```gzcat is an unknown command```.

## What you expected to happen

```lv example.txt.gz``` should use ```zcat``` for Linux and be, therefore, equivalent to ```zcat example.txt.gz | lv```.

**Comment by iMichka** [comment]
Fixed by #20086
