### ISSUE TITLE
swagger-codegen takes Exception

### ISSUE THREAD

**Issue by jkt628** [Homebrew/linuxbrew-core#19979]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

trying in install swagger-codegen on Fedora 30 and latest Ubuntu in order to generate openAPI specified  server.

## What happened (include command output)

a whole bunch of packages were installed successfully but then failed with error below.

<details>
  <summary>Command output</summary>
  <pre>
Error: An exception occurred within a child process:
  NotImplementedError: NotImplementedError
  </pre>
</details>

## What you expected to happen

success, profit!

## Step-by-step reproduction instructions (by running `brew install` commands)

```bash
brew install swagger-codegen
```

**Comment by jkt628** [comment]
https://gist.github.com/fbe9b98989d8d677f71590414183d289

**Comment by dawidd6** [comment]
Too few details given, can't really tell what's wrong. Please include the whole output.

**Comment by jkt628** [comment]
unfortunately, that **is** all the output.

**Comment by rwhogg** [comment]
I tried this out myself - looks like it's the call to `Language::Java.java_home_cmd` that raises the exception (a `NotImplementedError`)

**Comment by iMichka** [comment]
Looks like we made no progress on this and it is on our really low priority list. Sorry we could not help you further. I'll close this issues as nobody is currently working on this.

**Comment by bluewolf26** [comment]
hello guys ! I have the exact same issue but there is no documentation on the web to solve it ... any idea how to fix that ?
