### ISSUE TITLE
Linuxbrew install mpv "Error: undefined method `installed?' for OS::Mac::Xcode:Module"

### ISSUE THREAD

**Issue by humboldtux** [Homebrew/linuxbrew-core#20119]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs mpv`
Error: No logs.

## What you were trying to do (and why)

i tried to install mpv on Debian 10

## What happened (include command output)

brew install mpv
<details>
  <summary>Command output</summary>
  <pre>

Error: undefined method `installed?' for OS::Mac::Xcode:Module
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirements/xcode_requirement.rb:18:in `xcode_installed_version'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirements/xcode_requirement.rb:10:in `block in <class:XcodeRequirement>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:60:in `instance_eval'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:60:in `block in satisfied?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:191:in `yielder'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:60:in `satisfied?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:456:in `block in expand_requirements'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:222:in `block in prune?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:220:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:220:in `prune?'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:210:in `block (2 levels) in expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:338:in `each_key'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/set.rb:338:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/delegate.rb:349:in `block in delegating_block'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:209:in `block in expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:208:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/requirement.rb:208:in `expand'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1557:in `recursive_requirements'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:450:in `expand_requirements'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:388:in `compute_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:148:in `verify_deps_exist'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:141:in `prelude'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:328:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:261:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:259:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:259:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'

  </pre>
</details>

## What you expected to happen

mpv to install

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install mpv

- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

brew config
<details>
  <summary>Command output</summary>
  <pre>
HOMEBREW_VERSION: 2.2.13
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3d9cf83fec45a75af61551f53d25383abe009d31
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: c578a61401d889263a01cf13415adef059ac19b6
Core tap last commit: 10 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: N/A
Git: 2.20.1 => /bin/git
Curl: 7.64.0 => /usr/bin/curl
Kernel: Linux 4.19.0-8-amd64 x86_64 GNU/Linux
OS: Debian GNU/Linux 10 (buster) (buster)
Host glibc: 2.28
/usr/bin/gcc: 8.3.0
glibc: N/A
gcc: 5.5.0_7
xorg: 20170115_1
  </pre>
</details>

brew doctor
<details>
  <summary>Command output</summary>
  <pre>
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /bin/x86_64-linux-gnu-python3m-config
  /bin/python2-config
  /bin/libpng16-config
  /bin/python2.7-config
  /bin/x86_64-linux-gnu-python3.7m-config
  /bin/pkg-config
  /bin/x86_64-linux-gnu-python3-config
  /bin/x86_64-linux-gnu-python2.7-config
  /bin/libpng-config
  /bin/python3.7m-config
  /bin/x86_64-linux-gnu-python3.7-config
  /bin/python-config
  /bin/python3.7-config
  /bin/discover-config
  /bin/python3-config
  /bin/python3m-config
  /bin/x86_64-linux-gnu-python2-config
  /bin/x86_64-linux-gnu-pkg-config
  /bin/apt-config
  /bin/pcre-config
  /bin/x86_64-linux-gnu-python-config
  /bin/gts-config
  /bin/curl-config
  /bin/x86_64-pc-linux-gnu-pkg-config
  </pre>
</details>

**Comment by OpenA** [comment]
its bug in `Formula/mpv.rb`:
```diff
   depends_on "docutils" => :build
   depends_on "pkg-config" => :build
   depends_on "python@3.8" => :build
-  depends_on :xcode => :build
+  depends_on :xcode => :build if OS.mac?
```
