### ISSUE TITLE
Request support for ppc64le arch

### ISSUE THREAD

**Issue by Lyken17** [Homebrew/linuxbrew-core#20114]
Hi there, thanks for the contribution for supporting homebrew on Linux platforms. I am recently using powerpc (as known as ppc64le arch) for some large scale machine learning problems. As the cluster is managed it-admin, so we do not have the sudo power and have to compile everything we need. 

It would be great if homebrew can be supported so dependency just resolved by few commands! I also would like to contribute to this goal. However, I met some problems and hope can get some help here

I first clone the git repo to local 
```bash
git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
mkdir ~/.linuxbrew/bin
ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin
eval $(~/.linuxbrew/bin/brew shellenv)
```

then download the latest ruby from homepage and compile it to `$HOME/.local` (also added to environments).

Then I force homebrew to use locally compiled ruby by setting

```bash
export HOMEBREW_FORCE_VENDOR_RUBY=$(which ruby)
export HOMEBREW_RUBY_PATH=$(which ruby)
```

After doing all above jobs, I typed "brew" and got the following messages.

```bash
(base) [ligeng@service0001 ~]$ ruby -v
ruby 2.6.6p146 (2020-03-31 revision 67876) [powerpc64le-linux]
(base) [ligeng@service0001 ~]$ which ruby
~/.local/bin/ruby
(base) [ligeng@service0001 ~]$ brew
Error: Cannot find a vendored version of ruby for your ppc64le
processor on Linuxbrew!
Error: Failed to install vendor Ruby.
```

What is the difference between vendored ruby and locally compiled one? Can we use the local ruby instead of vendored one?

**Comment by iMichka** [comment]
Hi. Regarding ppc, a new project has started as a fork to support it: https://github.com/homebrew-ppc64le

We are not directly supporting ppc here, and would like to see the community grow around that fork before considering adding the changes there back to this repo.

For the portable ruby, it is a light-weight, self contained ruby, without any dependencies, which can be used on our side to bootstrap the installation for systems which do not provide ruby. We provide a mac, linux 64 and arm bottle for these, but not for PPC right now.
