### ISSUE TITLE
Syntax error for perl formula

### ISSUE THREAD

**Issue by thedrow** [Homebrew/linuxbrew-core#20123]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

HOMEBREW_VERSION: 2.2.13-48-gd6ffbf5
ORIGIN: https://github.com/Homebrew/brew
HEAD: d6ffbf5bb66e60d51e063926175e588c462aa6b3
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 2cf86849fa5b6259440d51ffd4488f580e72c0a6
Core tap last commit: 4 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: nano
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 8
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: N/A
Git: 2.26.1 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 5.3.0-46-generic x86_64 GNU/Linux
OS: Ubuntu 18.04.4 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.5.0
glibc: N/A
gcc: N/A
xorg: N/A

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/thedrow/.cache/pypoetry/virtualenvs/stories-AVEDjPRN-py3.7/bin/pre-commit-validate-config
  /home/thedrow/.pyenv/shims/python3.5-config
  /home/thedrow/.pyenv/shims/python3.8-config
  /home/thedrow/.pyenv/shims/python3.7-config
  /home/thedrow/.pyenv/shims/python3.7m-config
  /home/thedrow/.pyenv/shims/python-config
  /home/thedrow/.pyenv/shims/python3.6m-config
  /home/thedrow/.pyenv/shims/python2-config
  /home/thedrow/.pyenv/shims/python3.5m-config
  /home/thedrow/.pyenv/shims/python3.6-config
  /home/thedrow/.pyenv/shims/python3-config
  /home/thedrow/.pyenv/shims/python2.7-config

Warning: You have unlinked kegs in your Cellar.
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
  openssl@1.1

Warning: Some installed formulae are not readable:
  perl: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/perl.rb:46: syntax error, unexpected tSTRING_BEG, expecting do or '{' or '('
    args << "-Dusedevel" if build.head?
                       ^
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/perl.rb:48: dynamic constant assignment
    args << "-Dlocincpth=#{HOMEBREW_PREFIX}/include" ...
              ^~~~~~~~~~
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/perl.rb:50: syntax error, unexpected tSTRING_BEG, expecting do or '{' or '('
    system "./Configure", *args
           ^
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/perl.rb:50: syntax error, unexpected ',', expecting end
    system "./Configure", *args
                        ^
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/perl.rb:97: syntax error, unexpected end-of-input, expecting end

## What you were trying to do (and why)

Update perl.

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

Error: perl: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/perl.rb:46: syntax error, unexpected tSTRING_BEG, expecting do or '{' or '('
    args << "-Dusedevel" if build.head?
                       ^
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/perl.rb:48: dynamic constant assignment
    args << "-Dlocincpth=#{HOMEBREW_PREFIX}/include" ...
              ^~~~~~~~~~
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/perl.rb:50: syntax error, unexpected tSTRING_BEG, expecting do or '{' or '('
    system "./Configure", *args
           ^
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/perl.rb:50: syntax error, unexpected ',', expecting end
    system "./Configure", *args
                        ^
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/perl.rb:97: syntax error, unexpected end-of-input, expecting end

  </pre>
</details>

## What you expected to happen

Perl should upgrade

## Step-by-step reproduction instructions (by running `brew install` commands)

brew upgrade perl

**Comment by iMichka** [comment]
Hi. Yes sorry, I made a copy paste error while merging stuff this morning. It's fixed: 8ff4ff6

Bottles are being rebuilt by CI.
