### ISSUE TITLE
Perl upgrade gets stuck on cpan -i XML::Parser

### ISSUE THREAD

**Issue by CristianCantoro** [Homebrew/linuxbrew-core#20134]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? [output](https://gist.github.com/CristianCantoro/58b5627a2d2ec31adaaf0c03c35dd714)
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Upgrade `perl`

## What happened (include command output)

Upgrade gets stuck on `cpan -i XML::Parser`. Complete output of [brew gist-logs perl](https://gist.github.com/CristianCantoro/58b5627a2d2ec31adaaf0c03c35dd714).

<details>
  <summary>brew upgrade</summary>
  <pre>
==> Updated Formulae
perl ✔           bindfs           dune             gcc@6            ipopt            libuninameslist  nsd              operator-sdk     telegraf
ansible          cassandra        exodriver        gcc@7            jenkins          libuv            ocrmypdf         perl@5.18
apib             chapel           flow             gcc@8            kafka            libyaml          okteto           proteinortho
arduino-cli      contentful-cli   gcc@4.9          genders          kubernetes-cli   libzzip          openconnect      ruby
awscli           deno             gcc@5            influxdb         lgogdownloader   mbedtls          openjdk@11       ruby@2.6
==> Upgrading 1 outdated package:
perl 5.30.2 -> 5.30.2_1
==> Upgrading perl 5.30.2 -> 5.30.2_1 
==> Downloading https://linuxbrew.bintray.com/bottles/perl-5.30.2_1.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/f6/f6c3717740782d8d7fd0a36bc246d0bf8a59ad13c1d80b29159fd517182c2067?__gda__=exp=1587136992~hmac=f318d72c25891cb
######################################################################## 100.0%
==> Pouring perl-5.30.2_1.x86_64_linux.bottle.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/perl/5.30.2_1/bin/cpan -i XML::Parser
  </pre>
</details>

## What you expected to happen

Perl upgrade completes

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew upgrade perl`

## Additional notes

Trying to do 
```
brew reinstall -s perl
```
as suggested in https://github.com/Homebrew/linuxbrew-core/issues/4808  seems to have the same effect.

**Comment by iMichka** [comment]
> Connection timed out	...propagated at t/chunked.t line 157.

Looks like you, or the cpan server has connection issues.
I can not reproduce this, neither locally, neither on our CI.

**Comment by thedrow** [comment]
Me neither.

**Comment by CristianCantoro** [comment]
> @iMichka wrote:
> Looks like you, or the cpan server has connection issues.
> I can not reproduce this, neither locally, neither on our CI.

Ok, I am trying to `brew upgrade perl` over a VPN, and it looks like it is still getting stuck. Is there any way I could diagnose the issue further?

**Comment by CristianCantoro** [comment]
This is the logs for `brew reinstall -s perl`, I have killed it after it remained stuck for around half an hour: [`brew gist-logs perl`](https://gist.github.com/e4437e8bdc8356ea5a687614eafaed0f).

**Comment by iMichka** [comment]
Can you try without the VPN, just to be sure?

**Comment by CristianCantoro** [comment]
>> @iMichka wrote:
> Can you try without the VPN, just to be sure?

Sorry for the late reply.

I have tried with and without VPN and I always get the same result.

**Comment by CristianCantoro** [comment]
Ok, I have tried again with:
```
brew reinstall perl
```
(without `-s`)

and it completes successfully.
