### ISSUE TITLE
Libtool seems miss-configured for Linux

### ISSUE THREAD

**Issue by manuel-serrano** [Homebrew/linuxbrew-core#20199]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ x ] ran `brew update` and can still reproduce the problem? yes

I'm now to Homebrew and in order to learn it, I'm trying to develop my first formula under Linux.

## What you were trying to do (and why)

I'm trying to compile source packages that require libtool.

## What happened (include command output)

I have installed libtool with  `brew install libtool` but the installed command is not usable. 

A quick check to the libtool
script shows the usage of "@@HOMEBREW_CELLAR@@" which, I suspect,
makes sense under OS X but not Linux.

```
$ grep -n pkgauxdir /home/linuxbrew/.linuxbrew/bin/libtoolize 
57:# libraries, which are installed to $pkgauxdir under normal use, though
3406:          func_config_update "$file" "$pkgauxdir" "$aux_dir" pkgaux_header
3410:          func_install_update "$file" "$pkgauxdir" "$aux_dir" pkgaux_header
3413:          func_ltmain_update "$file" "$pkgauxdir" "$aux_dir" pkgaux_header
3417:          func_copy "$file" "$pkgauxdir" "$aux_dir" pkgaux_header
3432:      && func_ltmain_update "$file" "$pkgauxdir" . pkgaux_hdr
3444:      && func_config_update config.guess "$pkgauxdir" . pkgaux_hdr \
3445:      && func_config_update config.sub "$pkgauxdir" . pkgaux_hdr \
3446:      && func_install_update install-sh "$pkgauxdir" . pkgaux_hdr
4295:  pkgauxdir="@@HOMEBREW_CELLAR@@/libtool/2.4.6_2/share/libtool/build-aux"
4301:    pkgauxdir=$_lt_pkgdatadir/build-aux
4305:  func_nonemptydir_p pkgauxdir
4309:  extract_trace=$pkgauxdir/extract-trace
```

Line 4295 sounds suspicious to me but I must admit that I have no idea of how this
"@@HOMEBREW_CELLAR@@" prefix is further processed (if it it, of course).

<details>
  <summary>Command output</summary>
  <pre>
libtoolize:   error: $pkgauxdir is not a directory: '@@HOMEBREW_CELLAR@@/libtool/2.4.6_2/share/libtool/build-aux'
</pre>
</details>

## What you expected to happen

I would expect the following to succeed...

```
brew install libtool
./autogen.sh # of any autoconf generated file 
```

If this can help, I'm actually trying to build my Formula and for that I'm using Docker. Here is
the docker file I'm using

```
# This Dockerfile is used to test the construction of homebrew bottles
# on Linux

FROM debian

RUN apt-get update && apt-get install -y \
    sudo \
    bash \
    make \
    wget \
    git \
    curl \
    locales \
    build-essential \
    file \
    libtool

WORKDIR /tmp

sudo sh -c "echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen"
sudo locale-gen
sudo update-locale LANG=en_US.UTF-8

RUN useradd --no-log-init -m -d /home/visitor -s /bin/bash visitor
RUN mkdir -p /home/visitor && chown visitor /home/visitor
RUN echo "visitor ALL=NOPASSWD: ALL" > /etc/sudoers.d/visitor

USER visitor
ENV HOME /home/visitor
ENV LOGNAME visitor

RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

RUN echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >> /home/visitor/.profile
RUN eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
RUN brew install gcc

RUN brew tap hopbrew/hop https://gitlab.inria.fr/mserrano/hopbrew.git

STOPSIGNAL SIGINT

ENTRYPOINT ["/bin/bash"]
```

Then I loggued into that Docker container and I just issue:

```
brew update
brew install bigloo-unstable
```

Thanks in advance for your help and please let me know if I can help any further.

**Comment by jonchang** [comment]
I can't reproduce this in a Docker container. Unless you passed `--build-bottle` or otherwise disabled relocation this shouldn't happen.
