### ISSUE TITLE
llvm formula: linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found

### ISSUE THREAD

**Issue by rusdevops** [Homebrew/linuxbrew-core#20216]
please see: https://github.com/fast-ide/bootstrap/runs/617626849?check_suite_focus=true#step:3:955
```
$ brew install llvm
...
cmake: /home/developer/.linuxbrew/lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by cmake)
```

**Comment by rusdevops** [comment]
looks like you need to replace `gcc` to `gcc@9`:
https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/llvm.rb#L117

**Comment by iMichka** [comment]
Let's discuss this in the pull request: #20218
