### ISSUE TITLE
gtk+3: Bottle for 3.24.18 has pkg-config file with wrong version number

### ISSUE THREAD

**Issue by rwhogg** [Homebrew/linuxbrew-core#20221]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? **See 
https://gist.github.com/94ae2bcef3be0e7b40cde0b22cb34f4d**
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue? N/A

## What you were trying to do (and why)

Debug GTK+3, because I was trying to port the `puzzles` formula to Linux

## What happened (include command output)

The pkg-config file has, in its `Version` line, the number 3.24.17. But it should be 3.24.18

<details>
  <summary>Command output</summary>
  <pre>
wombat@laptop-laurel /home/linuxbrew/.linuxbrew/opt/gtk+3/lib/pkgconfig % brew info gtk+3
gtk+3: stable 3.24.18 (bottled)
Toolkit for creating graphical user interfaces
https://gtk.org/
/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.18 (737 files, 82.6MB) *
  Poured from bottle on 2020-04-25 at 10:47:52
From: https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/gtk+3.rb
==> Dependencies
Build: docbook ✔, docbook-xsl ✔, gobject-introspection ✔, meson ✔, ninja ✔, pkg-config ✔, libxslt ✔
Required: atk ✔, gdk-pixbuf ✔, glib ✔, gsettings-desktop-schemas ✔, hicolor-icon-theme ✔, libepoxy ✔, pango ✔, cmake ✔, at-spi2-atk ✔, cairo ✔, iso-codes ✔, libxkbcommon ✔, linuxbrew/xorg/wayland-protocols ✔, linuxbrew/xorg/xorgproto ✔
==> Analytics
install: 91 (30 days), 226 (90 days), 788 (365 days)
install-on-request: 55 (30 days), 121 (90 days), 366 (365 days)
build-error: 0 (30 days)
wombat@laptop-laurel /home/linuxbrew/.linuxbrew/opt/gtk+3/lib/pkgconfig % pkg-config --modversion --debug gtk+-3.0
Error printing enabled by default due to use of output options besides --exists, --atleast/exact/max-version or --list-all. Value of --silence-errors: 0
Error printing enabled
Adding virtual 'pkg-config' package to list of known packages
Looking for package 'gtk+-3.0'
Looking for package 'gtk+-3.0-uninstalled'
Reading 'gtk+-3.0' from file '/home/linuxbrew/.linuxbrew/lib/pkgconfig/gtk+-3.0.pc'
Parsing package file '/home/linuxbrew/.linuxbrew/lib/pkgconfig/gtk+-3.0.pc'
  line>prefix=/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.18
 Variable declaration, 'prefix' has value '/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.18'
  line>exec_prefix=${prefix}
 Variable declaration, 'exec_prefix' has value '/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.18'
  line>libdir=${prefix}/lib
 Variable declaration, 'libdir' has value '/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.18/lib'
  line>includedir=${prefix}/include
 Variable declaration, 'includedir' has value '/home/linuxbrew/.linuxbrew/Cellar/gtk+3/3.24.18/include'
  line>targets=wayland x11
 Variable declaration, 'targets' has value 'wayland x11'
  line>
  line>gtk_binary_version=3.0.0
 Variable declaration, 'gtk_binary_version' has value '3.0.0'
  line>gtk_host=x86_64-linux
 Variable declaration, 'gtk_host' has value 'x86_64-linux'
  line>
  line>Name: GTK+
  line>Description: GTK+ Graphical UI Library
  line>Version: 3.24.17
  line>Requires: gdk-3.0 atk >= 2.15.1  cairo >= 1.14.0 cairo-gobject >= 1.14.0 gdk-pixbuf-2.0 >= 2.30.0 gio-2.0 >= 2.57.2
  line>Requires.private: atk atk-bridge-2.0 wayland-client >= 1.14.91 wayland-protocols >= 1.14 xkbcommon >= 0.2.0 wayland-cursor >= 1.14.91 wayland-egl epoxy >= 1.4 fribidi >= 0.19.7 pangoft2 gio-unix-2.0 >= 2.57.2
  line>Libs: -L${libdir} -lgtk-3 
  line>Cflags: -I${includedir}/gtk-3.0 
Path position of 'gtk+-3.0' is 1
Adding 'gtk+-3.0' to list of known packages
3.24.17
  </pre>
</details>

## What you expected to happen

`pkg-config` should output version 3.24.18.

## Step-by-step reproduction instructions (by running `brew install` commands)

```bash
% brew install gtk+3
% /home/linuxbrew/.linuxbrew/bin/pkg-config --debug --modversion gtk+-3.0
```

I checked the bottle with a `wget` - it seems like the wrong version number is hardcoded in the bottle.

**Comment by rwhogg** [comment]
Note that all 8 pkg-config files in that directory seem to have the same issue:

```
wombat@laptop-laurel /home/me/tmp/repro/gtk+3/3.24.18/lib/pkgconfig % grep -r 3.24.17
gdk-wayland-3.0.pc:Version: 3.24.17
gdk-x11-3.0.pc:Version: 3.24.17
gail-3.0.pc:Version: 3.24.17
gtk+-3.0.pc:Version: 3.24.17
gtk+-wayland-3.0.pc:Version: 3.24.17
gtk+-x11-3.0.pc:Version: 3.24.17
gtk+-unix-print-3.0.pc:Version: 3.24.17
gdk-3.0.pc:Version: 3.24.17
```

**Comment by rwhogg** [comment]
Turns out that this is an upstream issue and affects macOS as well: https://gitlab.gnome.org/GNOME/gtk/-/issues/2632

That page says something interesting: that gtk 3 releases are built with autotools. Not sure what that should mean from Homebrew's perspective on what build system to use.

**Comment by iMichka** [comment]
I have seen this in the failed `wxpython` build but did not investigate more: #20015

Should we try to build gtk 3 with auto tools instead of meson?

**Comment by rwhogg** [comment]
> Should we try to build gtk 3 with auto tools instead of meson?

I guess so. https://developer.gnome.org/gtk3/stable/gtk-building.html mentions the usual `configure, make, make install` but does not mention Meson at all. Likewise with the INSTALL file in the 3.24.18 source release.

I guess they'll be moving to Meson when GTK 4 gets a stable release - if you look at [the mainline branch on the GH repo](https://github.com/gnome/gtk) you'll see that they've removed files like `autogen.sh` and `configure.ac`. It would be mildly unfortunate that the two formulae diverge, but it could be worse I suppose.

**Comment by rwhogg** [comment]
Any suggestions for actions on my part? I could submit a version of this issue upstream, or make an upstream PR to switch back to autotools, or even just add an `inreplace` on the Meson script.

There's no real urgency to this for me - if you want to handle it yourself or just not worry about it for now, either's fine with me, I can work around it locally if necessary.

**Comment by jonchang** [comment]
@tschoonj do you think that we should migrate gtk+3 build to autotools vs meson, given these issues?

**Comment by iMichka** [comment]
Yes, if upstream does not mention meson, I would like to try the other build toolchain out.

**Comment by tschoonj** [comment]
Hmm, no I would prefer to stick with meson. GNOME has deprecated autotools across all of their projects, and most don't even support autotools anymore. The upcoming Gtk+4 won't do so either.

That being said, I am aware that the Gtk+ releases have lately had some issues with getting the correct version in. This was supposed to be fixed in Homebrew/homebrew-core#53892, but they forgot to include the test in the tarball that was supposed to confirm that the version was correct, thereby breaking the build... Anyway this should not happen anymore in future releases (see https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/1723 and https://gitlab.gnome.org/GNOME/gtk/-/issues/2669).

Since the next release may be a couple weeks from now, I will open a PR in Homebrew with a patch for the current version of gtk+3, which should fix the pkg-config file.

**Comment by iMichka** [comment]
Cool, makes sense to me :)

**Comment by rwhogg** [comment]
Sounds like a good solution to me too. Thanks Tom!

**Comment by roccqqck** [comment]
centos:8
I did use ```dnf install make``` before
but

```
brew install pkg-config
```
```
==> ./configure --prefix=/root/.linuxbrew/Cellar/pkg-config/0.29.2_4 --disable-host-tool --with-internal-glib --with-pc-path=/root/.linuxbrew/lib/pkgconfig:/root/.linuxbrew/share
==> make
Last 15 lines from /root/.cache/Homebrew/Logs/pkg-config/02.make:
2020-05-02 05:58:45 +0000

make

/root/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/make: line 19: which: command not found
/root/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/make: line 25: exec: : not found

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
gtk+3: Bottle for 3.24.18 has pkg-config file with wrong version number https://github.com/Homebrew/linuxbrew-core/issues/20221
```

**Comment by iMichka** [comment]
This is unrelated to this issue. Please install the `Development Tools`, as explained in the documentation, and as explained by the homebrew installer: https://docs.brew.sh/Homebrew-on-Linux#fedora-centos-or-red-hat

**Comment by iMichka** [comment]
The original issue has been fixed.
