### ISSUE TITLE
qt: Request for a bottle

### ISSUE THREAD

**Issue by tseemann** [Homebrew/linuxbrew-core#20261]
qt (5.14.1_1) < 5.14.2

- [X] checked that there aren't other open issues for the same formula bottle request?
- [X] does the FORMULA not have the `bottle` block?
- [ ] ran `brew install FORMULA` and it succeeded?

**Comment by iMichka** [comment]
Yes, GitHub actions has an issue with disk space. I opened a pull request here: #20250, let's continue the discussion there.

**Comment by iMichka** [comment]
I am working on this

**Comment by iMichka** [comment]
Weird; the issue was closed but the stale bot added a label nevertheless :D
