### ISSUE TITLE
binutils: failed to compile on CentOS 7.8 due to missing texinfo

### ISSUE THREAD

**Issue by runlevel5** [Homebrew/linuxbrew-core#20279]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install binutils with `brew install binutils` on CentOS 7.8

## What happened (include command output)

Error with `make` step

<details>
  <summary>Command output</summary>
  <pre>

make[4]: Entering directory `/tmp/binutils-20200501-15063-101z3vk/binutils-2.34/gprof'
/tmp/binutils-20200501-15063-101z3vk/binutils-2.34/missing: line 81: makeinfo: command not found
make[4]: Entering directory `/tmp/binutils-20200501-15063-101z3vk/binutils-2.34/gold/testsuite'
/usr/bin/make  all-am
make[4]: Leaving directory `/tmp/binutils-20200501-15063-101z3vk/binutils-2.34/gprof'
WARNING: 'makeinfo' is missing on your system.
         You should only need it if you modified a '.texi' file, or
         any other file indirectly affecting the aspect of the manual.
         You might want to install the Texinfo package:
         <http://www.gnu.org/software/texinfo/>
         The spurious makeinfo call might also be the consequence of
         using a buggy 'make' (AIX, DU, IRIX), in which case you might
         want to install GNU make:
         <http://www.gnu.org/software/make/>
make[3]: Leaving directory `/tmp/binutils-20200501-15063-101z3vk/binutils-2.34/gprof'
make[2]: Leaving directory `/tmp/binutils-20200501-15063-101z3vk/binutils-2.34/gprof'
touch addr2line.1
perl ../../etc/texi2pod.pl -I "." -I "../../libiberty" -I "../../bfd/doc" -I ../../bfd/doc -Dman -Daddr2line < ./binutils.texi > addr2line.pod
make[3]: *** [binutils.info] Error 127
make[3]: *** Waiting for unfinished jobs....
make[5]: Entering directory `/tmp/binutils-20200501-15063-101z3vk/binutils-2.34/gold/testsuite'
make[5]: Nothing to be done for `all-am'.
make[5]: Leaving directory `/tmp/binutils-20200501-15063-101z3vk/binutils-2.34/gold/testsuite'
make[4]: Leaving directory `/tmp/binutils-20200501-15063-101z3vk/binutils-2.34/gold/testsuite'
./sysinfo -d <./sysroff.info >sysroff.h
make[4]: Entering directory `/tmp/binutils-20200501-15063-101z3vk/binutils-2.34/gold'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory `/tmp/binutils-20200501-15063-101z3vk/binutils-2.34/gold'
make[3]: Leaving directory `/tmp/binutils-20200501-15063-101z3vk/binutils-2.34/gold'
make[2]: Leaving directory `/tmp/binutils-20200501-15063-101z3vk/binutils-2.34/gold'
(pod2man --center="GNU Development Tools" --release="binutils-2.34" --section=1 addr2line.pod | sed -e '/^.if n .na/d' > addr2line.1.T$$ && \
	mv -f addr2line.1.T$$ addr2line.1) || (rm -f addr2line.1.T$$ && exit 1)
rm -f addr2line.pod
make[3]: Leaving directory `/tmp/binutils-20200501-15063-101z3vk/binutils-2.34/binutils/doc'
make[2]: *** [info-recursive] Error 1
make[2]: Leaving directory `/tmp/binutils-20200501-15063-101z3vk/binutils-2.34/binutils'
make[1]: *** [all-binutils] Error 2
make[1]: Leaving directory `/tmp/binutils-20200501-15063-101z3vk/binutils-2.34'
make: *** [all] Error 2

  </pre>
</details>

## What you expected to happen

No error

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install binutils`

**Comment by runlevel5** [comment]
This formula compilation failed due to missing `texinfo`. I think the formula should depend on `texinfo` formula. I am happy to submit new PR.

**Comment by runlevel5** [comment]
I am happy to submit a patch to address this issue

**Comment by sjackman** [comment]
Moving this discussion to PR #20425.
