### ISSUE TITLE
Formulae with CI disk space issues

### ISSUE THREAD

**Issue by iMichka** [Homebrew/linuxbrew-core#20283]
These formulae do not build anymore due to disk space issues:

packer
qt -> + needs a rebuild: qbs, treefrog

**Comment by dawidd6** [comment]
`packer` is fine now: https://github.com/Homebrew/linuxbrew-core/commit/e089372b1483441b8da3e92cb4da502dc03758fd

**Comment by qjayforever25** [comment]
qt -> + needs a rebuild: qbs, treefrog

**Comment by iMichka** [comment]
Disk space issues are gone for now, GitHub fixed their images/machines.
