### ISSUE TITLE
Error from installing open-mpi 

### ISSUE THREAD

**Issue by hochunlin** [Homebrew/linuxbrew-core#20281]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? 
Please see https://gist.github.com/hochunlin/72d9e1787a362075c0675d06f782b888
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to install `open-mpi`, which is a dependency to `mumps`

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
$ HOMEBREW_CC=gcc-9 HOMEBREW_CXX=g++-9 brew install openmpi
Updating Homebrew...
==> Downloading https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.3.tar.
Already downloaded: /home/rcf-40/hochunli/.cache/Homebrew/downloads/db72f3ca347dff643ecde8881e24754dd9027857a1fd844e0b2b20b9b64ee7d0--openmpi-4.0.3.tar.bz2
==> ./configure --prefix=/staging/ch3/hochunli/homebrew/Cellar/open-mpi/4.0.3 --enable
Last 15 lines from /home/rcf-40/hochunli/.cache/Homebrew/Logs/open-mpi/01.configure:
checking how to run the C++ preprocessor... g++-9 -E
checking for the C++ compiler vendor... gnu
checking if g++-9 supports -finline-functions... yes
configure: WARNING:  -finline-functions has been added to CXXFLAGS
checking if C and C++ are link compatible... no
**********************************************************************
* It appears that your C++ compiler is unable to link against object
* files created by your C compiler.  This generally indicates either
* a conflict between the options specified in CFLAGS and CXXFLAGS
* or a problem with the local compiler installation.  More
* information (including exactly what command was given to the
* compilers and what error resulted when the commands were executed) is
* available in the config.log file in this directory.
**********************************************************************
configure: error: C and C++ compilers are not link compatible.  Can not continue.

READ THIS: https://docs.brew.sh/Troubleshooting
  </pre>
</details>

## What you expected to happen

Successfully install `open-mpi`

## Step-by-step reproduction instructions (by running `brew install` commands)

`HOMEBREW_CC=gcc-9 HOMEBREW_CXX=g++-9 brew install openmpi`

**Comment by jeinson** [comment]
I am having the same issue. Has anybody found a solution?
