### ISSUE TITLE
NameError: uninitialized constant OS::Mac::CLT

### ISSUE THREAD

**Issue by Alpheron** [Homebrew/linuxbrew-core#20284]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [Yes ] ran `brew update` and can still reproduce the problem?
- [Yes ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [Yes] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to download Python 3.6 for my Ubuntu machine because of its support and compatibility with Tensorflow and OpenCV. 

## What happened (include command output)

It ended up erroring out after downloading Python 3.6 and said that there was an uninitialized Mac OS Constant.

<details>
  <summary>Command output</summary>
  <pre>

 Warning: Unsupported installation from a commit URL!
Consider using `brew extract python ...` instead!"
This will extract your desired python version to a stable tap instead of
installing from a commit URL that cannnot receive updates or fixes!

######################################################################## 100.0%
Warning: --ignore-dependencies is an unsupported Homebrew developer flag!
Adjust your PATH to put any preferred versions of applications earlier in the
PATH rather than using this unsupported flag!

Warning: python 3.7.7_1 is available and more recent than version 3.6.5_1.
==> Downloading https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tar.xz
Already downloaded: /home/tinku/.cache/Homebrew/downloads/84c11d22223143b4c2b0eba0709975feecf8f04d24909a0a8534afec604195a1--Python-3.6.5.tar.xz
Error: An exception occurred within a child process:
  NameError: uninitialized constant OS::Mac::CLT

  </pre>
</details>

## What you expected to happen

I would expect brew to download Python 3.6 and say successfully downloaded.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install --ignore-dependencies https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb`

**Comment by dawidd6** [comment]
You are pulling the commit from `homebrew-core`, yet you opened an issue in `linuxbrew-core`.

Try pulling the commit from this repo, but with Linux fixes applied.

**Comment by Alpheron** [comment]
Pulling from the linuxbrew-core repository ends up working
