### ISSUE TITLE
harfbuzz 2.6.5_1 failed to build on Linux Mint 19.3 Tricia

### ISSUE THREAD

**Issue by mlavi** [Homebrew/linuxbrew-core#20312]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
[https://gist.github.com/696a3f3681853d05a8b6d81282691331](https://gist.github.com/696a3f3681853d05a8b6d81282691331)

## What you were trying to do (and why)

Upgrading 1 outdated package:
harfbuzz 2.6.5 -> 2.6.5_1

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

==> Upgrading harfbuzz 2.6.5 -> 2.6.5_1 
==> Downloading https://github.com/harfbuzz/harfbuzz/releases/download/2.6.5/harfbuzz-2.6.5.tar.xz
Already downloaded: /home/mark/.cache/Homebrew/downloads/85d3db2dddf73273f58aa74bb6e0e6603ec515b77329dd65c23e41732eac69ee--harfbuzz-2.6.5.tar.xz
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/harfbuzz/2.6.5_1 --enable-introspection=yes --enable-static --with-cairo=yes --with-coretext=no --with-freetype=yes --with-gli
==> make install
Last 15 lines from /home/mark/.cache/Homebrew/Logs/harfbuzz/02.make:
make[3]: *** [libharfbuzz_la-hb-aat-layout.lo] Error 1
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/linuxbrew-core/issues> for instructions.
Makefile:2130: recipe for target 'libharfbuzz_la-hb-blob.lo' failed
make[3]: *** [libharfbuzz_la-hb-blob.lo] Error 1
make[3]: Leaving directory '/tmp/harfbuzz-20200508-11216-17v2vi4/harfbuzz-2.6.5/src'
Makefile:3041: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/tmp/harfbuzz-20200508-11216-17v2vi4/harfbuzz-2.6.5/src'
Makefile:3467: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/tmp/harfbuzz-20200508-11216-17v2vi4/harfbuzz-2.6.5/src'
Makefile:537: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

==> Checking for dependents of upgraded formulae...
==> No dependents found!

  </pre>
</details>

## What you expected to happen

Successful compile or better yet, a keg.

## Step-by-step reproduction instructions (by running `brew install` commands)
<pre>
$ brew install harfbuzz
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
pycharm-with-anaconda-plugin                                                                 transocks

Error: harfbuzz 2.6.5 is already installed
To upgrade to 2.6.5_1, run `brew upgrade harfbuzz`.

$ brew upgrade harfbuzz
</pre>

`brew upgrade harfbuzz` yields same output as above...

I removed the cached download file and still have the same issue, which is:

```
  CXX      libharfbuzz_la-hb-aat-map.lo
In file included from hb-static.cc:27:0,
                 from main.cc:335:
hb.hh:492:3: internal compiler error: Illegal instruction
   return x >= 0 ? floor ((double) x + .5) : ceil ((double) x - .5);
   ^
Please submit a full bug report,
with preprocessed source if appropriate.

```
Thanks for your help!

**Comment by jonchang** [comment]
> CPU: quad-core 64-bit unknown_0x10_0x4

What CPU are you using?

**Comment by iMichka** [comment]
I rebuilt a bottle. This should solve it for you if you installed into `home/linuxbrew/.linuxbrew`. If not you'll have to debug this by yourself.

**Comment by mlavi** [comment]
@jonchang AMD...

$ cat /proc/cpuinfo
<pre>processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 4
model name	: AMD Phenom(tm) II X4 955 Processor
stepping	: 3
microcode	: 0x10000c8
cpu MHz		: 3200.000
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs		: tlb_mmatch apic_c1e fxsave_leak sysret_ss_attrs null_seg amd_e400 spectre_v1 spectre_v2
bogomips	: 6421.76
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate
</pre>

**Comment by mlavi** [comment]
@iMichka Thank you, it works! :)
