### ISSUE TITLE
OpenSSL Install Fails on Docker Node Image

### ISSUE THREAD

**Issue by asennyey** [Homebrew/linuxbrew-core#20330]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ ] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install OpenSSL in a CI environment, node:latest image Docker. Only other error is brew doctor, but I am trying to use Linuxbrew in a different folder than /home/ due to caching restraints. This was working with the release last week, I had no issues installing or using the openssl formula last Tuesday.

## What happened (include command output)

Running 'brew install openssl' causes fatal error.
https://gist.github.com/asennyey/aab9a3aae3391d4f335990bebe0b6a41

<details>
  <summary>Command output</summary>
  <pre>

  root@734919969a66:/test# brew install openssl
/test/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh: line 4: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/test/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh: line 4: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/test/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.sh: line 4: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
==> Downloading https://www.openssl.org/source/openssl-1.1.1g.tar.gz
Already downloaded: /root/.cache/Homebrew/downloads/1178a9e293b3f8231b3a09a91b1a4cc8bf765526148a37a720ba4a89d49e3aff--openssl-1.1.1g.tar.gz
==> Downloading https://www.openssl.org/source/openssl-1.1.1g.tar.gz
Already downloaded: /root/.cache/Homebrew/downloads/1178a9e293b3f8231b3a09a91b1a4cc8bf765526148a37a720ba4a89d49e3aff--openssl-1.1.1g.tar.gz
tar: /root/.cache/Homebrew/downloads/4a5728e2132a470084886ad6e6278c6b23584e314ee60dcd57ea679202d5da4a--Test-Harness-3.42.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Error: Failure while executing; `tar xof /root/.cache/Homebrew/downloads/4a5728e2132a470084886ad6e6278c6b23584e314ee60dcd57ea679202d5da4a--Test-Harness-3.42.tar.gz -C /tmp/d20200511-5123-k3f9zj` exited with 2. Here's the output:
tar: /root/.cache/Homebrew/downloads/4a5728e2132a470084886ad6e6278c6b23584e314ee60dcd57ea679202d5da4a--Test-Harness-3.42.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

  </pre>
</details>

## What you expected to happen

No failure on installation. This was working last week, I don't know what changed.

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install openssl (on a docker image with node:latest)

**Comment by iMichka** [comment]
> Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this unsupported configuration.
