### ISSUE TITLE
brew install perl failed

### ISSUE THREAD

**Issue by gigi206** [Homebrew/linuxbrew-core#20331]
Cf issue https://github.com/Homebrew/brew/issues/7524

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install Perl or PHP (that depends on Perl)

## What happened (include command output)

`make` is not installed in the Perl dependencies and is required:
```
$ brew install make
```

Post-installation of Perl failed:
<details>
  <summary>brew install perl</summary>
  <pre>
==> Installing dependencies for perl: gdbm and berkeley-db
==> Installing perl dependency: gdbm
==> Downloading https://linuxbrew.bintray.com/bottles/gdbm-1.18.1.x86_64_linux.bottle.1.tar.gz
==> Downloading from https://akamai.bintray.com/80/80fc4bdfef26e3df4c1f7390e1169d32935faa69f00888318bf0ed8321798aad?__gda__=exp=1589221436~hmac=6e7ff012eac422b91394ef9320c7d6aa17836caa3030d3
######################################################################## 100.0%
==> Pouring gdbm-1.18.1.x86_64_linux.bottle.1.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/gdbm/1.18.1: 40 files, 1MB
==> Installing perl dependency: berkeley-db
==> Downloading https://linuxbrew.bintray.com/bottles/berkeley-db-18.1.32_1.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/a6/a61c738d8e2597fe1e662c1eda22005d1c846b2dee3516c89506c16d09fd0012?__gda__=exp=1589221438~hmac=e4207f858df4ff9a1eb8488def999164f63148f71c0a56
######################################################################## 100.0%
==> Pouring berkeley-db-18.1.32_1.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/berkeley-db/18.1.32_1: 5,673 files, 128.3MB
==> Installing perl
==> Downloading https://linuxbrew.bintray.com/bottles/perl-5.30.2_1.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/f6/f6c3717740782d8d7fd0a36bc246d0bf8a59ad13c1d80b29159fd517182c2067?__gda__=exp=1589221495~hmac=e4fd1018299a7636443b70f9ef5d74e83f74c5cc2905cf
######################################################################## 100.0%
==> Pouring perl-5.30.2_1.x86_64_linux.bottle.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/perl/5.30.2_1/bin/cpan -i XML::Parser
Last 15 lines from /home/gigix/VSCode-Anywhere/apps/vscode-anywhere/home/.cache/Homebrew/Logs/perl/post_install.01.cpan:

    EXPATLIBPATH=...  To set the directory in which to find libexpat

    EXPATINCPATH=...  To set the directory in which to find expat.h

For example:

    perl Makefile.PL EXPATLIBPATH=/home/me/lib EXPATINCPATH=/home/me/include

Note that if you build against a shareable library in a non-standard location
you may (on some platforms) also have to set your LD_LIBRARY_PATH environment
variable at run time for perl to find the library.

No 'Makefile' created  TODDR/XML-Parser-2.46.tar.gz
  /home/linuxbrew/.linuxbrew/Cellar/perl/5.30.2_1/bin/perl Makefile.PL -- NOT OK
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall perl`
==> Caveats
By default non-brewed cpan modules are installed to the Cellar. If you wish
for your modules to persist across updates we recommend using `local::lib`.

You can set that up like this:
  PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
  echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"' >> ~/.bash_profile
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/perl/5.30.2_1: 2,451 files, 70.3MB
==> Caveats
==> perl
By default non-brewed cpan modules are installed to the Cellar. If you wish
for your modules to persist across updates we recommend using `local::lib`.

You can set that up like this:
  PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
  echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"' >> ~/.bash_profile
  </pre>
</details>

```
$ echo $?
1
```

expat is installed:
```
$ brew info expat
expat: stable 2.2.9 (bottled), HEAD
XML 1.0 parser
https://libexpat.github.io/
/home/linuxbrew/.linuxbrew/Cellar/expat/2.2.9 (18 files, 757KB) *
  Poured from bottle on 2020-05-03 at 12:53:15
From: https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/expat.rb
==> Dependencies
Required: libbsd ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 7,915 (30 days), 22,655 (90 days), 94,099 (365 days)
install-on-request: 48 (30 days), 62 (90 days), 311 (365 days)
build-error: 0 (30 days)
```

```
$ brew postinstall perl
==> Postinstalling perl
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall perl`
```

Try to force with expat variables env:
```
EXPATLIBPATH=/home/linuxbrew/.linuxbrew/Cellar/expat/2.2.9/lib EXPATINCPATH=/home/linuxbrew/.linuxbrew/Cellar/expat/2.2.9/include cpan -i XML::Parser
Loading internal logger. Log::Log4perl recommended for better logging
Reading '/home/gigix/VSCode-Anywhere/apps/vscode-anywhere/home/.cpan/Metadata'
  Database was generated on Mon, 11 May 2020 17:17:03 GMT
Running install for module 'XML::Parser'
Checksum for /home/gigix/VSCode-Anywhere/apps/vscode-anywhere/home/.cpan/sources/authors/id/T/TO/TODDR/XML-Parser-2.46.tar.gz ok
'YAML' not installed, will not store persistent state
Configuring T/TO/TODDR/XML-Parser-2.46.tar.gz with Makefile.PL

Expat must be installed prior to building XML::Parser and I can't find
it in the standard library directories. Install 'expat-devel' (or
'libexpat1-dev') package with your OS package manager. See 'README'.

Or you can download expat from:

http://sourceforge.net/projects/expat/

If expat is installed, but in a non-standard directory, then use the
following options to Makefile.PL:

    EXPATLIBPATH=...  To set the directory in which to find libexpat

    EXPATINCPATH=...  To set the directory in which to find expat.h

For example:

    perl Makefile.PL EXPATLIBPATH=/home/me/lib EXPATINCPATH=/home/me/include

Note that if you build against a shareable library in a non-standard location
you may (on some platforms) also have to set your LD_LIBRARY_PATH environment
variable at run time for perl to find the library.

No 'Makefile' created  TODDR/XML-Parser-2.46.tar.gz
  /home/linuxbrew/.linuxbrew/Cellar/perl/5.30.2_1/bin/perl Makefile.PL -- NOT OK
```

Install the OS `libexpat1-devel` package:
```
$ sudo apt install libexpat1-dev
```

Post-install fails again:
```
$ brew postinstall perl
==> Postinstalling perl
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall perl`
```

But reinstalling the package works:
```
$ brew reinstall perl
==> Reinstalling perl 
==> Downloading https://linuxbrew.bintray.com/bottles/perl-5.30.2_1.x86_64_linux.bottle.tar.gz
Already downloaded: /home/gigix/VSCode-Anywhere/apps/vscode-anywhere/home/.cache/Homebrew/downloads/84c05b70d6d6d052725158edc193c72d2a8f28703f6cab639286d98e4f0e22b1--perl-5.30.2_1.x86_64_linux.bottle.tar.gz
==> Pouring perl-5.30.2_1.x86_64_linux.bottle.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/perl/5.30.2_1/bin/cpan -i XML::Parser
==> /home/linuxbrew/.linuxbrew/Cellar/perl/5.30.2_1/bin/cpan -i XML::SAX
==> Caveats
By default non-brewed cpan modules are installed to the Cellar. If you wish
for your modules to persist across updates we recommend using `local::lib`.

You can set that up like this:
  PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
  echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"' >> ~/.bash_profile
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/perl/5.30.2_1: 2,863 files, 74MB
```

## What you expected to happen

- make must be a dependency of the Perl package
- cpan compilation must work with the brew expat library
- Install must returns 0 and 

```
$ brew config
HOMEBREW_VERSION: 2.2.16
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: c0f5a52d85d3606e7600162a9d38936ab4b46f4f
Last commit: 22 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 98e1aef569fa6ecaace258bcdc0df849c97194bd
Core tap last commit: 43 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: N/A
Git: 2.26.2 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-28-generic x86_64 GNU/Linux
OS: Ubuntu 20.04 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: N/A
glibc: N/A
gcc: 5.5.0_7
xorg: N/A
```

```
$ brew doctor
Your system is ready to brew.
```

**Comment by dawidd6** [comment]
Look at the requirements for Homebrew on Linux:

https://docs.brew.sh/Homebrew-on-Linux#debian-or-ubuntu

It states that `build-essential` package is needed on Ubuntu and this package depends on `make`, so there is no need for this formula to depend on it too.

**Comment by gigi206** [comment]
Ok, but normally perl should install without error, right?
