### ISSUE TITLE
TeX Live is outdated

### ISSUE THREAD

**Issue by galaxy001** [Homebrew/linuxbrew-core#20374]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [.] ran `brew update` and can still reproduce the problem?
- [.] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

```
brew install --force-bottle texlive
tlmgr install scheme-medium
```

## What happened (include command output)

`tlmgr` failed as cert outdated.

After manually bypass cert check, it says I need to update to Tex Live 2020.
## What you expected to happen

Install texlive 2020

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install --force-bottle texlive
tlmgr install scheme-medium
```

The date of <http://ftp.math.purdue.edu/mirrors/ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz> is `17-May-2020 18:59`, so source install should fail too.

**Comment by galaxy001** [comment]
texlive is obvious outdated as `20190406` < `20200517`.

I have manually upgrade with `tlmgr` and find the new binary linked to system libs, not brewed ones.

**Comment by sjackman** [comment]
Feel free to open a PR to update `texlive`. Try `brew edit texlive` and see https://docs.brew.sh/#contributors

**Comment by galaxy001** [comment]
In fact I tried to build from source on my machine.
However, the Chinese Internet is not friendly to international sites, thus I am unable to download files with official TeXLive install program used in `texlive.rb`.

The patch should be simple as:

```
--- Homebrew/Library/Taps/homebrew/homebrew-core/Formula/texlive.rb	2020-05-05 01:26:26.000000000 +0800
+++ texlive.rb	2020-05-19 16:16:30.202842968 +0800
@@ -2,12 +2,12 @@
   desc "TeX Live is a free software distribution for the TeX typesetting system"
   homepage "https://www.tug.org/texlive/"
   url "http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz"
-  version "20190406"
-  sha256 "c7742ea5b0bc22fe2742e9fa2bf9aeb8ff88175722fcfb2b72c00a29c06e2fc9"
+  version "20200517"
+  sha256 "2de9bc1dd70ea62ffd5fc3b827d74ea2a89c0880a7159d432cf2c5b2c7cbf623"

   bottle do
     cellar :any_skip_relocation
-    sha256 "4e24715e406a78243cc4391aabc6dc7776390b43fd57d21315a002776ea8994a" => :x86_64_linux
   end

   depends_on "wget" => :build
```

**Comment by sjackman** [comment]
Looks great! Please do open that PR, @galaxy001!
