### ISSUE TITLE
brew install llvm --HEAD on Catalina 10.15.5 failing

### ISSUE THREAD

**Issue by jpz** [Homebrew/linuxbrew-core#20453]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ X] ran `brew update` and can still reproduce the problem?
- [ X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I have been trying to install llvm from source.  I have ensured the command line tools / XCode is on the latest version.

I've repeated the failure now 3 times.

## What happened (include command output)

https://gist.github.com/jpz/22ec414ebf5f8de8c95832b74c57b401

<details>
  <summary>Command output</summary>
  <pre>
▶ time brew install llvm --HEAD
Updating Homebrew...
==> Cloning https://github.com/llvm/llvm-project.git
Updating /Users/jasonz/Library/Caches/Homebrew/llvm--git
From https://github.com/llvm/llvm-project
   205085d4c..0892a96a0  master     -> origin/master
==> Checking out branch master
Already on 'master'
Your branch is behind 'origin/master' by 85 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at 0892a96a0 AMDGPU: Optimize s_setreg_b32 to s_denorm_mode/s_round_mode
==> cmake -G Unix Makefiles .. -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra;lld;lldb;openmp;polly -DLLVM_ENABLE_RUNTIMES=compiler-rt;libcxx;libunwind -DLIBOMP_ARCH=x86_64 -DLLVM_POLLY_LI
==> make
Last 15 lines from /Users/jasonz/Library/Logs/Homebrew/llvm/02.make:
[100%] Generating /tmp/llvm-20200530-47441-1rvj6u7/llvm/build/lib/clang/11.0.0/lib/darwin/libclang_rt.cc_kext_ios.a
[100%] Built target clang_rt.cc_kext_ios
Scanning dependencies of target builtins
[100%] Built target builtins
Scanning dependencies of target compiler-rt
[100%] Built target compiler-rt
[ 85%] No install step for 'builtins'
cd /tmp/llvm-20200530-47441-1rvj6u7/llvm/build/runtimes/builtins-bins && /usr/local/Cellar/cmake/3.17.3/bin/cmake -E echo_append
cd /tmp/llvm-20200530-47441-1rvj6u7/llvm/build/runtimes/builtins-bins && /usr/local/Cellar/cmake/3.17.3/bin/cmake -E touch /tmp/llvm-20200530-47441-1rvj6u7/llvm/build/runtimes/builtins-stamps//builtins-install
[ 85%] Completed 'builtins'
cd /tmp/llvm-20200530-47441-1rvj6u7/llvm/build/runtimes && /usr/local/Cellar/cmake/3.17.3/bin/cmake -E make_directory /tmp/llvm-20200530-47441-1rvj6u7/llvm/build/runtimes/CMakeFiles
cd /tmp/llvm-20200530-47441-1rvj6u7/llvm/build/runtimes && /usr/local/Cellar/cmake/3.17.3/bin/cmake -E touch /tmp/llvm-20200530-47441-1rvj6u7/llvm/build/runtimes/CMakeFiles/builtins-complete
cd /tmp/llvm-20200530-47441-1rvj6u7/llvm/build/runtimes && /usr/local/Cellar/cmake/3.17.3/bin/cmake -E touch /tmp/llvm-20200530-47441-1rvj6u7/llvm/build/runtimes/builtins-stamps//builtins-done
[ 85%] Built target builtins
make: *** [all] Error 2  </pre>
</details>

## What you expected to happen

The build should successfully complete.

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install llvm --HEAD

**Comment by jonchang** [comment]
We do not support HEAD builds in Homebrew/core. You would have seen this message when the build failed:

> Please create pull requests instead of asking for help on Homebrew's GitHub, Discourse, Twitter or IRC.

**Comment by jpz** [comment]
Thanks for taking the time to respond, and apologies - I put this in linuxbrew-core rather than homebrew-core.   

(I didn't see a message saying HEAD was not supported btw.)

![image](https://user-images.githubusercontent.com/934340/83323399-d1b5ac00-a2a1-11ea-900a-5fa7669438e3.png)
