### ISSUE TITLE
gss_2.2-0.tar.gz have been replaced by gss_2.2-2 in the CRAN repository

### ISSUE THREAD

**Issue by lileiting** [Homebrew/linuxbrew-core#20452]
https://github.com/Homebrew/linuxbrew-core/blob/4a8e82d9eef986c65037ec6623538c6ca721bdae/Formula/r.rb#L36-L37

**Comment by jonchang** [comment]
This was fixed in https://github.com/Homebrew/homebrew-core/pull/55287
