### ISSUE TITLE
qt build error in CentOS 7 system

### ISSUE THREAD

**Issue by nir-krakauer** [Homebrew/linuxbrew-core#20468]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [ x ] ran `brew update` and can still reproduce the problem?
- [ x ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ x ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
https://gist.github.com/4bff1fd04f7ec8b46e137d4cae7363a2
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install qt (needed as a dependency for octave).

## What happened (include command output)

Building failed with a number of errors, of which the first in the `02.make` file was

<details>
  <summary>Command output</summary>
  <pre>
+ cd /tmp/qt-20200601-17738-18orm5f/qt-everywhere-src-5.14.2/config.tests/c++1z && /tmp/qt-20200601-17738-18orm5f/qt-everywhere-src-5.14.2/qtbase/bin/qmake "CONFIG -= qt debug_and_release app_bundle lib_bundle" "CONFIG += shared warn_off console single_arch" /tmp/qt-20200601-17738-18orm5f/qt-everywhere-src-5.14.2/config.tests/c++1z
+ cd /tmp/qt-20200601-17738-18orm5f/qt-everywhere-src-5.14.2/config.tests/c++1z && MAKEFLAGS= /usr/bin/gmake
> g++ -c -pipe -O2 -std=gnu++1z -w -fPIC  -I. -I/tmp/qt-20200601-17738-18orm5f/qt-everywhere-src-5.14.2/qtbase/mkspecs/linux-g++ -o main.o main.cpp
> main.cpp:8:19: fatal error: variant: No such file or directory
> compilation terminated.
> gmake: *** [main.o] Error 1

  </pre>
</details>

## What you expected to happen

Successful installation

## Step-by-step reproduction instructions (by running `brew install` commands)

  <pre>

brew install qt

  </pre>

**Comment by joa-quim** [comment]
Can confirm this. It stops with
```
Info: creating super cache file /tmp/qt-20200701-180037-ssapog/qt-everywhere-src-5.15.0/.qmake.super
Info: creating cache file /tmp/qt-20200701-180037-ssapog/qt-everywhere-src-5.15.0/.qmake.cache
ERROR: Invalid value given for boolean command line option 'xcb'.
```

**Comment by iMichka** [comment]
See #20250 for further discussion.
