### ISSUE TITLE
pipenv 2020.5.28 can't find python3.8

### ISSUE THREAD

**Issue by mlavi** [Homebrew/linuxbrew-core#20474]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs pipenv`
Error: No logs.
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)
After upgrading brew, pipenv is broken, it appears to be trying to use Python 3.8 but brew seems to still be on 3.7.7

## What happened (include command output)
<pre>$ pipenv 
/home/linuxbrew/.linuxbrew/Cellar/pipenv/2020.5.28/libexec/bin/python3.8: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

$ python3 --version && which python3
Python 3.7.7
/home/linuxbrew/.linuxbrew/bin/python3
</pre>

<details>
  <summary>Command output</summary>
  <pre>

$ brew config
HOMEBREW_VERSION: 2.3.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: 77e09fc166f5fb7197b239d5e2727ddc0791c121
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 38d5e1e6b64109d0415197260bddb41d67429d69
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit unknown_0x10_0x4
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/bin/ruby
Clang: 10.0 build (parse error)
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 5.3.0-53-generic x86_64 GNU/Linux
OS: Linux Mint 19.3 Tricia (tricia)
Host glibc: 2.27
/usr/bin/gcc: 7.5.0
glibc: N/A
gcc: 5.5.0_7
xorg: 20170115_1

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  guile@2

$ pipenv 
/home/linuxbrew/.linuxbrew/Cellar/pipenv/2020.5.28/libexec/bin/python3.8: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

$ python3 --version && which python3
Python 3.7.7
/home/linuxbrew/.linuxbrew/bin/python3
</pre>

</details>

## What you expected to happen
I expect pipenv to work, using current Python. It might need rebuilding according to https://github.com/Homebrew/linuxbrew-core/issues/20188 and https://github.com/Homebrew/linuxbrew-core/issues/6380

## Step-by-step reproduction instructions (by running `brew install` commands)

brew update && brew upgrade

**Comment by tsela** [comment]
I have the same issue, and had it too once before on April the 21st (as explained in the linked issue above). Is there anything that can be done to prevent this kind of problems happening again?

**Comment by dawidd6** [comment]
Sorry about that, we need to rebuild the bottle.

Ideally we would merge `linuxbrew-core` with `homebrew-core` and that should prevent issues like this from happening, but it requires a bit of work to get to that point. Alternatively I don't know how we can workaround the issue for now, other than just rebuilding broken bottles.

**Comment by mlavi** [comment]
Verified working, thank you!
