### ISSUE TITLE
qt 5.14.2 does not build on Linux: error: variable 'const Qt3DCore::Matrix4x4_AVX2 inverse' has initializer but incomplete type

### ISSUE THREAD

**Issue by lrineau** [Homebrew/linuxbrew-core#20487]
# Issue checklist (from the template)
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`: it only reports `Warning: python is symlinked to python3`
- [x] ran `brew gist-logs qt`: here is the link https://gist.github.com/acf9557ac419a9be993c5b55c0d2cc45

## What you were trying to do (and why)

I ran `brew update` it failed on `qt`. I pinned `qt`, then `brew update` was fine. And then I unpinned `qt`, and rerun `brew update` so that it updates only `qt`. The build failed, and here is the issue-report.

## What happened (include command output)

```
[lrineau@bonnard]~% brew upgrade                                                          
==> Upgrading 1 outdated package:
qt 5.14.1_1 -> 5.14.2
==> Upgrading qt 5.14.1_1 -> 5.14.2 
==> Downloading https://download.qt.io/official_releases/qt/5.14/5.14.2/single/qt-everywhere-src-5.14.2.tar.xz
Already downloaded: /home/lrineau/.cache/Homebrew/downloads/79e4952d6a6661213a9f89064f912877f5b6e7a3fba13c9f6462e05ecb253dfe--qt-everywhere-src-5.14.2.tar.xz
==> Patching
patching file qtwebengine/src/buildtools/config/mac_osx.pri
==> ./configure -verbose -prefix /home/linuxbrew/.linuxbrew/Cellar/qt/5.14.2 -release -opensource -confirm-license -qt-libpng -qt-libjpeg -qt-freetype -qt-pcre -nomake examples -nomake tests -pkg-config -dbus-runtime -system-xcb -
==> make
Last 15 lines from /home/lrineau/.cache/Homebrew/Logs/qt/02.make:
```
See https://gist.github.com/acf9557ac419a9be993c5b55c0d2cc45 for the log files.

## What you expected to happen

The build to terminate successfully.

## Step-by-step reproduction instructions (by running `brew install` commands)

- `brew install qt`, or
- `brew upgrade`

**Comment by iMichka** [comment]
Can you report this to https://bugreports.qt.io/ ? There is nothing we can do here.

**Comment by lrineau** [comment]
I think linuxbrew should avoid shipping version of packages that do not build. That blocks any package that depends on qt.

**Comment by iMichka** [comment]
We plan to disable the builds for everything that does not work on linux soon. This means anyway that all the reverse dependencies of qt wont build too.

`qt` is in my experience one of the hardest package to build, and is crippled with bugs at build time.   It's a shame, but we can't do much about it right now.

Pull requests with fixes are welcome though :)

**Comment by lrineau** [comment]
> We plan to disable the builds for everything that does not work on linux soon. This means anyway that all the reverse dependencies of qt wont build too.
> 
> `qt` is in my experience one of the hardest package to build, and is crippled with bugs at build time. It's a shame, but we can't do much about it right now.
> 
> Pull requests with fixes are welcome though :)

I am working on it. The build error seems to be related to the config option `-no-avx2`. I am trying to see if it is still required.

**Comment by iMichka** [comment]
Last time I tried to remove it, other parts of the code failed to compile.

We have a pull request open which tries to build binaries here: #20250
Right now I am struggling with  disk space issues within github actions. It looks like the newest qt builds eat up more than the 14 Gigabytes of disk space we have at our disposal ...

**Comment by lrineau** [comment]
https://github.com/Homebrew/homebrew-core/pull/55964
