### ISSUE TITLE
libopenmpt build error

### ISSUE THREAD

**Issue by OpenA** [Homebrew/linuxbrew-core#20570]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew install libopenmpt`

## What happened (include command output)
libopenmpt needs higher version of gcc
<details>
  <summary>Command output</summary>
  <pre>
checking for gcc-5 option to accept ISO C99... none needed
checking for gcc-5 option to accept ISO Standard C... (cached) none needed
checking whether g++-5 supports C++17 features with -std=c++17... no
checking whether g++-5 supports C++17 features with +std=c++17... no
checking whether g++-5 supports C++17 features with -h std=c++17... no
checking whether g++-5 supports C++17 features with -std=c++1z... no
checking whether g++-5 supports C++17 features with +std=c++1z... no
checking whether g++-5 supports C++17 features with -h std=c++1z... no
configure: error: *** A compiler with support for C++17 language features is required.
  </pre>
</details>

## What you expected to happen
My solution: i just build this formulae with llvm
```diff
diff --git a/Formula/libopenmpt.rb b/Formula/libopenmpt.rb
index 53111d90e9..91f592b9c7 100644
--- a/Formula/libopenmpt.rb
+++ b/Formula/libopenmpt.rb
@@ -20,6 +20,7 @@ class Libopenmpt < Formula
   depends_on "libvorbis"
   depends_on "mpg123"
   depends_on "portaudio"
+  depends_on "llvm"
 
   resource "mystique.s3m" do
     url "https://api.modarchive.org/downloads.php?moduleid=54144#mystique.s3m"
@@ -27,7 +28,14 @@ class Libopenmpt < Formula
   end
 
   def install
-    system "./configure", "--disable-debug",
+    # C++17 compliant compiler needed
+    # see: https://lib.openmpt.org/doc/dependencies.html
+    ENV["CXX"] = Formula["llvm"].opt_bin/"clang++"
+    ENV["CC"]  = Formula["llvm"].opt_bin/"clang"
+
+    system "./configure", "--disable-tests",
+                          "--disable-examples",
+                          "--disable-static",
                           "--disable-dependency-tracking",
                           "--disable-silent-rules",
                           "--prefix=#{prefix}",
```
`--disable-debug` option is depricated
`--disable-tests --disable-examples` -30Mb
`--disable-static` -60Mb (shared libraries enabled by default)

**Comment by jonchang** [comment]
Thanks @OpenA for the bug report and patch. Do you mind [opening a pull request](https://github.com/Homebrew/linuxbrew-core/blob/master/CONTRIBUTING.md) with these changes? Also, please use compiler selection to pick a different compiler:

```ruby
unless OS.mac?
  depends_on "gcc@9"
  fails_with :gcc => "5"
  fails_with :gcc => "6"
  fails_with :gcc => "7"
  fails_with :gcc => "8"
end
```
