### ISSUE TITLE
zoxide: Request for a bottle

### ISSUE THREAD

**Issue by ajeetdsouza** [Homebrew/linuxbrew-core#20638]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] checked that there aren't other open issues for the same formula bottle request?
- [ ] does the FORMULA not have the `bottle` block?
- [x] ran `brew install FORMULA` and it succeeded?

**Comment by issyl0** [comment]
Thanks for the ping! I just started a build job in https://github.com/Homebrew/linuxbrew-core/runs/819539983?check_suite_focus=true.

**Comment by issyl0** [comment]
It succeeded, so a Linux bottle [now exists](https://github.com/Homebrew/linuxbrew-core/commit/25d738db67b038b013743954327ab3cb1b1d67c8). Thanks for using Homebrew on Linux!

**Comment by ajeetdsouza** [comment]
Thanks!
