### ISSUE TITLE
GCC-9 + GLIBC results in broken gcc-9 binary

### ISSUE THREAD

**Issue by dancooke** [Homebrew/linuxbrew-core#20684]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install `gcc@9` and `glibc` on a CentOS 7 system.

## What happened (include command output)

The installed `g++-9` binary doesn't work:

```shell
$ g++-9
g++-9:  u??: ELF: : Error 2054383991
```

## What you expected to happen

The `g++-9` binary to work. I've been using these packages installed with Homebrew for a while now with no problems. This started happening recently.

## Step-by-step reproduction instructions (by running `brew install` commands)

On a CentoOS 7 machine (I don't have sudo privileges, so installed into home directory);

```shell
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
$ .linuxbrew/bin/brew install gcc@9 glibc
$ .linuxbrew/bin/g++-9
g++-9:  u??: ELF: : Error 1364793719
```
I can also reproduce in a Docker container:

```shell
$ docker run -t -i centos:7 /bin/bash
$ yum -y update
$ yum -y groupinstall 'Development Tools'
$ yum -y install curl file git which perl-devel
$ cd /home && mkdir test && cd test
$ git clone https://github.com/Homebrew/brew
$ brew/bin/brew update
$ brew/bin/brew install gcc@9 glibc
$ brew/bin/g++-9
brew/bin/g++-9: `Y6??: ELF: : Error 1057823095
```

Additional info

```shell
$ .linuxbrew/bin/brew gist-logs gcc@8    
Error: No logs.
$ .linuxbrew/bin/brew config
HOMEBREW_VERSION: 2.4.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: c69d97aaa5ba07e8c2af3708c8093ca0875cfb06
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 6cb766a4351cdbb81868365358214ca15964f297
Core tap last commit: 30 minutes ago
HOMEBREW_PREFIX: /gpfs3/users/lunter/dcooke/.linuxbrew
HOMEBREW_REPOSITORY: /gpfs3/users/lunter/dcooke/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /gpfs3/users/lunter/dcooke/.linuxbrew/Cellar
HOMEBREW_DISPLAY: localhost:11.0
HOMEBREW_MAKE_JOBS: 24
CPU: 24-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /gpfs3/users/lunter/dcooke/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: N/A
Git: 2.27.0 => /gpfs3/users/lunter/dcooke/.linuxbrew/bin/git
Curl: 7.29.0 => /usr/bin/curl
Kernel: Linux 3.10.0-957.10.1.el7.x86_64 x86_64 GNU/Linux
OS: CentOS Linux release 7.6.1810 (Core) 
Host glibc: 2.17
/usr/bin/gcc: 4.8.5
glibc: 2.23
gcc: 5.5.0_7
xorg: N/A
```

**Comment by dancooke** [comment]
Trying to install `glibc` before `gcc@9` results in a different error - during installation this time:

```shell
$ brew/bin/brew install glibc  gcc@9
...
==> Downloading https://ftp.gnu.org/gnu/glibc/glibc-2.23.tar.gz
######################################################################## 100.0%
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/home/test/brew/Cellar/glibc/2.23 --enable-obsolete-rpc -
==> make
==> make install
Warning: Calling Formula#installed? is deprecated! Use Formula#latest_version_installed? (or Formula#any_version_installed? ) instead.
Please report this issue to the homebrew/core tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /home/test/brew/Library/Taps/homebrew/homebrew-core/Formula/glibc.rb:142

==> Installing locale data for en_US.UTF-8
==> /home/test/brew/Cellar/glibc/2.23/bin/localedef -i en_US -f UTF-8 en_US.UTF-8
🍺  /home/test/brew/Cellar/glibc/2.23: 1,403 files, 42.1MB, built in 3 minutes 16 seconds
==> Downloading https://linuxbrew.bintray.com/bottles/isl-0.22.1.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/f2/f211005727b3ff0a59cbca6521f9a5aaaef54cfc801e3725a1b2708f9576fa0c?__gda__=exp=1594113708~hmac=f12575e7
######################################################################## 100.0%
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-9.3.0/gcc-9.3.0.tar.xz
######################################################################## 100.0%
==> Installing dependencies for gcc@9: isl
==> Installing gcc@9 dependency: isl
==> Pouring isl-0.22.1.x86_64_linux.bottle.tar.gz
🍺  /home/test/brew/Cellar/isl/0.22.1: 74 files, 6.3MB
==> Installing gcc@9
==> ../configure --with-bugurl=https://github.com/Homebrew/linuxbrew-core/issues --disable-multilib --prefix=/home/test/brew/Cellar/gcc@9/9.3.0 --libdir
==> make
Last 15 lines from /root/.cache/Homebrew/Logs/gcc@9/02.make:
checking whether /usr/bin/make sets $(MAKE)... yes
checking whether /usr/bin/make supports nested variables... yes
checking for x86_64-pc-linux-gnu-gcc... /tmp/gcc@9-20200707-70411-rozmyp/gcc-9.3.0/build/./gcc/xgcc -B/tmp/gcc@9-20200707-70411-rozmyp/gcc-9.3.0/build/./gcc/ -B/home/test/brew/Cellar/gcc@9/9.3.0/x86_64-pc-linux-gnu/bin/ -B/home/test/brew/Cellar/gcc@9/9.3.0/x86_64-pc-linux-gnu/lib/ -isystem /home/test/brew/Cellar/gcc@9/9.3.0/x86_64-pc-linux-gnu/include -isystem /home/test/brew/Cellar/gcc@9/9.3.0/x86_64-pc-linux-gnu/sys-include   -fno-checking
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/tmp/gcc@9-20200707-70411-rozmyp/gcc-9.3.0/build/x86_64-pc-linux-gnu/libgomp':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
make[2]: *** [configure-stage1-target-libgomp] Error 1
make[2]: Leaving directory `/tmp/gcc@9-20200707-70411-rozmyp/gcc-9.3.0/build'
make[1]: *** [stage1-bubble] Error 2
make[1]: Leaving directory `/tmp/gcc@9-20200707-70411-rozmyp/gcc-9.3.0/build'
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
GCC-9 + GLIBC results in broken gcc-9 binary https://github.com/Homebrew/linuxbrew-core/issues/20684
gcc@9: fix build for Linuxbrew https://github.com/Homebrew/linuxbrew-core/pull/20688
gcc@5: align with upstream and improve https://github.com/Homebrew/linuxbrew-core/pull/20241
```

**Comment by danielnachun** [comment]
I can reproduce both of these errors and they are actually caused by the same underlying issue.  If I install gcc 9 before glibc or unlink glibc before installing gcc 9 with `brew unlink glibc`, I see the following output when I run `ldd g++-9` 

```
ldd g++-9
        linux-vdso.so.1 =>  (0x00007ffd997b1000)
        libm.so.6 => /lib64/libm.so.6 (0x00002af3fd9c4000)
        libc.so.6 => /lib64/libc.so.6 (0x00002af3fdcc6000)
        /lib64/ld-linux-x86-64.so.2 (0x00002af3fd7a0000)
```

This means that g++-9 (and all other executables in the gcc 9 cellar) are using the system glibc and interpreter.

However, after linking or install glibc, I see the following output

```
ldd g++-9
        linux-vdso.so.1 =>  (0x00007fffe632b000)
        libm.so.6 => /home/dnachun/.linuxbrew/lib/libm.so.6 (0x00002b583c42d000)
        libc.so.6 => /home/dnachun/.linuxbrew/lib/libc.so.6 (0x00002b583c62d000)
        /lib64/ld-linux-x86-64.so.2 (0x00002b583c409000)
```

Now it is using the Linuxbrew glibc, but is still using the system interpreter.  It is this mismatch between the interpreter and libc which causes the ELF error we're both seeing.  I also discovered that this is why gcc 9 will fail to compile if Linuxbrew glibc is already installed.  During the compile process for gcc, it creates a temporary compiler to compile gcc (you can see it doing this if you use `brew install -v gcc@9` and note that it starts using `xgcc` to compile at certain point).  If glibc is already installed, this temporary compiler suffers from the same mismatch between the interpreter and libc, which you can see if you use `brew install --debug gcc@9` and inspect `xgcc` with `ldd`.

Luckily there is a solution to this.  If you install gcc 9 before glibc or unlink glibc before installing gcc 9, you will successfully compile gcc 9 but still have the broken executables. I was able to fix them by changing the interpreter with `patchelf` (you must first give yourself write permission to modify the executable).  All of this should be done in the cellar for gcc 9 (`$(brew --cellar)/gcc@9/9.3.0/bin`):

```
chmod -R 755 ./*
ls | xargs patchelf --set-interpreter "/home/dnachun/.linuxbrew/lib/ld.so"
chmod -R 555 ./*
```

Your interpreter path will depend on the location of your Linuxbrew installation so adjust the path accordingly.  After patching the interpreter for the gcc 9 executables, if you check with `ldd` again:

```
ldd g++-9
        linux-vdso.so.1 (0x00007ffd7d132000)
        libm.so.6 => /home/dnachun/.linuxbrew/lib/libm.so.6 (0x00002b601595f000)
        libc.so.6 => /home/dnachun/.linuxbrew/lib/libc.so.6 (0x00002b6015a66000)
        /home/dnachun/.linuxbrew/lib/ld.so (0x00002b6015936000)
```
you will see that the interpreter now matches libc, and the ELF errors are fixed. 

I am not really sure why gcc does not pick up the Linuxbrew interpreter the way other packages normally do.  GCC is understandably probably a lot pickier about the interpreter it uses than other software, but it may still be possible to configure it in to use the right interpreter without requiring us to patch the interpreter after compiling.

**Comment by iMichka** [comment]
Hi. Thanks for your investigations.

I am currently fixing gcc@9 here: #20688
Then, big changes are planned here for gcc: #20241. I do need to test different glibc configurations, and will start to work on this during the next weeks. So do not expect any quick progress. But we definitively want to improve the situation.

**Comment by dancooke** [comment]
@danielnachun I followed your suggestion, and while the `gcc-9` binary does now 'work', it still fails when attempting to compile a simple test program:

```shell
$ docker run -t -i centos:7 /bin/bash
$ yum -y update
$ yum -y groupinstall 'Development Tools'
$ yum -y install curl file git which perl-devel
$ cd /home && mkdir test && cd test
$ git clone https://github.com/Homebrew/brew
$ brew/bin/brew update
$ brew/bin/brew install gcc@9 glibc
$ cd brew/Cellar/gcc@9/9.3.0/bin
$ chmod -R 755 ./*
$ ls | xargs /home/test/brew/bin/patchelf --set-interpreter "/home/test/brew/lib/ld.so"
$ chmod -R 555 ./*
$ cd /home/test
$ brew/bin/g++-9
g++-9: fatal error: no input files
compilation terminated.
$ printf '#include <iostream>\n\nint main()\n{\n\tstd::cout << "hello world!" << std::endl;\n}\n' >> hello.cpp
$ brew/bin/g++-9 -c hello.cpp -o hello.o
/home/test/brew/Cellar/gcc@9/9.3.0/libexec/gcc/x86_64-pc-linux-gnu/9.3.0/cc1plus: p>R??: ELF: : Error 18446744071730702711
```

**Comment by danielnachun** [comment]
Thanks @iMichka for your hard work on this - gcc is always a challenge to build.

@dancooke I had the same problem today when I tried to use the compiler.  I realized that I missed that there were some executables in the `libexec` subfolder of the gcc 9 cellar.  To fix these, you'll have to go to `$(brew --cellar)/gcc@9/9.3.0/libexec/gcc/x86_64-pc-linux-gnu/9.3.0` and then patch the executables there:

```
patchelf --set-interpreter "$(brew --prefix)/lib/ld.so" cc1
patchelf --set-interpreter "$(brew --prefix)/lib/ld.so" cc1obj
patchelf --set-interpreter "$(brew --prefix)/lib/ld.so" cc1objplus
patchelf --set-interpreter "$(brew --prefix)/lib/ld.so" cc1plus
patchelf --set-interpreter "$(brew --prefix)/lib/ld.so" collect2
patchelf --set-interpreter "$(brew --prefix)/lib/ld.so" f951
patchelf --set-interpreter "$(brew --prefix)/lib/ld.so" lto1
patchelf --set-interpreter "$(brew --prefix)/lib/ld.so" lto-wrapper
patchelf --set-interpreter "$(brew --prefix)/lib/ld.so" plugin/gengtype
patchelf --set-interpreter "$(brew --prefix)/lib/ld.so" install-tools/fixincl
```

I think that is all of the executables in the gcc 9 cellar.  After patching these, gcc worked for me.  It should be possible to aggregate these fixes plus what I posted above into a script that will work from any directory for any Linuxbrew install by using `$(brew --prefix)` and `$(brew --cellar)` in the right places.  @iMichka if you think this would be useful I can do so as I now believe this has actually been an issue for a while (the same problem happened in 2017 here https://github.com/Linuxbrew/brew/issues/237).
