### ISSUE TITLE
topgrade: Request for a bottle

### ISSUE THREAD

**Issue by develop7** [Homebrew/linuxbrew-core#20763]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] checked that there aren't other open issues for the same formula bottle request?
- [x] does the FORMULA not have the `bottle` block?
- [x] ran `brew install FORMULA` and it succeeded?

The topgrade 5.2.0 bottle seems to be slipped through cracks somehow

**Comment by dawidd6** [comment]
Done in: https://github.com/Homebrew/linuxbrew-core/commit/43c66208836def004129a15c8df62f7bb3eaaf5e
