### ISSUE TITLE
PopOS support?

### ISSUE THREAD

**Issue by dalisoft** [Homebrew/linuxbrew-core#20767]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Installing tools from **Linuxbrew** via terminal on PopOS.
Currently failed to install package was: **dprint** and **fnm**

## What happened (include command output)

See [here](https://github.com/Schniz/fnm/issues/230) or [here](https://github.com/dprint/dprint/issues/266#issuecomment-661625443)

I did think it's bug of their tool or Github Actions and remembered there PopOS uses OS family variable **PopOS**.
I today faced to bug in Ansible in PopOS and [fixed](https://github.com/dalisoft/config/blob/master/ansible/site.yml#L58) after some debugs

## What you expected to happen

Succesfully installing like in Ubuntu 20.04 (worked when last time tested)

## Step-by-step reproduction instructions (by running `brew install` commands)

Snippet from [here](https://github.com/dprint/dprint/issues/266#issuecomment-661617936)

```
brew remove dprint
brew tap dprint/dprint
brew install dprint
```

**Comment by dsherret** [comment]
I don't think the reproduction steps are valid here because only the Mac binary of dprint is distributed on homebrew (no linux binary at the moment).

**Comment by dalisoft** [comment]
@dsherret FNM also does not have compiled binary for Linux, it worked on Ubuntu but for PopOS did not

**Comment by iMichka** [comment]
Hi. We do not officially support PopOS. And we do not support formulae from external taps in this specific issue tracker. If you still need help you can try to open an issue on https://discourse.brew.sh/ and see if the community can help you.
