### ISSUE TITLE
Failed to install telnet formula

### ISSUE THREAD

**Issue by mizunashi-mana** [Homebrew/linuxbrew-core#20785]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

```bash
brew install telnet
```

## What happened (include command output)

Failed with error message.

<details>
  <summary>Command output</summary>
  <pre>
$ brew install telnet
==> Downloading https://opensource.apple.com/tarballs/libtelnet/libtelnet-13.tar.gz
Already downloaded: /home/mizunashi/.cache/Homebrew/downloads/4fe26613ac3f91bd2fa2ed4e9ca39a043c6fd5960c4e0a3f063c672911900665--libtelnet-13.tar.gz
==> Downloading https://opensource.apple.com/tarballs/remote_cmds/remote_cmds-63.tar.gz
Already downloaded: /home/mizunashi/.cache/Homebrew/downloads/557d5b69c452e48e5337f6d80e827514cd2218e1c02dcd42f893bd2cafe7d141--remote_cmds-63.tar.gz
Error: An exception occurred within a child process:
  NoMethodError: undefined method `sdk_path' for OS::Mac:Module
  </pre>
</details>

## What you expected to happen

Success to install.

## Step-by-step reproduction instructions (by running `brew install` commands)

1. On WSL/Debian:
   
    ```bash
    $ cat /etc/debian_version
    10.4
    $  uname -r
    4.19.104-microsoft-standard
    ```

2. With Linuxbrew:

   ```bash
   $ brew --version
   Homebrew 2.4.8
   Homebrew/linuxbrew-core (git revision a14dc; last commit 2020-07-24)
   ```

3. Install telnet formula:

   ```bash
   brew install telnet
   ```

**Comment by Akylzhan** [comment]
After exploring the source code, I have noticed that the brew installs telnet only on Xcode running machines. Correct me if I am wrong.

Also, I add linux installation, but I am newbie here

**Comment by mizunashi-mana** [comment]
@Akylzhan I found `inetutils` formula includes GNU `telnet`, and it runs well on my Linux WSL/Debian.  Then, fixed this problems for me.  Thank you!
