### ISSUE TITLE
Post install failed for perl while brew install pyenv

### ISSUE THREAD

**Issue by puremourning** [Homebrew/linuxbrew-core#20825]
- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew install pyenv` in a ubuntu container (to install pyenv, actually in a azure vm, which worked for years)

## What happened (include command output)

<details>
  <summary>Post install failed for perl</summary>
  <pre>

ben@a4013aeb455c:~$ brew install pyenv
==> Downloading https://linuxbrew.bintray.com/bottles/m4-1.4.18.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/9fbd4721316274995db37b5f92441b550d09bd131339ecc447377ee886970363--m4-1.4.18.x86_64_linux.bottle.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/libbsd-0.10.0.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/f3852ac033f269781a66c38aa84d861299f89ea0ad0f560beff780eb702455f5--libbsd-0.10.0.x86_64_linux.bottle.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/expat-2.2.9.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/6eeec8e2508cd7ebdfdd3c09eaccc362692aa5596ce902369a1ae898f143b469--expat-2.2.9.x86_64_linux.bottle.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/gdbm-1.18.1.x86_64_linux.bottle.1.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/99b956ce7c3ae9f974cfd24f34c0273ac86e0e4e83b3f351f8579937e6bc52ec--gdbm-1.18.1.x86_64_linux.bottle.1.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/openssl%401.1-1.1.1g.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/153de442ec90385f73424f726565a84a3e05ae80c38a8cec71ec905b974e2685--openssl@1.1-1.1.1g.x86_64_linux.bottle.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/berkeley-db-18.1.32_1.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/92a84aa10674be2e52718e86244adb06dbe46ebee73ae6d377fe0c77ad0040cc--berkeley-db-18.1.32_1.x86_64_linux.bottle.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/perl-5.32.0.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/6b76ba66192a64f545283afed14b01bca1fa9c071c0a88a909108c5142a25f2d--perl-5.32.0.x86_64_linux.bottle.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/autoconf-2.69_2.x86_64_linux.bottle.4.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/e2179cfbcc55c9ba6c615dc16d30bbef01c55699c60edd6928ac542536a86da2--autoconf-2.69_2.x86_64_linux.bottle.4.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/pkg-config-0.29.2_4.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/9ae792be0ff044cacdab5b0bbb96110b61ccaf488d49843e4b2fdc4cb66ca3a5--pkg-config-0.29.2_4.x86_64_linux.bottle.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/ncurses-6.2.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/e79d9016be84a9ae660850272b21a25af30d9387f2840bcef96a5e141a775cdf--ncurses-6.2.x86_64_linux.bottle.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/readline-8.0.4.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/f15c19dac959687a1fd76a2d53260350e6cc6baabf803c5ca68ec200780ee0e5--readline-8.0.4.x86_64_linux.bottle.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/zlib-1.2.11.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/e26d7f94e9190e27f35a0ca17586414d88d5bb82ae7927206a18556eab619109--zlib-1.2.11.x86_64_linux.bottle.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/sqlite-3.32.3.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/9a2fbe8754f5172e68861d466a4a583355b864e55a3de2a50afafe58e655de78--sqlite-3.32.3.x86_64_linux.bottle.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/xz-5.2.5.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/cc99f09de0205f95c3de0e181f3398c75f0eb085e42c16577a7e77ef2ae6d3c8--xz-5.2.5.x86_64_linux.bottle.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/bzip2-1.0.8.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/79106d289b4de8f074d2f6b35eaf301812e15b4ce383587bfcde5d082e025fc6--bzip2-1.0.8.x86_64_linux.bottle.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/libffi-3.3.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/920bab15ca8e94d3c97c24b0f4cec2794a07c3e96b46b7d16bcdc39e7acc35c1--libffi-3.3.x86_64_linux.bottle.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/unzip-6.0_6.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/c6dc201fab9558e948dc62e88ab17107d77ae4b77fc24509c3f1fe02d15deaec--unzip-6.0_6.x86_64_linux.bottle.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/python%403.8-3.8.5.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/5cd3b7774028bb112b480f45355553af2bbce2317e60c46723996a07de6981eb--python@3.8-3.8.5.x86_64_linux.bottle.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/pyenv-1.2.20.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ben/.cache/Homebrew/downloads/c2b69d7c2f9ed52d4c2c40b98d17a326ed74945422d2548666a906781e24e619--pyenv-1.2.20.x86_64_linux.bottle.tar.gz
==> Installing dependencies for pyenv: m4, libbsd, expat, gdbm, openssl@1.1, berkeley-db, perl, autoconf, pkg-config, ncurses, readline, zlib, sqlite, xz, bzip2, libffi, unzip and python@3.8
==> Installing pyenv dependency: m4
==> Pouring m4-1.4.18.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/m4/1.4.18: 13 files, 1.1MB
==> Installing pyenv dependency: libbsd
==> Pouring libbsd-0.10.0.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/libbsd/0.10.0: 261 files, 961.2KB
==> Installing pyenv dependency: expat
==> Pouring expat-2.2.9.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/expat/2.2.9: 18 files, 757.3KB
==> Installing pyenv dependency: gdbm
==> Pouring gdbm-1.18.1.x86_64_linux.bottle.1.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/gdbm/1.18.1: 40 files, 1MB
==> Installing pyenv dependency: openssl@1.1
==> Pouring openssl@1.1-1.1.1g.x86_64_linux.bottle.tar.gz
==> Downloading https://curl.haxx.se/ca/cacert-2020-01-01.pem
######################################################################## 100.0%
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /home/linuxbrew/.linuxbrew/etc/openssl@1.1/certs

and run
  /home/linuxbrew/.linuxbrew/opt/openssl@1.1/bin/c_rehash
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1g: 8,060 files, 21.4MB
==> Installing pyenv dependency: berkeley-db
==> Pouring berkeley-db-18.1.32_1.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/berkeley-db/18.1.32_1: 5,673 files, 128.3MB
==> Installing pyenv dependency: perl
==> Pouring perl-5.32.0.x86_64_linux.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall perl`
==> Caveats
By default non-brewed cpan modules are installed to the Cellar. If you wish
for your modules to persist across updates we recommend using `local::lib`.

You can set that up like this:
  PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
  echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"' >> ~/.profile
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/perl/5.32.0: 2,465 files, 71.7MB
==> Installing pyenv dependency: autoconf
==> Pouring autoconf-2.69_2.x86_64_linux.bottle.4.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/autoconf/2.69_2: 67 files, 3MB
==> Installing pyenv dependency: pkg-config
==> Pouring pkg-config-0.29.2_4.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/pkg-config/0.29.2_4: 11 files, 744.2KB
==> Installing pyenv dependency: ncurses
==> Pouring ncurses-6.2.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/ncurses/6.2: 3,901 files, 9.5MB
==> Installing pyenv dependency: readline
==> Pouring readline-8.0.4.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/readline/8.0.4: 53 files, 1.9MB
==> Installing pyenv dependency: zlib
==> Pouring zlib-1.2.11.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/zlib/1.2.11: 12 files, 424KB
==> Installing pyenv dependency: sqlite
==> Pouring sqlite-3.32.3.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/sqlite/3.32.3: 12 files, 4.9MB
==> Installing pyenv dependency: xz
==> Pouring xz-5.2.5.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/xz/5.2.5: 128 files, 1.8MB
==> Installing pyenv dependency: bzip2
==> Pouring bzip2-1.0.8.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/bzip2/1.0.8: 30 files, 549.3KB
==> Installing pyenv dependency: libffi
==> Pouring libffi-3.3.x86_64_linux.bottle.tar.gz
	🍺  /home/linuxbrew/.linuxbrew/Cellar/libffi/3.3: 17 files, 552.7KB
==> Installing pyenv dependency: unzip
==> Pouring unzip-6.0_6.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/unzip/6.0_6: 17 files, 581.8KB
==> Installing pyenv dependency: python@3.8
==> Pouring python@3.8-3.8.5.x86_64_linux.bottle.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-script
==> /home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-script
==> /home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.5/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-script
==> Caveats
Python has been installed as
  /home/linuxbrew/.linuxbrew/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /home/linuxbrew/.linuxbrew/opt/python@3.8/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.5: 3,980 files, 73.5MB
==> Installing pyenv
==> Pouring pyenv-1.2.20.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/pyenv/1.2.20: 708 files, 3MB
==> Caveats
==> openssl@1.1
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /home/linuxbrew/.linuxbrew/etc/openssl@1.1/certs

and run
  /home/linuxbrew/.linuxbrew/opt/openssl@1.1/bin/c_rehash
==> perl
By default non-brewed cpan modules are installed to the Cellar. If you wish
for your modules to persist across updates we recommend using `local::lib`.

You can set that up like this:
  PERL_MM_OPT="INSTALL_BASE=$HOME/perl5" cpan local::lib
  echo 'eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib=$HOME/perl5)"' >> ~/.profile
==> python@3.8
Python has been installed as
  /home/linuxbrew/.linuxbrew/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /home/linuxbrew/.linuxbrew/opt/python@3.8/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /home/linuxbrew/.linuxbrew/lib/python3.8/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
ben@a4013aeb455c:~$ echo $?
1

ben@a4013aeb455c:~$ brew update
Already up-to-date.

ben@a4013aeb455c:~$ brew doctor
Your system is ready to brew.

ben@a4013aeb455c:~$ brew gist-logs perl
Error: No logs.
ben@a4013aeb455c:~$ brew gist-logs pyenv
Error: No logs.

ben@a4013aeb455c:~$ brew config
HOMEBREW_VERSION: 2.4.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: e6b066a3d9fc5435009428fcd2855fddf9b455c0
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 6078c8ecfc37e0a4d8dc32a71ad60fba5ef27356
Core tap last commit: 47 minutes ago
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: N/A
Git: 2.17.1 => /usr/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 4.19.76-linuxkit x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.27
/usr/bin/gcc: 7.5.0
glibc: N/A
gcc: N/A
xorg: N/A

 </pre>
</details>

## What you expected to happen

`brew install pyenv` is successful (it has been used unchanged for at least a year)

## Step-by-step reproduction instructions (by running `brew install` commands)

I repro'd (above) with the following steps:

* `docker -it ubuntu:18.04`
* `useradd -d /home/ben -m -s /bin/bash ben`
* `apt-get install build-essential git sudo curl`
* `echo "ben ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ben`
* `su - ben`
* `mkdir -p $HOME/.cache`
* `sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"`
* `eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)`
* `brew install pyenv`
* `echo $?`

Likely caused by https://github.com/Homebrew/linuxbrew-core/commit/02e371da58ecf36178d7e6e24a7dc136485acf2d

**Comment by jonchang** [comment]
Think this was fixed in d43b12844d5bb39e61125251d2d9ea027dbbbb01

**Comment by puremourning** [comment]
> Think this was fixed in [d43b128](https://github.com/Homebrew/linuxbrew-core/commit/d43b12844d5bb39e61125251d2d9ea027dbbbb01)

Confirmed, thanks.
