### ISSUE TITLE
failing to install git@2.28.0_1 (regression after 2.27.0)

### ISSUE THREAD

**Issue by andreineculau** [Homebrew/linuxbrew-core#20930]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew upgrade git` (similar outcome from `brew install git` fresh)

## What happened (include command output)

Command fails with because of a ruby (?!) gem `nokogiri` that fails with `zlib is missing; necessary for building libxml2`.

<details>
  <summary>Command output</summary>
  <pre>

sf@4bdddfe52b94:/$ brew outdated
gdbm (1.18.1) < 1.18.1_1
gettext (0.20.2_1) < 0.21
git (2.27.0) < 2.28.0_1
gnu-getopt (2.35.2) < 2.36
node (14.5.0) < 14.7.0
rsync (3.2.2) < 3.2.3
xxhash (0.7.4) < 0.8.0_1
sf@4bdddfe52b94:/$ brew upgrade git
==> Upgrading 1 outdated package:
git 2.27.0 -> 2.28.0_1
==> Upgrading git 2.27.0 -> 2.28.0_1
==> Downloading https://linuxbrew.bintray.com/bottles/gettext-0.21.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/6c/6cf15ff1c76c4d767018e524b4cc2b627e95ce910a266fb7e0069ac07fb3d8f5?__g
######################################################################## 100.0%
==> Downloading https://linuxbrew.bintray.com/bottles/git-2.28.0_1.x86_64_linux.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/b3/b31c096a447ebba7a9cec3507e21ace0c0fdb570230b429f943039296099959a?__g
######################################################################## 100.0%
==> Installing dependencies for git: gettext
==> Installing git dependency: gettext
==> Pouring gettext-0.21.x86_64_linux.bottle.tar.gz
Fetching gem metadata from https://rubygems.org/.........
Fetching concurrent-ruby 1.1.7
Fetching thread_safe 0.3.6
Fetching minitest 5.14.1
Installing minitest 5.14.1
Installing thread_safe 0.3.6
Installing concurrent-ruby 1.1.7
Fetching zeitwerk 2.4.0
Installing zeitwerk 2.4.0
Fetching ast 2.4.1
Installing ast 2.4.1
Fetching bindata 2.4.8
Using bundler 1.17.2
Fetching byebug 11.1.3
Installing bindata 2.4.8
Installing byebug 11.1.3 with native extensions
Fetching colorize 0.8.1
Installing colorize 0.8.1
Fetching json 2.3.1
Installing json 2.3.1 with native extensions
Fetching docile 1.3.2
Installing docile 1.3.2
Fetching simplecov-html 0.12.2
Installing simplecov-html 0.12.2
Fetching coderay 1.1.3
Installing coderay 1.1.3
Fetching highline 2.0.3
Installing highline 2.0.3
Fetching connection_pool 2.2.3
Installing connection_pool 2.2.3
Fetching diff-lcs 1.4.4
Installing diff-lcs 1.4.4
Fetching unf_ext 0.0.7.7
Installing unf_ext 0.0.7.7 with native extensions
Fetching hpricot 0.8.6
Installing hpricot 0.8.6 with native extensions
Fetching mime-types-data 3.2020.0512
Installing mime-types-data 3.2020.0512
Fetching net-http-digest_auth 1.4.1
Installing net-http-digest_auth 1.4.1
Fetching mini_portile2 2.4.0
Installing mini_portile2 2.4.0
Fetching ntlm-http 0.1.1
Installing ntlm-http 0.1.1
Fetching webrobots 0.1.2
Installing webrobots 0.1.2
Fetching method_source 1.0.0
Installing method_source 1.0.0
Fetching mustache 1.1.1
Installing mustache 1.1.1
Fetching parallel 1.19.2
Installing parallel 1.19.2
Fetching rainbow 3.0.0
Installing rainbow 3.0.0
Fetching sorbet-runtime 0.5.5866
Installing sorbet-runtime 0.5.5866
Fetching plist 3.5.0
Installing plist 3.5.0
Fetching rdiscount 2.2.0.2
Installing rdiscount 2.2.0.2 with native extensions
Fetching regexp_parser 1.7.1
Installing regexp_parser 1.7.1
Fetching rexml 3.2.4
Installing rexml 3.2.4
Fetching rspec-support 3.9.3
Installing rspec-support 3.9.3
Fetching ruby-progressbar 1.10.1
Installing ruby-progressbar 1.10.1
Fetching unicode-display_width 1.7.0
Installing unicode-display_width 1.7.0
Fetching ruby-macho 2.2.0
Installing ruby-macho 2.2.0
Fetching sorbet-static 0.5.5866 (x86_64-linux)
Installing sorbet-static 0.5.5866 (x86_64-linux)
Fetching thor 1.0.1
Installing thor 1.0.1
Fetching parser 2.7.1.4
Installing parser 2.7.1.4
Fetching tzinfo 1.2.7
Installing tzinfo 1.2.7
Fetching elftools 1.1.2
Installing elftools 1.1.2
Fetching i18n 1.8.5
Installing i18n 1.8.5
Fetching simplecov 0.18.5
Installing simplecov 0.18.5
Fetching commander 4.5.2
Installing commander 4.5.2
Fetching net-http-persistent 4.0.0
Installing net-http-persistent 4.0.0
Fetching unf 0.1.4
Installing unf 0.1.4
Fetching mime-types 3.3.1
Installing mime-types 3.3.1
Fetching nokogiri 1.10.10
Installing nokogiri 1.10.10 with native extensions
Fetching pry 0.13.1
Installing pry 0.13.1
Fetching parallel_tests 3.1.0
Installing parallel_tests 3.1.0
Fetching rspec-core 3.9.2
Installing rspec-core 3.9.2
Fetching rspec-expectations 3.9.2
Installing rspec-expectations 3.9.2
Fetching rspec-mocks 3.9.1
Installing rspec-mocks 3.9.1
Fetching sorbet 0.5.5866
Installing sorbet 0.5.5866
Fetching rubocop-ast 0.3.0
Installing rubocop-ast 0.3.0
Fetching patchelf 1.2.0
Installing patchelf 1.2.0
Fetching activesupport 6.0.3.2
Installing activesupport 6.0.3.2
Fetching codecov 0.2.5
Installing codecov 0.2.5
Fetching parlour 4.0.1
Installing parlour 4.0.1
Fetching domain_name 0.5.20190701
Installing domain_name 0.5.20190701
Fetching rspec-retry 0.6.2
Installing rspec-retry 0.6.2
Fetching rspec-its 1.3.0
Installing rspec-its 1.3.0
Fetching rspec 3.9.0
Installing rspec 3.9.0
Fetching rubocop 0.88.0
Installing rubocop 0.88.0
Fetching tapioca 0.4.1
Installing tapioca 0.4.1
Fetching http-cookie 1.0.3
Installing http-cookie 1.0.3
Fetching rspec-wait 0.0.9
Installing rspec-wait 0.0.9
Fetching rubocop-performance 1.7.1
Installing rubocop-performance 1.7.1
Fetching rubocop-rspec 1.42.0
Installing rubocop-rspec 1.42.0
Fetching ronn 0.7.3
Installing ronn 0.7.3
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.10/ext/nokogiri
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby -I
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0 -r
./siteconf20200810-39896-2kbjrd.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.4.0
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build

To see why this extension failed to compile, please check the mkmf.log which can be found here:

/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0-static/nokogiri-1.10.10/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.10.10 for inspection.
Results logged to
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0-static/nokogiri-1.10.10/gem_make.out

An error occurred while installing nokogiri (1.10.10), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.10' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  mechanize was resolved to 2.7.6, which depends on
    nokogiri
Error: failed to run `/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/bundle install`!
Error: exit
Warning: Bottle installation failed: building from source.
==> Downloading https://ftp.gnu.org/gnu/gettext/gettext-0.21.tar.xz

  </pre>
</details>

## What you expected to happen

git to be upgraded successfully.

**Comment by andreineculau** [comment]
Just as I was writing this issue, I figured the problem isn't to do with the `git` formula.
Running any `brew` command, starts installing/upgrading some ruby gems including this failing gem.

For the time being, it looks like one needs to `sudo apt-get install zlib1g-dev` to get the latest linuxbrew to run properly

**Comment by sjackman** [comment]
Thanks for the bug report, Andrei. That's a bug in Homebrew/brew 2.4.10 released today that will be resolved in the next release of Homebrew.

**Comment by sjackman** [comment]
This issue has been resolved by PR https://github.com/Homebrew/brew/pull/8299 and released in Homebrew 2.4.11. https://github.com/Homebrew/brew/releases/tag/2.4.11
