### ISSUE TITLE
Binaries installed respond with permission denied

### ISSUE THREAD

**Issue by andrewhertog** [Homebrew/linuxbrew-core#20949]
# Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? https://gist.github.com/andrewhertog/99803aab5bc91ef2fe46951b199c7d40
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Trying to execute a binary installed by linuxbrew, in this case it was tfswitch, but it also occured on others.
Fresh install of linux brew as per instructions on https://docs.brew.sh/Homebrew-on-Linux
Ran `brew install tfswitch` 
then tried to execute `tfswitch`

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

zsh: permission denied: tfswitch  </pre>
</details>

## What you expected to happen

tfswitch application should successfully run
## Step-by-step reproduction instructions (by running `brew install` commands)
Environment:
- Ubuntu 20.04 VM (VirtualBox) on MacOS host
- zsh shell
- fresh install of linuxbrew as specified on homebrew docs

`brew install warrensbox/tap/tfswitch`
`tfswitch`

**Comment by issyl0** [comment]
We don't officially support installation issues from formulae in third-party taps, but you're in luck as I was feeling curious.

The `tfswitch` formula is [pulling the macOS version](https://github.com/warrensbox/homebrew-tap/blob/master/Formula/tfswitch.rb#L4) on both OSes, which is wrong. It needs some `on_macos` and `on_linux` blocks to differentiate the two platforms' binaries. To help you out, [here's a PR](https://github.com/warrensbox/homebrew-tap/pull/1) that I hope gets accepted.
