### ISSUE TITLE
Cannot install Clozure CL

### ISSUE THREAD

**Issue by tani** [Homebrew/linuxbrew-core#20968]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`$ brew install clozure-cl`

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
brew config
HOMEBREW_VERSION: 2.4.11-99-g6803bf5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 6803bf54f1833ca0646ffa4d366841bd6c451cb9
Last commit: 10 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 5d4f396e9d91656a61644f3618ef056bd67413ec
Core tap last commit: 24 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_EDITOR: emacs
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_EMOJI: set
CPU: octa-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 10.0 build (parse error)
Git: 2.28.0 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.58.0 => /usr/bin/curl
Kernel: Linux 4.15.0-112-generic x86_64 GNU/Linux
OS: Ubuntu 18.04.5 LTS (bionic)
Host glibc: 2.27
/usr/bin/gcc: 7.5.0
glibc: N/A
gcc: 5.5.0_7
xorg: N/A

brew install clozure-cl
==> Downloading https://github.com/Clozure/ccl/releases/download/v1.12/darwinx86.tar.gz
Already downloaded: /home/masaya/.cache/Homebrew/downloads/e8b7404966dff0be15909ede2b50c92af7562529a4000b26c4e9f303077dbd7a--darwinx86.tar.gz
==> Downloading https://github.com/Clozure/ccl/archive/v1.12.tar.gz
Already downloaded: /home/masaya/.cache/Homebrew/downloads/49c7250b676dc5b9c927d9514e8860869934be8c0a55b80cba2017f91f357805--ccl-1.12.tar.gz
==> make
Last 15 lines from /home/masaya/.cache/Homebrew/Logs/clozure-cl/01.make:
Assembler messages:
Assembler messages:
Assembler messages:
Fatal error: Fatal error: Fatal error: Fatal error: invalid listing option `r'invalid listing option `r'invalid listing option `r'invalid listing option `r'

Makefile:57: recipe for target 'imports.o' failed
make: *** [imports.o] Error 1
Makefile:57: recipe for target 'x86-subprims64.o' failed
make: *** [x86-subprims64.o] Error 1
Makefile:57: recipe for target 'x86-spjump64.o' failed
make: *** [x86-spjump64.o] Error 1
Makefile:57: recipe for target 'x86-spentry64.o' failed
make: *** [x86-spentry64.o] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

  </pre>
</details>

## What you expected to happen

Install clozure-cl with a bootstrap distributed by Clozure CL for Linux but it seems to download the bootstrap for macOS.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install clozure-cl`

**Comment by jonchang** [comment]
Thanks for reporting this issue. Unfortunately I don't have time to address this for you, but the issue with many formulae that need to bootstrap themselves is that the bootstrap binaries differ between macOS and Linux. For examples of how we address this, you can check the `sbcl` and `openjdk` formulae. Basically: point the bootstrap binaries in the same place, then make sure all the paths line up between the macOS and Linux versions. Feel free to open a partial pull request and cc me if you need help.
