### ISSUE TITLE
ocrmypdf: Request for a bottle

### ISSUE THREAD

**Issue by clpo13** [Homebrew/linuxbrew-core#20990]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] checked that there aren't other open issues for the same formula bottle request?
- [X] does the FORMULA not have the `bottle` block?
- [X] ran `brew install FORMULA` and it succeeded?

There's currently no Linux bottle for ocrmypdf 11.0.1. It builds successfully on my machine.

**Comment by jonchang** [comment]
https://github.com/Homebrew/linuxbrew-core/runs/1011299917?check_suite_focus=true

I already started a job based on your other issue. Should be done any minute now. Thanks for fixing the upstream issue!
