### ISSUE TITLE
adoptopenjdk and adoptopenjdk@11: Request for update

### ISSUE THREAD

**Issue by filunK** [Homebrew/linuxbrew-core#20993]
These Formula do not apply its latest version. Please update.

Current formula uses;

adoptopenjdk: 1.8.0.242
adoptopenjdk@11: 11.0.3.7

But the latest version for the AdoptOpenJDK;

adoptopenjdk: 8u265-b01 (1.8.0.265)
adoptopenjdk@11: 11.0.8_10 (11.0.8.10)

- [x] checked that there aren't other open issues for the same formula bottle request?
- [x] does the FORMULA not have the `bottle` block?
- [x] ran `brew install FORMULA` and it succeeded?

**Comment by issyl0** [comment]
#21085 and #21086 will close this, when they're passing CI and merged!
