### ISSUE TITLE
libcanberra: Request for a bottle

### ISSUE THREAD

**Issue by clpo13** [Homebrew/linuxbrew-core#20992]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] checked that there aren't other open issues for the same formula bottle request?
- [X] does the FORMULA not have the `bottle` block?
- [X] ran `brew install FORMULA` and it succeeded?

There's no Linux bottle for libcanberra. It built successfully for me.

**Comment by issyl0** [comment]
This exists as of c3b1ab4de0b1af9db17baf7b77f575e7d4af1ffe. Thanks for the reminder!
