### ISSUE TITLE
Could not install any formulae with patchelf dependency

### ISSUE THREAD

**Issue by dvdantunes** [Homebrew/linuxbrew-core#21033]
- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I'm trying to install any formula and it fails. Even I uninstalled homebrew, deleted cache and reinstalled it and the issue still persists

## What happened (include command output)

I just recently (2020-08-30 20:00 UTC+0) updated homebrew on my machine (`brew update && brew upgrade`) and then I tried to install any formulae (e.g: `brew install yq`) that has `patchelf` as dependency. Then it fails with the following output:

<details>
  <summary>Command output</summary>
  <pre>
==> Downloading http://timelessname.com/elfbin/helloworld.tar.gz
Already downloaded: /home/dvdantunes/.cache/Homebrew/downloads/e8943dd8577098994c9cc5eb1dc934bb5e93f97834dd65be5ea969e1d144deec--helloworld.tar.gz
==> Downloading https://github.com/NixOS/patchelf/archive/0.11.tar.gz
Already downloaded: /home/dvdantunes/.cache/Homebrew/downloads/bbcd82d38c35bbbe19f8fc9c11c1a6a9294473a0c235cd5d295718d3108dd349--patchelf-0.11.tar.gz
==> Downloading https://linuxbrew.bintray.com/bottles/yq-3.3.2.x86_64_linux.bottle.tar.gz
Already downloaded: /home/dvdantunes/.cache/Homebrew/downloads/386bea151c3413d35af006725746eb1f55fad680bcebda64a713c2b61cbdef1d--yq-3.3.2.x86_64_linux.bottle.tar.gz
==> Installing dependencies for yq: patchelf
==> Installing yq dependency: patchelf
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/patchelf/0.11 CXXFLAGS=-static-libgcc -static-libstdc++
Last 15 lines from /home/dvdantunes/.cache/Homebrew/Logs/patchelf/01.configure:
2020-08-29 23:49:08 -0400

./configure
--prefix=/home/linuxbrew/.linuxbrew/Cellar/patchelf/0.11
CXXFLAGS=-static-libgcc -static-libstdc++
--disable-debug
--disable-dependency-tracking
--disable-silent-rules

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
patchelf 0.12 https://github.com/Homebrew/linuxbrew-core/pull/21032

  </pre>
</details>

<details>
  <summary>Patchelf configure log (includes the error and brew config)</summary>
  <pre>
2020-08-29 23:37:38 -0400

./configure
--prefix=/home/linuxbrew/.linuxbrew/Cellar/patchelf/0.11
CXXFLAGS=-static-libgcc -static-libstdc++
--disable-debug
--disable-dependency-tracking
--disable-silent-rules

HOMEBREW_VERSION: 2.4.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: fa39db0192c3641ed18abf93371c31e3a220348f
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: a394692bb5092789dd8cf49561bf52cf61a1d228
Core tap last commit: 6 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :1
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 10.0 build (parse error)
Git: 2.26.2 => /bin/git
Curl: 7.69.1 => /usr/bin/curl
Kernel: Linux 5.7.16-200.fc32.x86_64 x86_64 GNU/Linux
OS: Fedora release 32 (Thirty Two)
Host glibc: 2.31
/usr/bin/gcc: 10.2.1
glibc: N/A
gcc: N/A
xorg: N/A

HOMEBREW_CC: gcc
HOMEBREW_CXX: g++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /home/linuxbrew/.linuxbrew
HOMEBREW_GIT: git
PATH: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super:/usr/bin:/bin:/usr/sbin:/sbin
  </pre>
</details>

## What you expected to happen

I expect that any formulae that has `patchelf` dependency could work

## Step-by-step reproduction instructions (by running `brew install` commands)

1. `brew update && brew upgrade`
2. `brew install yq`
3. Installation aborts due the patchelf dependency error 

## Additional info

*brew --version*
```
Homebrew 2.4.14
Homebrew/linuxbrew-core (git revision a39469; last commit 2020-08-29)
```

*brew config*
```
HOMEBREW_VERSION: 2.4.14
ORIGIN: https://github.com/Homebrew/brew
HEAD: fa39db0192c3641ed18abf93371c31e3a220348f
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: a394692bb5092789dd8cf49561bf52cf61a1d228
Core tap last commit: 6 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :1
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 4
CPU: quad-core 64-bit skylake
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
Clang: 10.0 build (parse error)
Git: 2.26.2 => /bin/git
Curl: 7.69.1 => /usr/bin/curl
Kernel: Linux 5.7.16-200.fc32.x86_64 x86_64 GNU/Linux
OS: Fedora release 32 (Thirty Two)
Host glibc: 2.31
/usr/bin/gcc: 10.2.1
glibc: N/A
gcc: N/A
xorg: N/A

HOMEBREW_CC: gcc
HOMEBREW_CXX: g++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /home/linuxbrew/.linuxbrew
HOMEBREW_GIT: git
PATH: /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by iMichka** [comment]
Fixed by 311fd33a5628b438772073601422e271b244d1b3

**Comment by chrisgloom** [comment]
@iMichka was just running into this for the past few hours and thought it was on my end. Thanks so much for the quick fix!

**Comment by dvdantunes** [comment]
Thanks @iMichka for such a quick fix!
