### ISSUE TITLE
zookeeper fails --build-from-source

### ISSUE THREAD

**Issue by jkt628** [Homebrew/linuxbrew-core#21108]
# Bug report

for the last few months `zookeeper` has failed to upgrade or install on ubuntu 20.04 or fedora 30.  i checked macOS with

```bash
brew reinstall -s zookeeper
```

and it had no problem so i guess this is a linuxbrew problem.

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?

note: `brew doctor` reports a deprecated package that is still a dependency but that is all.

- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew upgrade zookeeper`
`brew reinstall -s zookeeper`

## What happened (include command output)

quite prominent build failure "No such file or directory".  you can find more detail in the Command output and [gist-logs](https://gist.github.com/b7684828f97eb4ca996ebc42756f7195).

<details>
  <summary>Command output</summary>
  <pre>

```text
==> Installing zookeeper
==> mvn install -Pfull-build -DskipTests
Last 15 lines from /home/thomasso/.cache/Homebrew/Logs/zookeeper/01.mvn:
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:26 min
[INFO] Finished at: 2020-09-15T20:26:25-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (generate-Java-Jute) on project zookeeper-jute: Command execution failed.: Cannot run program "java" (in directory "/tmp/zookeeper-20200915-20700-a5wd1p/apache-zookeeper-3.6.2/zookeeper-jute/target/generated-sources/java"): error=2, No such file or directory -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :zookeeper-jute
```

  </pre>
</details>

## What you expected to happen

no errors, successful install.

i also wonder if the absence of a bottle points to a similar failure on the build systems.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew reinstall -s zookeeper`

**Comment by jkt628** [comment]
still failing today

**Comment by jonchang** [comment]
We haven't been able to get zookeeper to build on Linux since it moved from ant to maven for its build system. If you can help out by making a pull request to fix this it would be appreciated.

**Comment by clpo13** [comment]
Fixed in 52eef80.

**Comment by jkt628** [comment]
@clpo13 thanks! hopefully this gets through the system quickly.

**Comment by iMichka** [comment]
It's merged in linuxbrew-core now and I added a linux bottle.

Thanks for all the hard work!
