### ISSUE TITLE
brew installs breaking helm package - fails in v.3.3.2 and v.3.3.3

### ISSUE THREAD

**Issue by darkn3rd** [Homebrew/linuxbrew-core#21116]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Trying to use `helm` with `helmfile`.  Installation installs a breaking helm version.

## What happened (include command output)

The command `helm repo add <name> <url>` is no longer idempotent and will fail when there is no failure.  This breaks other tools like `helmfile`.  Earlier version, `v.3.3.1` works fine.

<details>
  <summary>Command output</summary>
  <pre>Error: repository name (jaegertracing) already exists, please specify a different name</pre>
</details>

## What you expected to happen

I expected to have a functional version of `helm`.  Instead I have a version of `helm` that is no longer idempotent and tools that rely on `helm`, such as `helmfile`, no longer work.  Please revert back to `v3.3.1` until they fix this issue.

## Step-by-step reproduction instructions (by running `brew install` commands)

```bash
brew install helm
brew install helmfile
helm repo add jaegertracing https://jaegertracing.github.io/helm-charts
helm repo add jaegertracing https://jaegertracing.github.io/helm-charts

cat <<-EOF > helmfile.yaml
repositories:
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts
EOF
helmfile apply
```

**Comment by jonchang** [comment]
This is not a Homebrew bug. Please report this to the helm maintainers.
