### ISSUE TITLE
`Error: Too many open files` eg for `brew install opencv` that has lots of dependencies

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/linuxbrew-core#21139]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

tried on multiple systems (fresh VM's, fresh brew install)

## What you were trying to do (and why)

`brew install opencv`

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>
...
==> Pouring libass-0.14.0_1.x86_64_linux.bottle.1.tar.gz                                                                   ==> Installing opencv dependency: adoptopenjdk                                                                             Error: Too many open files                                                                                                 
  </pre>
</details>

## What you expected to happen

works

## Step-by-step reproduction instructions (by running `brew install` commands)

from a fresh linuxbrew install (under /home/linuxbrew/.linuxbrew/), run `brew install opencv`

it has many dependencies and eventually fails with `Error: Too many open files`

it looks like a regression.
maybe some file descriptors are not being closed?

this likely could happen with other formulas, shouldn't be specific to opencv.

I reproduced this on several systems (including fresh VM's in EC2 with 8CPU/32GB RAM)

## workaround
keep running `brew install opencv` until it works as it makes progress each time by installing dependecies (but it adds a lot of overhead)

(note that it eventually fails for unrelated reasons, with `qt`: https://github.com/Homebrew/linuxbrew-core/issues/21130; EDIT: that one just got fixed)

**Comment by timotheecour** [comment]
this is worse than i initially thought, as it also affects semantics, eg:

here are logs from `brew install opencv`:

```nim
==> Installing opencv dependency: vtk
==> Pouring vtk-9.0.1.x86_64_linux.bottle.tar.gz
Error: Too many open files @ rb_sysopen - /home/linuxbrew/.linuxbrew/Cellar/vtk/9.0.1/lib/libvtkInfovisBoostGraphAlgorithms-9.0.so.9.0.1
Warning: Bottle installation failed: building from source.
==> Downloading https://www.vtk.org/files/release/9.0/VTK-9.0.1.tar.gz
```

=> it fails for unrelated reason (Too many open files) and then builds from source (which can be much slower) instead of building from bottle

**Comment by danielnachun** [comment]
This looks like an error I receive on one of the HPC systems I work with which limits the number of files than can be open if I don't request a dedicated interactive job with Slurm.  If you are on a system managed by a job scheduler, you might want to check if that helps.  If you are not or are already running in a job environment, I would try to investigate how to increase the limit on the number of open files allowed.  This would require administrative access and can't be controlled by Homebrew.

**Comment by timotheecour** [comment]
as mentioned in OP:
> I reproduced this on several systems (including fresh VM's in EC2 with 8CPU/32GB RAM)

(and also in ubuntu installed via parallels IIRC).
This just seems like a homebrew/linuxbrew bug: files for a formula be closed once the corresponding formula was built.

**Comment by danielnachun** [comment]
Oh I understand.  I guess in some VM environments the number of files allowed to be opened is limited.  It does seem like a bug or something that just wasn't optimized for this situation.  Perhaps that is something to be taken up with the main Homebrew repository?  Since it is probably not package-specific, just a function of how many files a given package uses.

**Comment by timotheecour** [comment]
=> https://github.com/Homebrew/brew/issues/9120

**Comment by timotheecour** [comment]
still relevant

**Comment by jonchang** [comment]
Please open a pull request to Homebrew/brew to fix this, as you were asked to in the issue you filed: https://github.com/Homebrew/brew/issues/9120#issuecomment-726699074
