### ISSUE TITLE
brew install qt fails: expected replacement of "python " with "python3 "

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/linuxbrew-core#21130]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

brew install qt (ran by brew install opencv)

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

==> Downloading https://codereview.qt-project.org/gitweb?p=qt/qt3d.git;a=patch;h=b456a7d47a36dc34
Already downloaded: /home/ubuntu/.cache/Homebrew/downloads/774933b2edc2b03911f16fa69ce84d09bb00b50ac9004cfc61999fca37713e25--qt3d.git-b456a7d47a36dc3429a5e7bac7665b12d257efea.patch
==> Downloading https://download.qt.io/official_releases/qt/5.15/5.15.1/single/qt-everywhere-src-
Already downloaded: /home/ubuntu/.cache/Homebrew/downloads/bbb4dae1de0205b5bf7d92b88f39540433452b5a8029a9827139c8611d7aeac5--qt-everywhere-src-5.15.1.tar.xz
==> Patching
==> Applying qt3d.git-b456a7d47a36dc3429a5e7bac7665b12d257efea.patch
patching file src/core/transforms/vector3d_sse.cpp
patching file src/core/transforms/vector3d_sse_p.h
Hunk #2 succeeded at 348 with fuzz 2.
Error: An exception occurred within a child process:
  Utils::Inreplace::Error: inreplace failed
qtdeclarative/qtdeclarative.pro:
  expected replacement of "python " with "python3 "
qtdeclarative/src/3rdparty/masm/masm.pri:
  expected replacement of "python " with "python3 "
  </pre>
</details>

## What you expected to happen

works

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install qt

## 
on 2 different systems, output of brew gist-logs qt:
https://gist.github.com/timotheecour/2e0e12f469c3b870bf1759cc72e072b4
https://gist.github.com/timotheecour/dc10465c551e93ad38f4704517698e9c

**Comment by issyl0** [comment]
Thanks for the issue, @timotheecour. I fixed this in https://github.com/Homebrew/linuxbrew-core/pull/21138, so if you `brew update` and try installing QT again, it should succeed now. Thanks for using Homebrew on Linux!
