### ISSUE TITLE
vivid: Request for a bottle

### ISSUE THREAD

**Issue by SimplyDanny** [Homebrew/linuxbrew-core#21146]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] checked that there aren't other open issues for the same formula bottle request?
- [x] does the FORMULA not have the `bottle` block?
- [x] ran `brew install FORMULA` and it succeeded?

**Comment by issyl0** [comment]
Thanks for this issue - the `vivid` formula is now bottled for Linux.
