### ISSUE TITLE
`brew install bazel`: JAVA_HOME is not a path to a working JDK.

### ISSUE THREAD

**Issue by baranyildirim** [Homebrew/linuxbrew-core#21182]
# Bug report

Created a pull request to address this: #21161

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

https://gist.github.com/3e7c1ba8e4a58fde86e8b7cb8d01df27

## What you were trying to do (and why)

Trying to install bazel

https://formulae.brew.sh/formula/bazel

## What happened (include command output)

Error: cannot install bazel due to incorrect JAVA_HOME

The JAVA_HOME environment variable is being set incorrectly by the bazel formula. The formula uses MacOS style Java directories that do not exist on Linux. See #21161.

<details>
  <summary>Command output</summary>
  <pre>

==> Installing bazel
==> ./compile.sh
Last 15 lines from /home/baran/.cache/Homebrew/Logs/bazel/01.compile.sh:
2020-10-01 17:42:14 -0400

./compile.sh

Building Bazel from scratch
ERROR: JAVA_HOME (/home/<...>/homebrew/opt/openjdk@11/libexec/openjdk.jdk/Contents/Home) is not a path to a working JDK.

  </pre>
</details>

## What you expected to happen

Should correctly install bazel

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install bazel`

**Comment by baranyildirim** [comment]
Found this earlier pull request on the same issue #20348. 

Is there a reason no one wants to fully fix bazel on linuxbrew?

**Comment by dawidd6** [comment]
It's not that we don't want to fix it. We just don't know how to do it and would use some help with that.

**Comment by baranyildirim** [comment]
Okay, I understand. I will try to create a PR that fully passes CI.

**Comment by baranyildirim** [comment]
still active

**Comment by limzykenneth** [comment]
Any progress on this? Is there a workaround in the meantime (editing the formula locally etc)?

**Comment by iMichka** [comment]
No progress as far as I know of. And no workaround. We have been unable to build bazel from source since 1-2 years now and have already put a lot of effort to fix it ...

**Comment by jonchang** [comment]
> It's not that we don't want to fix it. We just don't know how to do it and would use some help with that.

This is still true.

**Comment by baranyildirim** [comment]
I tried debugging but couldn’t get anywhere with the formula. I gave up and just used the prebuilt release.
