### ISSUE TITLE
openjdk: configure failed 14.0.1_1

### ISSUE THREAD

**Issue by ycrack** [Homebrew/linuxbrew-core#21213]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Upgrade the `ffmpeg`. It requires `openjdk`, then I faced this issue.
This issue also happens in the case of installing.

## What happened (include command output)

https://gist.github.com/effaf4dc04382cf07f1f89be59661e03

<details>
  <summary>Command output</summary>
  <pre>

  $ brew upgrade openjdk
==> Upgrading 1 outdated package:
openjdk 14.0.1 -> 14.0.1_1
==> Upgrading openjdk 14.0.1 -> 14.0.1_1
==> Downloading https://download.java.net/java/GA/jdk13.0.2/d4173c853231432d94f001e99d882ca7/8/GPL/openjdk-13.0.2_linux-x64_bin.tar.gz
######################################################################## 100.0%
==> Downloading https://hg.openjdk.java.net/jdk-updates/jdk14u/archive/jdk-14.0.1-ga.tar.bz2
                                            #     #     #    #          -=O=-
==> ./configure --without-version-pre --without-version-opt --with-version-build=14.0.1 --with-toolchain-path=/usr/bin  --with-boot-jdk=/tmp/openjdk-20201006-20234-1v7gfer/
Last 15 lines from /home/ycrack/.cache/Homebrew/Logs/openjdk/01.configure:
checking pkg-config is at least version 0.9.0... yes
checking for default LOG value...
checking headless only... no
checking for graphviz dot... no, cannot generate full docs
checking for pandoc... no, cannot generate full docs
checking full docs... no, missing dependencies
checking for cacerts file... default
checking for jni library path... default
checking if packaged modules are kept... yes (default)
configure: WARNING: Value for VERSION_BUILD has been sanitized from '14.0.1' to '14'
checking for version string... 14.0.1+14
configure: Found potential Boot JDK using configure arguments
configure: Potential Boot JDK found at /tmp/openjdk-20201006-20234-1v7gfer/jdk14u-jdk-14.0.1-ga/boot-jdk did not contain bin/java; ignoring
configure: error: The path given by --with-boot-jdk does not contain a valid Boot JDK
configure exiting with result code 1

READ THIS: https://docs.brew.sh/Troubleshooting

  </pre>
</details>

## What you expected to happen

works collectly

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install openjdk`

**Comment by black-snow** [comment]
Same, upgrading openjdk from 14.0.1 to 14.0.1_1.

**Comment by cbcoutinho** [comment]
I ran into the same issue. Looks like a broken Makefile target:

> ERROR: Build failed for target 'images' in configuration 'linux-x86_64-server-release' (exit code 2)

Verbose output when installing `openjdk` using Homebrew on openSUSE Tumbleweed.

[00.options.out.txt](https://github.com/Homebrew/linuxbrew-core/files/5334429/00.options.out.txt)

[01.configure.txt](https://github.com/Homebrew/linuxbrew-core/files/5334430/01.configure.txt)

[02.make.txt](https://github.com/Homebrew/linuxbrew-core/files/5334431/02.make.txt)

**Comment by jonchang** [comment]
Hi all, thanks for collating these reports. As you all can tell, the Homebrew maintainers are quite shorthanded and often don't have the time to track down problems, especially for challenging builds for languages and build systems that the current maintainers are not familiar with. The best thing to do, as dedicated users and contributors, would be to either link to our failing CI workflow run (it'll usually exist, just be hard to find), ideally with the failing lines pasted into an issue, or just opening up a pull request with a revision bump. CI workers are not limited on Linux as they are on macOS, so don't feel guilty about opening a pull request if you really want to help get something fixed.

Thanks!

**Comment by clpo13** [comment]
I think this problem is partially related to WSL. On WSL, the configure script automatically detects that it's running in WSL and sets the build target to `x86_64-pc-wsl`, which causes the boot JDK detection step to fail (presumably because the boot JDK was built with a different target). Specifying `--build=x86_64-unknown-linux-gnu` fixed that, but then I ran into a build error (not the same one as cboutinho): https://gist.github.com/clpo13/9e8df29fbaad96949da295afbc7d0c04.
