### ISSUE TITLE
openjdk: exec format error on WSL

### ISSUE THREAD

**Issue by clpo13** [Homebrew/linuxbrew-core#21293]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [X] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I'm trying to update the portmidi formula to work on Linux, and I included openjdk as a dependency.

## What happened (include command output)

After a lot of tinkering, the formula compiles successfully up until it calls `javac` to compile a Java file, at which point I get an error that `javac` can't be run:

```console
$ brew install -dv portmidi
[ 95%] Generating pmdefaults/PmDefaults.class
cd /tmp/portmidi-20201016-19703-10mqtna/portmidi/pm_java && javac -classpath . pmdefaults/PmDefaults.java
/bin/sh: 1: javac: Exec format error
```

portmidi logs: https://gist.github.com/cb628ed028300cbd6196a77e86e887c5

I'm running Debian on Windows Subsystem for Linux and can successfully run `java` and `javac` from adoptopenjdk and adoptopenjdk@11, but portmidi doesn't compile using either of those as a dependency, so that's no good. On native Linux, I don't have this problem at all. Here's what I get running `file`:

```console
$ file /home/linuxbrew/.linuxbrew/Cellar/openjdk/14.0.1_1/libexec/bin/javac
/home/linuxbrew/.linuxbrew/Cellar/openjdk/14.0.1_1/libexec/bin/javac: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /home/linuxbrew/.linuxbrew/lib/ld.so, BuildID[sha1]=44f887511e94b9a3c373774bbc619fb839d9e1e0, for GNU/Linux 2.6.32, not stripped
$ file /home/linuxbrew/.linuxbrew/Cellar/adoptopenjdk/1.8.0.242/bin/javac
/home/linuxbrew/.linuxbrew/Cellar/adoptopenjdk/1.8.0.242/bin/javac: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=0287d9757c7187a6a12120271e4717833373762f, not stripped
```

<details>
  <summary>brew test openjdk</summary>
  <pre>==> Testing openjdk
==> /home/linuxbrew/.linuxbrew/Cellar/openjdk/14.0.1_1/bin/javac HelloWorld.java
Last 15 lines from /home/cody/.cache/Homebrew/Logs/openjdk/test.01.javac:
2020-10-16 17:06:25 -0700

/home/linuxbrew/.linuxbrew/Cellar/openjdk/14.0.1_1/bin/javac
HelloWorld.java

/home/linuxbrew/.linuxbrew/Cellar/openjdk/14.0.1_1/bin/javac: 1: /home/linuxbrew/.linuxbrew/Cellar/openjdk/14.0.1_1/bin/javac: ELF: not found
/home/linuxbrew/.linuxbrew/Cellar/openjdk/14.0.1_1/bin/javac: 2: /home/linuxbrew/.linuxbrew/Cellar/openjdk/14.0.1_1/bin/javac: @: not found
/home/linuxbrew/.linuxbrew/Cellar/openjdk/14.0.1_1/bin/javac: 3: /home/linuxbrew/.linuxbrew/Cellar/openjdk/14.0.1_1/bin/javac: �: not found
/home/linuxbrew/.linuxbrew/Cellar/openjdk/14.0.1_1/bin/javac: 4: /home/linuxbrew/.linuxbrew/Cellar/openjdk/14.0.1_1/bin/javac: �J�:: not found
/home/linuxbrew/.linuxbrew/Cellar/openjdk/14.0.1_1/bin/javac: 7: /home/linuxbrew/.linuxbrew/Cellar/openjdk/14.0.1_1/bin/javac: Syntax error: ")" unexpected
Error: openjdk: failed
An exception occurred within a child process:
  BuildError: Failed executing: /home/linuxbrew/.linuxbrew/Cellar/openjdk/14.0.1_1/bin/javac HelloWorld.java
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2033:in `block in system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1971:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1971:in `system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/openjdk.rb:107:in `block in <class:Openjdk>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1842:in `block (3 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:497:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1841:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:901:in `with_logging'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1840:in `block in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:58:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:58:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:58:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2082:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:1834:in `run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:43:in `block in <main>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:42:in `<main>'</pre>
</details>

<details>
  <summary>brew config</summary>
  <pre>HOMEBREW_VERSION: 2.5.6
ORIGIN: https://github.com/Homebrew/brew
HEAD: abf214c01ff1edb57acf7e23d5eb24a777335e11
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 857dcd00b860804cf67de9d7b80e62b791df882a
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_GITHUB_API_TOKEN: set
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit skylake
Clang: N/A
Git: 2.20.1 => /usr/bin/git
Curl: 7.64.0 => /usr/bin/curl
Kernel: Linux 4.4.0-19041-Microsoft x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.28
/usr/bin/gcc: 8.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc: 5.5.0_7
xorg: N/A</pre>
</details>

<details>
  <summary>brew doctor</summary>
  <pre>Your system is ready to brew.</pre>
</details>

## What you expected to happen

I expected `javac` from openjdk to successfully compile Java files.

## Step-by-step reproduction instructions (by running `brew install` commands)

```console
$ brew install openjdk
<openjdk and its dependencies are installed>
$ /home/linuxbrew/.linuxbrew/opt/openjdk/bin/javac -version
bash: /home/linuxbrew/.linuxbrew/opt/openjdk/bin/javac: cannot execute binary file: Exec format error
```

**Comment by jonchang** [comment]
See https://github.com/Homebrew/linuxbrew-core/issues/20393#issuecomment-639533146. We aren't sure what causes this error on WSLv1, nor how to fix it for everyone. Upgrading to WSLv2 may fix this issue.

**Comment by clpo13** [comment]
Interesting. I don't recall having this problem with openjdk before, but testing on WSLv2 fixed it, as did building openjdk from source on WSLv1. Thanks for pointing me in the right direction.
