### ISSUE TITLE
git: Request for a bottle

### ISSUE THREAD

**Issue by mikesep** [Homebrew/linuxbrew-core#21309]
- [x] checked that there aren't other open issues for the same formula bottle request?
- [ ] does the FORMULA not have the `bottle` block?
- [x] ran `brew install FORMULA` and it succeeded?

Not sure why, but there doesn't appear to be an `x86_64_linux` bottle for [`git`](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/git.rb) as of 2.29.0. [`git-gui`](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/git-gui.rb) does have one, though.

I did check that `brew install git` builds and works on my machine. Sorry if I missed something obvious.

**Comment by dawidd6** [comment]
@jonchang failed workflow run: https://github.com/Homebrew/linuxbrew-core/runs/1280936989?check_suite_focus=true

**Comment by dawidd6** [comment]
Done: https://github.com/Homebrew/linuxbrew-core/commit/62ca5c7f83274bbc3235518ceef73801eea80041

**Comment by mikesep** [comment]
Thanks @dawidd6!
