### ISSUE TITLE
openjdk invalid hash

### ISSUE THREAD

**Issue by slimjim2234** [Homebrew/linuxbrew-core#21354]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew upgrade`

## What happened (include command output)

`SHA256 mismatch on openjdk -14.0.2`
Expected: `bb67...`
Actual: `9131...`

To fix it:

https://github.com/Homebrew/linuxbrew-core/blob/62c884fee9af26ab901c16441c80d95d5418ed5b/Formula/openjdk.rb#L45

This should be 91310200f072045dc6cef2c8c23e7e6387b37c46e9de49623ce0fa461a24623d

The value that's currently there is for the following file
https://download.java.net/java/GA/jdk15/779bf45e88a44cbd9ea6621d33e33db1/36/GPL/openjdk-15_linux-x64_bin.tar.gz.sha256

Notice it's right hash on the wrong file.  Either change the hash or change the file.

**Comment by iMichka** [comment]
Fix by a95cc469feb554636e780e75c846652ab81613e4

Sorry I made a copy-past error this morning and did not see your issue right away. I am building bottles right now.

**Comment by slimjim2234** [comment]
> Fix by [a95cc46](https://github.com/Homebrew/linuxbrew-core/commit/a95cc469feb554636e780e75c846652ab81613e4)
> 
> Sorry I made a copy-past error this morning and did not see your issue right away. I am building bottles right now.

right on, thanks!

**Comment by iMichka** [comment]
I have a follow-up PR too with another fix: #21357
