### ISSUE TITLE
dotenv-linter: Request for a bottle

### ISSUE THREAD

**Issue by mgrachev** [Homebrew/linuxbrew-core#21401]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] checked that there aren't other open issues for the same formula bottle request?
- [ ] does the FORMULA not have the `bottle` block?
- [x] ran `brew install FORMULA` and it succeeded?

**Comment by iMichka** [comment]
Done with 8fb1e2f53c14311c7199bff941d4e675aa6eeb74

**Comment by mgrachev** [comment]
Thank you! 🙂
