### ISSUE TITLE
Cant install id3lib

### ISSUE THREAD

**Issue by xsteadfastx** [Homebrew/linuxbrew-core#21417]
# Bug report

- [X] ran `brew update` and can still reproduce the problem?
- [X] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [X] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?

## What you were trying to do (and why)

Install abcde and or id3lib

## What happened (include command output)

https://gist.github.com/xsteadfastx/041147bc216cc348a7c5945fddd5e19d

<details>
  <summary>Command output</summary>
  <pre>

  
==> make install
Last 15 lines from /home/marv/.cache/Homebrew/Logs/id3lib/03.make:
       text += strlen(text) + 1;
               ^~~~~~
field_string_ascii.cpp:282:15: note: suggested alternative: ‘mbrlen’
       text += strlen(text) + 1;
               ^~~~~~
               mbrlen
Makefile:585: recipe for target 'c_wrapper.lo' failed
make[1]: *** [c_wrapper.lo] Error 1
Makefile:585: recipe for target 'field_string_ascii.lo' failed
make[1]: *** [field_string_ascii.lo] Error 1
libtool: compile:  g++-7 -DHAVE_CONFIG_H -I. -I.. -I../include/id3 -I../include -g -O2 -Wall -Wno-unused -Wno-inline -Woverloaded-virtual -Wmissing-declarations -c frame.cpp -o frame.o >/dev/null 2>&1
libtool: compile:  g++-7 -DHAVE_CONFIG_H -I. -I.. -I../include/id3 -I../include -g -O2 -Wall -Wno-unused -Wno-inline -Woverloaded-virtual -Wmissing-declarations -c field_binary.cpp -o field_binary.o >/dev/null 2>&1
make[1]: Leaving directory '/tmp/id3lib-20201110-6799-4n0t2f/id3lib-3.8.3/src'
Makefile:448: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
  </pre>
</details>

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install id3lib`

**Comment by xsteadfastx** [comment]
it looks like id3lib is not needed for abcde: https://github.com/Homebrew/linuxbrew-core/pull/21422

**Comment by xsteadfastx** [comment]
should i close this? even if this is still failing to compile?

**Comment by iMichka** [comment]
I am not interested on fixing this, so anyone can pick it up. I added a bottle for abcde so you should be good to go.
