### ISSUE TITLE
gcc depends on deprecated isl@0.18

### ISSUE THREAD

**Issue by black-snow** [Homebrew/linuxbrew-core#21424]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

`brew doctor` complains about `isl@0.18` being deprecated. I found that `gcc` is the only package that I have installed and that `depends_on "isl@0.18"`.

<details>
  <summary>Command output</summary>
  <pre>
Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  isl@0.18
  </pre>
</details>

https://github.com/Homebrew/linuxbrew-core/blob/HEAD/Formula/gcc.rb#L49

Was deprecated here: https://github.com/Homebrew/linuxbrew-core/commit/d345a5e45b8bbddd8c0f33d463efd367a5b23098#diff-0d1611ec4572ccf32c915945728e5d929b2cd036cda3be0739660224ec885316

It might be enough to drop the `OS.mac?` check for isl alltogether.

## Step-by-step reproduction instructions (by running `brew install` commands)

```
brew install gcc
brew doctor
```

**Comment by iMichka** [comment]
Don't worry; it's just a warning. I am doing a gcc cleanup here: #21380, so this will fix it.
