### ISSUE TITLE
Unable to install awscli on Linux

### ISSUE THREAD

**Issue by ashokm** [Homebrew/linuxbrew-core#21534]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Install `awscli` on Ubuntu 20.04.1 LTS

## What happened (include command output)

**Failed to install `awscli`.** See Command output:
<details>
  <summary>Command output</summary>
  <pre>

$ brew install awscli
Updating Homebrew...
libiconv: is not needed on Linux, where iconv.h is provided by glibc
Error: An unsatisfied requirement failed this build.

  </pre>
</details>

**brew doctor**
<details>
  <summary>Command output</summary>
  <pre>

$ brew doctor
Your system is ready to brew.

  </pre>
</details>

**brew config**
<details>
  <summary>Command output</summary>
  <pre>

$ brew config
HOMEBREW_VERSION: 2.5.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 07b3aa69f8dc5098437cf2562864558bae2d45aa
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 4e33a2578991defde97057072561bb9eeff4b171
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: N/A
Git: 2.29.2 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 4.19.104-microsoft-standard x86_64 GNU/Linux
OS: Ubuntu 20.04.1 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc: N/A
xorg: N/A

  </pre>
</details>

**brew gist-logs**
<details>
  <summary>Command output</summary>
  <pre>

$ brew gist-logs awscli
Error: No logs.

  </pre>
</details>

## What you expected to happen

`awscli` should be installed

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install awscli

**Comment by ChrisWiegman** [comment]
I'm wondering if this is related to #21533? It is clearly listed as a dep in the tree for `awscli` and not for `php` though.

**Comment by ashokm** [comment]
Might be related to:
* https://github.com/Homebrew/linuxbrew-core/pull/21532
* https://github.com/Homebrew/linuxbrew-core/pull/21532/commits/4ff488ffc18315c31824df560a19e627cc656a57

**Comment by iMichka** [comment]
Working on a fix here: #21539
