### ISSUE TITLE
SHA256 mismatch when installing cdparanoia.

### ISSUE THREAD

**Issue by ShellyYBlack** [Homebrew/linuxbrew-core#21543]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

Trying to install cdparanoia. Please note that I am running Ubuntu 20.04.1 via Hyper-V on Windows 10.

## What happened (include command output)

The install failed. See below for that output, plus the results of the checklist.

<details>
  <summary>Command output</summary>
  <pre>
shelly@shelly-Virtual-Machine:~$ brew install cdparanoia
==> Downloading https://gist.githubusercontent.com/iMichka/c6d0ed5adb5375a8117d7c06999ae1be/raw/1592803a16ede7d3e8e15a
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 496f53d21dde7e23f4c9cf1cc28219efcbb5464fe2abbd5a073635279281c9c4
  Actual: b648de4485d04cb91ccd8ed9601f20e166c2d7f70751b1a84e554039b4418dee
 Archive: /home/shelly/.cache/Homebrew/downloads/e4829cee5c3b991516d719cefc6800cb3439c04a2527f5021ac85bbec18e79ca--cdparanoia-fpic
To retry an incomplete download, remove the file above.
shelly@shelly-Virtual-Machine:~$ brew doctor
Your system is ready to brew.
shelly@shelly-Virtual-Machine:~$ brew gist-logs cdparanoia
Error: No logs.
shelly@shelly-Virtual-Machine:~$ brew config
HOMEBREW_VERSION: 2.5.11
ORIGIN: https://github.com/Homebrew/brew
HEAD: 07b3aa69f8dc5098437cf2562864558bae2d45aa
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: a70af2c7f99a5c4a3678c5031e9a45740d86780d
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 6
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: hexa-core 64-bit skylake
Clang: N/A
Git: 2.29.2 => /home/linuxbrew/.linuxbrew/bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-48-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.1 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc: N/A
xorg: N/A
shelly@shelly-Virtual-Machine:~$ brew doctor
Your system is ready to brew.

  </pre>
</details>

## What you expected to happen

Expected cdparanoia would install.

## Step-by-step reproduction instructions (by running `brew install` commands)

See above. And thanks!

**Comment by iMichka** [comment]
This particular issue has been fixed lately.
