### ISSUE TITLE
Installing bottled apps written in Rust like lsd or fd fails since patchelf 0.12

### ISSUE THREAD

**Issue by tkaehn** [Homebrew/linuxbrew-core#21601]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

$ brew install fd

## What happened (include command output)

Failed to install bottle and installing build dependencies from bottle fails, too.

<details>
  <summary>Command output</summary>
  <pre>
$ brew install fd
==> Downloading https://linuxbrew.bintray.com/bottles/fd-8.1.1.x86_64_linux.bottle.tar.gz
Already downloaded: /home/tk/.cache/Homebrew/downloads/3445da5e235ec70aa07d98d7ed9ff030eff80d9a8ae7f8bfb65995073c5aa19c--fd-8.1.1.x86_64_linux.bottle.tar.gz
==> Pouring fd-8.1.1.x86_64_linux.bottle.tar.gz
patchelf: cannot normalize PT_NOTE segment: non-contiguous SHT_NOTE sections
Error: Failure while executing; `/home/linuxbrew/.linuxbrew/bin/patchelf --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so --force-rpath --set-rpath /home/linuxbrew/.linuxbrew/Cellar/fd/8.1.1/lib:/home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/Cellar/fd/8.1.1/bin/fd` exited with 1.
Warning: Bottle installation failed: building from source.
==> Installing dependencies for fd: openssl@1.1, zlib, libssh2, pkg-config, curl, binutils and rust
==> Installing fd dependency: openssl@1.1
==> Pouring openssl@1.1-1.1.1h.x86_64_linux.bottle.tar.gz
tar: /home/tk/.cache/Homebrew/downloads/4e1927ff86b2ef79cebece52e1ca444bd1a7373e45b521afdebef332cb997a61--openssl@1.1-1.1.1h.x86_64_linux.bottle.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
Error: Failure while executing; `tar xof /home/tk/.cache/Homebrew/downloads/4e1927ff86b2ef79cebece52e1ca444bd1a7373e45b521afdebef332cb997a61--openssl@1.1-1.1.1h.x86_64_linux.bottle.tar.gz -C /tmp/d20201123-21252-qr4tv5` exited with 2. Here's the output:
tar: /home/tk/.cache/Homebrew/downloads/4e1927ff86b2ef79cebece52e1ca444bd1a7373e45b521afdebef332cb997a61--openssl@1.1-1.1.1h.x86_64_linux.bottle.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

Warning: Bottle installation failed: building from source.
[...]

$ brew config
HOMEBREW_VERSION: 2.5.11-178-g1ba26be
ORIGIN: https://github.com/Homebrew/brew
HEAD: 1ba26be10324f2ca7570dc3cb41dc6ec0244564b
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 5acb8228d5b47cae8a770c23397fcdb36edc6bad
Core tap last commit: 10 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :0
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_ANALYTICS: set
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: quad-core 64-bit skylake
Clang: N/A
Git: 2.20.1 => /usr/bin/git
Curl: 7.64.0 => /usr/bin/curl
Kernel: Linux 4.19.0-12-amd64 x86_64 GNU/Linux
OS: Debian GNU/Linux 10 (buster) (buster)
Host glibc: 2.28
/usr/bin/gcc: 8.3.0
/usr/bin/ruby: 2.5.5
glibc: N/A
gcc: N/A
xorg: N/A

$ brew doctor
Your system is ready to brew.
  </pre>
</details>

## What you expected to happen

Installation completing successfully. Switching back to patchelf 0.11 made it possible to install the bottle above.

## Step-by-step reproduction instructions (by running `brew install` commands)

$ brew install fd

**Comment by iMichka** [comment]
> patchelf: cannot normalize PT_NOTE segment: non-contiguous SHT_NOTE sections
Error: Failure while executing; `/home/linuxbrew/.linuxbrew/bin/patchelf --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so --force-rpath --set-rpath /home/linuxbrew/.linuxbrew/Cellar/fd/8.1.1/lib:/home/linuxbrew/.linuxbrew/lib /home/linuxbrew/.linuxbrew/Cellar/fd/8.1.1/bin/fd` exited with 1

@sjackman another patchelf issue.

**Comment by sjackman** [comment]
Opened an upstream bug report at https://github.com/NixOS/patchelf/issues/255

**Comment by sjackman** [comment]
Fortunately, I have a quick and easy work around for you, Thomas!
```console
$ HOMEBREW_PATCHELF_RB_WRITE=1 brew install fd
…
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/fd/8.1.1: 11 files, 3.2MB
```

All the thanks for this fix are owed to @rmNULL!

**Comment by sjackman** [comment]
This issue will be fixed by PR https://github.com/Homebrew/brew/pull/9280.

**Comment by tkaehn** [comment]
Thank you very much for the workaround!
