### ISSUE TITLE
ripgrep: rebuild bottle after patchelf issue

### ISSUE THREAD

**Issue by mikesep** [Homebrew/linuxbrew-core#21696]
- [x] checked that there aren't other open issues for the same formula bottle request?
- [x] does the FORMULA not have the `bottle` block?
- [x] ran `brew install FORMULA` and it succeeded?

-----

When trying to install `ripgrep` from a bottle (using `brew bundle`, though I don't think that's important), I get the following error:

```
==> Installing ripgrep
==> Pouring ripgrep-12.1.1.x86_64_linux.bottle.tar.gz
patchelf: cannot normalize PT_NOTE segment: non-contiguous SHT_NOTE sections
Error: Failure while executing; `/home/linuxbrew/.linuxbrew/bin/patchelf --set-interpreter /home/linuxbrew/.linuxbrew/lib/ld.so --force-rpath --set-rpath /home/linuxbrew/.linuxbrew/Cellar/ripgrep/12.1.1/lib:/home/linuxbrew/.linuxbrew/lib:/home/linuxbrew/.linuxbrew/opt/bzip2/lib:/home/linuxbrew/.linuxbrew/opt/zlib/lib:/home/linuxbrew/.linuxbrew/opt/pcre2/lib /home/linuxbrew/.linuxbrew/Cellar/ripgrep/12.1.1/bin/rg` exited with 1.
Installing ripgrep has failed!
```

I followed the trail to https://github.com/Homebrew/brew/pull/9280, which was only merged a few days ago, so it seems possible/likely that a bottle rebuild for `ripgrep` (and maybe for all Rust bottles?) could fix the issue.

**Comment by ceblan** [comment]
Same problem here

**Comment by mikesep** [comment]
Fixed via the process above. Thanks @dawidd6!
