### ISSUE TITLE
Brew install for pgloader HEAD fails - missing file

### ISSUE THREAD

**Issue by carsonhh** [Homebrew/linuxbrew-core#21742]
## What you were trying to do (and why)

brew install --HEAD pgloader

## What happened (include command output)

brew install for pg loader head fails

$ brew install --HEAD pgloader

<details>
  <summary>Command output</summary>
  <pre>

==> Cloning https://github.com/dimitri/pgloader.git
Updating /Users/cholt/Library/Caches/Homebrew/pgloader--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 63e4eea Add postgres version 13 tto Travis (#1235)
==> Patching
Error: Failure while executing; `patch -g 0 -f -p1` exited with 1. Here's the output:
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- a/local-projects/cl-csv/parser.lisp
|+++ b/local-projects/cl-csv/parser.lisp
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored

  </pre>
</details>

## What you expected to happen

Expected to compile and install

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install --HEAD pgloader

**Comment by issyl0** [comment]
Failing application of patches is to be expected with HEAD installs. We don't officially support HEAD builds, but you can help get it working for others by changing the `patch :DATA` line in the formula to apply to only stable (release) builds. `patch :DATA unless build.head?` should do it. This will have to be done in the [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core) repository. Or, you can wait for a new release of the software when the patch line will be removed from the formula by the person bumping its version.

Thanks for using Homebrew on Linux!
