### ISSUE TITLE
Building R from source on Ubuntu in WSL 2 fails

### ISSUE THREAD

**Issue by Tyrubias** [Homebrew/linuxbrew-core#21759]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [ ] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to install R from source in Ubuntu 20.10 running on WSL 2. The output of `brew gist-logs r` [can be found here](https://gist.github.com/eced8272c083a7e6bff48bd1ea602b8d).

Note that I couldn't quite fix all `brew doctor` issues as `gcc` depends on `isl@0.18`, which is deprecated.

## What happened (include command output)

The build failed with the message that `rpc/types.h` could not be found.

<details>
  <summary>Command output</summary>
  <pre>

  ==> Downloading https://cran.r-project.org/src/base/R-4/R-4.0.3.tar.gz
Already downloaded: /home/vsong/.cache/Homebrew/downloads/d0aba331f24b5d794d1b83d73e826f2ddaeb191efa58fd088d80eaba45d7450b--R-4.0.3.tar.gz
==> Reinstalling r
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/r/4.0.3 --enable-memory-profiling --with-lapack --enable-R-shlib --disable-java --with-blas=-L/home/linuxbrew/.linuxbrew/opt/openblas/lib -lopenblas SED=/usr/bin/sed --libdir=/home/linuxbrew/.
==> make
Last 15 lines from /home/vsong/.cache/Homebrew/Logs/r/02.make:
gcc-5 -I../../src/extra -I/usr/include/tirpc -I. -I../../src/include -I../../src/include -I/home/linuxbrew/.linuxbrew/Cellar/curl/7.74.0/include -I/home/linuxbrew/.linuxbrew/opt/gettext/include -I/home/linuxbrew/.linuxbrew/opt/readline/include -I../../src/nmath -DHAVE_CONFIG_H   -fopenmp -fpic  -g -O2  -c serialize.c -o serialize.o
gcc-5 -I../../src/extra -I/usr/include/tirpc -I. -I../../src/include -I../../src/include -I/home/linuxbrew/.linuxbrew/Cellar/curl/7.74.0/include -I/home/linuxbrew/.linuxbrew/opt/gettext/include -I/home/linuxbrew/.linuxbrew/opt/readline/include -I../../src/nmath -DHAVE_CONFIG_H   -fopenmp -fpic  -g -O2  -c sort.c -o sort.o
saveload.c:115:23: fatal error: rpc/types.h: No such file or directory
compilation terminated.
make[3]: *** [../../Makeconf:125: saveload.o] Error 1
make[3]: *** Waiting for unfinished jobs....
serialize.c:885:23: fatal error: rpc/types.h: No such file or directory
compilation terminated.
make[3]: *** [../../Makeconf:125: serialize.o] Error 1
make[3]: Leaving directory '/tmp/r-20201210-10532-1h907y5/R-4.0.3/src/main'
make[2]: *** [Makefile:138: R] Error 2
make[2]: Leaving directory '/tmp/r-20201210-10532-1h907y5/R-4.0.3/src/main'
make[1]: *** [Makefile:28: R] Error 1
make[1]: Leaving directory '/tmp/r-20201210-10532-1h907y5/R-4.0.3/src'
make: *** [Makefile:61: R] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

  </pre>
</details>

## What you expected to happen

The build should have succeeded.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install -s r`

**Comment by danielnachun** [comment]
It appears this is because `r` is trying to use `libtirpc` as a dependency.  If you add `depends_on "libtirpc"` after line 37 with `brew edit r` and it builds, then we need to make a pull request to add that fix.

**Comment by Tyrubias** [comment]
Unfortunately, adding `depends_on "libtirpc"` doesn't fix the build issue. Also it seems like `libtirpc` is already installed by the APT `build-essential` package, and the R build process has `-I/usr/include/tirpc`. Could it be an upstream issue?

**Comment by gromgit** [comment]
> Also it seems like `libtirpc` is already installed by the APT `build-essential` package, and the R build process has `-I/usr/include/tirpc`

Which the Homebrew superenv will strip out (see https://docs.brew.sh/Formula-Cookbook#superenv-notes). From your `02.make.cc` gist-log:
```
gcc-5 called with: -MM -I../../src/extra -I/usr/include/tirpc -I. -I../../src/include -I../../src/include -I/home/linuxbrew/.linuxbrew/Cellar/curl/7.74.0/include -I/home/linuxbrew/.linuxbrew/opt/gettext/include -I/home/linuxbrew/.linuxbrew/opt/readline/include -I../../src/nmath -DHAVE_CONFIG_H saveload.c
superenv removed:  -I/usr/include/tirpc
superenv added:    -pipe -w -O2 -march=native -isystem/home/linuxbrew/.linuxbrew/include -I/home/linuxbrew/.linuxbrew/opt/isl@0.18/include [...]
```
When you added `depends_on "libtirpc"` to the R formula, it should've:
* installed `libtirpc`, and 
* caused superenv to add the appropriate `-I` and `-L` flags for that library to your build.

Since you said that didn't work, please post the output of `brew info libtirpc` and post the URL from a new `brew gist-logs r` invocation (i.e. after you added the `depends_on` and run the build).

**Comment by Tyrubias** [comment]
Thanks for the clarification, I'm not very experienced with how Homebrew builds things.

The new `brew gist-logs r` output [is posted here](https://gist.github.com/955b3c689ac6b4f0b6e079ded039c1be).

The output of `brew info libtirpc` is

```
libtirpc: stable 1.3.1 (bottled)
Port of Sun's Transport-Independent RPC library to Linux
https://sourceforge.net/projects/libtirpc/
/home/linuxbrew/.linuxbrew/Cellar/libtirpc/1.3.1 (85 files, 1MB) *
  Built from source on 2020-12-03 at 01:21:06
From: https://github.com/Homebrew/linuxbrew-core/blob/HEAD/Formula/libtirpc.rb
License: BSD-3-Clause
==> Dependencies
Required: krb5 ✔
==> Requirements
Required: Linux ✔
==> Analytics
install: 957 (30 days), 2,289 (90 days), 7,864 (365 days)
install-on-request: 49 (30 days), 64 (90 days), 78 (365 days)
build-error: 0 (30 days)
```

**Comment by gromgit** [comment]
Can you also post the output of `brew cat r`?

**Comment by gromgit** [comment]
Also the output of `dpkg -S /usr/include/rpc/types.h`. That should be part of `libc6-dev`, which should've been installed as part of `build-essential`.

**Comment by Tyrubias** [comment]
The output of `brew cat r` (after I added `libtirpc` as a dependency):

```ruby
class R < Formula
  desc "Software environment for statistical computing"
  homepage "https://www.r-project.org/"
  url "https://cran.r-project.org/src/base/R-4/R-4.0.3.tar.gz"
  sha256 "09983a8a78d5fb6bc45d27b1c55f9ba5265f78fa54a55c13ae691f87c5bb9e0d"
  license "GPL-2.0-or-later"

  livecheck do
    url "https://cran.rstudio.com/banner.shtml"
    regex(%r{href=(?:["']?|.*?/)R[._-]v?(\d+(?:\.\d+)+)\.t}i)
  end

  bottle do
    sha256 "c19dce6be64d7b79bf0a3e2a7201aa6f3a9466ac665752b4021532cfda620ab6" => :big_sur
    sha256 "4050483a8ea4ff9fbe1531f5e9cbe98fb1c7d8091b42184e40a5bcc678733cf3" => :catalina
    sha256 "59f6e7ec476e78f4dbd99e01100cd6e937d97a3ecd818a00ad8c60dcb8ee7bea" => :mojave
    sha256 "a95f0100c9c16a0a45edd271dca3d70b20a4bc9599774510eb1544b901e3d89a" => :high_sierra
    sha256 "9deac29089ba3dc1673c9cb452f5ab6c53624be2b4fad8de9af30cb626c9b16f" => :x86_64_linux
  end

  depends_on "pkg-config" => :build
  depends_on "gcc" # for gfortran
  depends_on "gettext"
  depends_on "jpeg"
  depends_on "libpng"
  depends_on "openblas"
  depends_on "pcre2"
  depends_on "readline"
  depends_on "xz"

  unless OS.mac?
    depends_on "cairo"
    depends_on "curl"
    depends_on "pango"
    depends_on "libice"
    depends_on "libx11"
    depends_on "libxt"
    depends_on "libtirpc"
  end

  # needed to preserve executable permissions on files without shebangs
  skip_clean "lib/R/bin", "lib/R/doc"

  def install
    # Fix dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
    if MacOS.version == "10.11" && MacOS::Xcode.installed? &&
       MacOS::Xcode.version >= "8.0"
      ENV["ac_cv_have_decl_clock_gettime"] = "no"
    end

    args = [
      "--prefix=#{prefix}",
      "--enable-memory-profiling",
      "--with-lapack",
      "--enable-R-shlib",
      "--disable-java",
      "--with-blas=-L#{Formula["openblas"].opt_lib} -lopenblas",
    ]

    # don't remember Homebrew's sed shim
    args << "SED=/usr/bin/sed" if File.exist?("/usr/bin/sed")

    if OS.mac?
      args << "--without-cairo"
      args << "--without-tcltk"
      args << "--without-x"
      args << "--with-aqua"
    end

    unless OS.mac?
      args << "--libdir=#{lib}" # avoid using lib64 on CentOS
      args << "--with-cairo"

      # If LDFLAGS contains any -L options, configure sets LD_LIBRARY_PATH to
      # search those directories. Remove -LHOMEBREW_PREFIX/lib from LDFLAGS.
      ENV.remove "LDFLAGS", "-L#{HOMEBREW_PREFIX}/lib"
    end

    # Help CRAN packages find gettext and readline
    ["gettext", "readline"].each do |f|
      ENV.append "CPPFLAGS", "-I#{Formula[f].opt_include}"
      ENV.append "LDFLAGS", "-L#{Formula[f].opt_lib}"
    end

    # Avoid references to homebrew shims
    args << "LD=ld" unless OS.mac?

    system "./configure", *args
    system "make"
    ENV.deparallelize do
      system "make", "install"
    end

    cd "src/nmath/standalone" do
      system "make"
      ENV.deparallelize do
        system "make", "install"
      end
    end

    r_home = lib/"R"

    # make Homebrew packages discoverable for R CMD INSTALL
    inreplace r_home/"etc/Makeconf" do |s|
      s.gsub!(/^CPPFLAGS =.*/, "\\0 -I#{HOMEBREW_PREFIX}/include")
      s.gsub!(/^LDFLAGS =.*/, "\\0 -L#{HOMEBREW_PREFIX}/lib")
      s.gsub!(/.LDFLAGS =.*/, "\\0 $(LDFLAGS)")
    end

    include.install_symlink Dir[r_home/"include/*"]
    lib.install_symlink Dir[r_home/"lib/*"]

    # avoid triggering mandatory rebuilds of r when gcc is upgraded
    inreplace lib/"R/etc/Makeconf",
      Formula["gcc"].prefix.realpath,
      Formula["gcc"].opt_prefix,
      OS.mac?
  end

  def post_install
    short_version =
      `#{bin}/Rscript -e 'cat(as.character(getRversion()[1,1:2]))'`.strip
    site_library = HOMEBREW_PREFIX/"lib/R/#{short_version}/site-library"
    site_library.mkpath
    ln_s site_library, lib/"R/site-library"
  end

  test do
    dylib_ext = OS.mac? ? ".dylib" : ".so"
    assert_equal "[1] 2", shell_output("#{bin}/Rscript -e 'print(1+1)'").chomp
    assert_equal dylib_ext, shell_output("#{bin}/R CMD config DYLIB_EXT").chomp

    system bin/"Rscript", "-e", "install.packages('gss', '.', 'https://cloud.r-project.org')"
    assert_predicate testpath/"gss/libs/gss.so", :exist?,
                     "Failed to install gss package"
  end
end
```
The output of `dpkg -S /usr/include/rpc/types.h` is:

```
dpkg-query: no path found matching pattern /usr/include/rpc/types.h
```

I've verified that `build-essential` is installed.

**Comment by danielnachun** [comment]
Actually it seems RPC was removed from `glibc` 2.26 and above: https://wiki.gentoo.org/wiki/Glibc_2.26_porting_notes/RPC_implementation, so depending on the system glibc version you are using, it may be expected that `/usr/include/rpc/types.h` may not exist on your system.  This snippet from the R `configure` script was informative:

```
TIRPC_CPPFLAGS=
if test "${r_xdr}" = no ; then
  ## No RPC headers, so try for TI-RPC headers: need /usr/include/tirpc
  ## on include path to find /usr/include/tirpc/netconfig.h
  save_CPPFLAGS=${CPPFLAGS}
  CPPFLAGS="${CPPFLAGS} -I/usr/include/tirpc"
  ac_fn_c_check_header_mongrel "$LINENO" "tirpc/rpc/types.h" "ac_cv_header_tirpc_rpc_types_h" "$ac_includes_default"
if test "x$ac_cv_header_tirpc_rpc_types_h" = xyes; then :

fi


  if test "${ac_cv_header_tirpc_rpc_types_h}" = yes ; then
    ac_fn_c_check_header_compile "$LINENO" "tirpc/rpc/xdr.h" "ac_cv_header_tirpc_rpc_xdr_h" "#include <tirpc/rpc/types.h>
"
if test "x$ac_cv_header_tirpc_rpc_xdr_h" = xyes; then :

fi


  fi
  if test "${ac_cv_header_tirpc_rpc_types_h}" = yes && \
       test "${ac_cv_header_tirpc_rpc_xdr_h}" = yes &&
       test "${ac_cv_search_xdr_string}" != no ; then
    TIRPC_CPPFLAGS=-I/usr/include/tirpc
    r_xdr=yes
  fi
  CPPFLAGS="${save_CPPFLAGS}"
fi
```

I can't follow everything happening in the script, but my best guess is that when you are on a new enough `glibc` that doesn't ship with RPC support, R hardcodes the path to `libtirpc` as `/usr/include/tirpc`.  This is just a hunch, but can you try changing

```
    system "./configure", *args
    system "make"
    ENV.deparallelize do
      system "make", "install"
    end
```

to 

```
    system "./configure", *args
    ENV.append "TIRPC_CPPFLAGS", "-I#{Formula["libtirpc"].opt_include}" unless OS.mac?
    system "make"
    ENV.deparallelize do
      system "make", "install"
    end
```

in the `r` formula?  It seems that the `libtirpc` CPPFLAGS are handled in a separate variable from the rest of the CPPFLAGS, which doesn't get cleaned by the Homebrew superenv, hence why adding `libtirpc` as a dependency doesn't fix the problem.

**Comment by gromgit** [comment]
Since `TIRPC_CPPFLAGS` is an implementation detail rather than a published interface, I recommend augmenting `CPPFLAGS` and `LDFLAGS` instead (both vars are documented in `configure --help`):
```
    ENV.append "CPPFLAGS", "-I#{Formula["libtirpc"].opt_include}"
    ENV.append "LDFLAGS", "-L#{Formula["libtirpc"].opt_lib}"
    system "./configure", *args
    ...
```

**Comment by danielnachun** [comment]
Good point, I shouldn't have made such a complicated suggestion when we should just see if appending to `LDFLAGS` and `CPPFLAGS` does the job.  If this works I think the most sensible solution would be to always use `libtirpc` for RPC support in R so that we don't have to figure out if `glibc` supports it.  That seems to be recommended in the link I posted anyway as it says the RPC implementation in `libtirpc` is better.

**Comment by Tyrubias** [comment]
I changed the formula to this:

```ruby
class R < Formula
  desc "Software environment for statistical computing"
  homepage "https://www.r-project.org/"
  url "https://cran.r-project.org/src/base/R-4/R-4.0.3.tar.gz"
  sha256 "09983a8a78d5fb6bc45d27b1c55f9ba5265f78fa54a55c13ae691f87c5bb9e0d"
  license "GPL-2.0-or-later"

  livecheck do
    url "https://cran.rstudio.com/banner.shtml"
    regex(%r{href=(?:["']?|.*?/)R[._-]v?(\d+(?:\.\d+)+)\.t}i)
  end

  bottle do
    sha256 "c19dce6be64d7b79bf0a3e2a7201aa6f3a9466ac665752b4021532cfda620ab6" => :big_sur
    sha256 "4050483a8ea4ff9fbe1531f5e9cbe98fb1c7d8091b42184e40a5bcc678733cf3" => :catalina
    sha256 "59f6e7ec476e78f4dbd99e01100cd6e937d97a3ecd818a00ad8c60dcb8ee7bea" => :mojave
    sha256 "a95f0100c9c16a0a45edd271dca3d70b20a4bc9599774510eb1544b901e3d89a" => :high_sierra
    sha256 "9deac29089ba3dc1673c9cb452f5ab6c53624be2b4fad8de9af30cb626c9b16f" => :x86_64_linux
  end

  depends_on "pkg-config" => :build
  depends_on "gcc" # for gfortran
  depends_on "gettext"
  depends_on "jpeg"
  depends_on "libpng"
  depends_on "openblas"
  depends_on "pcre2"
  depends_on "readline"
  depends_on "xz"

  unless OS.mac?
    depends_on "cairo"
    depends_on "curl"
    depends_on "pango"
    depends_on "libice"
    depends_on "libx11"
    depends_on "libxt"
    depends_on "libtirpc"
  end

  # needed to preserve executable permissions on files without shebangs
  skip_clean "lib/R/bin", "lib/R/doc"

  def install
    # Fix dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
    if MacOS.version == "10.11" && MacOS::Xcode.installed? &&
       MacOS::Xcode.version >= "8.0"
      ENV["ac_cv_have_decl_clock_gettime"] = "no"
    end

    args = [
      "--prefix=#{prefix}",
      "--enable-memory-profiling",
      "--with-lapack",
      "--enable-R-shlib",
      "--disable-java",
      "--with-blas=-L#{Formula["openblas"].opt_lib} -lopenblas",
    ]

    # don't remember Homebrew's sed shim
    args << "SED=/usr/bin/sed" if File.exist?("/usr/bin/sed")

    if OS.mac?
      args << "--without-cairo"
      args << "--without-tcltk"
      args << "--without-x"
      args << "--with-aqua"
    end

    unless OS.mac?
      args << "--libdir=#{lib}" # avoid using lib64 on CentOS
      args << "--with-cairo"

      # If LDFLAGS contains any -L options, configure sets LD_LIBRARY_PATH to
      # search those directories. Remove -LHOMEBREW_PREFIX/lib from LDFLAGS.
      ENV.remove "LDFLAGS", "-L#{HOMEBREW_PREFIX}/lib"
    end

    # Help CRAN packages find gettext and readline
    ["gettext", "readline"].each do |f|
      ENV.append "CPPFLAGS", "-I#{Formula[f].opt_include}"
      ENV.append "LDFLAGS", "-L#{Formula[f].opt_lib}"
    end

    # Avoid references to homebrew shims
    args << "LD=ld" unless OS.mac?

    ENV.append "CPPFLAGS", "-I#{Formula["libtirpc"].opt_include}"
    ENV.append "LDFLAGS", "-L#{Formula["libtirpc"].opt_lib}"

    system "./configure", *args
    system "make"
    ENV.deparallelize do
      system "make", "install"
    end

    cd "src/nmath/standalone" do
      system "make"
      ENV.deparallelize do
        system "make", "install"
      end
    end

    r_home = lib/"R"

    # make Homebrew packages discoverable for R CMD INSTALL
    inreplace r_home/"etc/Makeconf" do |s|
      s.gsub!(/^CPPFLAGS =.*/, "\\0 -I#{HOMEBREW_PREFIX}/include")
      s.gsub!(/^LDFLAGS =.*/, "\\0 -L#{HOMEBREW_PREFIX}/lib")
      s.gsub!(/.LDFLAGS =.*/, "\\0 $(LDFLAGS)")
    end

    include.install_symlink Dir[r_home/"include/*"]
    lib.install_symlink Dir[r_home/"lib/*"]

    # avoid triggering mandatory rebuilds of r when gcc is upgraded
    inreplace lib/"R/etc/Makeconf",
      Formula["gcc"].prefix.realpath,
      Formula["gcc"].opt_prefix,
      OS.mac?
  end

  def post_install
    short_version =
      `#{bin}/Rscript -e 'cat(as.character(getRversion()[1,1:2]))'`.strip
    site_library = HOMEBREW_PREFIX/"lib/R/#{short_version}/site-library"
    site_library.mkpath
    ln_s site_library, lib/"R/site-library"
  end

  test do
    dylib_ext = OS.mac? ? ".dylib" : ".so"
    assert_equal "[1] 2", shell_output("#{bin}/Rscript -e 'print(1+1)'").chomp
    assert_equal dylib_ext, shell_output("#{bin}/R CMD config DYLIB_EXT").chomp

    system bin/"Rscript", "-e", "install.packages('gss', '.', 'https://cloud.r-project.org')"
    assert_predicate testpath/"gss/libs/gss.so", :exist?,
                     "Failed to install gss package"
  end
end
```

However, it still fails with the same error.

**Comment by gromgit** [comment]
Run `brew gist-logs libtirpc` and post the new URL.

**Comment by Tyrubias** [comment]
@gromgit Apologies for the late update. There are no logs for `libtirpc`

**Comment by gromgit** [comment]
Sorry, I meant `brew gist-logs r`. :grin:

**Comment by Tyrubias** [comment]
https://gist.github.com/756b19383c194f4bc25569b00d3fdef2

**Comment by gromgit** [comment]
OK, `01.configure` says, in part:
```
checking rpc/types.h usability... no
checking rpc/types.h presence... no
checking for rpc/types.h... no
checking tirpc/rpc/types.h usability... yes
checking tirpc/rpc/types.h presence... yes
checking for tirpc/rpc/types.h... yes
checking for tirpc/rpc/xdr.h... yes
```
so it clearly found the tirpc headers in the expected place (`tirpc/rpc/types.h`). However, the compile errors say they're still trying to include `rpc/types.h` instead, so I suggest letting upstream know that they seem to have forgotten to actually use the very files they were looking for.

In the meantime, change:
```
    ENV.append "CPPFLAGS", "-I#{Formula["libtirpc"].opt_include}"
```
to:
```
    ENV.append "CPPFLAGS", "-I#{Formula["libtirpc"].opt_include}/tirpc"
```

**Comment by Tyrubias** [comment]
@gromgit @danielnachun This fix allows the build to occur. Thank you both so much for helping me resolve this issue. I'll submit a pull request to fix it.

**Comment by danielnachun** [comment]
I'm glad to see this finally made it work.  If this passes our checks in CI, I think it could be worth contacting R upstream about this.  I don't see why R doesn't just use `pkg-config` to find the headers for `libtirpc` - that would avoid all of these issues, and would be consistent with how they locate other dependencies.
