### ISSUE TITLE
root: Request for a bottle

### ISSUE THREAD

**Issue by tueda** [Homebrew/linuxbrew-core#21780]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] checked that there aren't other open issues for the same formula bottle request?
- [ ] does the FORMULA not have the `bottle` block?
- [x] ran `brew install FORMULA` and it succeeded?

**Comment by iMichka** [comment]
Done with 3c264c43aeaa74fa7ff1a707c47227810f3dce09

**Comment by dawidd6** [comment]
Actually the bottle upload failed: https://github.com/Homebrew/linuxbrew-core/runs/1597134639?check_suite_focus=true

```
root:
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      lib/root/libCling.so
```

**Comment by iMichka** [comment]
How is it that we got the bottle commit then?

**Comment by dawidd6** [comment]
`brew request-bottle --ignore-errors`

**Comment by dawidd6** [comment]
Gonna revert this commit.
