### ISSUE TITLE
libxcb fails to build (cannot import name gcd)

### ISSUE THREAD

**Issue by rook59** [Homebrew/linuxbrew-core#21816]
# Bug report

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [x] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I am trying to install `libxcb`
`brew install libxcb`

## What happened (include command output)

`libxcb` fails to compile

<details>
  <summary>Command output</summary>
  <pre>

$ brew install libxcb
Warning: Building libxcb from source as the bottle needs:
- HOMEBREW_CELLAR: any (yours is /usr/home/software/.linuxbrew/Cellar)
- HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew (yours is /usr/home/software/.linuxbrew)
- HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew (yours is /usr/home/software/.linuxbrew/Homebrew)
==> Downloading https://xcb.freedesktop.org/dist/libxcb-1.14.tar.gz
Already downloaded: /usr/home/software/.cache/Homebrew/downloads/6ec184ba2dba6b50b91a5bfe0202add69d78cd9e3b695db048a43d30500195d9--libxcb-1.14.tar.gz
==> ./configure --prefix=/usr/home/software/.linuxbrew/Cellar/libxcb/1.14 --sysconfdir=/usr/home/software/.linuxbrew/etc --localstatedir=/usr/home/software/.linuxbrew/var --enable-dri3 --enable-ge --enable-xevie --enable-xprint --enable-selinux --enable-devel-docs=no --w
==> make
Last 15 lines from /usr/home/software/.cache/Homebrew/Logs/libxcb/02.make:
Traceback (most recent call last):
  File "./c_client.py", line 3338, in <module>
    from xcbgen.state import Module
  File "//usr/home/software/.linuxbrew/Cellar/xcb-proto/1.14_3/lib/python3.9/site-packages/xcbgen/state.py", line 7, in <module>
    from xcbgen import matcher
  File "//usr/home/software/.linuxbrew/Cellar/xcb-proto/1.14_3/lib/python3.9/site-packages/xcbgen/matcher.py", line 12, in <module>
    from xcbgen.xtypes import *
  File "//usr/home/software/.linuxbrew/Cellar/xcb-proto/1.14_3/lib/python3.9/site-packages/xcbgen/xtypes.py", line 5, in <module>
    from xcbgen.align import Alignment, AlignmentLog
  File "//usr/home/software/.linuxbrew/Cellar/xcb-proto/1.14_3/lib/python3.9/site-packages/xcbgen/align.py", line 5, in <module>
    from math import gcd
ImportError: cannot import name gcd
make[1]: *** [Makefile:1406: bigreq.c] Error 1
make[1]: Leaving directory '/usr/home/software/.software-tmp/libxcb-20201214-39865-r38805/libxcb-1.14/src'
make: *** [Makefile:792: all-recursive] Error 1

READ THIS: https://docs.brew.sh/Troubleshooting

  </pre>
</details>

## What you expected to happen

`libxcb` should compile and install successfully.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew install libxcb`

## Additional information

```bash
$ brew config
HOMEBREW_VERSION: 2.6.2-2-g7331a9b
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 7331a9ba51c56fd35b71158336666bca38696dac
Last commit: 80 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 7da749e9f7e7d1480a02451329792b0d29a9c6be
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/home/software/.linuxbrew
HOMEBREW_REPOSITORY: /usr/home/software/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /usr/home/software/.linuxbrew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 2
HOMEBREW_TEMP: /usr/home/software/.software-tmp
Homebrew Ruby: 2.6.3 => /usr/home/software/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dual-core 64-bit skylake
Clang: N/A
Git: 2.20.1 => /usr/bin/git
Curl: 7.64.0 => /usr/bin/curl
Kernel: Linux 4.19.0-13-amd64 x86_64 GNU/Linux
OS: Debian GNU/Linux 10 (buster) (buster)
Host glibc: 2.28
/usr/bin/gcc: 8.3.0
/usr/bin/ruby: 2.5.5
glibc: N/A
gcc: N/A
xorg: N/A
```

```bash
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
```

**Comment by rook59** [comment]
Reverting this patch (importing gcd from fractions again even if removed in python3.9) https://github.com/Homebrew/linuxbrew-core/pull/21321/files#diff-bd52bc69e280448a74a6a4df926e7c9595325a813bd6f3aca603cfdc287e6470R20 fixes the issue on this machine
```bash
$ python3 -V
Python 3.9.1
$ ~/.linuxbrew/bin/python3 -V
Python 3.9.1
$ /usr/bin/python3 -V
Python 3.7.3
```

maybe related https://github.com/Homebrew/linuxbrew-core/pull/21320#issuecomment-715586568

**Comment by SeekingMeaning** [comment]
Related patch: https://gitlab.freedesktop.org/xorg/proto/xcbproto/-/commit/426ae35bee1fa0fdb8b5120b1dcd20cee6e34512

**Comment by SeekingMeaning** [comment]
This should hopefully be fixed now @rook59
