### ISSUE TITLE
Failed to install `deno`: `macOS is required for this software.`

### ISSUE THREAD

**Issue by JounQin** [Homebrew/linuxbrew-core#21849]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I'm running linuxbrew on GitHub Actions CI.

```sh
brew install deno
```

## What happened (include command output)

<details>
  <summary>Command output</summary>
  <pre>

```sh
deno: macOS is required for this software.
Error: An unsatisfied requirement failed this build.
Installing deno has failed!
```

  </pre>
</details>

## What you expected to happen

No error

## Step-by-step reproduction instructions (by running `brew install` commands)

https://github.com/JounQin/.dotfiles/runs/1561661184#step:4:339

**Comment by jonchang** [comment]
Deno currently requires macOS because it needs python 2 to build. Please open a pull request at homebrew/homebrew-core to update the deno build scripts to use python 3.
