### ISSUE TITLE
cloudformation-guard: Request for a bottle

### ISSUE THREAD

**Issue by ashokm** [Homebrew/linuxbrew-core#21892]
- [x] checked that there aren't other open issues for the same formula bottle request?
- [ ] does the FORMULA not have the `bottle` block?
- [x] ran `brew install FORMULA` and it succeeded?
  - `brew install --build-from-source cloudformation-guard` succeeded on Ubuntu 20.04.1 LTS

**Comment by iMichka** [comment]
Done with: 4f5f8b5b47b22be6fe5a19a93c81256c371e2b50

You are lucky the build passed directly :)

**Comment by ashokm** [comment]
Thank you! :)
