### ISSUE TITLE
vercel-cli: Request for a bottle

### ISSUE THREAD

**Issue by SeekingMeaning** [Homebrew/linuxbrew-core#21959]
- [ ] checked that there aren't other open issues for the same formula bottle request?
- [ ] does the FORMULA not have the `bottle` block?
- [ ] ran `brew install FORMULA` and it succeeded?

---

[`now-cli`](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/now-cli.rb) (which can be deleted) was renamed to `vercel-cli` in upstream, see https://github.com/Homebrew/homebrew-core/pull/65904

**Comment by jonchang** [comment]
fadf63767dce1e3588f00a62bc62efa0d691885f
