### ISSUE TITLE
gst-devtools: Request for a bottle

### ISSUE THREAD

**Issue by SeekingMeaning** [Homebrew/linuxbrew-core#21958]
- [ ] checked that there aren't other open issues for the same formula bottle request?
- [ ] does the FORMULA not have the `bottle` block?
- [ ] ran `brew install FORMULA` and it succeeded?

---

`gst-devtools` replaced [`gst-validate`](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/gst-validate.rb) (which can be deleted) in upstream, see https://github.com/Homebrew/homebrew-core/pull/60923

**Comment by jonchang** [comment]
bef0dfc47e62853d40fa024904be84216d5dc6ca
