### ISSUE TITLE
makensis: Request for a bottle

### ISSUE THREAD

**Issue by rfay** [Homebrew/linuxbrew-core#21968]
From https://github.com/Homebrew/homebrew-core/issues/67825

- [x] checked that there aren't other open issues for the same formula bottle request?
- [x] does the FORMULA not have the `bottle` block? https://github.com/Homebrew/linuxbrew-core/blob/6e1c9e747bb3ad74ae7ea21b719223737e3e836f/Formula/makensis.rb
- [x] ran `brew install makensis` and it FAILED!

```
rfay@ubuntu-20-04:~$ brew install makensis
Error: makensis: no bottle available!
You can try to install from source with e.g.
brew install --build-from-source makensis
```

The bottle have been there for years.... Now it's not.

**Comment by rfay** [comment]
This is much less painful now that there is a bottle for mingw-w64, but it would still be wonderful to have a makensis bottle, thanks.

**Comment by danielnachun** [comment]
This is being fixed upstream: https://github.com/Homebrew/homebrew-core/pull/81549.
