### ISSUE TITLE
mingw-w64: Request for a bottle

### ISSUE THREAD

**Issue by rfay** [Homebrew/linuxbrew-core#22007]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] checked that there aren't other open issues for the same formula bottle request?
- [x] does the FORMULA not have the `bottle` block?
- [x] ran `brew install FORMULA` and it succeeded? (It succeeds, but the build takes an incomprehensible amount of time)

mingw-w64 has had a bottle in linuxbrew forever. It's a dependency of makensis, which also lost its bottle somehow. https://github.com/Homebrew/linuxbrew-core/issues/21968 - but until today, it was easy enough to build makensis... but now that it requires a build of mingw-w64, it's much harder.

**Comment by dawidd6** [comment]
Build fails:
https://github.com/Homebrew/linuxbrew-core/runs/1650491167?check_suite_focus=true

**Comment by dskiff** [comment]
This is unfortunately biting something I'm working on, as well. https://github.com/Homebrew/homebrew-core/pull/68070 appears to be the culprit.

If you need a quick patch to unblock things, checking out a fixed version of of the core tap (I used `3ac7145d03664d6ad81980264510cd36a9d81c60`) and then using `HOMEBREW_NO_AUTO_UPDATE=1 brew install ...` worked for me.

**Comment by iMichka** [comment]
Fixed by 351ea049e00a08b5ae355b0e5e0b49613b9779ab

**Comment by dskiff** [comment]
Thanks @iMichka!
