### ISSUE TITLE
Build from source of llvm (brew install llvm -s -v) with LinuxBrew in home folder on CentOS 7.7 fails.

### ISSUE THREAD

**Issue by dbankov-vmware** [Homebrew/linuxbrew-core#22060]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [x] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link? - https://gist.github.com/1ac65d77d5d0e34954c325cfbea796cd
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I was trying to install llvm on CentOS 7.7 with HomeBrew installed in my home folder.

## What happened (include command output)

While installing llvm HomeBrew decided to build llvm from source and the build failed.

<details>
  <summary>Command output</summary>
  <pre>

bash-4.2$ brew install llvm -s
==> Downloading https://github.com/llvm/llvm-project/commit/c86f56e32e724c6018e579bb2bc11e667c96fc96.patch?full_index=1
Already downloaded: /dbc/sof2-dbc401/dbankov/.cache/Homebrew/downloads/e7b8196b333d3b3b4524e79831c75065ee8ad3ab75098aa5d0bbe6e6138ed21e--c86f56e32e724c6018e579bb2bc11e667c96fc96.patch
==> Downloading https://github.com/llvm/llvm-project/commit/31e5f7120bdd2f76337686d9d169b1c00e6ee69c.patch?full_index=1
Already downloaded: /dbc/sof2-dbc401/dbankov/.cache/Homebrew/downloads/103e4c67e2e8bb360a92a9e9154bb9d4d3b3d893ae8c848d39dfe9a475e01cc2--31e5f7120bdd2f76337686d9d169b1c00e6ee69c.patch
==> Downloading https://github.com/llvm/llvm-project/commit/3c7bfbd6831b2144229734892182d403e46d7baf.patch?full_index=1
Already downloaded: /dbc/sof2-dbc401/dbankov/.cache/Homebrew/downloads/c5307741241de593d0b6e57f2eb4d73d2ff4e94b1c61ea621edea4bf3e559630--3c7bfbd6831b2144229734892182d403e46d7baf.patch
==> Downloading https://github.com/llvm/llvm-project/commit/c4d7536136b331bada079b2afbb2bd09ad8296bf.patch?full_index=1
Already downloaded: /dbc/sof2-dbc401/dbankov/.cache/Homebrew/downloads/7c6620f0ae26a9b375dd4f94643c21bed7a925e77b3b433451d68b2886780cce--c4d7536136b331bada079b2afbb2bd09ad8296bf.patch
==> Downloading https://raw.githubusercontent.com/Homebrew/formula-patches/6166a68c/llvm/openmp_arm.patch
Already downloaded: /dbc/sof2-dbc401/dbankov/.cache/Homebrew/downloads/f6dd7ea5236a95cd68ccedb3c9770e645acf95fb5c778d936cd5d47445b28b8a--openmp_arm.patch
==> Downloading https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/llvm-project-11.0.0.tar.xz
Already downloaded: /dbc/sof2-dbc401/dbankov/.cache/Homebrew/downloads/6a300c0a37830bce028525b4b03cb8c3922c9b0713684cbaff1e9965993d7f6e--llvm-project-11.0.0.tar.xz
==> Patching
==> Applying c86f56e32e724c6018e579bb2bc11e667c96fc96.patch
patching file lldb/cmake/modules/LLDBStandalone.cmake
==> Applying 31e5f7120bdd2f76337686d9d169b1c00e6ee69c.patch
patching file clang/test/CMakeLists.txt
patching file clang/test/lit.site.cfg.py.in
patching file compiler-rt/test/lit.common.configured.in
Hunk #1 succeeded at 56 (offset -1 lines).
patching file lld/test/CMakeLists.txt
patching file lld/test/lit.site.cfg.py.in
patching file lldb/cmake/modules/LLDBStandalone.cmake
patching file lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunication.cpp
patching file lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationClient.cpp
patching file llvm/cmake/config-ix.cmake
patching file llvm/cmake/modules/LLVMConfig.cmake.in
patching file llvm/include/llvm/Config/config.h.cmake
Hunk #1 succeeded at 112 (offset -3 lines).
Hunk #2 succeeded at 220 (offset -3 lines).
patching file llvm/lib/Support/CMakeLists.txt
patching file llvm/lib/Support/CRC.cpp
patching file llvm/lib/Support/Compression.cpp
patching file llvm/test/CMakeLists.txt
patching file llvm/test/lit.site.cfg.py.in
patching file llvm/unittests/Support/CompressionTest.cpp
patching file llvm/utils/gn/secondary/clang/test/BUILD.gn
patching file llvm/utils/gn/secondary/compiler-rt/test/BUILD.gn
Hunk #1 succeeded at 85 (offset -1 lines).
patching file llvm/utils/gn/secondary/lld/test/BUILD.gn
patching file llvm/utils/gn/secondary/llvm/include/llvm/Config/BUILD.gn
patching file llvm/utils/gn/secondary/llvm/test/BUILD.gn
Hunk #1 succeeded at 173 (offset -1 lines).
==> Applying 3c7bfbd6831b2144229734892182d403e46d7baf.patch
patching file compiler-rt/cmake/config-ix.cmake
Hunk #1 succeeded at 131 (offset -2 lines).
patching file compiler-rt/lib/xray/tests/CMakeLists.txt
patching file lldb/source/Core/CMakeLists.txt
patching file llvm/CMakeLists.txt
Hunk #1 succeeded at 632 (offset -10 lines).
patching file llvm/cmake/config-ix.cmake
Hunk #1 succeeded at 147 (offset -1 lines).
Hunk #2 succeeded at 175 (offset -1 lines).
patching file llvm/include/llvm/Config/config.h.cmake
Hunk #1 succeeded at 206 with fuzz 1 (offset -6 lines).
patching file llvm/lib/Support/CMakeLists.txt
Hunk #3 succeeded at 223 (offset -29 lines).
patching file llvm/lib/Support/Unix/Process.inc
patching file llvm/utils/gn/secondary/llvm/include/llvm/Config/BUILD.gn
Hunk #1 succeeded at 284 (offset -2 lines).
==> Applying c4d7536136b331bada079b2afbb2bd09ad8296bf.patch
patching file lld/test/CMakeLists.txt
patching file lld/test/lit.cfg.py
patching file lld/test/lit.site.cfg.py.in
patching file llvm/cmake/config-ix.cmake
Hunk #1 succeeded at 136 (offset -1 lines).
Hunk #2 succeeded at 181 (offset -1 lines).
Hunk #3 succeeded at 188 (offset -1 lines).
patching file llvm/cmake/modules/GetLibraryName.cmake
patching file llvm/cmake/modules/LLVMConfig.cmake.in
patching file llvm/include/llvm/Config/config.h.cmake
Hunk #1 succeeded at 300 (offset -6 lines).
patching file llvm/lib/Support/CMakeLists.txt
Hunk #2 succeeded at 199 (offset -28 lines).
Hunk #3 succeeded at 210 (offset -28 lines).
patching file llvm/lib/WindowsManifest/CMakeLists.txt
patching file llvm/lib/WindowsManifest/WindowsManifestMerger.cpp
patching file llvm/test/CMakeLists.txt
patching file llvm/test/lit.cfg.py
Hunk #1 succeeded at 352 (offset -4 lines).
patching file llvm/test/lit.site.cfg.py.in
patching file llvm/utils/gn/secondary/lld/test/BUILD.gn
patching file llvm/utils/gn/secondary/llvm/include/llvm/Config/BUILD.gn
Hunk #1 succeeded at 302 (offset -2 lines).
patching file llvm/utils/gn/secondary/llvm/test/BUILD.gn
Hunk #1 succeeded at 161 (offset -1 lines).
==> Applying openmp_arm.patch
patching file openmp/runtime/src/z_Linux_asm.S
==> cmake -G Unix Makefiles .. -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra;lld;lldb;openmp;polly;mlir -DLLVM_ENABLE_RUNTIMES=compiler-rt;libunwind;libcxxabi -DLLVM_POLLY_LINK_INTO_TOOLS=ON -DLLVM_BUILD_EXTERNAL_COMPILER_RT=ON -DLLVM_L
==> cmake --build .
^[[1;2BLast 15 lines from /dbc/sof2-dbc401/dbankov/.cache/Homebrew/Logs/llvm/02.cmake:
gmake[3]: Leaving directory `/tmp/llvm-20210108-215313-vbiqf/llvm-project-11.0.0/llvm/build/runtimes/runtimes-bins'
gmake[2]: *** [runtimes/runtimes-stamps/runtimes-build] Error 2
gmake[2]: Leaving directory `/tmp/llvm-20210108-215313-vbiqf/llvm-project-11.0.0/llvm/build'
gmake[1]: *** [runtimes/CMakeFiles/runtimes.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX shared library ../../../../lib/liblldb.so
cd /tmp/llvm-20210108-215313-vbiqf/llvm-project-11.0.0/llvm/build/tools/lldb/source/API && /dbc/sof2-dbc401/dbankov/.linuxbrew/Cellar/cmake/3.19.2/bin/cmake -E cmake_link_script CMakeFiles/liblldb.dir/link.txt --verbose=1
/dbc/sof2-dbc401/dbankov/.linuxbrew/Homebrew/Library/Homebrew/shims/linux/super/g++-5 -fPIC  -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -ffunction-sections -fdata-sections -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-deprecated-register -Wno-vla-extension -DNDEBUG  -Wl,-rpath-link,/tmp/llvm-20210108-215313-vbiqf/llvm-project-11.0.0/llvm/build/./lib  -Wl,-O3 -Wl,--gc-sections  -Wl,--version-script,"/tmp/llvm-20210108-215313-vbiqf/llvm-project-11.0.0/llvm/build/tools/lldb/source/API/liblldb.exports"  -Wl,-z,defs -Wl,-z,nodelete -shared -Wl,-soname,liblldb.so.11 -o ../../../../lib/liblldb.so.11.0.0 CMakeFiles/liblldb.dir/SBAddress.cpp.o CMakeFiles/liblldb.dir/SBAttachInfo.cpp.o CMakeFiles/liblldb.dir/SBBlock.cpp.o CMakeFiles/liblldb.dir/SBBreakpoint.cpp.o CMakeFiles/liblldb.dir/SBBreakpointLocation.cpp.o CMakeFiles/liblldb.dir/SBBreakpointName.cpp.o CMakeFiles/liblldb.dir/SBBreakpointOptionCommon.cpp.o CMakeFiles/liblldb.dir/SBBroadcaster.cpp.o CMakeFiles/liblldb.dir/SBCommandInterpreter.cpp.o CMakeFiles/liblldb.dir/SBCommandInterpreterRunOptions.cpp.o CMakeFiles/liblldb.dir/SBCommandReturnObject.cpp.o CMakeFiles/liblldb.dir/SBCommunication.cpp.o CMakeFiles/liblldb.dir/SBCompileUnit.cpp.o CMakeFiles/liblldb.dir/SBData.cpp.o CMakeFiles/liblldb.dir/SBDebugger.cpp.o CMakeFiles/liblldb.dir/SBDeclaration.cpp.o CMakeFiles/liblldb.dir/SBEnvironment.cpp.o CMakeFiles/liblldb.dir/SBError.cpp.o CMakeFiles/liblldb.dir/SBEvent.cpp.o CMakeFiles/liblldb.dir/SBExecutionContext.cpp.o CMakeFiles/liblldb.dir/SBExpressionOptions.cpp.o CMakeFiles/liblldb.dir/SBFileSpec.cpp.o CMakeFiles/liblldb.dir/SBFile.cpp.o CMakeFiles/liblldb.dir/SBFileSpecList.cpp.o CMakeFiles/liblldb.dir/SBFrame.cpp.o CMakeFiles/liblldb.dir/SBFunction.cpp.o CMakeFiles/liblldb.dir/SBHostOS.cpp.o CMakeFiles/liblldb.dir/SBInstruction.cpp.o CMakeFiles/liblldb.dir/SBInstructionList.cpp.o CMakeFiles/liblldb.dir/SBLanguageRuntime.cpp.o CMakeFiles/liblldb.dir/SBLaunchInfo.cpp.o CMakeFiles/liblldb.dir/SBLineEntry.cpp.o CMakeFiles/liblldb.dir/SBListener.cpp.o CMakeFiles/liblldb.dir/SBMemoryRegionInfo.cpp.o CMakeFiles/liblldb.dir/SBMemoryRegionInfoList.cpp.o CMakeFiles/liblldb.dir/SBModule.cpp.o CMakeFiles/liblldb.dir/SBModuleSpec.cpp.o CMakeFiles/liblldb.dir/SBPlatform.cpp.o CMakeFiles/liblldb.dir/SBProcess.cpp.o CMakeFiles/liblldb.dir/SBProcessInfo.cpp.o CMakeFiles/liblldb.dir/SBQueue.cpp.o CMakeFiles/liblldb.dir/SBQueueItem.cpp.o CMakeFiles/liblldb.dir/SBReproducer.cpp.o CMakeFiles/liblldb.dir/SBSection.cpp.o CMakeFiles/liblldb.dir/SBSourceManager.cpp.o CMakeFiles/liblldb.dir/SBStream.cpp.o CMakeFiles/liblldb.dir/SBStringList.cpp.o CMakeFiles/liblldb.dir/SBStructuredData.cpp.o CMakeFiles/liblldb.dir/SBSymbol.cpp.o CMakeFiles/liblldb.dir/SBSymbolContext.cpp.o CMakeFiles/liblldb.dir/SBSymbolContextList.cpp.o CMakeFiles/liblldb.dir/SBTarget.cpp.o CMakeFiles/liblldb.dir/SBThread.cpp.o CMakeFiles/liblldb.dir/SBThreadCollection.cpp.o CMakeFiles/liblldb.dir/SBThreadPlan.cpp.o CMakeFiles/liblldb.dir/SBTrace.cpp.o CMakeFiles/liblldb.dir/SBTraceOptions.cpp.o CMakeFiles/liblldb.dir/SBType.cpp.o CMakeFiles/liblldb.dir/SBTypeCategory.cpp.o CMakeFiles/liblldb.dir/SBTypeEnumMember.cpp.o CMakeFiles/liblldb.dir/SBTypeFilter.cpp.o CMakeFiles/liblldb.dir/SBTypeFormat.cpp.o CMakeFiles/liblldb.dir/SBTypeNameSpecifier.cpp.o CMakeFiles/liblldb.dir/SBTypeSummary.cpp.o CMakeFiles/liblldb.dir/SBTypeSynthetic.cpp.o CMakeFiles/liblldb.dir/SBValue.cpp.o CMakeFiles/liblldb.dir/SBValueList.cpp.o CMakeFiles/liblldb.dir/SBVariablesOptions.cpp.o CMakeFiles/liblldb.dir/SBWatchpoint.cpp.o CMakeFiles/liblldb.dir/SBUnixSignals.cpp.o CMakeFiles/liblldb.dir/SystemInitializerFull.cpp.o  -Wl,-rpath,"\$ORIGIN/../lib" ../../../../lib/liblldbBase.a ../../../../lib/liblldbBreakpoint.a ../../../../lib/liblldbCore.a ../../../../lib/liblldbDataFormatters.a ../../../../lib/liblldbExpression.a ../../../../lib/liblldbHost.a ../../../../lib/liblldbInitialization.a ../../../../lib/liblldbInterpreter.a ../../../../lib/liblldbSymbol.a ../../../../lib/liblldbTarget.a ../../../../lib/liblldbUtility.a ../../../../lib/liblldbPluginABIAArch64.a ../../../../lib/liblldbPluginABIARM.a ../../../../lib/liblldbPluginABIHexagon.a ../../../../lib/liblldbPluginABIMips.a ../../../../lib/liblldbPluginABIPowerPC.a ../../../../lib/liblldbPluginABISystemZ.a ../../../../lib/liblldbPluginABIX86.a ../../../../lib/liblldbPluginArchitectureArm.a ../../../../lib/liblldbPluginArchitectureMips.a ../../../../lib/liblldbPluginArchitecturePPC64.a ../../../../lib/liblldbPluginDisassemblerLLVMC.a ../../../../lib/liblldbPluginDynamicLoaderDarwinKernel.a ../../../../lib/liblldbPluginDynamicLoaderMacOSXDYLD.a ../../../../lib/liblldbPluginDynamicLoaderPosixDYLD.a ../../../../lib/liblldbPluginDynamicLoaderStatic.a ../../../../lib/liblldbPluginDynamicLoaderHexagonDYLD.a ../../../../lib/liblldbPluginDynamicLoaderWindowsDYLD.a ../../../../lib/liblldbPluginDynamicLoaderWasmDYLD.a ../../../../lib/liblldbPluginInstructionARM.a ../../../../lib/liblldbPluginInstructionARM64.a ../../../../lib/liblldbPluginInstructionMIPS.a ../../../../lib/liblldbPluginInstructionMIPS64.a ../../../../lib/liblldbPluginInstructionPPC64.a ../../../../lib/liblldbPluginInstrumentationRuntimeASan.a ../../../../lib/liblldbPluginInstrumentationRuntimeMainThreadChecker.a ../../../../lib/liblldbPluginInstrumentationRuntimeTSan.a ../../../../lib/liblldbPluginInstrumentationRuntimeUBSan.a ../../../../lib/liblldbPluginJITLoaderGDB.a ../../../../lib/liblldbPluginCPlusPlusLanguage.a ../../../../lib/liblldbPluginObjCLanguage.a ../../../../lib/liblldbPluginObjCPlusPlusLanguage.a ../../../../lib/liblldbPluginCXXItaniumABI.a ../../../../lib/liblldbPluginAppleObjCRuntime.a ../../../../lib/liblldbPluginRenderScriptRuntime.a ../../../../lib/liblldbPluginMemoryHistoryASan.a ../../../../lib/liblldbPluginObjectContainerBSDArchive.a ../../../../lib/liblldbPluginObjectContainerMachOArchive.a ../../../../lib/liblldbPluginObjectFileBreakpad.a ../../../../lib/liblldbPluginObjectFileELF.a ../../../../lib/liblldbPluginObjectFileMachO.a ../../../../lib/liblldbPluginObjectFilePECOFF.a ../../../../lib/liblldbPluginObjectFileJIT.a ../../../../lib/liblldbPluginObjectFileWasm.a ../../../../lib/liblldbPluginPlatformLinux.a ../../../../lib/liblldbPluginPlatformFreeBSD.a ../../../../lib/liblldbPluginPlatformNetBSD.a ../../../../lib/liblldbPluginPlatformOpenBSD.a ../../../../lib/liblldbPluginPlatformMacOSX.a ../../../../lib/liblldbPluginPlatformWindows.a ../../../../lib/liblldbPluginPlatformGDB.a ../../../../lib/liblldbPluginPlatformAndroid.a ../../../../lib/liblldbPluginProcessGDBRemote.a ../../../../lib/liblldbPluginProcessElfCore.a ../../../../lib/liblldbPluginProcessMachCore.a ../../../../lib/liblldbPluginProcessMinidump.a ../../../../lib/liblldbPluginScriptInterpreterNone.a ../../../../lib/liblldbPluginStructuredDataDarwinLog.a ../../../../lib/liblldbPluginSymbolFileBreakpad.a ../../../../lib/liblldbPluginSymbolFileDWARF.a ../../../../lib/liblldbPluginSymbolFileSymtab.a ../../../../lib/liblldbPluginSymbolFilePDB.a ../../../../lib/liblldbPluginSystemRuntimeMacOSX.a ../../../../lib/liblldbPluginSymbolVendorELF.a ../../../../lib/liblldbPluginSymbolVendorWasm.a ../../../../lib/liblldbPluginTypeSystemClang.a ../../../../lib/liblldbPluginUnwindAssemblyInstEmulation.a ../../../../lib/liblldbPluginUnwindAssemblyX86.a ../../../../lib/liblldbPluginProcessPOSIX.a ../../../../lib/liblldbPluginPlatformLinux.a ../../../../lib/liblldbPluginPlatformGDB.a ../../../../lib/liblldbPluginDynamicLoaderDarwinKernel.a ../../../../lib/liblldbPluginPlatformMacOSX.a ../../../../lib/liblldbPluginPlatformPOSIX.a ../../../../lib/liblldbPluginDynamicLoaderMacOSXDYLD.a ../../../../lib/liblldbPluginObjectFileMachO.a ../../../../lib/liblldbPluginDynamicLoaderPosixDYLD.a ../../../../lib/liblldbPluginProcessElfCore.a ../../../../lib/liblldbPluginDynamicLoaderPosixDYLD.a ../../../../lib/liblldbPluginProcessElfCore.a ../../../../lib/liblldbPluginObjectFileBreakpad.a ../../../../lib/liblldbPluginObjectFileELF.a ../../../../lib/liblldbPluginObjectFileWasm.a ../../../../lib/liblldbBreakpoint.a ../../../../lib/liblldbCore.a ../../../../lib/liblldbDataFormatters.a ../../../../lib/liblldbExpression.a ../../../../lib/liblldbInterpreter.a ../../../../lib/liblldbSymbol.a ../../../../lib/liblldbTarget.a ../../../../lib/liblldbPluginCPlusPlusLanguage.a ../../../../lib/liblldbPluginObjCLanguage.a ../../../../lib/liblldbPluginAppleObjCRuntime.a ../../../../lib/liblldbPluginRenderScriptRuntime.a ../../../../lib/liblldbPluginObjectFileJIT.a ../../../../lib/liblldbPluginSymbolFileDWARF.a ../../../../lib/liblldbPluginSymbolFilePDB.a ../../../../lib/liblldbPluginTypeSystemClang.a ../../../../lib/liblldbCommands.a ../../../../lib/liblldbPluginExpressionParserClang.a ../../../../lib/liblldbPluginProcessUtility.a ../../../../lib/liblldbPluginClangCommon.a ../../../../lib/liblldbPluginCPPRuntime.a ../../../../lib/liblldbPluginSymbolFileNativePDB.a ../../../../lib/liblldbPluginObjCRuntime.a ../../../../lib/liblldbBreakpoint.a ../../../../lib/liblldbCore.a ../../../../lib/liblldbDataFormatters.a ../../../../lib/liblldbExpression.a ../../../../lib/liblldbInterpreter.a ../../../../lib/liblldbSymbol.a ../../../../lib/liblldbTarget.a ../../../../lib/liblldbPluginCPlusPlusLanguage.a ../../../../lib/liblldbPluginObjCLanguage.a ../../../../lib/liblldbPluginAppleObjCRuntime.a ../../../../lib/liblldbPluginRenderScriptRuntime.a ../../../../lib/liblldbPluginObjectFileJIT.a ../../../../lib/liblldbPluginSymbolFileDWARF.a ../../../../lib/liblldbPluginSymbolFilePDB.a ../../../../lib/liblldbPluginTypeSystemClang.a ../../../../lib/liblldbCommands.a ../../../../lib/liblldbPluginExpressionParserClang.a ../../../../lib/liblldbPluginProcessUtility.a ../../../../lib/liblldbPluginClangCommon.a ../../../../lib/liblldbPluginCPPRuntime.a ../../../../lib/liblldbPluginSymbolFileNativePDB.a ../../../../lib/liblldbPluginObjCRuntime.a ../../../../lib/liblldbBreakpoint.a ../../../../lib/liblldbCore.a ../../../../lib/liblldbDataFormatters.a ../../../../lib/liblldbExpression.a ../../../../lib/liblldbInterpreter.a ../../../../lib/liblldbSymbol.a ../../../../lib/liblldbTarget.a ../../../../lib/liblldbPluginCPlusPlusLanguage.a ../../../../lib/liblldbPluginObjCLanguage.a ../../../../lib/liblldbPluginAppleObjCRuntime.a ../../../../lib/liblldbPluginRenderScriptRuntime.a ../../../../lib/liblldbPluginObjectFileJIT.a ../../../../lib/liblldbPluginSymbolFileDWARF.a ../../../../lib/liblldbPluginSymbolFilePDB.a ../../../../lib/liblldbPluginTypeSystemClang.a ../../../../lib/liblldbCommands.a ../../../../lib/liblldbPluginExpressionParserClang.a ../../../../lib/liblldbPluginProcessUtility.a ../../../../lib/liblldbPluginClangCommon.a ../../../../lib/liblldbPluginCPPRuntime.a ../../../../lib/liblldbPluginSymbolFileNativePDB.a ../../../../lib/liblldbPluginObjCRuntime.a ../../../../lib/liblldbBreakpoint.a ../../../../lib/liblldbCore.a ../../../../lib/liblldbDataFormatters.a ../../../../lib/liblldbExpression.a ../../../../lib/liblldbInterpreter.a ../../../../lib/liblldbSymbol.a ../../../../lib/liblldbTarget.a ../../../../lib/liblldbPluginCPlusPlusLanguage.a ../../../../lib/liblldbPluginObjCLanguage.a ../../../../lib/liblldbPluginAppleObjCRuntime.a ../../../../lib/liblldbPluginRenderScriptRuntime.a ../../../../lib/liblldbPluginObjectFileJIT.a ../../../../lib/liblldbPluginSymbolFileDWARF.a ../../../../lib/liblldbPluginSymbolFilePDB.a ../../../../lib/liblldbPluginTypeSystemClang.a ../../../../lib/liblldbCommands.a ../../../../lib/liblldbPluginExpressionParserClang.a ../../../../lib/liblldbPluginProcessUtility.a ../../../../lib/liblldbPluginClangCommon.a ../../../../lib/liblldbPluginCPPRuntime.a ../../../../lib/liblldbPluginSymbolFileNativePDB.a ../../../../lib/liblldbPluginObjCRuntime.a ../../../../lib/liblldbBreakpoint.a ../../../../lib/liblldbCore.a ../../../../lib/liblldbDataFormatters.a ../../../../lib/liblldbExpression.a ../../../../lib/liblldbInterpreter.a ../../../../lib/liblldbSymbol.a ../../../../lib/liblldbTarget.a ../../../../lib/liblldbPluginCPlusPlusLanguage.a ../../../../lib/liblldbPluginObjCLanguage.a ../../../../lib/liblldbPluginAppleObjCRuntime.a ../../../../lib/liblldbPluginRenderScriptRuntime.a ../../../../lib/liblldbPluginObjectFileJIT.a ../../../../lib/liblldbPluginSymbolFileDWARF.a ../../../../lib/liblldbPluginSymbolFilePDB.a ../../../../lib/liblldbPluginTypeSystemClang.a ../../../../lib/liblldbCommands.a ../../../../lib/liblldbPluginExpressionParserClang.a ../../../../lib/liblldbPluginProcessUtility.a ../../../../lib/liblldbPluginClangCommon.a ../../../../lib/liblldbPluginCPPRuntime.a ../../../../lib/liblldbPluginSymbolFileNativePDB.a ../../../../lib/liblldbPluginObjCRuntime.a /dbc/sof2-dbc401/dbankov/.linuxbrew/lib/libcurses.so /dbc/sof2-dbc401/dbankov/.linuxbrew/lib/libform.so /dbc/sof2-dbc401/dbankov/.linuxbrew/lib/libpanel.so /dbc/sof2-dbc401/dbankov/.linuxbrew/lib/libtinfo.so ../../../../lib/liblldbBase.a ../../../../lib/liblldbHost.a /dbc/sof2-dbc401/dbankov/.linuxbrew/lib/libxml2.so /dbc/sof2-dbc401/dbankov/.linuxbrew/lib/libedit.so ../../../../lib/liblldbUtility.a -lpthread -ldl ../../../../lib/libclang-cpp.so.11 ../../../../lib/libLLVM-11.so 
gmake[2]: Leaving directory `/tmp/llvm-20210108-215313-vbiqf/llvm-project-11.0.0/llvm/build'
[100%] Built target lldb-server
cd /tmp/llvm-20210108-215313-vbiqf/llvm-project-11.0.0/llvm/build/tools/lldb/source/API && /dbc/sof2-dbc401/dbankov/.linuxbrew/Cellar/cmake/3.19.2/bin/cmake -E cmake_symlink_library ../../../../lib/liblldb.so.11.0.0 ../../../../lib/liblldb.so.11 ../../../../lib/liblldb.so
gmake[2]: Leaving directory `/tmp/llvm-20210108-215313-vbiqf/llvm-project-11.0.0/llvm/build'
[100%] Built target liblldb
gmake[1]: Leaving directory `/tmp/llvm-20210108-215313-vbiqf/llvm-project-11.0.0/llvm/build'
gmake: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
llvm@7: use on_linux and on_macos https://github.com/Homebrew/linuxbrew-core/pull/21635
llvm: clang installed from linuxbrew is not able to link binary executable https://github.com/Homebrew/linuxbrew-core/issues/22034
  </pre>
</details>

## What you expected to happen

I expected to be installed successfully.

## Step-by-step reproduction instructions (by running `brew install` commands)

brew install llvm -s

**Comment by dbankov-vmware** [comment]
I investigated the problem a bit and saw that the build is failing because it couldn't find <cassert> header while building compiler-rt:
>/tmp/llvm-20210107-8133-1wzqqov/llvm-project-11.0.0/compiler-rt/lib/fuzzer/FuzzerDefs.h:14:10: fatal error: 'cassert' file not found
>#include <cassert>
>         ^~~~~~~~~

And the above seemed to be because the llvm build was trying to find <cassert> in my hosts gcc include folders and it was not available there. Adding -DGCC_INSTALL_PREFIX=#{HOMEBREW_PREFIX} to cmake flags fixed the problem but since there is a comment in the llvm.rb formula which states that the latter is explicitly avoided I'm filing this PR to come up with a correct solution.

**Comment by iMichka** [comment]
I had this error to when working on #21380.
I fixed it by removing this: https://github.com/Homebrew/linuxbrew-core/pull/21380/files#diff-5e996f93f5a1c45f4e6fc81331d60ad9171f503668b9d2521cce250d3c164dd9L119-L129

Once #21380 is merged this should be solved, but there is still an bigger issue in brew to fix before I can do this.

**Comment by dbankov-vmware** [comment]
I removed these lines as well but also added -DGCC_INSTALL_PREFIX=#{HOMEBREW_PREFIX} at the same time.

Let me check if just removing the lines will fix the problem for me.

**Comment by dbankov-vmware** [comment]
I can confirm that removing the workaround lines fixes my problem as well.

Based on the above I don't know if I should post a PR with the addition of -DGCC_INSTALL_PREFIX=#{HOMEBREW_PREFIX}.

**Comment by dbankov-vmware** [comment]
Actually with the removed workaround lines llvm build succeeds but 'brew test llvm' fails.

Also 'brew test llvm' against llvm installed with --force-bottle on my CentOS 7.7 also fails.

**Comment by dbankov-vmware** [comment]
And the problem with 'brew test llvm' seems to be that the binary produced by llvm doesn't have the correct interpreter set.

**Comment by Char-Aznable** [comment]
FYI @dbankov-vmware @iMichka Removing those lines and/or using the cmake option -DGCC_INSTALL_PREFIX is just repeating the problems that was fixed by https://github.com/Homebrew/linuxbrew-core/pull/11074. One of the problems was that the bottle was not portable. Good luck

**Comment by danielnachun** [comment]
I believe these issues should now be resolved.  All versions of `llvm` are relocatable bottles and built with the system `gcc` in CI.
