### ISSUE TITLE
binwalk & terraform are listed as Apple Silicon but they are not.

### ISSUE THREAD

**Issue by Knight1** [Homebrew/linuxbrew-core#22277]
Hi!

binwalk & terraform are listed on the [Website](https://formulae.brew.sh/formula/terraform#default) as Apple Silicon compatible but 

```% brew install binwalk
Error: binwalk: no bottle available!
You can try to install from source with:
  brew install --build-from-source binwalk
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

The Terraform PR is still open https://github.com/Homebrew/homebrew-core/pull/68456

We should fix this.

**Comment by danielnachun** [comment]
You have posted this in the repo for Homebrew on **Linux**, not macOS.  Please visit https://github.com/Homebrew/homebrew-core for macOS-related issues.
