### ISSUE TITLE
gitui: Installation error

### ISSUE THREAD

**Issue by peaceiris** [Homebrew/linuxbrew-core#22329]
- Ubuntu 18.04.5 LTS
- Homebrew 3.0.1

```console
$ brew install gitui
libiconv: is not needed on Linux, where iconv.h is provided by glibc
Error: An unsatisfied requirement failed this build.
```

This may be related to #20601 and same as https://github.com/extrawurst/gitui/issues/200.

**Comment by danielnachun** [comment]
This formula is one of several that have `uses_from_macos "libiconv"`.  I believe we need to get rid of that line entirely, as it is not needed for macOS or Linux.  I'll update here when I've removed those lines and tried to bottle the affected formulae.

**Comment by danielnachun** [comment]
This is now bottled after https://github.com/Homebrew/linuxbrew-core/pull/22364 and https://github.com/Homebrew/linuxbrew-core/commit/a6ff2e039531b1f57f50dbdb12e2d2130e89b2c7.
