### ISSUE TITLE
Neovim 0.4.4_1 bottle URL is broken: Failed to download resource (404)

### ISSUE THREAD

**Issue by sergekir** [Homebrew/linuxbrew-core#22333]
# Bug report

**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x] ran `brew update` and can still reproduce the problem?
- [x] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [ ] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [ ] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

## What you were trying to do (and why)

I'm trying to update `neovim` to the latest version using bottle.
 
## What happened (include command output)

Bottle URL is broken (returns 404)

https://linuxbrew.bintray.com/bottles/neovim-0.4.4_1.x86_64_linux.bottle.tar.gz

<details>
  <summary>Command output</summary>
  <pre>

brew upgrade --force-bottle neovim                                                                     ==> Upgrading 1 outdated package:
neovim 0.4.4 -> 0.4.4_1
==> Upgrading neovim 0.4.4 -> 0.4.4_1

==> Downloading https://linuxbrew.bintray.com/bottles/neovim-0.4.4_1.x86_64_linux.bottle.tar.gz
curl: (22) The requested URL returned error: 404 Not Found

Error: Failed to download resource "neovim"
Download failed: https://linuxbrew.bintray.com/bottles/neovim-0.4.4_1.x86_64_linux.bottle.tar.gz
  </pre>
</details>

## What you expected to happen

Successful upgrade of neovim bottle.

## Step-by-step reproduction instructions (by running `brew install` commands)

`brew upgrade --force-bottle neovim`

**Comment by jonchang** [comment]
Thanks for reporting. This was a very interesting bug. Once https://github.com/Homebrew/homebrew-core/pull/71636 is merged into homebrew/core and linuxbrew/core this will be fixed.

**Comment by hongtron** [comment]
Thanks for the fast PR! Looks like the branch is merged, but I'm seeing the same command output as in the original issue description (after `brew update && brew update && brew doctor`). Is this normal delay in publishing the archive, or might something still be wonky?

**Comment by jonchang** [comment]
https://github.com/Homebrew/linuxbrew-core/commit/4e1e8897522fcf3eda91f165ddc6bceb2b17a6a6
