### ISSUE TITLE
Make error when updating Cups

### ISSUE THREAD

**Issue by m3griffi** [Homebrew/linuxbrew-core#22338]
==> Reinstalling cups 
==> ./configure --with-components=core --without-bundledir --prefix=/home/linuxbrew/.linuxbrew/Cellar/cups/2.3.3op2 --libdir=/home/linuxbrew/.linuxbrew/Cellar/cups/2.3.3op2/lib
==> make install
Last 15 lines from /home/marlong/.cache/Homebrew/Logs/cups/02.make:
Compiling options.c...
Compiling pwg-media.c...
Compiling raster-error.c...
Compiling raster-stream.c...
Compiling request.c...
pwg-media.c:48:3: internal compiler error: Illegal instruction
   _PWG_MEDIA_IN("na_personal_3.625x6.5in", NULL, "EnvPersonal", 3.625, 6.5),
   ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/linuxbrew-core/issues> for instructions.
make[1]: *** [../Makedefs:270: pwg-media.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/cups-20210222-12604-fijz61/cups-2.3.3op2/cups'
make: *** [Makefile:168: install-data] Error 2

**Comment by jonchang** [comment]
Please always fill out the issue template. This issue can be reopened when you provide all requested information.
