### ISSUE TITLE
bpytop: Request for a bottle

### ISSUE THREAD

**Issue by mellery451** [Homebrew/linuxbrew-core#22359]
**Please note we will close your issue without comment if you delete, do not read or do not fill out the issue checklist below and provide ALL the requested information. If you repeatedly fail to use the issue template, we will block you from ever submitting issues to Homebrew again.**

- [x ] checked that there aren't other open issues for the same formula bottle request?
- [-] does the FORMULA not have the `bottle` block?
- [-] ran `brew install FORMULA` and it succeeded?

(currently fails to build locally for me:)

  ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
  Exception information:
  Traceback (most recent call last):
    File "/home/linuxbrew/.linuxbrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
      status = self.run(options, args)
    File "/home/linuxbrew/.linuxbrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
      return func(self, options, args)
    File "/home/linuxbrew/.linuxbrew/Cellar/bpytop/1.0.63/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 358, in run
      raise InstallationError(
  pip._internal.exceptions.InstallationError: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
  Removed build tracker: '/tmp/pip-req-tracker-opwve_uw'
  Installing build dependencies: finished with status 'error'

but since I have no other way to open an issue against this repo, I'm creating the bottle request. Of course, having a bottle would solve the issue too. thanks.

**Comment by danielnachun** [comment]
The bottle is now built after https://github.com/Homebrew/linuxbrew-core/pull/22363 and https://github.com/Homebrew/linuxbrew-core/commit/a7f88d93abe1ce76a3e0313c951a469cd4249f80.

**Comment by mellery451** [comment]
works perfectly - thanks.
