### ISSUE TITLE
Missing bottles after merge

### ISSUE THREAD

**Issue by iMichka** [Homebrew/linuxbrew-core#22414]
qt #22412
qt@5 #22413 afd07c83a6ba9bc4c2fbe7ba425094a3fd4ed752
qtkeychain
cgal 463809684ab7a66368183057120cb07b46e70ec0
djview4 #22419 32bd32335f8100b6346d388699fb7bec14b236f9
gnuplot a3bfc67af88db03a462cc2b0ca03840897a1f8ca
gpsbabel b77d3af9783a3c9a65dc6bdca31872f182895b91
inspectrum 208390ed1c7b4e4239776420de9037cbd02f5072
octave
poppler
pyqt 980bb20f25b0d389b507c4a04124a2709701e95e
qcachegrind
qscintilla2

vtk@8.2 #22404 dbdac925233a31d829355cbbb3928cc947da1a33
gdcm
opencv

vtk
gdal

pgpool-ii, osm2pgsql

**Comment by danopia** [comment]
I just noticed node@14 doesn't have a linux bottle right now and it seems various 'merge' commits are not including new linux bottles when updating packages. Is there a strategy for getting bottles posted onto these? Otherwise it seems like building from source is going to be more common for a while 😄

**Comment by dawidd6** [comment]
The ultimate solution to this is core tap merger. We are currently in the process to do so. After completion there will no more be a problem with missing bottles.

**Comment by latipun7** [comment]
[postgresql](https://formulae.brew.sh/formula-linux/postgresql) missing linux bottle too.

**Comment by iMichka** [comment]
Regarding `postgresql` it fails to build against openldap 2.5, as the `ldap_r.so` file is gone and has been replaced by `ldap.so`. If someone could check if there is a patch for this it would be great to move things forward.

**Comment by develop7** [comment]
https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/nushell.rb looks missing too

**Comment by iMichka** [comment]
Closing here, we focus on bottling in homebrew-core, so the effort has to be done in that repo.
