### ISSUE TITLE
brew install latexindent: OS unsupported

### ISSUE THREAD

**Issue by tueda** [Homebrew/linuxbrew-core#22542]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

gist-logs: https://gist.github.com/tueda/039aa95ffb74faeed4465bc153771590

Sorry that I checked `The brew doctor above contains no "Warning" lines.` to proceed, though there are many "Warning" lines, which are probably irrelevant for this issue.

Related discussion: https://github.com/Homebrew/discussions/discussions/1027

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I tried `brew install latexindent` (to install it).

### What happened (include all command output)?

Got the following error message:
```
perl
Makefile.PL
INSTALL_BASE=/home/linuxbrew/.linuxbrew/Cellar/latexindent/3.8.3_1/libexec

OS unsupported
```

### What did you expect to happen?

`latexindent` (which is a Perl script) should be successfully installed.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew update
brew install latexindent
```

**Comment by danielnachun** [comment]
This is now fixed after https://github.com/Homebrew/homebrew-core/pull/73995 was merged to linuxbrew-core.  There is currently an audit issue that prevents this from bottling, but it builds correctly from source so it is now fixed.
