### ISSUE TITLE
Unable to install tree-sitter

### ISSUE THREAD

**Issue by lalitmee** [Homebrew/linuxbrew-core#22644]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
- brew config

HOMEBREW_VERSION: 3.0.7-44-g7e2ba95
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7e2ba95169593366565e84bce44da28a5aefe62c
Last commit: 25 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 0a25b88d52fda35348904d58e2065242c14d4213
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :1
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 11.1 build (parse error)
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.8.0-7642-generic x86_64 GNU/Linux
OS: Pop!_OS 20.04 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: 2.7.0
glibc: N/A
gcc@5: N/A
xorg: N/A

- brew doctor

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/lalitmee/.pyenv/shims/python2.7-config
  /home/lalitmee/.pyenv/shims/python3-config
  /home/lalitmee/.pyenv/shims/python-config
  /home/lalitmee/.pyenv/shims/python2-config
  /home/lalitmee/.pyenv/shims/python3.8-config

Unexpected header files:
  /usr/local/include/libffmpegthumbnailer/ffmpegthumbnailertypes.h
  /usr/local/include/libffmpegthumbnailer/filmstripfilter.h
  /usr/local/include/libffmpegthumbnailer/ifilter.h
  /usr/local/include/libffmpegthumbnailer/imagetypes.h
  /usr/local/include/libffmpegthumbnailer/videoframe.h
  /usr/local/include/libffmpegthumbnailer/videothumbnailer.h
  /usr/local/include/libffmpegthumbnailer/videothumbnailerc.h

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/libffmpegthumbnailer.pc
```

### 

- [X] The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I am trying to install the `tree-sitter` to use it inside `neovim` for syntax highlighting.

### What happened (include all command output)?

/home/lalitmee/.cache/Homebrew/downloads/bae893027c031d3ca00b3d1a71f2159823f39f0e9d53f1e844e1a65b68c079c9--tree-sitter-0.19.4.tar.gzbrew uninstall --ignore-dependencies tree-sittersudo chown -R $(whoami) /home/linuxbrew/.linuxbrew/Cellar/ffmpeg/4.3.2_1Warning: Formula reports different sha256:❯ brew install tree-sitter
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

==> Downloading https://github.com/tree-sitter/tree-sitter/archive/v0.19.4.tar.gz
==> Downloading from https://codeload.github.com/tree-sitter/tree-sitter/tar.gz/v0.19.4
      # -=#=- #     #
Error: SHA256 mismatch
Expected: b90c1107a3e09b2dbef9ba317db9fde18f7222898d8470782f539cee286eebad
  Actual: 98e6b7f77d277235ef43023a8eee37745d1bc315c138481ed1b054cff158e817
    File: /home/lalitmee/.cache/Homebrew/downloads/bae893027c031d3ca00b3d1a71f2159823f39f0e9d53f1e844e1a65b68c079c9--tree-sitter-0.19.4.tar.gz
To retry an incomplete download, remove the file above.
HOMEBREW_VERSION: 3.0.7-44-g7e2ba95
ORIGIN: https://github.com/Homebrew/brew
HEAD: 7e2ba95169593366565e84bce44da28a5aefe62c
Last commit: 25 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 0a25b88d52fda35348904d58e2065242c14d4213
Core tap last commit: 3 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :1
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 11.1 build (parse error)
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.8.0-7642-generic x86_64 GNU/Linux
OS: Pop!_OS 20.04 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: 2.7.0
glibc: N/A
gcc@5: N/A
xorg: N/A
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  grv
  guile@2
  isl@0.18

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /home/lalitmee/.pyenv/shims/python2.7-config
  /home/lalitmee/.pyenv/shims/python3-config
  /home/lalitmee/.pyenv/shims/python-config
  /home/lalitmee/.pyenv/shims/python2-config
  /home/lalitmee/.pyenv/shims/python3.8-config

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/libffmpegthumbnailer/ffmpegthumbnailertypes.h
  /usr/local/include/libffmpegthumbnailer/filmstripfilter.h
  /usr/local/include/libffmpegthumbnailer/ifilter.h
  /usr/local/include/libffmpegthumbnailer/imagetypes.h
  /usr/local/include/libffmpegthumbnailer/videoframe.h
  /usr/local/include/libffmpegthumbnailer/videothumbnailer.h
  /usr/local/include/libffmpegthumbnailer/videothumbnailerc.h

Warning: Unbrewed '.pc' files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected '.pc' files:
  /usr/local/lib/pkgconfig/libffmpegthumbnailer.pc
❯ brew install tree-sitter
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 3 formulae.

==> Downloading https://github.com/tree-sitter/tree-sitter/archive/v0.19.4.tar.gz
Already downloaded: /home/lalitmee/.cache/Homebrew/downloads/bae893027c031d3ca00b3d1a71f2159823f39f0e9d53f1e844e1a65b68c079c9--tree-sitter-0.19.4.tar.gz
Error: SHA256 mismatch
Expected: b90c1107a3e09b2dbef9ba317db9fde18f7222898d8470782f539cee286eebad
  Actual: 98e6b7f77d277235ef43023a8eee37745d1bc315c138481ed1b054cff158e817
    File: /home/lalitmee/.cache/Homebrew/downloads/bae893027c031d3ca00b3d1a71f2159823f39f0e9d53f1e844e1a65b68c079c9--tree-sitter-0.19.4.tar.gz
To retry an incomplete download, remove the file above.

### What did you expect to happen?

I expect it to install `tree-sitter`

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
- brew install tree-sitter

It is the only command which will reproduce the issue.
```

**Comment by jcvar** [comment]
Thanks for opening this issue, I was trying to `install neovim --HEAD` when I came across this error.
I can confirm the `Actual` checksum, it was the same the couple of times I ran the command and even when downloading the source.

To be noted: the `sha256sum` on the formula was commited 2 days ago, while the v0.19.4 release was built only 1 day ago.

**Comment by iMichka** [comment]
This needs to be fixed in https://github.com/Homebrew/homebrew-core first. I'll merge the change when the fix is done there.

**Comment by iMichka** [comment]
Thanks for opening the issue nevertheless :)
