### ISSUE TITLE
sshfs fails to install due to missing `fuse` dependency

### ISSUE THREAD

**Issue by rb3ckers** [Homebrew/linuxbrew-core#22813]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
https://gist.github.com/rb3ckers/b4de4951f02ffa167cf57d73c5fec32d

Brew doctor has 2 unrelated warnings on pyenv and an unrelated package that I can't possibly uninstall (it being a dependency of gcc).
```

### 

The `brew doctor` above contains no "Warning" lines.

### What were you trying to do (and why)?

I was trying to install the sshfs formula with `brew install sshfs`. I was trying this because `sshfs` is needed by another formula that failed to install due to sshfs failing.

### What happened (include all command output)?

Installation failed during `pkg-config` checking. It cannot find the `fuse` package. That is indeed correct. If I run pkg-config manually (the pkg-config installed by brew) it shows I do have `fuse3` but not `fuse`. Looking at the `libfuse` formula that the sshfs formula depends on it shows indeed that fuse 3 is installed, while the sshfs formula is installing sshfs 2.10 which depends on fuse 2. There seems to be a discrepancy there.

I'm not sure if bumping the sshfs version to one of the 3.x versions is the desired solution, that would require an update to the patch that is applied as well. Or can that be dropped as it is OSX only?

```
==> Downloading https://github.com/libfuse/sshfs/commit/667cf34622e2e873db776791df275c7a582d6295.patch?full_index=1
Already downloaded: /home/remco/.cache/Homebrew/downloads/cdcad74dd3989c7992d0df5c9d06cabde2b6d7523ddbb551712a3733e0ba4b02--667cf34622e2e873db776791df275c7a582d6295.patch
==> Downloading https://github.com/libfuse/sshfs/releases/download/sshfs-2.10/sshfs-2.10.tar.gz
Already downloaded: /home/remco/.cache/Homebrew/downloads/530b903f02c905bfdb15b1859c391f8383cfaac570656f7396ed07ca0817fd93--sshfs-2.10.tar.gz
==> Patching
==> Applying 667cf34622e2e873db776791df275c7a582d6295.patch
patching file sshfs.c
Hunk #1 succeeded at 3862 (offset -58 lines).
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/sshfs/2.10_3
Last 15 lines from /home/remco/.cache/Homebrew/Logs/sshfs/01.configure:
checking dependency style of gcc-5... none
checking for library containing dlsym... -ldl
checking for pkg-config... /home/linuxbrew/.linuxbrew/opt/pkg-config/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for SSHFS... no
configure: error: Package requirements (fuse >= 2.3 glib-2.0 gthread-2.0) were not met:

No package 'fuse' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables SSHFS_CFLAGS
and SSHFS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

READ THIS: https://docs.brew.sh/Troubleshooting
```

### What did you expect to happen?

I expected the sshfs formula to be installed 

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
On linux run `brew install sshfs`
```

**Comment by danielnachun** [comment]
I think I know what's happening here.  On macOS, `sshfs` is deprecated because the FUSE driver on macOS has an incompatible license for homebrew-core, and is only available as a cask.  Furthermore we are deprecating cask dependencies in macOS.  The formula is **not** deprecated on Linux, but for the aforementioned reasons hasn't been updated in a while.

I think the version we currently have still depends on fuse2, which we don't have as a formula (but will need to add eventually for some other formulae).  The solution here is to update the `sshfs` formula (meaning we may need to make it Linux-only explicitly) to the newest version which supports fuse3.  This may not actually require any changes to the build process in the formula, just updating it and dealing with the macOS deprecation correctly.

**Comment by danielnachun** [comment]
`sshfs` is now bottled.  Thanks @rb3ckers for your help with this!
