### ISSUE TITLE
Missing some Perl dependencies in openssl@1.1

### ISSUE THREAD

**Issue by lzap** [Homebrew/linuxbrew-core#22985]
Hello,

I was asked by @danielnachun to create a separate issue in https://github.com/Homebrew/linuxbrew-core/issues/22015#issuecomment-808592213

```
==> Installing dependencies for ruby@2.7: openssl@1.1, gpatch, ncurses, readline and zlib
==> Installing ruby@2.7 dependency: openssl@1.1
==> perl Makefile.PL INSTALL_BASE=/home/foreman/.linuxbrew/Cellar/openssl@1.1/1.1.1j/libex
==> make PERL5LIB=/home/foreman/.linuxbrew/Cellar/openssl@1.1/1.1.1j/libexec/lib/perl5 CC=
Last 15 lines from /home/foreman/.cache/Homebrew/Logs/openssl@1.1/02.make:
2021-03-25 11:03:36 +0100

make
PERL5LIB=/home/foreman/.linuxbrew/Cellar/openssl@1.1/1.1.1j/libexec/lib/perl5
CC=gcc

Can't locate ExtUtils/Command.pm in @INC (you may need to install the ExtUtils::Command module) (@INC contains: inc blib/arch blib/lib /home/foreman/.linuxbrew/Cellar/openssl@1.1/1.1.1j/libexec/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5).
BEGIN failed--compilation aborted.
make: *** [Makefile:437: blib/lib/ExtUtils/.exists] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
Cannot update openssl@1.1 because their test fails https://github.com/Homebrew/linuxbrew-core/issues/22015
```

In my case the issue is that openssl needs perl to be built, however perl needs openssl. Therefore on a system without perl or without this specific module openssl cannot be built.

In my case, I have a CentOS 8 Stream here with perl installed however without the `ExtUtils/Command.pm` module. Quick search in my package manager showed that the missing piece is indeed perl ExtUtils::Command module, so I installed it:

```
dnf install perl-ExtUtils-Command
```

And openssl now bootstrap just fine. Then brew can install its own perl and other dependencies for the software I want to install: Ruby 2.7.

**Comment by danielnachun** [comment]
Thanks for reporting this.  If I open a PR to add that module and provide instructions for you to test locally, would you be willing to try it?  Both our CI Docker image and the machines I use already have `ExtUtils::Command` installed with their Perl distro, so you'd need to confirm it fixes it the install for you without needing to use `dnf` on your machine locally.

**Comment by lzap** [comment]
Sure let me know when and how.

**Comment by MikeMcQuaid** [comment]
Closing, sorry. If this issue is still relevant: please reopen on homebrew-core.
