### ISSUE TITLE
Error: no implicit conversion of false into String

### ISSUE THREAD

**Issue by mwm126** [Homebrew/linuxbrew-core#22986]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config
HOMEBREW_VERSION: 3.1.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: bc9b98aa0ba777889218ac51f67ccc76b0be6a28
Last commit: 2 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 1e54b8510a0f8f227f5b1acd2f0fdeea0d87f580
Core tap last commit: 4 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 2
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dual-core 64-bit zen
Clang: 11.1 build (parse error)
Git: 2.23.4 => /bin/git
Curl: 7.61.1 => curl
Kernel: Linux 4.14.225-169.362.amzn2.x86_64 x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.26
/usr/bin/gcc: 7.3.1
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A





brew doctor
Your system is ready to brew.
```

### 

I ran `brew update` and am still able to reproduce my issue.
I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install awscli fails; maybe the netbpm depedency?

### What happened (include all command output)?

brew install awscli
==> Downloading https://ghcr.io/v2/linuxbrew/core/netpbm/manifests/10.86.21
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/37245d9571693bc53b4345dbb0d216184d4f618e252a0b380791f7d7520390f6--netpbm-10.86.21.bottle_manifest.json
==> Downloading https://ghcr.io/v2/linuxbrew/core/netpbm/blobs/sha256:49aa89662fc30e78fc8628b87a21de2599a2748798dabe2800d97dfbf21549d2
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/9b282391e02b420600658b6612c69889e32aaf3d2bfe0d68bca53277439d6b94--netpbm--10.86.21.x86_64_linux.bottle.tar.gz
==> Downloading https://ghcr.io/v2/linuxbrew/core/psutils/manifests/p17-1
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/dada597ac532b1372304d5cb9afa200df2620c62d9a600e1cb4902fdb7fc7253--psutils-p17-1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/linuxbrew/core/psutils/blobs/sha256:096cf231524d69e34b00382a617d3269e86926c78b8071752a568031b91a3258
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/c1840e3dcdf61d9dcd66bb4361fc50e9456d70ed3ef9811e9f1655cdc675e6fa--psutils--p17.x86_64_linux.bottle.1.tar.gz
==> Downloading https://ghcr.io/v2/linuxbrew/core/uchardet/manifests/0.0.7
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/9ae9080bd3459943d517becda8785c158556ace94b94135596280e1f45fc9354--uchardet-0.0.7.bottle_manifest.json
==> Downloading https://ghcr.io/v2/linuxbrew/core/uchardet/blobs/sha256:6d5d176e4f2caae139d5f42376a08da54913f4018f26504267677f6ab319b641
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/40654fac13731b206179398a330b6d2e9b86248203994802b8f12e458882794c--uchardet--0.0.7.x86_64_linux.bottle.tar.gz
==> Downloading https://ghcr.io/v2/linuxbrew/core/berkeley-db/manifests/18.1.40
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/ae724b4d70a1879f33c74bab6dd7e477c347965e04701c4766aec0548f09609f--berkeley-db-18.1.40.bottle_manifest.json
==> Downloading https://ghcr.io/v2/linuxbrew/core/berkeley-db/blobs/sha256:9935bb07d8c09bc317aa61776b12b0277b136d1d5dfb65feb85c786a71a93e37
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/527d0b9034d43711418e0ccf37eddb71b4df07e4b16bcd38935835e6b9f67b03--berkeley-db--18.1.40.x86_64_linux.bottle.tar.gz
==> Downloading https://ghcr.io/v2/linuxbrew/core/perl/manifests/5.32.1_1
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/3b9604bfc1e70a9c67e2cefcda5517ff8f9b141d6d9a840df8154da9e1d5befe--perl-5.32.1_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/linuxbrew/core/perl/blobs/sha256:141572cbbe109dec63cee8b9b84fc97f07a41027c6b8f4fad404120e95719f6e
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/a448a4d63f052728261a3cb7010ba874e01f4e6f7002e8b458df52023ecadd73--perl--5.32.1_1.x86_64_linux.bottle.tar.gz
==> Downloading https://ghcr.io/v2/linuxbrew/core/pcre/manifests/8.44
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/2d63360a99ae8a6b885a68fe674be97cc8a1515e3d597ed57d379e1249d399ef--pcre-8.44.bottle_manifest.json
==> Downloading https://ghcr.io/v2/linuxbrew/core/pcre/blobs/sha256:e09f36059975d108b0e42fa9d69b9ed25bc81bc25371dcee58134ad7416a6a61
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/d7138e1a1dd70da6692172d97ea568db75dd574c4b34fcee9e4e9217b1a39bdb--pcre--8.44.x86_64_linux.bottle.tar.gz
==> Downloading https://ghcr.io/v2/linuxbrew/core/glib/manifests/2.68.1
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/47c78b7a309d5823dcedfbc35d51d8028e13077f445100baef5d623520fa1d43--glib-2.68.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/linuxbrew/core/glib/blobs/sha256:6383208467d73f17e9aba2c5fa990cdba980151054e867a6dcce60aa6fbe1ee8
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/ff542074dae3eb4507e29921bbf9dafccc05fb0b3f2a8e6d4ec0db216a7d972f--glib--2.68.1.x86_64_linux.bottle.tar.gz
==> Downloading https://ghcr.io/v2/linuxbrew/core/groff/manifests/1.22.4_1
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/f6425e6e1a347b03450fbca11b4b1586522515ad568d46ea66683a6d2ef67430--groff-1.22.4_1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/linuxbrew/core/groff/blobs/sha256:a4f66aad6f49b4e5f562e79837c4f7a189e908e074f18d8fdcad6df48bba98ac
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/88ef13fa259e02ded2233fa50762a8e2ab93080ccd8d66e68eb2f5eea79e6cbb--groff--1.22.4_1.x86_64_linux.bottle.tar.gz
==> Downloading https://ghcr.io/v2/linuxbrew/core/libyaml/manifests/0.2.5
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/40426523f32c67053524ea24c739b6723dc4f36d4c182b804596039f6a9c8127--libyaml-0.2.5.bottle_manifest.json
==> Downloading https://ghcr.io/v2/linuxbrew/core/libyaml/blobs/sha256:7467d0c0a6a389b6e3b90dee0ea083be1a85be412f85afc0a6f027ad838dd6c0
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/9a1c74fd573893ef0cb6440709f6f0b1d6166caff4d4cd967b9ad188ba3a81b3--libyaml--0.2.5.x86_64_linux.bottle.tar.gz
==> Downloading https://github.com/aws/aws-cli/archive/2.1.37.tar.gz
Already downloaded: /home/ssm-user/.cache/Homebrew/downloads/453dd257ab5e8b986a8108b6dae8dad64f3a2becc3059fb136f1d660d8217fc3--aws-cli-2.1.37.tar.gz
==> Installing dependencies for awscli: netpbm, psutils, uchardet, berkeley-db, perl, pcre, glib, groff and libyaml
==> Installing awscli dependency: netpbm
==> Pouring netpbm--10.86.21.x86_64_linux.bottle.tar.gz
Error: no implicit conversion of false into String
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:47:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:47:in `popen'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:47:in `popen'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils/popen.rb:9:in `popen_read'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/git_repository.rb:120:in `popen_git'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/git_repository.rb:35:in `git_head'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/tap.rb:181:in `git_head'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:1165:in `pour'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:418:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:741:in `install_dependency'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:661:in `block in install_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:661:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:661:in `install_dependencies'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula_installer.rb:389:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:422:in `install_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:324:in `block in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:322:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:322:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'

### What did you expect to happen?

Install `awscli` successfully

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install awscli
```

**Comment by danielnachun** [comment]
This issue was probably related to the transition to GitHub packages.  I can't reproduce this locally, so I'm closing.
