### ISSUE TITLE
sdl2_ttf: can't build formula from tap because bottle not available

### ISSUE THREAD

**Issue by aconchillo** [Homebrew/linuxbrew-core#23060]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew config
HOMEBREW_VERSION: 3.1.2
ORIGIN: https://github.com/Homebrew/brew
HEAD: bc9b98aa0ba777889218ac51f67ccc76b0be6a28
Last commit: 5 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: ee86da1b558991aa4cf39a0d0c81d14faccf7ba7
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 6
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: hexa-core 64-bit skylake
Clang: N/A
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.10.25-linuxkit x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
```

```
$ brew doctor
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I was trying to build a new version of a formula from my tap.

https://github.com/aconchillo/homebrew-guile/pull/31

The formula depends on `sdl2_tff`: https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/sdl2_ttf.rb

### What happened (include all command output)?

The github workflow job failed saying that `sdl2_ttf` needs to be a bottle and that building from source is not supported (see below).

https://github.com/aconchillo/homebrew-guile/pull/31/checks?check_run_id=2367910533

```
Error: sdl2_ttf: no bottle available!
You can try to install from source with:
  brew install --build-from-source sdl2_ttf
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

### What did you expect to happen?

Tap formulas to build properly. This was not happening before, so something changed that cause the bottles to go away.

I initially reported this issue at https://github.com/Homebrew/homebrew-core/issues/75345 but they mentioned to come to `linuxbrew-core` instead. I have locally installed `sdl2_ttf` without issues, so there shouldn't be a problem rebuilding the bottles.

### Step-by-step reproduction instructions (by running `brew` commands)

Steps are in the job:

https://github.com/aconchillo/homebrew-guile/pull/31/checks?check_run_id=2367910533

**Comment by danielnachun** [comment]
For some reason the bottle is missing.  I have dispatched a new bottle request and we'll see if it fails to build and needs to be fixed.

**Comment by aconchillo** [comment]
thank you @danielnachun! that fixed the issue, closing.
