### ISSUE TITLE
bug: installing podman in WSL installs the darwin version

### ISSUE THREAD

**Issue by gclair** [Homebrew/linuxbrew-core#23170]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config:

❯ brew config
HOMEBREW_VERSION: 3.1.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 227445ece9414a82aa8929b91ca2e0cca28a561b
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 1b335ee000c1ca1c2a52edb7dfc9f46c989952d2
Core tap last commit: 10 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit zen3
Clang: N/A
Git: 2.20.1 => /usr/bin/git
Curl: 7.64.0 => /usr/bin/curl
Kernel: Linux 5.4.72-microsoft-standard-WSL2 x86_64 GNU/Linux
OS: Unknown
Host glibc: 2.28
/usr/bin/gcc: 8.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
```
brew doctor:
```
❯ brew doctor
Your system is ready to brew.
```
```


### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install podman for Debian Linux inside of WSL.

### What happened (include all command output)?

Installing podman in Debian compiled and installed a Darwin binary.

```
❯ brew install podman
==> Downloading https://github.com/containers/podman/archive/v3.1.2.tar.gz
Already downloaded: /home/gclair/.cache/Homebrew/downloads/15458fe10827377fcc1d3f56b3d6c3953073425525eaae391787aeb1321622bc--podman-3.1.2.tar.gz
==> make podman-remote-darwin
==> make install-podman-remote-darwin-docs
==> Caveats
zsh completions have been installed to:
  /home/linuxbrew/.linuxbrew/share/zsh/site-functions
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/podman/3.1.2: 159 files, 29.9MB, built in 1 minute 5 seconds

❯ file  /home/linuxbrew/.linuxbrew/Cellar/podman/3.1.2/bin/podman
/home/linuxbrew/.linuxbrew/Cellar/podman/3.1.2/bin/podman: Mach-O 64-bit x86_64 executable

```


### What did you expect to happen?

I expected to get a Linux version of the binary.


### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install podman
```
```

**Comment by danielnachun** [comment]
We're a bit stuck with this one.  There was an attempt to fix this earlier, but it became clear that a number of dependencies need to be added as new formula (some of them possibly Linux-only): https://github.com/Homebrew/linuxbrew-core/pull/22227.  I expect we'll eventually get this to build on Linux, but it may not be for a while.

**Comment by gclair** [comment]
Appreciate the feedback on this. If thats the case could podman be removed from linux installs? Or at least something that very clearly states it won't work on Linux installs?

**Comment by MikeMcQuaid** [comment]
Closing, sorry. If this issue is still relevant: please reopen on homebrew-core.
