### ISSUE TITLE
Upgrading device-mapper 2.03.11 -> 2.03.12 Failed

### ISSUE THREAD

**Issue by apulache** [Homebrew/linuxbrew-core#23238]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$ brew upgrade
Upgrading 1 outdated package:
device-mapper 2.03.11 -> 2.03.12
==> Upgrading device-mapper 2.03.11 -> 2.03.12 
==> Downloading https://ghcr.io/v2/linuxbrew/core/device-mapper/manifests/2.03.12
curl: (22) The requested URL returned error: 404                              

Error: Failed to download resource "device-mapper_bottle_manifest"
Download failed: https://ghcr.io/v2/linuxbrew/core/device-mapper/manifests/2.03.12
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Upgrading  device-mapper 2.03.11 -> 2.03.12

### What happened (include all command output)?

$ brew upgrade
Upgrading 1 outdated package:
device-mapper 2.03.11 -> 2.03.12
==> Upgrading device-mapper 2.03.11 -> 2.03.12 
==> Downloading https://ghcr.io/v2/linuxbrew/core/device-mapper/manifests/2.03.12
curl: (22) The requested URL returned error: 404                              

Error: Failed to download resource "device-mapper_bottle_manifest"
Download failed: https://ghcr.io/v2/linuxbrew/core/device-mapper/manifests/2.03.12

### What did you expect to happen?

Upgrade successful

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
$ brew upgrade
Upgrading 1 outdated package:
device-mapper 2.03.11 -> 2.03.12
==> Upgrading device-mapper 2.03.11 -> 2.03.12 
==> Downloading https://ghcr.io/v2/linuxbrew/core/device-mapper/manifests/2.03.12
curl: (22) The requested URL returned error: 404                              

Error: Failed to download resource "device-mapper_bottle_manifest"
Download failed: https://ghcr.io/v2/linuxbrew/core/device-mapper/manifests/2.03.12
```

Enviroment
=========

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"
NAME="Ubuntu"
VERSION="21.04 (Hirsute Hippo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 21.04"
VERSION_ID="21.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute

**Comment by danielnachun** [comment]
Fixed by https://github.com/Homebrew/linuxbrew-core/commit/2dc1bc3054119af378b99b84cdf51948a3698e95.
