### ISSUE TITLE
Error: bats-core: no bottle available!

### ISSUE THREAD

**Issue by smorimoto** [Homebrew/linuxbrew-core#23342]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
I don't have any hardware which installed brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

`brew install bats-core`

### What happened (include all command output)?

```
Error: bats-core: no bottle available!
You can try to install from source with:
  brew install --build-from-source bats-core
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

### What did you expect to happen?

Installation should be successful without `--build-from-source`.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. `brew install bats-core`
```

**Comment by danielnachun** [comment]
This will be fixed once https://github.com/Homebrew/homebrew-core/pull/78736 is merged in homebrew-core and then into here.  After that we can request a bottle and this will be fixed.

**Comment by smorimoto** [comment]
Cool, thank you @danielnachun!

**Comment by danielnachun** [comment]
This is now bottled: https://github.com/Homebrew/linuxbrew-core/commit/3b34e1045894f7d2f0e0f43978b867386c22a9d5.

**Comment by smorimoto** [comment]
Great thanks.
