### ISSUE TITLE
Homebrew on Linux should use bottles if a symlink from /home/linuxbrew/.linuxbrew exists

### ISSUE THREAD

**Issue by vriesk** [Homebrew/linuxbrew-core#23567]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
$  brew config
HOMEBREW_VERSION: 3.1.12
ORIGIN: https://github.com/Homebrew/brew
HEAD: 33e71c99dc40c0a134a236fffe2594ae6572d83c
Last commit: 9 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: de00112de28ef7d9a42b3c6f69bb48836f3865dc
Core tap last commit: 3 days ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 12.0.0 build (parse error)
Git: 2.30.2 => /usr/bin/git
Curl: 7.74.0 => /usr/bin/curl
Kernel: Linux 5.10.16.3-microsoft-standard-WSL2 x86_64 GNU/Linux
OS: Debian GNU/Linux 11 (bullseye) (bullseye)
Host glibc: 2.31
/usr/bin/gcc: 10.2.1
/usr/bin/ruby: 2.7.3
glibc: N/A
gcc@5: N/A
xorg: N/A
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

I want to have a non-standard location for homebrew installation.

### What happened (include all command output)?

`brew` will by default use only pre-built bottles iff the installation directory is `/home/linuxbrew/.linuxbrew`. It will compile from source if the installation directory is any other than that.

### What did you expect to happen?

I would expect/want that if a symlink pointing correctly from `/home/linuxbrew/.linuxbrew` to the actual installation directory exists, `brew` would accept the pre-built binaries, as the hardcoded path in those binaries will resolve correctly.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. Install brew to /somewhere
2. mkdir -p /home/linuxbrew
3. ln -s /somewhere /home/linuxbrew/.linuxbrew
4. brew install something

.... does not use bottles.
```

**Comment by MikeMcQuaid** [comment]
Closing, sorry. If this issue is still relevant: please reopen on homebrew-core.
