### ISSUE TITLE
zip manifest HTTP-404 error while install Maven

### ISSUE THREAD

**Issue by joeman155** [Homebrew/linuxbrew-core#23713]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
joeman@uno-dev:~$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  guile@2
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

i want to install Maven

### What happened (include all command output)?

.
.
.
==> Downloading https://ghcr.io/v2/linuxbrew/core/libxfixes/manifests/6.0.0
Already downloaded: /home/joeman/.cache/Homebrew/downloads/4a5dcbee895967570b59874815b725c74098c5fe1cef19c658f4cf8c912cfc1d--libxfixes-6.0.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/linuxbrew/core/libxfixes/blobs/sha256:b10945be16e84b8e7cd08c600d64408e1332574f1fa8e33a44aadb3bf5e0
Already downloaded: /home/joeman/.cache/Homebrew/downloads/cccb975a9af424863be745b82175e46b836578f0f1c43524a5bc189016ead670--libxfixes--6.0.0.x86_64_linux.bottle.tar.gz
==> Downloading https://ghcr.io/v2/linuxbrew/core/libxi/manifests/1.7.10
Already downloaded: /home/joeman/.cache/Homebrew/downloads/9add7e2024d29f66e295329381dabadce368a62900e63b43697097ee69f2f2c9--libxi-1.7.10.bottle_manifest.json
==> Downloading https://ghcr.io/v2/linuxbrew/core/libxi/blobs/sha256:3f8973202e820185cf4976d01580f63ef9f43d299f7a983415abc08a5e658a1d
Already downloaded: /home/joeman/.cache/Homebrew/downloads/c8019268a5a072c58af38c9604f46d9b5251390459df7807038d0d5a936e3415--libxi--1.7.10.x86_64_linux.bottle.tar.gz
==> Downloading https://ghcr.io/v2/linuxbrew/core/libxtst/manifests/1.2.3
Already downloaded: /home/joeman/.cache/Homebrew/downloads/4e75b8f815657703816ba62c75683713eff3e169959d56b2bbb673496d2ba2f6--libxtst-1.2.3.bottle_manifest.json
==> Downloading https://ghcr.io/v2/linuxbrew/core/libxtst/blobs/sha256:683834d974c399696213f15dffff6104240d75436def1c233f4f490198913b
Already downloaded: /home/joeman/.cache/Homebrew/downloads/819fd1ed9ba324e848a9e79a5dad16eb63144c99d7ca0cb9919cc1b1d215c13d--libxtst--1.2.3.x86_64_linux.bottle.tar.gz
==> Downloading https://ghcr.io/v2/linuxbrew/core/zip/manifests/3.0-2
curl: (22) The requested URL returned error: 404                              

Error: Failed to download resource "zip_bottle_manifest"
Download failed: https://ghcr.io/v2/linuxbrew/core/zip/manifests/3.0-2

### What did you expect to happen?

Maven to be installed and no errors.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install maven
```

**Comment by IGOTAGHOSTa1007** [comment]
title: "my awesome site: an adventure in parse errors".

**Comment by MikeMcQuaid** [comment]
Closing, sorry. If this issue is still relevant: please reopen on homebrew-core.
