### ISSUE TITLE
sudo <any_command> not working due to symlink?

### ISSUE THREAD

**Issue by freeo** [Homebrew/linuxbrew-core#23914]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
(`brew install neovim` works fine)

❯ brew update
Already up-to-date.
❯ brew config
HOMEBREW_VERSION: 3.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 16b01d6e019e93b66e41d0bb8da66fec3fcc5cca
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: 2cc8aa7af7216e265fc20860cc22b7e94b134edd
Core tap last commit: 10 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: :1
HOMEBREW_EDITOR: snap run nvim
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: dodeca-core 64-bit zen
Clang: N/A
Git: 2.30.2 => /bin/git
Curl: 7.74.0 => /usr/bin/curl
Kernel: Linux 5.11.0-7620-generic x86_64 GNU/Linux
OS: Pop!_OS 21.04 (hirsute)
Host glibc: 2.33
/usr/bin/gcc: 10.3.0
/usr/bin/ruby: 2.7.2
glibc: N/A
gcc@5: N/A
xorg: N/A
❯ brew doctor
Your system is ready to brew.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

after installation, just trying to run `sudo nvim`

### What happened (include all command output)?

❯ sudo nvim
sudo: nvim: command not found

### What did you expect to happen?

Expectation: nvim opens in sudo mode

I've investigated up the point, that I removed all the symlinks and ran it directly like so, which works as expected:
`sudo /home/linuxbrew/.linuxbrew/Cellar/neovim/0.5.0/bin/nvim`

this alone doesn't work, as nvim is still a symlink:
`sudo /home/linuxbrew/.linuxbrew/bin/nvim`

I assume this is an issue for all packages trying to be run as sudo, but I didn't test more.

This is less of a bug and more how linuxbrew is designed, but this issue kept me from managing neovim with linuxbrew. Running this command as sudo is frequent enough to require a less brittle approach. I couldn't find anything regarding this issue in the web & issue tracker. At least it's documented now even if you decide to just close.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install neovim
sudo nvim
```

**Comment by gromgit** [comment]
> ❯ sudo nvim
> sudo: nvim: command not found

What's the output of `sudo env | grep PATH`? I'm betting that the Homebrew bin directory isn't in it.

That said:

> this alone doesn't work, as nvim is still a symlink:
> `sudo /home/linuxbrew/.linuxbrew/bin/nvim`

Nope, that means your install is b0rked:
```
$ brew install neovim
==> Downloading https://ghcr.io/v2/linuxbrew/core/unibilium/manifests/2.1.1
######################################################################## 100.0%
[...]
==> Installation times
unibilium                 0.157 s
libtermkey                0.070 s
libuv                     0.105 s
libvterm                  0.133 s
luv                       0.105 s
msgpack                   0.151 s
tree-sitter               0.237 s
libtirpc                  0.124 s
libnsl                    0.098 s
neovim                    9.073 s

$ sudo /home/linuxbrew/.linuxbrew/bin/nvim
# Neovim starts up just fine
```
What's the output of `ls -lL /home/linuxbrew/.linuxbrew/bin/nvim`?

**Comment by freeo** [comment]
Nice avatar :-D

You're right! I was trying `sudo echo $PATH` (which included linuxbrew) but now I suppose this isn't the same.
```
❯ sudo env | grep PATH
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
```

Looks good?!
```
❯ ls -lL /home/linuxbrew/.linuxbrew/bin/nvim
drwxr-xr-x   - root 22 Jul 15:42 bin
drwxr-xr-x   - root 22 Jul 12:14 codium
drwxr-xr-x   - root 22 Jul 12:14 core18
drwxr-xr-x   - root 22 Jul 15:42 nvim
drwxr-xr-x   - root 22 Jul 12:13 snapd
.r--r--r-- 548 root 22 Jul 11:50 README
```

**Comment by dawidd6** [comment]
```
alias sudo="sudo env \"PATH=$PATH\""
```
Then try again

**Comment by gromgit** [comment]
> Looks good?!
> 
> ```
> ❯ ls -lL /home/linuxbrew/.linuxbrew/bin/nvim
> drwxr-xr-x   - root 22 Jul 15:42 bin
> drwxr-xr-x   - root 22 Jul 12:14 codium
> drwxr-xr-x   - root 22 Jul 12:14 core18
> drwxr-xr-x   - root 22 Jul 15:42 nvim
> drwxr-xr-x   - root 22 Jul 12:13 snapd
> .r--r--r-- 548 root 22 Jul 11:50 README
> ```

Looks 100% wrong. The fact you got more than one line of output is confirmation that `.../bin/nvim` is pointing to a _directory_, which never makes sense. Try `brew reinstall nvim`.

**Comment by freeo** [comment]
reinstall doesn't change anything.

Also, it's pointing here:
`/home/linuxbrew/.linuxbrew/bin/nvim -> ../Cellar/neovim/0.5.0/bin/nvim`

**Comment by freeo** [comment]
@dawidd6 Your alias "fixes" it. I doubt adding to sudo env that way is encouraged though?!

**Comment by gromgit** [comment]
> reinstall doesn't change anything.
> 
> Also, it's pointing here:
> `/home/linuxbrew/.linuxbrew/bin/nvim -> ../Cellar/neovim/0.5.0/bin/nvim`

Then you should be seeing something like this, which you clearly aren't:
```
$ ls -l /home/linuxbrew/.linuxbrew/bin/nvim
lrwxrwxrwx 1 aho aho 31 Jul 22 22:42 /home/linuxbrew/.linuxbrew/bin/nvim -> ../Cellar/neovim/0.5.0/bin/nvim
$ ls -lL /home/linuxbrew/.linuxbrew/bin/nvim
-r-xr-xr-x 1 aho aho 3962440 Jul 22 22:42 /home/linuxbrew/.linuxbrew/bin/nvim
```
What's the output of:
```
ls -ld /home/linuxbrew/.linuxbrew /home/linuxbrew/.linuxbrew/bin
```
?

**Comment by gromgit** [comment]
> @dawidd6 Your alias "fixes" it. I doubt adding to sudo env that way is encouraged though?!

Yes, adding user-controlled directories (with binaries that can be subverted at any time) to `sudo`'s `PATH` is generally not encouraged.

**Comment by freeo** [comment]
I had `exa` for `ls`, which was interfering with those commands. It looks better now. I've repeated your other cmds as well:

```
freeo@pop-os:/snap$ ls -lL /home/linuxbrew/.linuxbrew/bin/nvim
-r-xr-xr-x 1 freeo freeo 3962440 Jul 22 17:05 /home/linuxbrew/.linuxbrew/bin/nvim
freeo@pop-os:/snap$ ls -ld /home/linuxbrew/.linuxbrew /home/linuxbrew/.linuxbrew/bin
drwxr-xr-x 14 freeo freeo 4096 Jul 22 11:31 /home/linuxbrew/.linuxbrew
drwxrwxr-x  2 freeo freeo 4096 Jul 22 17:05 /home/linuxbrew/.linuxbrew/bin
freeo@pop-os:/snap$ ls -ld /home/linuxbrew/.linuxbrew /home/linuxbrew/.linuxbrew/bin
file /home/linuxbrew/.linuxbrew/bin/nvim
drwxr-xr-x 14 freeo freeo 4096 Jul 22 11:31 /home/linuxbrew/.linuxbrew
drwxrwxr-x  2 freeo freeo 4096 Jul 22 17:05 /home/linuxbrew/.linuxbrew/bin
/home/linuxbrew/.linuxbrew/bin/nvim: symbolic link to ../Cellar/neovim/0.5.0/bin/nvim
```

```
freeo@pop-os:/snap$ ls -lL /home/linuxbrew/.linuxbrew/bin/nvim
-r-xr-xr-x 1 freeo freeo 3962440 Jul 22 17:05 /home/linuxbrew/.linuxbrew/bin/nvim
```

**Comment by gromgit** [comment]
And `sudo /home/linuxbrew/.linuxbrew/bin/nvim` still fails?

**Comment by dawidd6** [comment]
_Not encouraged_ and I found this solution to be working best tbh. Homebrew on Linux has a tough time with sudo because sudo filters PATH out. So we need to somehow sneak the prefix in later.

**Comment by freeo** [comment]
Something definitely changed, as this works now (it didn't before reinstall)
```
sudo /home/linuxbrew/.linuxbrew/bin/nvim
```

@dawidd6 Do you have this alias in your rc? Where exactly do you keep it?

**Comment by dawidd6** [comment]
In my shell config. I use fish, so the file is `config.fish`.

**Comment by freeo** [comment]
@gromgit  I've reread your first answer - you wrote `sudo /home/linuxbrew/.linuxbrew/bin/nvim` there already.
Does this imply I shouldn't expect a regular `sudo nvim` to work (without that alias)?

**Comment by gromgit** [comment]
> Something definitely changed, as this works now (it didn't before reinstall)
> 
> ```
> sudo /home/linuxbrew/.linuxbrew/bin/nvim
> ```

That means your original installation was b0rked exactly as I described it earlier (`nvim` linking to a directory instead of a binary).

> Does this imply I shouldn't expect a regular `sudo nvim` to work (without that alias)?

Yes. Every Linux distro I've seen has a stock `/etc/sudoers` config that locks the environment down for safety. You _can_ loosen those restrictions across all `sudo` invocations, but you'd better first read the sudoers man page carefully, to avoid punching a security hole the size of a blue whale.

**Comment by freeo** [comment]
Thank you! Much appreciated and closed.

**Comment by freeo** [comment]
In case somebody finds this and is interested in my final solution to enable `sudo nvim`:
```
  alias sudo='sudo '
  alias nvim='/home/linuxbrew/.linuxbrew/bin/nvim'
```

The sudo alias enables you to use another alias in subsequent parameters. Neat workaround that is explained here:
https://askubuntu.com/questions/22037/aliases-not-available-when-using-sudo

**Comment by gromgit** [comment]
>   alias sudo='sudo '

Note that this formulation will not expand your `nvim` alias if you need to use any `sudo` options. This likely won't be an issue with `nvim`, but it's something that may bite you with more advanced uses of `sudo` with, say, an `ls` alias.
