### ISSUE TITLE
python-launcher: Failed to download resource "python-launcher_bottle_manifest"

### ISSUE THREAD

**Issue by brettcannon** [Homebrew/linuxbrew-core#23953]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
> brew config                                                                                                          ~
HOMEBREW_VERSION: 3.2.4
ORIGIN: https://github.com/Homebrew/brew
HEAD: 071d769b00dca6abe73827fdc736d25372385105
Last commit: 6 hours ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: b98ded734e8b30d02503d1d11c2d7a1ee3a151b8
Core tap last commit: 10 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: vim
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit skylake
Clang: 10.0.0 build (parse error)
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.10.16.3-microsoft-standard-WSL2 x86_64 GNU/Linux
OS: Ubuntu 20.04.2 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A
```

```
> brew doctor                                                                                                          ~
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed formulae are deprecated or disabled.
You should find replacements for the following formulae:
  isl@0.18
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install the `python-launcher` bottle.

### What happened (include all command output)?

```
Updating Homebrew...
==> Downloading https://ghcr.io/v2/linuxbrew/core/python-launcher/manifests/1.0.0
curl: (22) The requested URL returned error: 404

Error: Failed to download resource "python-launcher_bottle_manifest"
Download failed: https://ghcr.io/v2/linuxbrew/core/python-launcher/manifests/1.0.0
```

### What did you expect to happen?

Install https://formulae.brew.sh/formula/python-launcher#default. Works on macOS, looks like Linux bottles were built.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
1. `brew install python-launcher`
```

**Comment by brettcannon** [comment]
May be related to #23906 .

**Comment by brettcannon** [comment]
https://github.com/Homebrew/homebrew-core/pull/81855 is the PR on the homebrew-core side which added the formula.

**Comment by iMichka** [comment]
Fixed by d6f5e1a16036f9722d3e6523a8af12cb70d1e0a3

**Comment by brettcannon** [comment]
@iMichka thanks! Is there anything I need to do to prevent the issue from occurring in the future?

**Comment by iMichka** [comment]
The issue happened due to the way we merge homebrew-core into linuxbrew-core. As it is a manual process, some errors happen. We are working on getting rid of linuxbrew-core, and rely only on homebrew-core. We are close to complete that migration. Once it is done, these kind of issues should not happen anymore.

**Comment by joelberkeley** [comment]
@iMichka thanks for the info. When you say close, are you talking days, weeks or months close?
