### ISSUE TITLE
Older local version when install Texlive

### ISSUE THREAD

**Issue by argyili** [Homebrew/linuxbrew-core#23978]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
brew config:
HOMEBREW_VERSION: 3.2.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3e52e8b48ab036af77a582219ea250107c84432f
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/linuxbrew-core
Core tap HEAD: dd830cd82f33c86f27afd5d5b882a9d4445535c6
Core tap last commit: 2 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /home/li-aiyi/.linuxbrew
HOMEBREW_REPOSITORY: /home/li-aiyi/.linuxbrew/Homebrew
HOMEBREW_CELLAR: /home/li-aiyi/.linuxbrew/Cellar
HOMEBREW_BROWSER: /home/li-aiyi/.vscode-server/bin/c3f126316369cd610563c75b1b1725e0679adfb3/bin/helpers/browser.sh
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 104
Homebrew Ruby: 2.6.3 => /home/li-aiyi/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: 104-core 64-bit skylake
Clang: 10.0.0 build (parse error)
Git: 2.25.1 => /bin/git
Curl: 7.68.0 => /usr/bin/curl
Kernel: Linux 5.4.0-66-generic x86_64 GNU/Linux
OS: Ubuntu 20.04.1 LTS (focal)
Host glibc: 2.31
/usr/bin/gcc: 9.3.0
/usr/bin/ruby: N/A
glibc: N/A
gcc@5: N/A
xorg: N/A

brew doctor:
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Your Homebrew's prefix is not /home/linuxbrew/.linuxbrew.
Some of Homebrew's bottles (binary packages) can only be used with the default
prefix (/home/linuxbrew/.linuxbrew).
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
unsupported configuration.
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Install Texlive for writing Latex on the server without sudo privilege. 

### What happened (include all command output)?

**Command**
```
==> ./install-tl -profile ./texlive.profile
Last 15 lines from /home/li-aiyi/.cache/Homebrew/Logs/texlive/01.install-tl:
-profile
./texlive.profile

Automated TeX Live installation using profile: ./texlive.profile
Loading https://ftp.jaist.ac.jp/pub/CTAN/systems/texlive/tlnet/tlpkg/texlive.tlpdb

=============================================================================
./install-tl: The TeX Live versions of the local installation
and the repository being accessed are not compatible:
      local: 2020
 repository: 2021
Perhaps you need to use a different CTAN mirror?
(For more, see the output of install-tl --help, especially the
 -repository option.  Online via https://tug.org/texlive/doc.)
=============================================================================

READ THIS: https://docs.brew.sh/Troubleshooting

These open issues may also help:
texlive 20210415 https://github.com/Homebrew/linuxbrew-core/pull/22998
```

<br>

**Analysis**
The remote repository has updated around July 29, 2021 (recently). However, the local version of Linuxbrew installing is still 2020 version. The versions conflict, so installation fails.

Speaking of the solution, maybe I can find one repository from the [list](https://ctan.org/mirrors) that has not been updated. But it is time-consuming and not thoroughly solved.

### What did you expect to happen?

Texlive is installed successfully.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
`brew install texlive`
```

**Comment by danielnachun** [comment]
The `texlive` formula here is very broken.  It tries to download pre-built binaries, some of which do not work, rather than building the TeXLive binaries from source as we normally require.  We will have to remake this formula essentially from scratch, and it is missing several dependencies not currently available as formula.  

Our current top priority is getting this repo merged with Homebrew/core so it may take a bit for this to get fixed.  However I would like to have this formula working soon as I could make use of it on a server.

**Comment by argyili** [comment]
Thank you for replying to me. So it may take a while to make texlive available, right? I will also wait until it is solved.

**Comment by danielnachun** [comment]
I think @gromgit is interested in working on this: https://github.com/Homebrew/linuxbrew-core/pull/22998.  I will update this issue once a PR is opened in homebrew-core.

**Comment by MikeMcQuaid** [comment]
Closing, sorry. If this issue is still relevant: please reopen on homebrew-core.
