### ISSUE TITLE
Bottle shfmt

### ISSUE THREAD

**Issue by smorimoto** [Homebrew/linuxbrew-core#24136]
### `brew gist-logs <formula>` link OR `brew config` AND `brew doctor` output

```shell
NONE
```

### 

- [X] I ran `brew update` and am still able to reproduce my issue.
- [X] I have resolved all warnings from `brew doctor` and that did not fix my problem.

### What were you trying to do (and why)?

Trying to install shfmt via Linux Brew.

### What happened (include all command output)?

```
Error: shfmt: no bottle available!
You can try to install from source with:
  brew install --build-from-source shfmt
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
Error: Process completed with exit code 1.
```

### What did you expect to happen?

I expect that shfmt will be bottled for `x86_64_linux`.

### Step-by-step reproduction instructions (by running `brew` commands)

```shell
brew install shfmt
```

**Comment by sjackman** [comment]
Done! https://github.com/Homebrew/linuxbrew-core/commit/5c4dafcf3b2455f7baf30201445038b2aaa6df15

**Comment by smorimoto** [comment]
Thank you so much!
