### ISSUE TITLE
Cyclic dependency involving cmake and curl

### ISSUE THREAD

**Issue by rwhogg** [Homebrew/linuxbrew-core#3348]
_From @sjackman on July 15, 2015 21:2_

`brew deps` on any of the following packages results in a dependency cycle.

`curl nghttp2 libevent doxygen graphviz pango harfbuzz graphite2 cmake`

_Copied from original issue: Linuxbrew/legacy-linuxbrew#484_

**Comment by rwhogg** [comment]
_From @1ne on July 25, 2017 3:2_

Have been struggling with this when using a non-bottled version of curl with the following options. The only workaround I got was to work is to run `brew install curl` before I run this. It feels like a patchwork, not a solution. 
```
~ ❯❯❯ brew install curl --with-c-ares  --with-libmetalink --with-libssh2 --with-nghttp2 --with-rtmpdump
Error: curl contains a recursive dependency on itself:
  curl depends on cmake
  cmake depends on curl
  curl depends on doxygen
  doxygen depends on curl
  curl depends on libevent
  libevent depends on curl
  curl depends on spdylay
  spdylay depends on curl
  curl depends on nghttp2
  nghttp2 depends on curl
```

**Comment by iMichka** [comment]
Options are now gone. I do not see this cyclic dependency anymore. Closing here, but if the issue still persists, we can reopen this.
